include::../header.adoc[]

= CLONE(nged)

== NAME

clone - The clone command performs a deep copy of an object,
optionally duplicating in a geometric pattern.

== SYNOPSIS

*clone* [_options_]... {_object_to_clone_}

== OPTIONS

*-h*:: Display help.

*-n <copies>*:: Specifies the number of copies to make.  Default is 1.

*-t <x> <y> <z>*:: Specifies an [opt]*x*, [opt]*y*, and [opt]*z*
translation distance between each copy.  Default is 0.0, no
translation.  This option conflicts with [opt]*-a* which specifies
total translation distance.

*-r <x> <y> <z>*:: Specifies [opt]*x*, [opt]*y*, and [opt]*z* angles
to rotate around the x, y, and z axes between each copy.  Default is
0.0, no rotation.  This option conflicts with [opt]*-b* which
specifies total rotation angles.

*-p <x> <y> <z>*:: Specifies an [opt]*x*, [opt]*y*, and [opt]*z* point
to rotate around for [opt]*-b* and [opt]*-r*.  Default is 0 0 0.

*-a <n> <x> <y> <z>*:: Specifies a total [opt]*x*, [opt]*y*, and
[opt]*z* translation distance split across [opt]*n* copies.  This
option conflicts with [opt]*-t* which specifies incremental distances.

*-b <n> <x> <y> <z>*:: Specifies a total rotation in degrees about the
[opt]*x*, [opt]*y*, and [opt]*z* axes, split across [opt]*n* copies.
This option conflicts with [opt]*-r* which specifies incremental
rotation angles.

*-m <axis> <distance>*:: Specifies an axis and distance along that
axis about which to create a mirrored copy.  The [opt]*axis* must be
'x', 'y', or 'z'.  The distance may be a positive or negative distance
along that axis.

*-i <increment>*:: This option pertains to the copy naming convention.
It specifies the increment to use when naming copies.  If a number is
not found in the name, the increment number is appended to the end of
the name (e.g., [cmd]*clone box* creates a 'box100' object).  Default
[opt]*increment* is 100.

*-c*:: This option pertains to the copy naming convention.  Increment
the _next_ number encountered in object names.  You can specify
[opt]*-c* multiple times to increment the Nth number.  For example,
[cmd]*clone -c -c -c* will increment the 4th number in object namess.
Default is to increment the first number encountered.

== DESCRIPTION

Clone performs a deep copy, traversing the entire hierarchy of the
object specified and creating a new independent hierarchy.  The
[cmd]*clone* command uses an automatic naming convention as it creates
copies, incrementing and/or appending to numbers encountered in the
object specified.  The number convention may be configured with the
[opt]*-i* and [opt]*-c* options.

If you specify different numbers of copies with the [opt]*-a*,
[opt]*-b*, and/or [opt]*-n* options, the last value of [opt]*n*
specified will be used for the number of copies.

== AUTHOR

BRL-CAD Team

include::../footer.adoc[]
