include::../header.adoc[]

= DEBUGBU(nged)

== NAME

debugbu - Allows the user to set or check the debug flags used by
libbu.

== SYNOPSIS

*debugbu* [_hex_code_]

== DESCRIPTION

Allows the user to set or check the debug flags used by _libbu_. With
no arguments, the [cmd]*debugbu* command displays all the possible
settings for the _bu_debug_ flag and the current value. When a
_hex_code_ is supplied, that value is used as the new value for
_bu_debug_. Similar debug commands for other _BRL-CAD_ libraries are
[cmd]*debuglib* for _librt_ and [cmd]*debugnmg* for the NMG portion of
_librt_.

== EXAMPLES

The first example shows the use of the [cmd]*debugbu* command (without
an argument) to display all possible settings for the _bu_debug_ flag
and the current value. The second example shows the use of the
[cmd]*debugbu* command with a hex code, which is used as the new value
for _bu_debug_.

.Display a list of available _bu_debug_ values andthe current value.
====
[prompt]#mged># [in]`debugbu`

Lists available _bu_debug_ values and the current value.
====

.Set a new value for _bu_debug_.
====
[prompt]#mged># [in]`debugbu 2`

Sets _bu_debug_ to <MEM_CHECK>. 
====

== AUTHOR

BRL-CAD Team

include::../footer.adoc[]
