include::../header.adoc[]

= EDCOMB(nged)

== NAME

edcomb - Allows the user to modify the attributes of a combination.

== SYNOPSIS

*edcomb* {_combname_} [_regionflag regionID airID los% materialID_]

== DESCRIPTION

Allows the user to modify the attributes of a combination. The
_combname_ is the name of the combination to be modified. The
_regionflag_ controls whether the combination is identified as a
region - supplying either _R_ or _1_ for the _regionflag_ indicates
that the combination is a region; to indicate the combination is NOT a
region simply supply any other character (_C_ or _0_ are useful
conventions here.) If the region flag is not being set, then the
remainder of the attributes are ignored.  However, the [cmd]*edcomb*
command requires that something is supplied for those arguments in
order to work - so if using [cmd]*edcomb* to turn off the region flag
on a combination simply supply 0 for each of the remaining arguments
to [cmd]*edcomb*. If the region flag is being set, then the
_region_id, aircode, los,_ and _material_code_ are set according to
the arguments supplied.

== EXAMPLES

The first example shows the use of the [cmd]*edcomb* command with the
_R_ flag (region) added along with the _region_id, air_code, los_ and
_material_code_. The second example shows how to unset the region flag
for a particular combination.

.Make a combination a region having specific attributes.
====
[prompt]#mged># [in]`edcomb comb1 R 1001 0 50 8`

Makes _comb1_ a _region_ and set its _ident_ to 1001, its _air code_
to 0, its _los_ to 50, and its _material code_ to 8.
====

.Unset a _region_ flag for a particular combination.
====
[prompt]#mged># [in]`edcomb comb1 C 0 0 0 0`

Unsets the _region_ flag for combination _comb1_.
====

== AUTHOR

BRL-CAD Team

include::../footer.adoc[]
