include::../header.adoc[]

= PUTMAT(nged)

== NAME

putmat - Replaces the existing transformation matrix in the
combination specified that corresponds to the member specified.

== SYNOPSIS

*putmat* {_comb_name/member_name_} {[I] | [m0 m1 m2 m3 ... m16]}

== DESCRIPTION

Replaces the existing transformation matrix in the combination
specified that corresponds to the member specified. The transformation
matrix may be specified with an "I" to indicate the identity matrix,
or it may be specified as 16 elements listed row-by-row. The
[cmd]*copymat* command allows the user to copy an existing
transformation matrix.

== EXAMPLES

The example shows the use of the [cmd]*putmat* command to set the
transformation matrix for a specified region in a specified group to
the identity matrix.

.Set the transformation matrix for a specified region in a specified group to the identity matrix. 
====
[prompt]#mged># [in]`putmat group1/regiona I`

Sets the transformation matrix for _regiona_ in _group1_ to the
identity matrix.
====

== AUTHOR

BRL-CAD Team

include::../footer.adoc[]
