include::../header.adoc[]

= SUMMARY(nged)

== NAME

summary - The summary command with no arguments lists the number of
primitive shapes, regions, and nonregion combinations in the current
database.

== SYNOPSIS

*summary* [s] [r] [g]

== DESCRIPTION

The [cmd]*summary* command with no arguments lists the number of
primitive shapes, regions, and nonregion combinations in the current
database. If the _s_ argument is supplied, then the name of each
_primitive shape_ is also listed. Similarly, the _r_ flag asks for the
_region_ names, and _g_ asks for the names of all the combinations
(including _region_). The flags may be concatenated to get combined
output.

== EXAMPLES

The example shows the use of the [cmd]*summary* command with an
argument to list a summary of primitive shapes and regions for the
current database.

.List a summary of primitive shapes and regions for the current database.
====
[prompt]#mged># [in]`summary sr`

Lists a summary of primitive shapes and regions for the current
database.
====

== AUTHOR

BRL-CAD Team

include::../footer.adoc[]
