include::../header.adoc[]

= WHO(nged)

== NAME

who - Lists the top-level objects that are currently displayed.

== SYNOPSIS

*who* +[+[real] | [phony] | [both]]

== DESCRIPTION

Lists the top-level objects that are currently displayed. The _phony_
flag asks for just _phony_ objects. _Phony_ objects are typically
objects that are drawn in the MGED display, but are not actual
database objects. Some _phony_ objects are drawings from the
[cmd]*vdraw* command and the edgeuses drawn by the [cmd]*ev -u*
command. The _real_ flag asks for just _real_ objects, and the _both_
flag asks for both _real_ and _phony_ objects. The default is just
_real_ objects. Any of the flags may be abbreviated by its first
letter. The [cmd]*x* command also lists displayed shapes, but in more
detail.

== EXAMPLES

The example shows the use of the [cmd]*who* command to list the
top-level phony objects that are currently displayed.

.List the top-level phony objects that are currently displayed.
====
[prompt]#mged># [in]`who p`

Lists all top-level _phony_ objects currently displayed.
====

== AUTHOR

BRL-CAD Team

include::../footer.adoc[]
