[[_whatisbrlcad]]
= What is BRL-CAD?
:doctype: book
:sectnums:
:toc: left
:icons: font
:experimental:
:sourcedir: .

Since the late 1950s, computers have been used to assist with the
design and study of combat vehicle systems.  The result has been a
reduction in the amount of time and money required to take a system
from the drawing board to full-scale production as well as increased
efficiency in testing and evaluation.

In 1979, the U.S.  Army Ballistic Research Laboratory (BRL) (now the
U.S.  Army Research Laboratory [ARL]) expressed a need for tools that
could assist with the computer simulation and engineering analysis of
combat vehicle systems and environments.  When no existing
computer-aided design (CAD) package was found to be adequate for this
purpose, BRL software developers began assembling a suite of utilities
capable of interactively displaying, editing, and interrogating
geometric models.  This suite became known as BRL-CAD.

Now comprising almost a million lines of C code, BRL-CAD has become a
powerful constructive solid geometry (CSG) modeling package that has
been licensed at over 2,000 sites throughout the world.  It contains a
large collection of tools, utilities, and libraries including an
interactive geometry editor, raytracing and generic framebuffer
libraries, a network-distributed image-processing and
signal-processing capability, and a customizable embedded scripting
language.  In addition, BRL-CAD simultaneously supports dual
interaction methods, one using a command line and one using a
graphical user interface (GUI).

A particular strength of the package lies in its ability to build and
analyze realistic models of complex objects using a relatively small
set of "primitive shapes." To do this, the shapes are manipulated by
employing the basic Boolean operations of union, subtraction, and
intersection.  Another strength of the package is the speed of its
raytracer, which is one of the fastest in existence.  Finally, BRL-CAD
users can accurately model objects on scales ranging from the
subatomic through the galactic and get "all the details, all the
time."
