= Libraries
:doctype: book
:sectnums:
:toc: left
:icons: font
:experimental:
:sourcedir: .

The BRL-CAD libraries (designated by the prefix "lib") are designed
primarily for the geometric modeler who also wants to tinker with
software and, perhaps, design custom tools.  Each library fits into
one of three categories: (1) creating and/or editing geometry, (2)
raytracing geometry, or (3) image handling.  The following is a list
of the major BRL-CAD libraries and descriptions of their functions.

* `libbu` -- a basic utility (bu) library containing fundamental
  computer science types of routines, including manipulating data
  (e.g., converting from host format data to network format data),
  parallel processing, parsing parameters, handling variable-length
  strings, performing error checks, converting units from one format
  to another, manipulating bit vectors, running parallel-safe versions
  of input/output (I/O) routines, and maintaining symbol tables.
* `libbn` -- a library of routines to support basic numerical (bn)
  handling, including 2-D/3-D vector, matrix, and quaternion
  manipulation; 3-D plotting support; automatic inference of image
  size (BRL-CAD images have no internal header; image dimensions are
  intuited from the size of the file); and wavelet decomposition and
  reconstruction, etc.
* `libdm` -- BRL-CAD's primary graphics display manager (dm)
  library. It handles opening windows onto the display and displaying
  geometry in the graphics window, etc.
* `libfb` -- the framebuffer (fb) library, which supports having a
  window in which the user puts pixel data when raytracing.
* `liboptical` -- the shader and texturing library for the raytracer.
* `libpkg` -- a library that implements a remote procedure call (rpc)
  mechanism. This library is a predecessor of the modern rpc
  system. Unlike the typical UNIX rpc service, applications can set up
  services and handle requests without requiring configuration by a
  system administrator.
* `librt` -- the library that contains all of the geometry support,
  including data representations for the primitives, support for
  raytracing (rt), and binary I/O support for CSG geometric
  descriptions.
* `libz` -- a public-domain compression library.
* `libtcl`, `libtk`, and `libitcl` -- libraries that provide the
  Tcl/Tk scripting language.
* `libpng` -- a library that provides portable network graphics (png).
