[[_toolsutilities]]
= Tools and Utilities
:doctype: book
:sectnums:
:toc: left
:icons: font
:experimental:
:sourcedir: .

The application side of BRL-CAD also offers a number of tools and utilities.
They primarily concern (1) geometric conversion, (2) geometric interrogation, (3) image format conversion, and (4) command-line-oriented image manipulation.
The following is a list of the major BRL-CAD tools and utilities. 

* MGED (Multiple-Device Geometry Editor) - BRL-CAD's graphics editor. (For detailed guidance on the use of MGED as well as a list of all the MGED commands currently available, see Butler et al. [2001].) 
* Tools for raytracing and interrogating raytraced geometric objects. 
+
** rt - the main raytracer for rendering images in BRL-CAD. 
** nirt - a package for firing rays interactively and getting information about what the rays run into. 
** remrt - a network-distributed raytracing package. 
* An assortment of geometric converters to convert to and/or from other geometry formats, including Euclid, ACAD, AutoCAD DXF, TANKILL, Wavefront OBJ, Pro/ENGINEER, JACK (the human factors model for doing workload/usability studies), Viewpoint Data Lab, NASTRAN, Digital Equipment's Object File Format (OFF), Virtual Reality Mark-up Language (VRML), Stereo Lithography (STL), Cyberware Digitizer data, and FASTGEN4. 
* bwish - a Tcl/Tk interpreter in a windowing shell with enhancements compiled into it for accessing BRL-CAD libraries. It also includes various other extensions to the Tcl language. 
* irprep - produces input to the PRISM (Physically Realistic Infrared Simulation Model) code. 
* JOVE (Jonathan's Own Version of Emacs) - a fast, light implementation of Emacs. 
* Applications for displaying images of various types on the framebuffer application and retrieving data from that framebuffer into images of various types. 
* Tools for generating geometry for common objects such as fences, walls, and geometric mathematical oddities (e.g., the sphereflake shown in Figure 2 in Section 4). 
* Data manipulation programs to (1) convert integers to floats, floats to doubles, etc. (e.g., cv); (2) perform mathematical operations on file elements (e.g., imod, umod, and dmod); (3) compute statistics of file elements (e.g., istat, ustat, and dstat); etc. 
* Utilities for building animation scripts - keeping track of columnar data and interpolating it to allow one to produce input to the rt program to render multiple items for animation. 
* Utah Raster Tool Kit - image manipulation of all RLE-based images. 
* Programs for manipulating images and converting between different image file types. The two primary BRL-CAD types are pix (24-bit red, green, and blue [RGB] color images) and bw (8-bit grayscale images). Converters exist for various image formats including alias, png, ppm, etc. 
* Programs for filtering images, doing histograms on the image data, and extracting rectangles from the images. 
* Tools for combining two images and blending them together. (These tools were created before good image editing tools for video production were available; today users would typically load the images directly into a video editing package.) 
