= BRL-CAD Tutorial Series: Volume IV: Converting Geometry Between BRL-CAD and Other Formats
John R. Anderson; Eric W. Edwards

****
[cols=">h,<", frame="all"]
|===
| AUTHORS:
| John R. Anderson +
  Eric W. Edwards

| ORGANIZATION:
| *U.S. Army Research Laboratory* +
  Aberdeen Proving Ground, MD  21005-5068

| REPORT:
| ARL-SR-121 +
  May 2004
|===
****

.Disclaimers
****
The findings in this report are not to be construed as an official
Department of the Army position unless so designated by other
authorized documents.

Citation of manufacturer's or trade names does not constitute an
official endorsement or approval of the use thereof.

Destroy this report when it is no longer needed. Do not return it\ to
the originator.

Note that the name BRL-CAD and the BRL-CAD eagle logo are trademarks
of the U.S. Army.
****

.Dedication
****
The authors would like to thank Messrs. Lee Butler, Edwin Davisson,
William Landis, and David Davis for technically reviewing this
document in a timely manner and for making numerous suggestions to
improve its content and presentation. The authors also thank Dr. Paul
Tanenbaum for the use of his graphics for figures 1 and 2
and Ms. TraNese Christy for her help in adapting them for presentation
in this document. Finally, the authors would like to posthumously
acknowledge Mr. Michael Muuss, the original architect of
BRL-CAD. Without his vision, intellect, and diligence, this work would
not have been possible. Thus, the BRL-CAD Tutorial Series is dedicated
to his memory.
****

== Chapters

* xref:tutorials:volume4/chapter1.adoc[]
* xref:tutorials:volume4/chapter2.adoc[]
* xref:tutorials:volume4/chapter3.adoc[]
* xref:tutorials:volume4/chapter4.adoc[]
* xref:tutorials:volume4/chapter5.adoc[]
* xref:tutorials:volume4/chapter6.adoc[]
* xref:tutorials:volume4/chapter7.adoc[]

