
:sectnums!:

[preface]
= Preface

Since 1979, the U.S.  Army Research Laboratory (formerly the Ballistic
Research Laboratory) has been developing the [app]`BRL-CAD`
constructive solid geometry (CSG) modeling package for a wide range of
military and industrial applications.  The strength of the package
lies in its ability to build realistic models of complex objects from
a relatively small set of "primitive shapes" by employing the basic
Boolean operations of union, subtraction, and intersection and by
assigning real-world material attributes.

The package comprises a large collection of tools, utilities, and
libraries including an interactive geometry editor, ray-tracing and
generic framebuffer libraries, a network-distributed image-processing
and signal-processing capability, and an embedded scripting language.

Although [app]`BRL-CAD` has continued to mature in performance and
utility, developers have strived to keep the package approachable and
easy to use, as evidenced by the package's dual command formats, its
newly renovated graphical user interface (GUI), and its customization
potential through user scripting.

In addition, a multivolume tutorial series is being developed to
assist users in a variety of [app]`BRL-CAD` areas and applications.
The "Introduction to [app]`MGED`," which is the second volume in the
series, is intended to provide new users with a basic understanding of
the [app]`Multi-Device Geometry Editor` ([app]`MGED`), which is the
heart of the [app]`BRL-CAD` package.  Other volumes focus on
installation procedures, advanced features, and programming.

:sectnums:
