= BWROT(1)
BRL-CAD Team
ifndef::site-gen-antora[:doctype: manpage]
:man manual: BRL-CAD
:man source: BRL-CAD
:page-role: manpage

== NAME

bwrot - rotate, invert, or reverse a black and white bw file

== SYNOPSIS

*bwrot*[-rifb | -a _angle_][-s _squaresize_][-w _in_width_][-n _in_height_][-o _out.bw_][_file.bw_][>_out.bw_]

== DESCRIPTION

[cmd]*bwrot* will rotate, vertically invert, and horizontally reverse a black and white xref:man:5/bw.adoc[*bw*(5)] format file or read from standard input if a file name is not given.  The [opt]*-w* and [opt]*-n* flags specify the input file width and number of scan lines in pixels (both values default to 512); they can be set to same value via [opt]*-s.*

The [opt]*-r* flag reverses the scan lines left to right. The [opt]*-i* flag inverts the image top to bottom. The [opt]*-f* and [opt]*-b* flag will rotate the image ninety degrees forward or backward respectively. The sense of the rotation is relative to a first quadrant coordinate system, i.e. origin lower left, where "forward" means clockwise.

Note that a 180 degree rotation can be obtained by both reversing and inverting.

If the [opt]*-a* flag is used, the image will be rotated counterclockwise by the specified arbitrary angle (in degrees).

The [opt]*-o* option can be used to specify an output file instead of redirecting standard out.

== METHOD

A fairly large buffer is kept in memory so that, file size permitting, the entire rotation can occur without seeking on input or output. In any event, the algorithm is designed to process the input sequentially, so that if any seeking is required, it will happen on output only.  If these seeks fail, e.g. the output is a pipe, the user will be told that it needs a file on output. A more general solution to this problem would be to see if seeks can be done on input instead, and switch the algorithm to seek on input only.

== SEE ALSO

xref:man:1/brlcad.adoc[*brlcad*(1)], xref:man:1/pixrot.adoc[*pixrot*(1)], xref:man:5/bwscale.adoc[*bwscale*(5)], xref:man:1/bwrect.adoc[*bwrect*(1)], xref:man:5/bw.adoc[*bw*(5)]

== BUGS

If the file size is very large, excessive seeking may occur on output and the rotation will take a very long time.  More complicated algorithms could remedy this.

== AUTHOR

BRL-CAD Team

== COPYRIGHT

This software is Copyright (c) 1989-2021 by the United States Government as represented by U.S. Army Research Laboratory.

== BUG REPORTS

Reports of bugs or problems should be submitted via electronic mail to mailto:devs@brlcad.org[]