= DBCLEAN(1)
ifndef::site-gen-antora[:doctype: manpage]
:man manual: BRL-CAD
:man source: BRL-CAD
:page-role: manpage

== NAME

dbclean -  a shell script for compacting mged databases.

== SYNOPSIS

*dbclean*_in_model.g__out_model.g_

== DESCRIPTION

[cmd]*dbclean* operates on the indicated input database __in_model.g__ and produces a compacter version of the same as __out_model.g.__

The objective is to remove "holes" in the original database which resulted from use of the __kill__/__killall__ commands in xref:man:1/mged.adoc[*mged*(1)]. Note that when a database is compacted in this manner, the compacting is dependent on the successful completion of the converters xref:man:1/g2asc.adoc[*g2asc*(1)] and xref:man:1/asc2g.adoc[*asc2g*(1)]. The compacting will only be aborted if one of the conversions fails.  Thus, when either converter "skips" solids, [cmd]*dbclean* will continue, and __out_model.g__ will be written, albeit without the skipped solids.  This will also result in a smaller database.

== EXAMPLE

This section will acquaint the user with the ordinary usage of [cmd]*dbclean* .

....

dbclean in_model.g out_model.g
....

This will result in a compacted version of the input.

== SEE ALSO

xref:man:1/mged.adoc[*mged*(1)]

== DIAGNOSTICS

Numerous error conditions are possible, usually due to errors in the geometry database. Descriptive messages are printed on standard error (file descriptor 2).

== BUGS

Most deficiencies observed while using the [cmd]*dbclean* program are usually with the xref:man:1/g2asc.adoc[*g2asc*(1)] and xref:man:1/asc2g.adoc[*asc2g*(1)] packages instead.

== AUTHOR

_BRL-CAD Team_

== COPYRIGHT

This software is Copyright (c) 1991-2021 United States Government as represented by the U.S. Army Research Laboratory.

== BUG REPORTS

Reports of bugs or problems should be submitted via electronic mail to mailto:devs@brlcad.org[]