= DBUPGRADE(1)
ifndef::site-gen-antora[:doctype: manpage]
:man manual: BRL-CAD
:man source: BRL-CAD
:page-role: manpage

== NAME

dbupgrade -  a program to upgrade BRL-CAD mged geometry databases files to the current version.

== SYNOPSIS

*dbupgrade*_input.g__output.g_

== DESCRIPTION

[cmd]*dbupgrade* operates on the indicated input geometry database __input.g__, recognizing the version of the BRL-CAD database provided as input and then converting it to the current database version.  Output is then saved to the specified __output.g__ file.

Note that this tool will attempt to automatically 'fix' an existing (v4 format) binary database that was transferred from a binary-incompatible platform.  However, this process may be imperfect - the best approach (if the original platform on which the file was created is available) is to run [cmd]*dbupgrade* on the file before transferring from the originating platform.  Once upgraded the output file will be platform-independent regardless of the platform on which the upgrade was done.

Running [cmd]*dbupgrade* removes the need to run xref:man:1/g2asc.adoc[*g2asc*(1)] and xref:man:1/asc2g.adoc[*asc2g*(1)] on a database to move it between computers (historically this was a way to work around the platform-specific nature of v4 files). The latest BRL-CAD geometry database format is platform-independent.

== SEE ALSO

xref:man:1/mged.adoc[*mged*(1)], xref:man:1/g2asc.adoc[*g2asc*(1)], xref:man:1/asc2g.adoc[*asc2g*(1)]

== DIAGNOSTICS

Numerous error conditions are possible, usually due to errors in the geometry database. Descriptive messages are printed on standard error (file descriptor 2).

== AUTHOR

BRL-CAD Team

== COPYRIGHT

This software is Copyright (c) 2006-2021 by the United States Government as represented by U.S. Army Research Laboratory.

== BUG REPORTS

Reports of bugs or problems should be submitted via electronic mail to mailto:devs@brlcad.org[]