= DXF-G(1)
BRL-CAD Team
ifndef::site-gen-antora[:doctype: manpage]
:man manual: BRL-CAD
:man source: BRL-CAD
:page-role: manpage

== NAME

dxf-g - DXF Translator (DXF to BRL-CAD)

== SYNOPSIS

*dxf-g*[-c][-d][-v][-s _scale_factor_][-t _tolerance_]_file.dxf__database.g_

== DESCRIPTION

[cmd]*dxf-g* converts the specified __file.dxf__ to a BRL-CAD __database.g__ file.

The following options are available:

*-c*::
Only the first color seen for a layer should be used. Without this option, layers may be broken into separate BOT primitives according to color assigned.

*-d*::
Sets a debug flag. The only effect is to cause a core dump on failure. This is probably not useful except for developers.

*-v*::
Produces very verbose output on stderr.

*-s*__scale_factor__::
Provides a scale factor to be applied to the DXF input. This can be used for DXF files that do not provide units information.

*-t*__tolerance__::
Specifies the maximum distance (in mm) between two vertices at which the two vertices will be considered to be the same vertex.

The __file.dxf__ file is expected to be in the ASCII Autodesk DXF format as defined in the Autocad 2006 manuals. This converter handles entities of types:

POLYLINE LWPOLYLINE LEADER DIMENSION VERTEX LINE CIRCLE ARC ELLIPSE 3DFACE TEXT MTEXT ATTRIB SOLID SPLINE

The POLYLINE entities in AUTOCAD are actually a container for numerous different entity types. The types of POLYLINE entities converted include:

3D polylines; 3D polygon meshes; polyface meshes

SOLID entities are 2D shapes with a solid fill, but this converter does not do any filling. Each layer is converted to a separate object. Colors are also converted.

== EXAMPLE
// <synopsis>
// $ dxf-g <emphasis remap="I">sample.dxf sample.g</emphasis>
// </synopsis>


== SEE ALSO

_http://images.autodesk.com/adsk/files/dxf_format.pdf_

== DIAGNOSTICS

Error messages are intended to be self-explanatory.

== AUTHOR

BRL-CAD Team

== COPYRIGHT

This software is Copyright (c) 1993-2021 by the United States Government as represented by U.S. Army Research Laboratory.

== BUG REPORTS

Reports of bugs or problems should be submitted via electronic mail to mailto:devs@brlcad.org[]