= FB-PNG(1)
BRL-CAD Team
ifndef::site-gen-antora[:doctype: manpage]
:man manual: BRL-CAD
:man source: BRL-CAD
:page-role: manpage

== NAME

fb-png - save a framebuffer image in a color Portable Network Graphics (PNG) file

== SYNOPSIS

*fb-png* [-ic] [-# _nbytes/pixel_] [-g _gamma_] [-F _framebuffer_] [-s _squaresize_] [-w _width_] [-n _height_] [_file.png_]

== DESCRIPTION

[cmd]*fb-png* will take a region of a framebuffer display and save it as a color __png__ format file. The environment variable [var]`FB_FILE` is used to select the display device (see xref:man:1/brlcad.adoc[*brlcad*(1)]). If this variable is not set, the default device for your system will be used. Alternatively, the framebuffer may be explicitly specified by using the [opt]*-F* flag.

By default, the output __png__ file, and the requested framebuffer size, is assumed to be 512x512 pixels. The [opt]*-s* flag will set both the file height and width to be the given size, while [opt]*-w* and [opt]*-n* are used for setting them individually.

A first quadrant coordinate system is used (origin in lower left of screen), and the area saved is normally from this origin. The [opt]*-i* flag switches to a fourth quadrant system, both in the storage order as well as the origin offset coordinates (i.e. origin is now the upper left corner of the screen).

The [opt]*-#*[rep]_nbytes/pixel_ flag specifies the number of bytes per pixel.  The only values accepted are 1 and 3.

The [opt]*-c* flag specifies that the color map in the frame buffer should be applied to the pixel values (crunched) before they are written to the output file.

The [opt]*-g*[rep]_gamma_ flag sets the specified gamma correction value into the created PNG file.  A value of 0.6 is a close approximation of PC display monitors. A negative gamma value disables writing a gAMA chunk out entirely (and is the default).

== SEE ALSO

xref:man:1/brlcad.adoc[*brlcad*(1)], xref:man:1/png-fb.adoc[*png-fb*(1)], xref:man:1/fb-bw.adoc[*fb-bw*(1)], xref:man:5/pix.adoc[*pix*(5)]

== AUTHOR

John R. Anderson

== COPYRIGHT

This software is Copyright (c) 1998-2021 by the United States Government as represented by U.S. Army Research Laboratory.

== BUG REPORTS

Reports of bugs or problems should be submitted via electronic mail to mailto:devs@brlcad.org[]