= FBLABEL(1)
ifndef::site-gen-antora[:doctype: manpage]
:man manual: BRL-CAD
:man source: BRL-CAD
:page-role: manpage

== NAME

fblabel - display a text string on a framebuffer

== SYNOPSIS

*fblabel* [-dca] [-F _framebuffer_] [-f _fontname_] [-{sS} _squaresize_] [-{wW} _width_] [-{nN} _height_] [-C _r/g/b_] _x_position_ _y_position_ _text_string_

== DESCRIPTION

[cmd]*fblabel* writes a text string to the image on the currently selected framebuffer. The text string will be filtered to the image currently displayed. Use xref:man:1/fbpoint.adoc[*fbpoint*(1)] to determine where to position the text string. The lower left corner of the text string starts displaying at the x and y position given. The environment variable FB_FILE specifies the current framebuffer; see xref:man:1/brlcad.adoc[*brlcad*(1)]. Alternatively, the framebuffer may be explicitly specified by using the [opt]*-F* flag.

By default, the requested framebuffer size is assumed to be 512x512 pixels.

The [opt]*-d* flag is for debugging.

The [opt]*-c* flag causes the screen to be cleared before the text string is displayed. The default behavior is to label the current image without clearing the screen.

The [opt]*-a* flag causes the text not to be filtered against the frame buffer image.

The [opt]*-C*[rep]_r/g/b_ option specifies red, green, and blue (r/g/b) values [0..255] for the text. The default color is white.

The [opt]*-f*[rep]_fontname_ option will change the current default font from nonie.r.12 to "/usr/lib/vfont/fontname".

The [opt]*-S* (or [opt]*-s*) flag sets the width and the height to the same value; the [opt]*-W* (or [opt]*-w*) and [opt]*-N* (or [opt]*-n*) flags are used for setting them individually.

== FONTS

[cmd]*fblabel* expects the Berkeley fonts in the directory /usr/lib/vfont. The fonts are expected to be in Vax byte order, even if that is not the natural byte order of the machine, to avoid having to create a font converter.

== EXAMPLE

fblabel -f "oldenglish.14" `fbpoint -H` "Hello"

== SEE ALSO

xref:man:1/brlcad.adoc[*brlcad*(1)], xref:man:1/fbed.adoc[*fbed*(1)], xref:man:1/fbpoint.adoc[*fbpoint*(1)], xref:man:3/libfb.adoc[*libfb*(3)], xref:man:5/pix.adoc[*pix*(5)]

== AUTHOR

BRL-CAD Team

== COPYRIGHT

This software is Copyright (c) 1989-2021 by the United States Government as represented by U.S. Army Research Laboratory.

== BUG REPORTS

Reports of bugs or problems should be submitted via electronic mail to mailto:devs@brlcad.org[]