= G-IGES(1)
ifndef::site-gen-antora[:doctype: manpage]
:man manual: BRL-CAD
:man source: BRL-CAD
:page-role: manpage

== NAME

g-iges - IGES Translator (BRL-CAD to IGES)

== SYNOPSIS

*g-iges*[-f | _t_ | _m_][-v][-s][-x _flag1_][-X _flag2_][-a _abs_tol_][-r _rel_tol_][-n _norm_tol_][-o _output_file_or_directory_]_database.g__object(s)_

== DESCRIPTION

[cmd]*g-iges* converts the specified objects of the BRL-CAD database, __database.g__, to an IGES version 5.1 file, __file.iges__.

The following options are recognized

*-f*::
selects  a  BREP  IGES  file  consisting  of  only  Manifold Solid BREP Objects.  All CSG solids in the specified objects  are  tessellated  to produce  facetted  BREP  objects, then the indicated Boolean operations are performed for each region. Individual regions are  written  to  the IGES  file  as individual BREP objects.  This procedure results in some approximations since curved surface solids, such as TGCs or ellipsoids, are  approximated  by flat facets.  The accuracy of the tessellation may be controlled through the use of the [opt]*-a, -r, -n* options.

*-a*__abs_tol__::
Sets the absolute tolerance (floating point value) for tessellation.

*-r*__rel_tol__::
Sets the relative (to the size of the object) tolerance (floating point value) for tessellation.

*-n*__norm_tol__::
Sets the normal tolerance (floating point value 0..1) for tessellation. This value is compared to the dot product of the normals to determine if the surfaces are within tolerance

*-t*::
indicates that an IGES file consisting of only trimmed NURBs should be created. The trimmed  NURBs  will  all  be planar NURBs, and they are the facets derived from the tessellation and Boolean evaluation as in the -f option. The file produced in  this  way is  acceptable  to the Pro/Engineer IGES import routine.

*-m*::
implies the -t option, and is used to produce multiple IGES files  (one for  each region converted). In this case the argument to the -o option should be a directory where the IGES files  will  accumulate.

*-v*::
requests debugging information

*-s*::
all facets in  BREP  objects  should  be output  in  the form of planar NURBs (Intergraph likes their IGES files this way).

*-x*__flag1__::
set the librt debug flag (see raytrace.h for values)

*-X*__flag2__::
set the librt debug flag (see nmg.h for values)

*-o*__output_file_or_directory__::
Specifies the output file (or in the case of the -m) the output directory for the iges file(s).

*-P*__num_cpus__::
Specifies the number of processors to use.

If neither the -f , -t , nor the -m options  are  selected, the  default is a CSG IGES file. In this situation, all regions will be written to the IGES file as Boolean trees with all possible solids represented  by their IGES CSG equivalent. In cases where there is no IGES CSG equivalent, the BRL-CAD solid is  tesellated  (using  the  provided tolerances),  and  a  BREP  object  is  written for that solid.

== EXAMPLE

g-iges -f -o _gsample.iges sample.g object1_

This command will produce an IGES BREP output file, __sample.iges__, from __object1__ of the BRL-CAD database file __sample.g__.

== SEE ALSO

xref:man:1/iges-g.adoc[*iges-g*(1)]__The Initial Graphics Exchange Specification (IGES) Version 5.1__, IGES/PDES Organization, September 1991

== DIAGNOSTICS

Error messages are intended to be self-explanatory.

== AUTHOR

BRL-CAD Team

== COPYRIGHT

This software is Copyright (c) 1993-2021 by the United States Government as represented by U.S. Army Research Laboratory.

== BUG REPORTS

Reports of bugs or problems should be submitted via electronic mail to mailto:devs@brlcad.org[]