= G-PLY(1)
BRL-CAD Team
ifndef::site-gen-antora[:doctype: manpage]
:man manual: User Commands
:man source: BRL-CAD
:page-role: manpage

== NAME

g-ply -  Stanford PLY exporter (BRL-CAD to PLY)

== SYNOPSIS

*g-ply*[-v][-xX _lvl_][-a _abs_tess_tol_][-r _rel_tess_tol_][-n _norm_tess_tol_][-t _type_][-s][-D _dist_calc_tol_]-o _output_file_name__database.g__object(s)_...

== DESCRIPTION

[cmd]*g-ply* converts the specified__object(s)__ from a BRL-CAD _database.g_ file to the _Stanfort PLY_ file format. 

The following options are recognized.

*-o filename*::
Specify output file name.

*-s*::
Write out one object per file, instead of merging individual objects into a single ply file. 

*-t* type (asc: ascii), (le: little endian), (be: big endian)::
Specify the type of PLY file to write. 

*-D#*::
Specify a calculational distance tolerance (mm). Any two vertices that are less than this distance apart will be treated as the same vertex.

*-a#*::
Specify the absolute tesselation tolerance.

*-r#*::
Specify the relative tesselation tolerance.

*-n#*::
Specify the surface-normal tesselation tolerance.

*-x#*::
Specify an RT debug flag.

*-X#*::
Specify an NMG debug flag.

*-v*::
Enable verbose output.

== EXAMPLE
// <synopsis>
//       $ g-ply -o <emphasis remap="I">sample.ply sample.g sample_object</emphasis>
//     </synopsis>


== DIAGNOSTICS

Error messages are intended to be self-explanatory.

== AUTHOR

BRL-CAD Team

== COPYRIGHT

This software is Copyright (c) 2003-2021 by the United States Government as represented by U.S. Army Research Laboratory. 

== BUG REPORTS

Reports of bugs or problems should be submitted via electronic mail to mailto:devs@brlcad.org[]