= G-RAW(1)
BRL-CAD Team
ifndef::site-gen-antora[:doctype: manpage]
:man manual: User Commands
:man source: BRL-CAD
:page-role: manpage

== NAME

g-raw -  RAW Translator (BRL-CAD to RAW)

== SYNOPSIS

*g-raw*[-o _output_file_][-m _output_directory_][-i][-8][-D _calculation_tolerance_][-a _absolute_tol_][-r _relative_tol_][-n _normal_tol_][-xX _level_][-v]_database.g__object(s)_...

== DESCRIPTION

[cmd]*g-raw* converts the specified __object(s)__ from a BRL-CAD __database.g__ file to the __stereolithography__ file format.

The following options are recognized.

*-o PATH*::
Specify output file name (default is stdout).

*-m DIR*::
Specify a directory for output files. Each region converted is written to a separate file. File names are constructed from the full path names of each region (the path from the specified object to the region). Any "/" characters in the path name are replaced by "@" characters and "." and white space are replaced by "_" characters. If the -m option is not specified, all regions are written to the same file. The [opt]*-o* and [opt]*-m* options are mutually exclusive. 

*-i*::
Use inches as the output format (the default is mm).

*-8*::
Facetize using the marching cubes algorithm.

*-D#*::
Specify a calculational distance tolerance (mm). Any two vertices that are less than this distance apart will be treated as the same vertex.

*-a#*::
Specify the absolute tesselation tolerance.

*-r#*::
Specify the relative tesselation tolerance.

*-n#*::
Specify the surface-normal tesselation tolerance.

*-x#*::
Specify an RT debug flag.

*-X#*::
Specify an NMG debug flag.

*-v*::
Enable verbose output.

== EXAMPLE
// <synopsis>
// $ g-raw -o <emphasis remap="I">sample.raw sample.g sample_object</emphasis>
// </synopsis>


== DIAGNOSTICS

Error messages are intended to be self-explanatory.

== AUTHOR

BRL-CAD Team

== COPYRIGHT

This software is Copyright (c) 2013-2021 by the United States Government as represented by U.S. Army Research Laboratory.

== BUG REPORTS

Reports of bugs or problems should be submitted via electronic mail to mailto:devs@brlcad.org[]