= G2ASC(1)
BRL-CAD Team
ifndef::site-gen-antora[:doctype: manpage]
:man manual: BRL-CAD
:man source: BRL-CAD
:page-layout: base

== NAME

g2asc - convert a BRL-CAD mged geometry database from binary to ASCII form.

== SYNOPSIS

*g2asc* _input.g_ _output.asc_

== DESCRIPTION

_[cmd]*g2asc*_ is a utility provided by BRL-CAD used to convert _[cmd]*mged(1)*_ geometry databases in binary format to ASCII form to be later converted back by __[cmd]*asc2g(1)*__. Databases in the new format will be converted to the new (Tcl script) ASCII format and databases in the old format will be converted to the old ASCII format (see __HISTORY__).

The local machine binary representation of a mged database is inherently non-portable. _[cmd]*g2asc*_ and its converse, _[cmd]*asc2g*_ , are simple filters which convert between the binary form and an ASCII representation.

This was traditionally performed so the files could be transferred to another machine in a portable format.  Although no longer necessary for the current binary geometry database files that  are  created by  mged  ("v5"  format), the conversion process is still necessary if manipulating older ("v4" format) geometry database files.

[[_examples]]
== EXAMPLE

g2asc _file.g file.asc_

[quote]
On the local machine, convert the mged databases to ASCII using _[cmd]*g2asc*_ . 

scp _file.asc_ remote:__file.asc__

[quote]
Transfer the converted databases to the remote machine. 

ssh remote "asc2g __file.asc file.g__"

[quote]
On the remote machine, convert the files back to the binary representation for that machine using _[cmd]*asc2g*_ . 

== OPTIONS

_[cmd]*g2asc*_ does not take any options. However, you have to supply the input and output files.

== FILES

_input.g_ is a geometry database previously created using _[cmd]*mged*_ and _output.asc_ is the name of the file in which the ASCII representation should be stored.

== SEE ALSO

xref:man:1/asc2g.adoc[*asc2g*(1)], xref:man:1/brlcad.adoc[*brlcad*(1)], xref:man:1/mged.adoc[*mged*(1)]

== DIAGNOSTICS

The diagnostics are intended to be self-explanatory. Any warning messages are written to standard error.

== BUGS

Reports of bugs or problems should be submitted via e-mail to __mailto:devs@brlcad.org[]__.

== HISTORY

Release 6.0 introduced a new ASCII format. This format is simply a Tcl script that, when executed by a simplified geometry command interpreter (in essence, a properly empowered Tcl interpreter), rebuilds the database from which it was derived.

In contrast, the old ASCII format consisted of a sequence of one-line records that corresponded to the old database format records.

[[_author]]
== AUTHORS

_BRL-CAD Team_

== COPYRIGHT

This software is Copyright (c) 1989-2021 by the United States Government as represented by U.S. Army Research Laboratory.

== DISCLAIMER

The ASCII representation of BRL-CAD geometry databases is not a fixed format and is allowed to change without deprecation notice. In general, this will not occur any more frequently than the binary geometry database format changes, though both are open specifications. Regardless, the ASCII representation is subject to change without notice and should not be relied upon by external codes. (See __HISTORY__.)