= G_LINT(1)
ifndef::site-gen-antora[:doctype: manpage]
:man manual: BRL-CAD
:man source: BRL-CAD
:page-role: manpage

== NAME

glint - a BRL-CAD geometry checker

== SYNOPSIS

*glint*[_options_]_model.g__objects_...

== DESCRIPTION

[cmd]*glint* uses xref:man:3/librt.adoc[*librt*(3)] to fire an array of parallel rays at the specified __objects__ in the database __model.g__ and reports overlaps, vacuums, and potential problems with air regions. By default, the output consists of single-line reports, each of which contains a tag identifying the report type and then other data as appropriate for that type report. Unless the [opt]*-p* option is specified, the exact formats are:

_overlap___r1 r2 length x_in y_in z_in x_out y_out z_out__::
Consecutive partitions overlap by more than __tol__ (see the [opt]*-t* option). The data reported are the names of the two regions involved, the length of the overlap along the ray, and the model coordinates of the ray's entry into and exit from the overlap.

_air_contiguous___r1 a1 r2 a2 x y z__::
Consecutive partitions have unlike (nonzero) air codes and the space between them is less than __tol__ (see the [opt]*-t* option). The data reported are the names and air codes of the two regions involved and the model coordinates of the point of contiguity.

_air_unconfined___r1 (s1) r2 (s2) length x1 y1 z1 x2 y2 z2__::
A partition with nonzero air code follows or precedes another partition and the space between them is more than __tol__ (see the [opt]*-t* option). The data reported are the names of the two regions (and solids) involved, the length of the gap along the ray, and the model coordinates of the ray's exiting the first partition and entering the second.

_air_first___r a x y z__::
The first partition has a nonzero air code. The data reported are the name and air code of the region involved and the model coordinates of the ray's entering the partition.

_air_last___r a x y z__::
The last partition has a nonzero air code. The data reported are the name and air code of the region involved and the model coordinates of the ray's exiting the partition.

_vacuum___r1 (s1) r2 (s2) length x1 y1 z1 x2 y2 z2__::
The space between consecutive partitions is more than __tol__ (see the [opt]*-t* option). The data reported are the names of the two regions (and solids) involved, the length of the gap along the ray, and the model coordinates of the ray's exiting the first partition and entering the second.

[[_commandline_options]]
=== Command-line options

*-a*_az_::
Sets the azimuth from which to fire rays to __az__ degrees. The default is 0.

*-c*::
Specifies that one ray should be fired from the center of each grid cell. By default, [cmd]*glint* fires a ray from one random point in each cell.

*-e*_el_::
Sets the elevation from which to fire rays to __el__ degrees. The default is 0.

*-g*_gridsize_::
Sets the width and height of each grid cell to __gridsize__ millimeters. The default is 100 mm.

*-o*::
Causes [cmd]*glint* to include in each report the model coordinates of the ray origination point. These appear between the tag and the rest of the data.

*-p*::
Causes [cmd]*glint* to produce its reports as __plot3(5)__ drawing commands instead of ASCII text. This is useful in conjunction with the "overlay" command of __mged__.

*-r*_bits_::
Specifies which types of reports to produce. If, after an optional minus sign, __bits__ begins with either "0x" or "0X", the remainder is interpreted in hexadecimal. Otherwise, if __bits__ begins with "0", the remainder is interpreted in octal. Otherwise, __bits__ is interpreted in decimal. The meaning of the individual bits is as follows: 1 overlaps 2 contiguous unlike airs 4 unconfined airs 8 air first on rays 16 air last on rays 32 vacuums. If there was no initial minus sign, then __bits__ specifies which report types to produce. The minus sign implies complementation: when it is present, __bits__ specifies which report types __not__ to produce. The default is 1.

*-s*::
Causes [cmd]*glint* to collect all the overlap reports and sort them before printing them. The reports for a given pair of regions are printed contiguously, and the clusters of reports for the various pairs of regions appear in order of decreasing cumulative overlap length. By default, [cmd]*glint* reports overlaps immediately and in the order of their discovery.

*-t*_tol_::
Sets the tolerance for overlaps, contiguous and unconfined airs, and vacuums to __tol__ millimeters. The default is 0.

*-u*::
Sets the __useair__ member of the __rt_i__ structure to 1, which causes __librt__ to report partitions containing air. It is also set implicitly if any air-related reports have been specified. By default, __librt__ ignores air regions.

*-x*_bits_::
Sets the [cmd]*glint* debug flags to __bits__. See the [opt]*-r* option for more details. Note that some of the report types have no corresponding diagnostics.

== EXAMPLE

The command

glint -a 35 -e 25 -c -g 1 -r 31 -t 0.01 _kitchen.g appliances_

fires a ray every millimeter and produces overlap reports and every type of air-related report, but no vacuum reports.

== SEE ALSO

xref:man:1/mged.adoc[*mged*(1)], xref:man:3/librt.adoc[*librt*(3)], xref:man:3/strtoul.adoc[*strtoul*(3)], xref:man:5/plot3.adoc[*plot3*(5)]

== AUTHOR

BRL-CAD Team

== COPYRIGHT

This software is Copyright (c) 1995-2021 by the United States Government as represented by U.S. Army Research Laboratory.

== BUG REPORTS

Reports of bugs or problems should be submitted via electronic mail to mailto:devs@brlcad.org[]