= HALFTONE(1)
ifndef::site-gen-antora[:doctype: manpage]
:man manual: BRL-CAD
:man source: BRL-CAD
:page-role: manpage

== NAME

halftone - Translate a bw file to a halftoned bw file

== SYNOPSIS

*halftone*[-RSa][-s _squarefilesize_][-w _file_width_][-n _file_height_][-B _contrast_][-I _Number_Intensity_Levels_][-M _Method_][-T _Tone_Scale_Curve_Points_][-D _debug_level_]<_file.bw_

== DESCRIPTION

[cmd]*halftone* reads a xref:man:5/bw.adoc[*bw*(5)] format file from the named file, or from standard input if no file is specified, and reduces the number of intensity levels from 256 to a default of 2. [cmd]*halftone* tries to preserve as much information as possible by applying dither.

By default, the __bw__ file is assumed to be 512x512 pixels. 

If the [opt]*-R* flag is specified, random noise is added to the dither, and this can sometimes improve the results.

The [opt]*-S* flag causes a surpentine raster to be used rather than a left to right scan.

The [opt]*-a* flag is used when automatic file sizing is wanted.  This does not work on pipes.

The [opt]*-w*[rep]_file_width_ flag specifies the width of each scanline in the input file, in pixels.

The [opt]*-n*[rep]_file_height_ flag specifies the height in scanlines of the input file.

[opt]*-s*[rep]_squarefilesize_ sets both the height and width to the size given.

[opt]*-B*[rep]_contrast_ will define a floating point value to be used as the Beta portion of a edge sharpening algorithm.  The default is 0.0, which is no sharpening.

[opt]*-I*[rep]_Levels_ defines the number of different intensity levels to use on output.  The default is 2 (1 bit) and the max is 256 (8 bits).

[opt]*-M*[rep]_method_ allows a choice of dither methods.  The default is 0 a Floyd-Steinberg diffused error dither, 1 is a 45 degree classical clustered halftone screen, 2 is a simple threshold dither, 3 is a 0 degree dispersed halftone screen.

The [opt]*-T*[rep]_x1 y1 x2 y2 ..._ parameter is used to define a curve to be used as a tone scale.  The resulting curve is used to map input pixels to output pixels.  The default curve is -T  0 0 128 128 255 255; a curve suggested by Robert Ulichney in Digital Halftoning is -T  0  0  15  0  128  100  200  200  240  255  255  255.

[opt]*-D*[rep]_debug_level_ supplies the debug level; setting the argument to 9 provides all debugging. 

== FORMAT

A xref:man:5/bw.adoc[*bw*(5)] file contains sequences of pixels. Each pixel is stored as one __unsigned char.__ The first pixel in a __bw__ file is the lower left corner of the image. The pixels proceed from left-to-right across each scanline, with scanlines being written from the bottom to the top of the image.

The output from [cmd]*halftone* is scaled so that each intensity level is output as 255/Levels*value.

== SEE ALSO

xref:man:1/rt.adoc[*rt*(1)], xref:man:1/pix-bw.adoc[*pix-bw*(1)], xref:man:5/bw.adoc[*bw*(5)], xref:man:1/bw-fb.adoc[*bw-fb*(1)]

== AUTHOR

BRL-CAD Team

== COPYRIGHT

This software is Copyright (c) 1990-2021 by the United States Government as represented by U.S. Army Research Laboratory.

== BUG REPORTS

Reports of bugs or problems should be submitted via electronic mail to mailto:devs@brlcad.org[]