= NIRT(1)
BRL-CAD Team
:doctype: manpage
:man manual: BRL-CAD User Commands
:man source: BRL-CAD
:page-layout: base

== NAME

nirt - interactively ray trace a BRL-CAD geometric model

== SYNOPSIS

*nirt* [_options_] _model.g_ _objects_...

== DESCRIPTION

[cmd]*nirt* operates on the specified _objects_ in the database __model.g__, using xref:man:3/librt.adoc[*librt*(3)] to trace rays according to commands read from the standard input and producing an ASCII report of the results. By default, the user can interact with [cmd]*nirt*, repeatedly specifying origination points and directions for rays and the format and destination for the reports. Locations may be input and output in either model coordinates (__x__, __y__, __z__) or view (a.k.a. grid-plane) coordinates (__h__, __v__, __d__). Similarly, direction may be input and output either as vectors expressed in model coordinates or as angles of azimuth and elevation. 

=== Options

*-A [rep]_attribute_name..._*::
Adds the names to the list of attributes that will be reported when the "attributes" partition information value is specified. See also the _attr_	  command below. 

*-M*::
Causes [cmd]*nirt*	to read the eye point and either the orientation quaternion (new format) or the view-rotation matrix (old format) from the standard input, and fire a single ray from the point in the specified direction. This option allows [cmd]*nirt* to be called directly from within [cmd]*mged*	  using the [cmd]*nirt* and _rrt_ commands. 

*-b*::
Causes [cmd]*nirt* to perform a _backout_	  command before the first _shoot_	  command (see the description of these two commands below). This is probably only useful with the [opt]*-M*	  option. 

*-B*_rt_bot_minpieces_::
Causes [cmd]*nirt* to adjust the setting of _rt_bot_minpieces_	  to the indicated value. A value of zero here indicates that the "pieces" methodology should not be used. A value greater than zero indicates that all BOT primitives containing more than _rt_bot_minpieces_ triangles should be broken down into a separate piece for each triangle. This can result in significant improvement in raytrace speed at the cost of more memory use. 

*-e*_script_::
Causes [cmd]*nirt* to run the _script_	  string before reading the standard input. Multiple commands in _script_  may be separated with a semicolon ';'. Scripts specified with either the [opt]*-e* or [opt]*-f*	  options are executed in the order in which they are specified on the command line. 

*-f*_format_::
Causes [cmd]*nirt* to load the predefined format (see [opt]*-L*) _format_ or script file before reading standard input.  Scripts specified with either the [opt]*-e* or [opt]*-f* options are executed in the order in which they are specified on the command line. 

*-E*::
Causes [cmd]*nirt* to ignore any [opt]*-e* or [opt]*-f*	  options specified previously on the command line. 

*-L*::
List output formatting options. 

*-s*::
Causes [cmd]*nirt* to run in silent (that is, non-verbose) mode. In this mode,	which is useful in a pipeline,[cmd]*nirt*	  does not print its initial lines of output or the prompt. 

*-v*::
Causes [cmd]*nirt* to run in verbose mode. The default is verbose mode, except if standard input has been redirected, in which case the default is silent mode. 

*-H*_n_::
Set flag (__n__) for enable/disable informational header (__n__=1 [on] by default, always off in silent mode). 

*-u*_n_::
Sets the _useair_ member	of the _rt_i_ structure to __n__. See the discussion of the _useair_	  command below. 

*-O*_n_::
Causes [cmd]*nirt* to handle multiple regions' claims to segments of a ray according to action __n__.	The argument _n_ may be any of the values 0, 1, 2, or 3, or their corresponding key words "resolve", "rebuild_fastgen", "rebuild_all", or "retain". See the discussion of the _overlap_claims_	  command below. 

*-x*_v_::
Sets the xref:man:3/librt.adoc[*librt*(3)]	  debug flags to the hexadecimal bit vector __v__. See the discussion of the _libdebug_	  command below. 

*-X*_v_::
Sets [cmd]*nirt*'s own debug flags to the hexadecimal bit vector __v__. See the discussion of the _debug_ command below. 

[cmd]*nirt* will check in two places for a [path]_.nirtrc_ file - first in the current directory, and if it is not found there, in the user's home directory. If found, [cmd]*nirt* begins by reading from it.  This start-up file may contain any [cmd]*nirt* commands and is useful for loading predefined states or initializing actions for output statements. 

=== Commands

__xyz [____x y z____]__::
Sets the ray origination point to (__x__, __y__, __z__). If this command is invoked with no arguments, [cmd]*nirt* prints the current ray origination point in model coordinates. Default is (0, 0, 0). Changing (__x__, __y__, __z__) will change (__h__, __v__, __d__), according to the current direction vector. 

_hv [___h v____[____d____]]__::
Sets the ray origination point to (__h__, __v__, __d__). If this command is invoked with only two arguments, [cmd]*nirt*	  interprets them as _h_ and __v__, and _d_ retains its previous value. If invoked with no argument, the command causes [cmd]*nirt*	  to print the current ray origination point in view coordinates. Default is (0, 0, 0).  Changing (__h__, __v__, __d__) will change (__x__, __y__, __z__), according to the current direction vector. 

__dir [____dx dy dz____]__::
Sets the direction vector to the unit vector in direction (__dx__, __dy__, __dz__). If this command is invoked with no arguments, [cmd]*nirt* prints the current direction vector.  Default is (-1, 0, 0).  Changing (__dx__, __dy__, __dz__) will change the azimuth and elevation angles. 

__ae [____az el____]__::
Sets the direction vector to point _from_	azimuth = _az_ and elevation = __el__. If this command is invoked with no arguments, [cmd]*nirt*	prints the current values of the azimuth and elevation angles. Default is (0, 0).  Changing azimuth and elevation will change the direction vector. 

_s_::
Fires a ray from the current origination point in the current direction. 

__bot_minpieces [____n____]__::
Sets "rt_bot_minpieces" to the new value __n__. If _n_ is not provided, the current value of "rt_bot_minpieces" is displayed.  See the discussion of the [opt]*-B* option above for more details. 

__backout [____n____]__::
Command to set the backout flag.  With no option, prints the current value. When activated, backs the ray origination point out of the geometry: _h_ and _v_	retain their previous values and _d_ is set to __Dmax__, the largest value of _d_  anywhere in the geometry.  Default is 0 (deactivated), 1 is active. 

__useair [____n____]__::
Sets the _useair_ member  of the _rt_i_	structure to the integer __n__.  If _n_ is 0, then [cmd]*nirt* ignores any air in the geometry.  If this command is invoked with no arguments, [cmd]*nirt* prints the current value of __useair__. Default is 0. 

__overlap_claims [____n____]__::
Specifies how to handle multiple regions' claims to segments of a ray. If _n_ is 0 or "resolve", then all overlaps are resolved in favor of a single region  and any other claimants are ignored.  If _n_ is 2 or "rebuild_all", then all overlaps are rebuilt, so any overlapping regions along the ray create individual (geometrically intersecting) partitions.  If _n_ is 3 or "retain", then all overlaps are retained. In this case, the resulting partitions are always geometrically disjoint,  each one is owned by a single region according to the current overlap resolution strategy, but every claimant is recorded. If _n_ is 1 or "rebuild_fastgen", then [cmd]*nirt* takes on _FASTGEN_ behavior, so overlaps of plate-mode primitives are rebuilt, but other overlaps are retained. This command is useful with the __claimant_count__, __claimant_list__, and _claimant_listn_	output items.  Default is "resolve". 

_attr {-f|-p|attr_names...}_::
When used with one or more names, adds the names to the list of attributes that will be printed when the "attributes" value is requested in the output format string. 
+
The [opt]*-p* option to the [cmd]*attr* command causes it to print the list of attributes that will be reported. 
+
The [opt]*-f*  option clears the attributes table. 

__units [____u____]__::
Causes [cmd]*nirt* to read and write all distances and locations in units of __u__.  Valid choices for _u_	are "mm"; "cm"; "m"; "in"; and "ft".   If this command is invoked with no arguments, [cmd]*nirt*  prints the current choice of I/O units.  Default is the units of __model.g__. 

__fmt [____t format item item ...____]__::
Sets the action for output statements of type __t__. If this command is invoked with only one argument, a valid statement type, [cmd]*nirt* prints the current format and items for the specified type. See the discussion of output statements below. 

__dest [____d____]__::
Sets the destination for subsequent output actions to __d__. If the first character of _d_ is `|', then _d_ is interpreted as a pipeline to which to write its output. Otherwise, if _d_ is the string "default", [cmd]*nirt* sets the destination to the standard output. Otherwise, _d_ is interpreted as a file. In any event, _d_ is not closed until the user quits [cmd]*nirt* or resets the destination by another invocation of the _dest_ command. If this command is invoked with no arguments, [cmd]*nirt* prints the current value of __d__. Default is "default", that is, the standard output. 

__statefile [____f____]__::
Sets the name of the state file to which to dump and from which to load state information. See the discussion of the _dump_ and _load_	commands below.  If this command is invoked with no arguments, [cmd]*nirt*	prints the current name of the state file.  Default is "nirt_state". 

_dump_::
Writes state information to the state file.  The ray origination point and direction vector, useair, units, destination, and all the output actions are dumped. 

_load_::
Reads state information from the state file.  The state file loaded may contain any [cmd]*nirt* commands. 

_print___item__::
Prints the current value of the output item __item__. See the discussion of output statements below. 

_libdebug___v__::
Sets the xref:man:3/librt.adoc[*librt*(3)]	debug flags (the _debug_ member of the _rt_g_	structure) to the hexadecimal bit vector __v__. These flags control the amount and kind of diagnostic print statements xref:man:3/librt.adoc[*librt*(3)] executes.  If _v_ is 0, then no diagnostics are produced. If this command is invoked with no arguments, [cmd]*nirt* prints the current value of _v_	and the names of any of its bits that are set.  Default is 0. 

_debug___v__::
Sets [cmd]*nirt*'s internal debug flags to the hexadecimal bit vector __v__.  These flags control the amount and kind of diagnostic print statements [cmd]*nirt* executes.  If _v_ is 0, then no diagnostics are produced.  If this command is invoked with no arguments, [cmd]*nirt* prints the current value of _v_	and the names of any of its bits that are set.  Default is 0. 

_?_::
Prints a help menu to the standard output. 

_q_::
Quits [cmd]*nirt*. 

=== Output Statements

[cmd]*nirt* allows the user a high degree of control, via the _fmt_ command, over what information gets printed out for each ray and in what format. There are six types of output statements, each of which is executed under appropriate circumstances. The types and their use are: 

_r_::
Ray. The first output statement executed whenever the _s_ command is invoked. 

_h_::
Head.  Executed immediately after the ray statement if the ray hits anything. 

_p_::
Partition.  Executed once for each partition along the ray if the ray hits anything. 

_f_::
Foot. The last output statement executed if the ray hits anything. 

_m_::
Miss.  Executed immediately after the ray statement if the ray hits nothing. 

_o_::
Overlap.  Executed once for each overlap along the ray if the ray hits anything. 

_g_::
Gap.  Executed once for each gap along the ray if the ray encounters any gaps. 

The action associated with each output statement type is essentially a xref:man:3/printf.adoc[*printf*(3)] statement, with a format string and a list of output items. The items may be chosen from a set of values that [cmd]*nirt* updates according to user commands and location along the ray. These values may be categorized as pertaining to the entire ray,  partitions along the ray, or overlaps.  The values are explained in the following table. 

Ray Information

_x_orig_::
_x_ coordinate of ray origination point.

_y_orig_::
_y_ coordinate of ray origination point.

_z_orig_::
_z_ coordinate of ray origination point.

_d_orig_::
_d_ coordinate of ray origination point.

_h_::
_h_ coordinate for the entire ray.

_v_::
_v_ coordinate for the entire ray.

_x_dir_::
_x_ component of direction vector.

_y_dir_::
_y_ component of direction vector.

_z_dir_::
_z_ component of direction vector.

_a_::
azimuth of view (i.e., of ray direction).

_e_::
elevation of view (i.e., of ray direction).

Partition Information

_attributes_::
A string variable consisting of the names and values of the attributes requested by the _attr_	command or the [opt]*-A*	command line option.

_x_in_::
_x_ coordinate of entry into current region.

_y_in_::
_y_ coordinate of entry into current region.

_z_in_::
_z_ coordinate of entry into current region.

_d_in_::
_d_ coordinate of entry into current region.

_x_out_::
_x_ coordinate of exit from current region.

_y_out_::
_y_ coordinate of exit from current region.

_z_out_::
_z_ coordinate of exit from current region.

_d_out_::
_d_ coordinate of exit from current region.

_los_::
line-of-sight distance through current region.

_scaled_los_::
scaled line of sight: product of line-of-sight distance through current region and region solidity (sometimes called "percent LOS").

_path_name_::
full path name of current region.

_reg_name_::
name of current region, as might be obtained by passing _path_name_	to xref:man:1/basename.adoc[*basename*(1)].

_reg_id_::
region ID of current region.

_claimant_count_::
number of regions claiming this partition (that is, participating in a retained overlap).

_claimant_list_::
space-separated list of names of regions claiming this partition (that is, participating in a retained overlap).

_claimant_listn_::
Same as __claimant_list__, except that it is newline-, rather than space-separated.

_obliq_in_::
entry obliquity for current region.

_obliq_out_::
exit obliquity for current region.

_nm_x_in_::
_x_ component of entry normal vector

_nm_y_in_::
_y_ component of entry normal vector

_nm_z_in_::
_z_ component of entry normal vector

_nm_h_in_::
_h_ component of entry normal vector

_nm_v_in_::
_v_ component of entry normal vector

_nm_d_in_::
_d_ component of entry normal vector

_nm_x_out_::
_x_ component of exit normal vector

_nm_y_out_::
_y_ component of exit normal vector

_nm_z_out_::
_z_ component of exit normal vector

_nm_h_out_::
_h_ component of exit normal vector

_nm_v_out_::
_v_ component of exit normal vector

_nm_d_out_::
_d_ component of exit normal vector

_surf_num_in_::
entry-surface ID of entry solid.

_surf_num_out_::
exit-surface ID of exit solid.

Gap Information

_x_gap_in_::
_x_ coordinate of entry into gap.

_y_gap_in_::
_y_ coordinate of entry into gap.

_z_gap_in_::
_z_ coordinate of entry into gap.

_gap_los_::
line-of-sight distance through gap.

Overlap Information

_ov_reg1_name_::
name of one of the overlapping regions.

_ov_reg2_name_::
name of the other overlapping region.

_ov_reg1_id_::
region ID of one of the overlapping regions.

_ov_reg2_id_::
region ID of the other overlapping region.

_ov_sol_in_::
name of one of the overlapping solids.

_ov_sol_out_::
name of the other overlapping solid.

_ov_los_::
line-of-sight distance through the overlap.

_ov_x_in_::
_x_ coordinate of entry into overlap.

_ov_y_in_::
_y_ coordinate of entry into overlap.

_ov_z_in_::
_z_ coordinate of entry into overlap.

_ov_d_in_::
_d_ coordinate of entry into overlap.

_ov_x_out_::
_x_ coordinate of exit from overlap.

_ov_y_out_::
_y_ coordinate of exit from overlap.

_ov_z_out_::
_z_ coordinate of exit from overlap.

_ov_d_out_::
_d_ coordinate of exit from overlap.

== HINTS

Ray origination coordinates specified with the _hv_ command are immediately converted for internal use  to model coordinates, according to the current direction vector.  If you want to change the ray direction and origination point, and you're using view coordinates, you probably want to change the ray direction _before_ you use the _hv_ command. 

The name "nirt" stands for "Natalie's interactive ray tracer". 

== DEFINITIONS

The usage in [cmd]*nirt* of the following terms corresponds to that found in xref:man:1/mged.adoc[*mged*(1)] and elsewhere throughout BRL-CAD. We provide the definitions here for reference. 

=== View Coordinates

We define the view coordinate system (more precisely its basis vectors __m__, __n__, and __o__) in terms of the basis vectors __i__, __j__, and _k_ of the model coordinate system as follows: 

_m_ is the opposite of the direction vector and corresponds to __d__, _n_ = _k_ × _m_ corresponds to __h__, and _o_ = _m_ × _n_ corresponds to __v__. 

Thus if the direction vector is (-1, 0, 0), then (__d__, __h__, __v__) = (__x__, __y__, __z__). 

=== Azimuth and Elevation

Azimuth is the angle measured around _k_ (right-hand rule) from the _xz_ plane to __m__. Elevation is the angle measured toward _k_ from the _xy_ plane to __m__. 

== FILES

_~/.nirtrc_::
run-time configuration file

== SEE ALSO

xref:man:1/mged.adoc[*mged*(1)], xref:man:3/librt.adoc[*librt*(3)], xref:man:3/printf.adoc[*printf*(3)]

== AUTHOR

BRL-CAD Team

== COPYRIGHT

This software is Copyright (c) 1984-2021 United States Government as represented by the U.S. Army Research Laboratory.

== BUG REPORTS

Reports of bugs or problems should be submitted via electronic mail to mailto:devs@brlcad.org[]