= PIX-PS(1)
BRL-CAD Team
ifndef::site-gen-antora[:doctype: manpage]
:man manual: BRL-CAD
:man source: BRL-CAD
:page-role: manpage

== NAME

pix-ps - convert a color pix file to PostScript

== SYNOPSIS

*pix-ps*[-e][-c|-l][-L][-s _input_squaresize_][-w _input_width_][-n _input_height_][-S _inches_square_][-W _inches_width_][-N _inches_height_][_infile.pix_]>_outfile.ps_

== DESCRIPTION

[cmd]*pix-ps* will take a color xref:man:5/pix.adoc[*pix*(5)] format file of given dimensions and produce a Postscript file on the standard output. The [opt]*-w* and [opt]*-n* flags specify the input file width and number of scan lines in pixels. They can both be set to the same value via [opt]*-s.* If no input size is given, defaults of 512 are assumed.

By default the output PostScript image size is 6.75 inches. The [opt]*-c* option (on by default) will center it on a 8.5 x 11 inch page; otherwise, the [opt]*-l* option uses the lower left corner. If a different output size is desired, [opt]*-S*, [opt]*-W*, and [opt]*-N* can be used to set the size in inches analogous to the input parameters. Finally, [opt]*-L* selects landscape mode, i.e. rotates the output image by ninety degrees.

Encapsulated PostScript files can be generated via [opt]*-e.*

== EXAMPLES

pix-ps -c image.pix > image.ps

Produces a 6.75 inch PostScript file from a 512x512 input image and centers it on an 8.5 x 11 inch page.

pix-ps -e -w 1024 -n 768 image.pix > image.ps

Takes the file image.pix which has the dimensions of 1024 pixels wide by 768 pixels high, and produces an Encapsulated Postscript version of it.

pix-ps -L -c -S 5.2 < image.pix > image.ps

Makes a PostScript file of the (assumed 512x512) image, with the output image 5.2 inches square, in landscape mode, centered on an 8.5 x 11 inch page.

== SEE ALSO

xref:man:1/brlcad.adoc[*brlcad*(1)], xref:man:1/bw-ps.adoc[*bw-ps*(1)], xref:man:5/pix.adoc[*pix*(5)]

== AUTHOR

BRL-CAD Team

== COPYRIGHT

This software is Copyright (c) 1991-2021 by the United States Government as represented by U.S. Army Research Laboratory.

== BUG REPORTS

Reports of bugs or problems should be submitted via electronic mail to mailto:devs@brlcad.org[]