= PIX2ASC/ASC2PIX(1)
BRL-CAD Team
ifndef::site-gen-antora[:doctype: manpage]
:man manual: BRL-CAD
:man source: BRL-CAD
:page-role: manpage

== NAME

pix2asc - encode and decode color pixel files

== SYNOPSIS

*pix2asc*<_file.pix_>_file.asc_
*asc2pix*<_file.asc_>_file.pix_

== DESCRIPTION

[cmd]*pix2asc* and [cmd]*asc2pix* are simple filters which convert color __pix(5)__ files from their binary form to a portable ASCII form, and back. [cmd]*pix2asc* reads the binary file on standard in and writes ASCII on standard out. [cmd]*asc2pix* does the reverse.

The binary file consists of a sequence of three-tuples of __unsigned chars__ representing the red, green, and blue intensities for each pixel. The ASCII version of the file has one RGB pixel per newline-terminated line, with each pixel represented as six hexadecimal digits.

When moving __pix(5)__ files between UNIX systems via tape (see __tar(1)__ and __cpio(1)__) or via network (see __rcp(1)__ and __ftp(1)__), this conversion to ASCII is unnecessary, as all UNIX files are byte streams, regardless of the underlying hardware. However, when transporting images to non-UNIX machines, these tools are invaluable. Note that xref:man:1/rt.adoc[*rt*(1)] can directly generate the ASCII form of an image file using the [opt]*-O* flag, allowing it to be easily used on non-UNIX systems.

== SEE ALSO

xref:man:1/brlcad.adoc[*brlcad*(1)], xref:man:5/pix.adoc[*pix*(5)], xref:man:5/bw.adoc[*bw*(5)]

== AUTHOR

_BRL-CAD Team_

== COPYRIGHT

This software is Copyright (c) 1989-2021 by the United States Government as represented by U.S. Army Research Laboratory.

== BUG REPORTS

Reports of bugs or problems should be submitted via electronic mail to mailto:devs@brlcad.org[]