= PIXAUTOSIZE(1)
ifndef::site-gen-antora[:doctype: manpage]
:man manual: BRL-CAD
:man source: BRL-CAD
:page-role: manpage

== NAME

pixautosize - determine if a file size or byte count is a standard image size

== SYNOPSIS

*pixautosize* [-b _bytes_per_sample_] [-f _file_name_] [-l _file_length_]

== DESCRIPTION

[cmd]*pixautosize* determines if a given file is one of the standard sizes used in the BRL-CAD package, _i.e._ one of the sizes recognized by the [opt]*-a* option on xref:man:1/pix-fb.adoc[*pix-fb*(1)]. If the dimensions are recognized, it prints a string suitable for use in a Bourne shell xref:man:1/sh.adoc[*sh*(1)] script to set the variables WIDTH and HEIGHT, _e.g._

WIDTH=512; HEIGHT=512

The file name can be specified by using the [opt]*-f*[rep]_file_name_ commandline option, or the file length (in bytes) can be specified by using the [opt]*-l*[rep]_file_length_ commandline option. One of these two options must be present. In either case, the [opt]*-b*[rep]_bytes_per_sample_ option can be used to specify the number of bytes which are used for each sample (pixel) in the file. The default value is three (3), which is appropriate for use with xref:man:5/pix.adoc[*pix*(5)] files. This should be changed to one with [opt]*-b*`1` when processing a xref:man:5/bw.adoc[*bw*(5)] file. Similarly, the proper value for a xref:man:5/dbw.adoc[*dbw*(5)] file is 8 (1 channel of 8 byte samples), and the value for xref:man:5/dpix.adoc[*dpix*(5)] files is 24 (3 channels of 8 byte samples).

== EXAMPLES

These two examples both give the result of

WIDTH=50; HEIGHT=50;

the first could be for a xref:man:5/bw.adoc[*bw*(5)] file and the second for a xref:man:5/pix.adoc[*pix*(5)] file:

pixautosize -b 1 -l 2500

pixautosize -b 3 -l 7500

This example shows how to determine the size of a xref:man:5/pix.adoc[*pix*(5)] file by giving the file name:

pixautosize -b 3 -f ../pix/moss.pix

with the result being

WIDTH=512; HEIGHT=512

This command can be used easily in shell scripts with a line like this:

eval `pixautosize -b 3 -f $FILE`	# sets WIDTH, HEIGHT

For a major shell script which uses this program, examine xref:man:1/pixinfo.sh.adoc[*pixinfo.sh*(1)] .

== SEE ALSO

pixinfo.xref:man:1/sh.adoc[*sh*(1)], xref:man:1/pix-fb.adoc[*pix-fb*(1)], xref:man:3/libfb.adoc[*libfb*(3)], xref:man:5/bw.adoc[*bw*(5)], xref:man:5/pix.adoc[*pix*(5)]

== DIAGNOSTICS

If the file or file_length specified does not match any of the standard sizes, one of these messages is printed on standard error:

pixautosize: unable to autosize nsamples=999

pixautosize: unable to autosize file '/dev/null'

In this case, the string printed on standard output is:

WIDTH=0; HEIGHT=0

== AUTHOR

BRL-CAD Team

== COPYRIGHT

This software is Copyright (c) 1992-2021 by the United States Government as represented by U.S. Army Research Laboratory.

== BUG REPORTS

Reports of bugs or problems should be submitted via electronic mail to mailto:devs@brlcad.org[]