= PIXBACKGND(1)
BRL-CAD Team
:doctype: manpage
:man manual: BRL-CAD
:man source: BRL-CAD
:page-layout: base

== NAME

pixbackgnd - generate a pix(5) shaded background

== SYNOPSIS

*pixbackgnd*[-H][-i][-s _squaresize_][-w _width_][-n _height_][-t _title_height_][-a _top_inten_][-b _bottom_inten_]_hue__saturation_>_file.pix_
*pixbackgnd*[-H][-i][-s _squaresize_][-w _width_][-n _height_][-t _title_height_]_red__green__blue_>_file.pix_

== DESCRIPTION

[cmd]*pixbackgnd* generates a xref:man:5/pix.adoc[*pix*(5)] format shaded background on stdout suitable for making slides for a presentation on. The upper portion of the screen is reserved for a title area, and is drawn at constant intensity 240, followed by a 4 scanline white bar, after which the intensity smoothly decreases from 240 to 50. The values of __hue__ and __saturation__ range from 0 to 255 inclusive and can be selected via xref:man:1/fbcolor.adoc[*fbcolor*(1)]. A hue of 160 is a pleasing blue.

The [opt]*-a* and [opt]*-b* options can be used to set the top and bottom intensity, in the range of 0 to 255. By default, the top intensity is 240, and the bottom is 50 (these values are used above).

[opt]*-w* and [opt]*-n* options set the width and height, respectively; [opt]*-s* sets them to the same value. By default, the display is assumed to be 512x512 pixels; specifying the [opt]*-H* flag, in addition to changing the title height to 90 scanlines (see below), changes the output size to 1024x1024.

By default, the title height is 80 scanlines, or 90 scanlines if the [opt]*-H* flag is set, but the [opt]*-t*[rep]_title_height_ option may be used to specify another value. If __title_height__ is set to zero, then the white bar is omitted as well, and the entire display is smoothly shaded.

If the [opt]*-i* flag is specified, the scanlines will be written out in inverted order (i.e., top to bottom).

== EXAMPLES

pixbackgnd 160 200  |   pixmerge fg.pix - | pix-fb

pixbackgnd -t120 160 250

pixbackgnd -i -t0 160 200   |   pix-fb

== SEE ALSO

xref:man:1/brlcad.adoc[*brlcad*(1)], xref:man:1/fbcolor.adoc[*fbcolor*(1)], xref:man:1/pix-fb.adoc[*pix-fb*(1)], xref:man:1/pixmerge.adoc[*pixmerge*(1)]

== BUGS

The starting and ending intensities should probably be an option.

== AUTHOR

BRL-CAD Team

== COPYRIGHT

This software is Copyright (c) 1989-2021 by the United States Government as represented by U.S. Army Research Laboratory.

== BUG REPORTS

Reports of bugs or problems should be submitted via electronic mail to mailto:devs@brlcad.org[]