= PIXFILTER(1)
BRL-CAD Team
:doctype: manpage
:man manual: BRL-CAD
:man source: BRL-CAD
:page-layout: base

== NAME

pixfilter - apply a 3x3 filter to a color pix file

== SYNOPSIS

*pixfilter*[-f _type_][-v][-d _div_][-o _offset_][-w _width_][-n _height_][-s _squaresize_][_file.pix_]>_newfile.pix_

== DESCRIPTION

[cmd]*pixfilter* applies one of several 3x3 kernel filters to a color xref:man:5/pix.adoc[*pix*(5)] format file. It will take a file name or else read from standard input. The input file size will be assumed to be 512 by 512 pixels unless the [opt]*-w*, and/or [opt]*-n*, or the [opt]*-s* flags are used to tell it otherwise. By default a low pass filter is used.  The [opt]*-f*[rep]_type_ flag can be used to specify a different type of filter.

The __type__ choices include:

_lo_::
low pass (the default)

_hi_::
high pass

_vg_::
vertical gradient

_hg_::
horizontal gradient

_la_::
laplacian

_b_::
boxcar low pass

Most filters divide the result of the kernel multiplication by some value in order to scale it back to a 0->255 range. For example, the boxcar divides by nine.  The [opt]*-d* flag can be used to change this divisor. Some filters also add an offset to their results.  The output of a laplacian for example is "centered" about zero, thus it adds 128 to the answer to yield a difference from neutral grey. The [opt]*-o* flag can be used to change this offset.

The [opt]*-v* flag displays the kernel values on standard error.

== SEE ALSO

xref:man:1/brlcad.adoc[*brlcad*(1)], xref:man:1/pixscale.adoc[*pixscale*(1)], xref:man:5/pix.adoc[*pix*(5)]

== BUGS

This should allow any 3x3 kernel to be specified.

== AUTHOR

BRL-CAD Team

== COPYRIGHT

This software is Copyright (c) 1989-2021 by the United States Government as represented by U.S. Army Research Laboratory.

== BUG REPORTS

Reports of bugs or problems should be submitted via electronic mail to mailto:devs@brlcad.org[]