= PIXMORPH(1)
ifndef::site-gen-antora[:doctype: manpage]
:man manual: BRL-CAD
:man source: BRL-CAD
:page-role: manpage

== NAME

pixmorph - morph two pix(5) images

== SYNOPSIS

*pixmorph*[-w _width_][-n _height_]_picA.pix__picB.pix__linesfile__warpfrac__dissolvefrac_>_out.pix_

== DESCRIPTION

[cmd]*pixmorph* performs feature-based image metamorphosis between "picA.pix" and "picB.pix". The feature correspondences are specified in the file "linesfile", which can be created using a utility such as __morphedit.tcl__ (see __morphedit(1)__).

The output image is computed in the following fashion. First, for each pixel in the output image, we choose a set __A__ of pixels (and associated weights) from "picA.pix" and another set __B__ of pixels from "picB.pix" (how these sets and weights are chosen will be described momentarily). The pixel values from __A__ are then averaged (using the associated weights) to determine the contribution __cA__ from the original image; the contribution __cB__ is computed similarly.  Then, the values __cA__ and __cB__ are interpolated by the value __dissolvefrac__ to compute the final value of the output pixel.

Now, the contribution __cA__ from the original image is intended to be the value from __picA.pix__ that gets "warped to" the location in question. It is this computation (more specifically, the computation of __A__ and associated weights) that is the heart of the morphing algorithm, and is described briefly here.

First, the linesfile is processed.  The linesfile is of the form a b p n lineseg1_initial lineseg1_final lineseg2_initial lineseg2_final linesegn_initial linesegn_final , where __n__ equals the number of line segments, and __a__, __b__, and __p__ are constants that alter the nature of the morph. A line segment is represented as a list of four real numbers (and is interpreted as a directed line segment). For example, 0.1 2.0 0.2 2 0.714844 0.560547 0.988281 0.277344 0.347656 0.646484 0.654297 0.896484 0.341797 0.611328 0.757812 0.265625 0.628906 0.519531 0.925781 0.763672 is a valid lines file. Typically, the pairs __linesegi_initial linesegi_final__ have been placed by the user in the lines file to match up particular features of __picA.pix__ and __picB.pix__ (the feature at __linesegi_initial__ in __picA.pix__ corresponds to the feature at __linesegi_final__ in __picB.pix__). For instance, __lineseg1_initial__ might be a line segment running down the length of the nose of a person displayed in __picA.pix__; then __lineseg1_final__ would be a line segment running down the length of the nose of the person featured in __picB.pix__. See __morphedit(1)__ for more information about creating a lines file.

Now, for each line segment pair __(s,t)__, we perform the following procedure: We interpolate between __s__ and __t__ by factor __warpfrac__ to yield the interpolated line segment __s'__. From the change in position, scale, and orientation of a line segment from its initial position __s__ to its interpolated counterpart __s'__ we may deduce a linear transformation in the image space. More specifically, if the line segment __s__ must undergo translation, stretching, and rotation to yield __s'__, we compute a linear transformation __T__ of the image space that performs the same translation, stretching, and rotation. (So __T__ applied to __s__ yields __s'__.) The inverse __T*__ of this transformation maps __s'__ to __s__; for instance, __T*__ will take an endpoint of __s'__ to the corresponding endpoint of __s__, and will preserve the relationship of every other point to the line segment. We apply this inverse __T*__ to the coordinates __(x,y)__ to find an appropriate pixel in the original image. Along with this, we compute a weight based on the length of the line segment __s__ along with its distance from __(x,y)__. This weight is equal to ( (length ** p) / (a + dist) ) ** b (where __\**__ denotes exponentiation, __length__ is the length of __s__, __dist__ is the distance from __s__ to __(x,y)__, and __a__, __b__, __p__ are constants chosen by the user and stored in the lines file).

The set __A__ of pixels is then collected by performing these computations for each line segment, and the resulting contribution __cA__ is then computed by averaging over __A__ with the appropriate weights.

In practice, __a__ = 0.1, __b__ = 2.0, and __p__ = 0.2 seems to work well.

In general, the user will wish to set __warpfrac__ = __dissolvefrac__. Typically, a morph animation will be produced by computing a sequence of images using __pixmorph__, each with slightly greater __warpfrac__ (and __dissolvefrac__) (see the example). For a clearer and more thorough explanation, see T. Beier and S. Neely, Feature-Based Image Metamorphosis, "SIGGRAPH 1992 Computer Graphics Proceedings (volume 26 number 2)", (Chicago, July 26-31, 1992), pp 35-42, which presents the algorithm used by __pixmorph__.

== OPTIONS

*-w*_WIDTH_::
Tells [cmd]*pixmorph* that the input images have width WIDTH.

*-n*_HEIGHT_::
Tells [cmd]*pixmorph* that the input images have height HEIGHT.

== EXAMPLES

pixmorph face1.pix face2.pix lf 0.0 0.0 > frame0.pix

pixmorph face1.pix face2.pix lf 0.2 0.2 > frame1.pix

pixmorph face1.pix face2.pix lf 0.4 0.4 > frame2.pix

pixmorph face1.pix face2.pix lf 0.6 0.6 > frame3.pix

pixmorph face1.pix face2.pix lf 0.8 0.8 > frame4.pix

pixmorph face1.pix face2.pix lf 1.0 1.0 > frame5.pix

Note that the example above will result in __frame0.pix__ = __face1.pix__ and __frame5.pix__ = __face2.pix__.

pixmorph face1.pix face2.pix lf 0.5 0.0 > out.pix

Note that in this example, __dissolvefrac__ = 0. This will warp __face1.pix__ and __face2.pix__ by the appropriate amount, but will ignore the contributions of __face2.pix__ at the cross-dissolve stage. So the final image __out.pix__ will consist entirely of values from __face1.pix__ warped 50% according to the linesfile __lf__.

pixmorph face1.pix face2.pix lf 0.0 0.5 > out.pix

In this example, __warpfrac__ = 0. This will perform a simple 50% cross-dissolve between __face1.pix__ and __face2.pix__.

== SEE ALSO

xref:man:1/brlcad.adoc[*brlcad*(1)], xref:man:1/morphedit.adoc[*morphedit*(1)], xref:man:5/pix.adoc[*pix*(5)]

== AUTHOR

BRL-CAD Team

== COPYRIGHT

This software is Copyright (c) 1996-2021 by the United States Government as represented by U.S. Army Research Laboratory.

== BUG REPORTS

Reports of bugs or problems should be submitted via electronic mail to mailto:devs@brlcad.org[]