= PIXMATTE(1)
BRL-CAD Team
:doctype: manpage
:man manual: BRL-CAD
:man source: BRL-CAD
:page-layout: base

== NAME

pixmatte - matte (merge) two pix(5) or bw(5) images by a formula

== SYNOPSIS

*pixmatte*[-a][-w _bytes_wide_][-glen]_in1__in2__true_out__false_out_>_output_

== DESCRIPTION

Given four streams of data elements, where element is of arbitrary width, typically xref:man:5/pix.adoc[*pix*(5)] or xref:man:5/bw.adoc[*bw*(5)] images, [cmd]*pixmatte* outputs a stream of the same number of data elements. The value of the output stream is determined element-by-element, by comparing the first (foreground) input stream with the second (background, or matte) input stream. If the formula holds true, the element from the true-output stream is written, otherwise, the element from the false-output stream is written. Each of these streams comes from a file, or is given as a constant. A particular file may be used to feed more than one stream, and the name '-' specifies stdin. For example, the foreground file may also be the true-output file. This routine operates on an element-by-element basis, and thus is independent of the resolution of the image.

A constant value is specified instead of a filename if the first character of what would be the filename is an equal sign (=). The value is specified as a slash-separated string of [rep]_bytes_wide_ decimal numbers, with no separating white space. If in1 and in2 are both specified as constant values, the output file will be 512 x 512. 

The formula can be any combination of [opt]*-g* (in1 greater than in2), [opt]*-l* (in1 less than in2), [opt]*-e* (in1 equal to in2), [opt]*-n* (in1 not equal to in2). For example: [opt]*-ge* specifies in1 greater than or equal to in2; that is, when each byte of the in1 element is greater than or equal to the corresponding byte of the in2 element. 

The [opt]*-a* flag can be used with [opt]*-n* or [opt]*-e* to specify approximately equal or approximately not equal to match dithered backgrounds. (Approximate equality exists when all bytes in the elements match to within plus or minus one.)  It can also be used in combination with [opt]*-g* and/or [opt]*-l*; the effect of this usage is to exclude those elements which meet the approximately-equal criterion. If [opt]*-a* is used, at least one of [opt]*-g*, [opt]*-l*, [opt]*-e*, [opt]*-n* must be used.

The [opt]*-w#* flag specifies the width (in bytes) of each element;  the default is 3, _i.e._xref:man:5/pix.adoc[*pix*(5)] file format.  A width of 1 is used for processing xref:man:5/bw.adoc[*bw*(5)] files.  It is unclear if other widths are useful.

== EXAMPLES

To compare all foreground pixels to black (all bytes zero), selecting the foreground pixels when true and a background elsewhere, specify:

pixmatte -g fg.pix =0/0/0 fg.pix bg.pix

To keep all foreground pixels greater than 20/20/20, and replace all those less than or equal to it with 200/0/200, use:

pixmatte -g fg.pix =20/20/20 fg.pix =200/0/200

To keep all foreground pixels which are not equal to 63/0/127, and to replace those which are equal with a generated background from stdin, use the following commands (can be useful when compositing an xref:man:1/rt.adoc[*rt*(1)] generated image on top of a nicer background):

pixbackgnd -t0 160 200 | pixmatte -n fg.pix =63/0/127 fg.pix - | pix-fb

To produce a black-and-white stencil matte file for further processing, use:

pixmatte -n fg.pix bg.pix =255/255/255 =0/0/0

To set to black all pixels that approximately match (by +/- 1) a given background file, use:

pixmatte -a -e fg.pix bg.pix =0/0/0 fg.pix

== SEE ALSO

xref:man:1/brlcad.adoc[*brlcad*(1)], xref:man:1/gencolor.adoc[*gencolor*(1)], xref:man:1/pixbackgnd.adoc[*pixbackgnd*(1)], xref:man:1/pixmerge.adoc[*pixmerge*(1)], xref:man:5/pix.adoc[*pix*(5)], xref:man:5/bw.adoc[*bw*(5)]

== AUTHOR

BRL-CAD Team

== COPYRIGHT

This software is Copyright (c) 1989-2021 by the United States Government as represented by U.S. Army Research Laboratory.

== BUG REPORTS

Reports of bugs or problems should be submitted via electronic mail to mailto:devs@brlcad.org[]