= PIXROT(1)
BRL-CAD Team
ifndef::site-gen-antora[:doctype: manpage]
:man manual: BRL-CAD
:man source: BRL-CAD
:page-layout: base

== NAME

pixrot - rotate, invert, or reverse a color pix file

== SYNOPSIS

*pixrot*[-#bytes][-rifb][-s _squaresize_][-w _in_width_][-n _in_height_][_file.pix_]>_newfile.pix_

== DESCRIPTION

[cmd]*pixrot* will rotate, invert, or reverse a color xref:man:5/pix.adoc[*pix*(5)] format file or read from standard input if a file name is not given.  The [opt]*-w* and [opt]*-n* flags specify the input file width and number of scan lines in pixels; they can be set to the same value via [opt]*-s*.

The [opt]*-r* flag reverses the scan lines left to right. The [opt]*-i* flag inverts the image top to bottom. The [opt]*-f* and [opt]*-b* flag will rotate the image ninety degrees forward or backward respectively. The sense of the rotation is relative to a first quadrant coordinate system, i.e. origin lower left, where "forward" means clockwise.

Note that a 180 degree rotation can be obtained by both reversing and inverting.

By default three byte pixels are assumed as in the xref:man:5/pix.adoc[*pix*(5)] format.  However, the [opt]*-#*[rep]_bytes_ flag can be used to specify some other pixel size, where __bytes__ is the number of bytes per pixel.  Thus this program can be used to manipulate rectangles of other data types, such as an array of floating point numbers, files of text, etc.

== METHOD

A fairly large buffer is kept in memory so that, file size permitting, the entire rotation can occur without seeking on input or output. In any event, the algorithm is designed to process the input sequentially, so that if any seeking is required, it will happen on output only.  If these seeks fail, e.g. the output is a pipe, the user will be told that it needs a file on output. A more general solution to this problem would be to see if seeks can be done on input instead, and switch the algorithm to seek on input only.

== SEE ALSO

xref:man:1/brlcad.adoc[*brlcad*(1)], xref:man:1/pixscale.adoc[*pixscale*(1)], xref:man:1/pixrect.adoc[*pixrect*(1)], xref:man:5/pix.adoc[*pix*(5)]

== BUGS

If the file size is very large, excessive seeking may occur on output and the rotation will take a very long time.  More complicated algorithms could remedy this. Rotations of arbitrary angle are not supported.

== AUTHOR

BRL-CAD Team

== COPYRIGHT

This software is Copyright (c) 1989-2021 by the United States Government as represented by U.S. Army Research Laboratory.

== BUG REPORTS

Reports of bugs or problems should be submitted via electronic mail to mailto:devs@brlcad.org[]