= PIXSTAT(1)
ifndef::site-gen-antora[:doctype: manpage]
:man manual: BRL-CAD
:man source: BRL-CAD
:page-role: manpage

== NAME

pixstat - list statistics related to a color pix image

== SYNOPSIS

*pixstat*[-v][_file.pix_]

== DESCRIPTION

[cmd]*pixstat* will take the given xref:man:5/pix.adoc[*pix*(5)] format file, or read from standard in.  A collection of statistics related to the pixel intensities is produced for each color plane (red, green, and blue). These include: the number of pixels (and the square root of this which is the file dimensions if square); the max and min values; the mean; the median (dividing line where half the pixels are above this value, half below); the mode (most frequently occurring value) and the number of pixels at this value; the variance, standard deviation, and skew.

The [opt]*-v* flag will also dump a histogram of the pixel values.

== METHOD

Since the pixel values are quantized (each color having discrete values from 0 to 255), the statistics can be computed from "lump sums" after building a histogram of the input.  This results in a fantastic savings in computation while also making a single pass over the input file sufficient.

== SEE ALSO

xref:man:1/brlcad.adoc[*brlcad*(1)], xref:man:1/pixhist.adoc[*pixhist*(1)], xref:man:1/bwstat.adoc[*bwstat*(1)], xref:man:5/pix.adoc[*pix*(5)]

== AUTHOR

BRL-CAD Team

== COPYRIGHT

This software is Copyright (c) 1989-2021 by the United States Government as represented by U.S. Army Research Laboratory.

== BUG REPORTS

Reports of bugs or problems should be submitted via electronic mail to mailto:devs@brlcad.org[]