= PROE-G(1)
BRL-CAD Team
ifndef::site-gen-antora[:doctype: manpage]
:man manual: User Commands
:man source: BRL-CAD
:page-layout: base

== NAME

proe-g - Pro/Engineer Translator (Pro/Engineer to BRL-CAD)

== SYNOPSIS

*proe-g*[-darS][-i _initial_ident_][-I _constant_ident_][-m _material_code_][-u _reg_exp_][-x _RT_DEBUG_FLAG_]_file.brl__file.g_

== DESCRIPTION

[cmd]*proe-g* converts the specified __file.brl__ to a BRL-CAD __file.g__ file. The [opt]*-d* option prints debugging information. The [opt]*-a* option implies that all the parts in the Pro/E model should be converted to BRL-CAD __air__ regions. The [opt]*-i* option sets the starting ident number for the regions created. As each new region is created, this number will be incremented before assigning the next ident number (conflicts with [opt]*-I* ). The [opt]*-I* option sets a constant ident number that will be assigned to all the regions created (conflicts with [opt]*-i* ). The [opt]*-m* option sets a material code that will be assigned to all the regions created (default is 1). The [opt]*-r* flag indicates that the model should not be rotated, translated, or scaled, but left in the same orientation and size as it was created in __Pro/E.__ This allows the user to convert parts that are referenced by previously converted assemblies, so that the transformation matrix in the referencing assembly will size and position the part. The [opt]*-x* option sets an RT debug flags (see raytrace.h). The __file.brl__ file is expected to be output from the __BRL-CAD__ menu option of the Pro/Engineer __EXPORT__ menu. This menu option is a Pro/Develop application produced by the USARL.

Note that the routine documented here is obsolete, and only maintained for compatibility with older versions of Pro/Engineer. The current method of converting from Pro/Engineer to BRL-CAD is still a two step process, but a newer Pro/Toolkit application must be installed (see “install.doc” in the “pro-engineer” directory of the BRL-CAD distribution). From within Pro/Engineer, the “proe-brl” option must be selected from the “File” menu, and the user will be prompted for an output file name, a starting ident number, a maximum tessellation error, and an additional curvature correction. The output from this new routine, is a Tcl script that may be converted to a BRL-CAD model using “asc2g” or by sourcing the file during an MGED session.

== EXAMPLE
// <synopsis>
// $ proe-g <emphasis remap="I">sample.brl sample.g</emphasis>
// </synopsis>


== SEE ALSO

_Pro/Engineer Modeling User's Guide,_ Version 13.0, Parametric Technology Corporation

== DIAGNOSTICS

Error messages are intended to be self-explanatory.

== AUTHOR

BRL-CAD Team

== COPYRIGHT

This software is Copyright (c) 1994-2021 by the United States Government as represented by U.S. Army Research Laboratory.

== BUG REPORTS

Reports of bugs or problems should be submitted via electronic mail to mailto:devs@brlcad.org[]