= RTHIDE(1)
ifndef::site-gen-antora[:doctype: manpage]
:man manual: BRL-CAD
:man source: BRL-CAD
:page-role: manpage

== NAME

rthide -  ray-traces a model and writes a hidden line removed UNIX-Plot file.

== SYNOPSIS

*rthide*[_options_]..._model.g__objects_...>_model.plot3_

== DESCRIPTION

[cmd]*rthide* operates on the indicated __objects__ in the input __model.g__ and produces a hidden line removed UNIX-Plot file with bas-relief features. [cmd]*rthide* produces plots by drawing a boundary whenever a change in region_id is detected.  It also recognizes and portrays abrupt changes in surface curvature and changes in surface height.  This permits the recognition of pits, protrusions, and changes in surface curvature.

The orientation of the rays to be fired may be specified by the [opt]*-a* and [opt]*-e* options, in which case the model will be autosized, and the grid will be centered on the centroid of the model, with ray spacing chosen to span the entire set of __objects__. Alternatively, with the [opt]*-M* option, a transformation matrix may be provided on standard input which maps model-space to view-space. In this case, the grid ranges from -1.0 <= X,Y <= +1.0 in view space, with the size of the grid (number of rays fired) specified with [opt]*-s* This option is most useful when [cmd]*rthide* is being invoked from a shell script created by an xref:man:1/mged.adoc[*mged*(1)]__saveview__ command.

The following options are recognized.

*-s#*::
Number of rays to fire in X and Y directions (square grid). Default is 512 (512x512).

*-a#*::
Select azimuth in degrees.  Used with [opt]*-e* and conflicts with [opt]*-M*

*-A#*::
Select angle for shading.  Default is 5.0 degrees. 89.0 will produce a plot where only steep drops and rises are shaded.

*-e#*::
Select elevation in degrees.  Used with [opt]*-a* and conflicts with [opt]*-M*

*-M*::
Read model2view matrix from standard input. Conflicts with [opt]*-a* and [opt]*-e*

*-g#*::
Select grid cell width.

*-G#*::
Select grid cell height.  If _not_ specified, cell height equals cell width.

*-U #*::
sets the Boolean variable __use_air__ to the given value.

*-o*::
_output.plot3_ specifies a named file for output. By default, the plot is written to hide.plot3.

*-x#*::
Set librt debug flags to (hexadecimal) number.

The [cmd]*rthide* program is a simple front-end to xref:man:3/librt.adoc[*librt*(3)] which is most useful when used with xref:man:1/mged.adoc[*mged*(1)].

== EXAMPLE

This section shows the ordinary usage of [cmd]*rthide* .  For example,

....

rthide -a# -e# -s32 model.g all.g > file.plot3
....

results in a 32 by 32 UNIXplot file of the named model at the specified azimuth and elevation.  There will be some cross-hatching of the plot based on surface curvature.  In order to minimize this cross-hatching, an angle can be specified:

....

rthide -a# -e# -s32 -A89.0  model.g all.g > file.plot3
....

eliminates cross-hatching due to curvature.  However, cross-hatching resulting from sharp changes in gradient cannot be eliminated.

The plotfile resulting from an [cmd]*rthide* run can be viewed directly via _plot3-fb_ and may be rotated with _plot3rot_ at the user's option:

....

plot3-fb hide.plot3
....

or

....

plot3rot -a# -e# -g hide.plot3 | plot3-fb
....

or it can be overlaid onto a solid model in __mged__:

....

mged> overlay hide.plot3
....

This technique can be used to position and plot [cmd]*rthide* output.

The output of [cmd]*rthide* can be overlaid on top of a _rt_ shaded image, for "edge enhancement".  Here is a complete example, which assumes that FB_FILE points to a valid framebuffer:

....

	AZ=35
	EL=25
	# Directly to the framebuffer
	rt -s512 -a$AZ -e$EL moss.g all.g 2> rt.log
	rthide -A89.9 -s256 -a$AZ -e$EL -o rthide.plot3 moss.g all.g 2> rthide.log
	eval `rtregis rthide.log rt.log` < rthide.plot3 | plot3-fb -o -s512
....

== SEE ALSO

xref:man:1/cell-fb.adoc[*cell-fb*(1)], xref:man:1/mged.adoc[*mged*(1)], xref:man:1/plot3-fb.adoc[*plot3-fb*(1)], xref:man:1/plot3rot.adoc[*plot3rot*(1)], xref:man:1/rt.adoc[*rt*(1)], xref:man:1/rtray.adoc[*rtray*(1)], xref:man:1/rtregis.adoc[*rtregis*(1)], xref:man:1/rtscale.adoc[*rtscale*(1)], xref:man:3/librt.adoc[*librt*(3)], xref:man:3/libplot3.adoc[*libplot3*(3)], xref:man:5/plot3.adoc[*plot3*(5)], xref:man:5V/ray.adoc[*ray*(5V)].

== DIAGNOSTICS

Numerous error conditions are possible, usually due to errors in the geometry database. Descriptive messages are printed on standard error (file descriptor 2).

== BUGS

Most deficiencies observed while using the [cmd]*rthide* program are usually with the xref:man:3/librt.adoc[*librt*(3)] package instead.

== AUTHORS

_BRL-CAD Team_

== COPYRIGHT

This software is Copyright (c) 1990-2021 by the United States Government as represented by U.S. Army Research Laboratory.

== BUG REPORTS

Reports of bugs or problems should be submitted via electronic mail to mailto:devs@brlcad.org[]