= RTSCALE(1)
BRL-CAD Team
:doctype: manpage
:man manual: BRL-CAD
:man source: BRL-CAD
:page-layout: base

== NAME

rtscale -  supplements rthide output by plotting a scale to indicate drawing size in arbitrary units.

== SYNOPSIS

*rtscale*_width__units__intervals__file.log__optional_string_>_scale.plot3_

== DESCRIPTION

[cmd]*rtscale* supplements the use of _rthide_ by generating a UNIX-Plot of a scale that permits the accurate measuring of _rthide_ plots. _rthide_ provides a hidden-line-removed plot of the geometry, and [cmd]*rtscale* produces an identical plot file containing just a scale.   The two files can then be concatenated making sure that the scale precedes the _rthide_ file to produce a finished plot with scale.

[cmd]*Rtscale* operates on the RT log file from the _rthide_ run and produces a UNIX-Plot file of a scale with desired units and number of tick marks.  The scale's width is given in model units.  A descriptive string may be added.  The scale and the strings are plotted in the lower left corner of the image.

The inputs required are: __width,__ which specifies the length of the scale in model space, __units,__ which may be any units (metric or English), __intervals,__ which allows the user to specifies the number of tickmarks on the scale. __filename,__ which names the  RT log file that is used to calculate the view2model matrix for the raytraced. A view such as azimuth 45, elevation 45, is useful for measuring diagonal dimensions of the geometry. Optionally, a __descriptive string__ may be given to identify the view or the model.

== EXAMPLE

This section shows the ordinary usage of [cmd]*rtscale*.  For example:

....

rtscale 30 mm 10 rt.log > scale.plot3
....

This will result in a 30 mm scale with ten tickmarks being plotted in the lower left corner of the scale.plot3 image.  Alternately, a descriptive string may be given to identify the view or the model:

....

rtscale 30 mm 10 rt.log "UH-60 a90 e0" > scale.plot3
....

Note that a descriptive string longer than 28 characters will be cut off by __plot3-fb__.

The plot file is now concatenated with the plot file of the image to scale needs to be put on.  The order in which they are concatenated is important: the scale is always concatenated over top of the model plot:

....

cat scale.plot3 model.plot3 >> model.w.scale.plot3
....

The resulting UNIX-Plot of the geometry with a scale added to it can be viewed in several ways.  It can be overlaid in __mged__, or it can be rotated to the desired azimuth and elevation with _plot3rot_ and be stored in a file or view with __plot3-fb__:

....

plot3rot -a# -e# -g model.w.scale.plot3 | plot3-fb
....

== SEE ALSO

xref:man:1/mged.adoc[*mged*(1)], xref:man:1/plot3rot.adoc[*plot3rot*(1)], xref:man:1/rt.adoc[*rt*(1)], xref:man:1/rthide.adoc[*rthide*(1)], xref:man:3/librt.adoc[*librt*(3)], xref:man:3/libplot3.adoc[*libplot3*(3)], xref:man:5/plot3.adoc[*plot3*(5)], xref:man:5V/ray.adoc[*ray*(5V)]

== DIAGNOSTICS

Numerous error conditions are possible, usually due to errors in the geometry database. Descriptive messages are printed on standard error (file descriptor 2).

== AUTHOR

_BRL-CAD Team_

== COPYRIGHT

This software is Copyright (c) 1991-2021 United States Government as represented by the U.S. Army Research Laboratory.

== BUG REPORTS

Reports of bugs or problems should be submitted via electronic mail to mailto:devs@brlcad.org[]