= RTWIZARD(1)
ifndef::site-gen-antora[:doctype: manpage]
:man manual: BRL-CAD User Commands
:man source: BRL-CAD
:page-role: manpage

== NAME

rtwizard - Combines images from several raytracing techniques to produce complex images.

== SYNOPSIS

*rtwizard* [_options_]...

[[_rtwizard_description]]
== DESCRIPTION

[cmd]*rtwizard* is a tool that automates the use of several BRL-CAD graphical programs to produce complex images.  There are two primary modes of operation - a graphical client to guide users through the process of creating images, and a command line mode to allow users who already know what options they wish to use to quickly and automatically produce images.  Graphical mode is used when insufficient information is supplied to produce an image (unless an option specifically ruling out graphical mode is passed) and command line mode (used automatically when there _is_ enough information to produce an image, unless GUI mode is specifically requested.) When in graphical mode, rtwizard is self explanatory.  This manual documents the command line options available when _not_ operating in graphical mode. 

Images produced by _rtwizard_ use three primary elements - standard full color raytracings produced by [cmd]*rt*, "line drawing" style images produced by [cmd]*rtedge*, and a faded greyscale version of color raytracings produced with a variety of image manipulation tools included with BRL-CAD. 

When specifying options on the command line, it is usually better practice to fully qualify what a particular item is - for example, using [opt]*-i* to specifically identify the input file instead of relying on the .g suffix.  There is a limited ability to recognize common usage patterns (for example, "[cmd]*rtwizard* file.g output_image.png geometry_object" will generate an image of geometry_object in the file output_image.png) but the most unambigous specification uses the options. 

The following options are recognized. 

.Input/Output Options
_geometry_file.g_::
The first argument without an option flag (the leftmost argument is regarded as the first) that identifies an existing file with a .g suffix will be used to specify the working geometry database, unless overridden by the [opt]*i* option.  Remember that some option flags accept multiple arguments and can create ambiguities about the meaning of a .g option and in such situations [opt]*i*	    should be used. 

*-i*_geometry_file_::
Specifying the geometry database containing the objects to be raytraced.  The [opt]*i* option will override a non-flagged geometry file specification. 

_output_file.imgformat_::
The name and image format of the final output image generated by rtwizard.   When specifying the output file name without using a flag, a .pix or .png image format extension is necessary.  The first valid, unflagged output file name will be used unless overridden by the [opt]*o*.  If the output filename uses a .png image format extension, the Portable Network Graphics image format will be used when writing out the file.  Otherwise, a standard BRL-CAD pix image will be generated. Remember that some option flags accept multiple arguments and can create ambiguities about the meaning of a image name option and in such situations [opt]*o*	    should be used. 

*-o*_output_file[.imgformat]_::
The name (and optionally the image format) of the final output image generated by rtwizard.   If the output filename uses a .png file extension, the Portable Network Graphics image format will be used when writing out the file.  Otherwise, a standard BRL-CAD pix image will be generated. 

*-d*_framebuffer_device_::
The type of framebuffer to use when running fbserv to establish a framebuffer.  By default, "/dev/mem" is used for a non-graphical framebuffer - other options include /dev/X, /dev/ogl, and (Windows only) /dev/wgl. A /dev/mem framebuffer created by [cmd]*rtwizard*	    will be closed after the image generation is complete. 

*-p*_port_number_::
The number of the framebuffer port to use when running [cmd]*fbserv* to establish a framebuffer.  An existing framebuffer may also be specified and used.  In the case of a pre-existing non-graphical framebuffer, [cmd]*rtwizard* will not close the framebuffer automatically after the raytracing process is complete. 

*--gui*::
Run rtwizard's graphical interface, even if the command line options specify enough information to produce an image. 

*--no-gui*::
Run rtwizard on the command line, even if the command line options do not specify enough information to produce an image.  Overridden by --gui option if both are specified. 

.Model View Options
When it comes to preparing the view for an RtWizard image, there are two options.  One is to use the "user level" controls, which reflect the view manipulations used by users on the command line.  The other is to use the "low level" specifiers, which are more typically used when [cmd]*rtwizard* is run by automated scripts.  The two methods are mutually exclusive. 

*-a*_angle (degrees)_::
Set azimuth angle.

*-e*_angle (degrees)_::
Set elevation angle. 

*--twist*_angle (degrees)_::
Set twist angle. 

*-P*_angle (degrees)_::
Set the perspective angle. 

*-z*_value_::
Set the zoom factor (smaller factor results in a smaller object in the view, and vice versa). 

*--center*_X Y Z_::
Set the xyz coordinates of the center of the view. 

.Image Generation Options
The three options that are used to input geometry object lists need to parse multiple arguments, so any options immediately following either of them need to use an explicit argument flag to signal termination of the input list to the option parser - for example, an input .g file needs to be specified with the [opt]*-i* if it comes after a list of ghost objects. 

*-c*_obj1[,...]_::
Specify objects to render using full color using a comma separated list. 

*-C*_value_::
Set the background color to use when raytracing full color objects.  May use R/G/B or hex style color specification. 

*-g*_obj1[,...]_::
Specify objects to be rendered using ghosting using a comma separated list. 

*-G*_value_::
Control the degree of visibility to use when rendering ghost objects. 

*-l*_obj1[,...]_::
Specify objects to render lines with using rtedge using a comma separated list. 

*--line-color*_value_::
Specify color to use when rendering edge lines.  In addition to R/G/B and hex color specifications, the keyword "region" is also supported - in the latter case, region colors will be used for lines. 

*--non-line-color*_value_::
Specify color rtedge will use for non-line rendering. 

*-n*_value_::
Specify the height of the generated image in pixels. 

*-O*_value_::
Specify the occlusion mode rtedge will use for line rendering. 

*-s*_value_::
Specify the width and height of the generated image in pixels.  Width can be overridden by the [opt]*w* option and height by the [opt]*n* option. 

*-t*_image_type_::
Specify the type of image to be rendered. The images produces by [cmd]*rtwizard*	    are categorized by _picture type_ - there are six picture types built on full color raytracing, ghosting, and [cmd]*rtedge* line renderings. If a type is specified and insufficient information is supplied to generate that particular image type, rtwizard will exit with an error. 
+

.RtWizard Image Types
[cols="1,1,1", options="header"]
|===
| Type
| Name
| Description

|A
|Simple Full-Color Image
|Standard [cmd]*rt* image.

|B
|Simple Line Drawing
|Standard [cmd]*rtedge* image.

|C
|Highlighted Image
|Full Color [cmd]*rt* image enhanced with [cmd]*rtedge* lines.

|D
|Mixed Full Color and Edges
|Like Type C, except objects may be selectively enhanced with [cmd]*rtedge* lines.

|E
|Ghost Image with Inserts
|A combination of Full Color elements and faded greyscale raytracings for context.

|F
|Ghost Image with Inserts and Edges
|A Type E image further enhanced with [cmd]*rtedge* lines.
|===

*-w*_value_::
Specify the width of the generated image in pixels. 

== EXAMPLES

Introduction 

.Basic Color Image
====
[ui]`rtwizard m35.g component`

Results in a default color image of the m35 truck, output to rtwizard.pix 
====

.Line Drawing Image
====
[ui]`rtwizard -d /dev/ogl m35.g -l component`

Results in a line drawing of the m35 truck being display in an OpenGL framebuffer 
====

.Complex Image
====
[ui]`rtwizard -d /dev/ogl -i m35.g -c component/power.train -g component -l component`

Results in a view of the m35 truck highlighting the engine (in color) with the truck being shown as a ghosted, edged background. 
====

.Complex Image with Non-Default View
====
[ui]`rtwizard -d /dev/ogl -i m35.g -c component/power.train -g component -l component -a -35 -e 15 -z 1.6`

Same as the previous image, except viewing the truck from a different direction and zoomed in closer. 
====

.Multiple Color Objects
====
[ui]`rtwizard -d /dev/ogl -i m35.g -c component/power.train,component/suspension -z 1.6`

View the power train and suspension of the truck as color objects. 
====

== SEE ALSO

xref:man:1/rt.adoc[*rt*(1)], xref:man:1/rtedge.adoc[*rtedge*(1)]

== COPYRIGHT

This software is Copyright (c) 2001-2021 United States Government as represented by the U.S. Army Research Laboratory.

== AUTHOR

BRL-CAD Team

== BUGS

Most deficiencies observed while using the [cmd]*rtwizard* program are a consequence of problems in commands used by rtwizard to generate images, such as rtedge.

== BUG REPORTS

Reports of bugs or problems should be submitted via electronic mail to mailto:devs@brlcad.org[]