= FAQ

== What is BRL-CAD?

BRL-CAD is a powerful cross-platform open source solid modeling system.

See http://brlcad.org/d/about[here] for the longer version.

== What license is BRL-CAD distributed under?

BRL-CAD is a large system with various portions under different license
but is predominantly distributed as a collective work under the v2.1
LGPL. Most of our data files and documentation are provided under a
modified BSD license or are in the public domain. See our
http://brlcad.svn.sourceforge.net/svnroot/brlcad/brlcad/trunk/COPYING[COPYING]
file for more details.

== Where is the roadmap for BRL-CAD?

BRL-CAD is a large project with various development efforts that are
heavily dependent upon how the community sustainably contributes, but
these should help give an idea of where we're going:

* http://brlcad.org/BRL-CAD_Priorities.png[BRL-CAD Project
Priorities]
(0.7MB http://brlcad.org/BRL-CAD_Priorities.png[PNG], 0.1MB http://brlcad.org/BRL-CAD_Priorities.pdf[PDF])
* http://brlcad.org/~sean/ideas.html[BRL-CAD Project Ideas]

== How do I start BRL-CAD?

BRL-CAD is a suite of more than 400 tools and utilities. The suite of
applications are intentionally designed to perform a succinct task so
that they can be chained together, scripted, and expanded upon in
order to provide powerful flexibility.

That said, most users will be interested in using
xref:man:1/mged.adoc[mged] as a first step in getting started with BRL-CAD.
Documentation on mged can be found in the share directory where
BRL-CAD was installed. There is also extensive mged documentation
available on the website under xref:wiki:Documentation.adoc[].

If you're on Windows, there should be an icon for MGED in your start
menu or on your desktop. For any other platform, you should be able to
run this in an X11 terminal: */usr/brlcad/bin/mged*

== What does the "BRL" in BRL-CAD mean?

The "BRL" in BRL-CAD comes from the project's origins at the
*Ballistic Research Laboratory*.
http://en.wikipedia.org/wiki/Ballistic_Research_Laboratory[BRL] was
later absorbed into the U.S. Army Research Laboratory in 1992 but
BRL-CAD retained its original distinctive name and trademark heritage.

== How do you pronounce BRL-CAD?

BRL-CAD is correctly pronounced as "*be are el cad*".

Incorrect albeit perhaps humorous mispronunciations overheard include
"burl cad", "burly cad", "brill cad", "brail cad", just "be are el"
and other variations without the "cad" designation, and of course
"brazilian real canadian dollars".

== How do you pronounce mged?

According to the earliest developers, as well as the current core
development team, the pronunciation is "em ged" with a hard "g" as in
"get."

== How should BRL-CAD be spelled?

The proper name of the project is "BRL-CAD", with specific importance
to spell the name in uppercase and utilizing a hyphen for consistency
and uniformity of name recognition. The "BRL-CAD" name should be used
for all materials that will be publicly displayed or published.

While it is acceptable to use the non-hyphenated and lowercase
"brlcad" name for files and directories that refer to the package,
e.g.  brlcad-7.8.2.tar.gz will compile and install into the
/usr/brlcad directory by default, the "BRL-CAD" name should be used as
the official name of the project wherever possible unless technical
limitations prohibit it. Similarly, the source code may utilize
variations on the name due to technical limitations, but they are
considered private internal use.

Unacceptable variations of the project name for public documentation
and articles include BRLCAD, BrlCAD, BrlCad, Brlcad, BRLcad, BrlCAD,
Brl-CAD, Brl-Cad, Brl-cad, BrLcAd, etc.

== How can I check out the Archer prototype (on Windows)?

* Install the Windows version BRL-CAD
* Start Archer
* Open an example geometry database file
 ** File -> Open
 ** Select one of the examples like "axis"
 ** Select "havoc" and wait until you see a drawing of three big
axis bars shown in the black window on the right
* Select "Raytrace" -> rt -> 512x512, then you can see the 3D
model rendered

== How do I get a hard copy of what I'm looking at in MGED?

The File->Raytrace and File->Render_View->RT_Script menu options in
MGED will generate a raster image of MGED's current view. The
xref:man:1/pix-png.adoc[pix-png] utility can be used to convert from
BRL-CAD's .pix raw image file format to the .png file format, and can
then be printed or embedded into other documents using other tools.

Additionally, the other File->Render_View options for generating
standard Plot and PostScript output files of the MGED wireframe
suitable for printing. The xref:man:1/pl-fb.adoc[pl-fb] and
xref:man:1/fb-png.adoc[fb-png] tools can be used to rasterize a Plot file
to the .png format.

Finally, there are a variety of renderers and lighting models
available in BRL-CAD that are useful for various purposes. The
xref:man:1/rt.adoc[rt] tool is the primary ray-tracer that is used for
shaded view rendering.  The xref:man:1/rtedge.adoc[rtedge] and
xref:man:1/rthide.adoc[rthide] commands are used for hidden-line renderings
similar to what you'd want for generating drafting
documents. xref:man:1/rtwizard.adoc[rtwizard] is a graphical 'wizard'
tool that can be used to generate a variety of hybrid renderings.

== How can I fix the huge transparent yellow cursor when I run MGED?

This is a bug in the X11 client/server communication when you run MGED
on a remote machine and display to a local display. It's also
unfortunately not something we can fix inside BRL-CAD. There is,
however, a pretty simple work-around that forces the application to load
a local cursor. Run this:

`.id_0 config -cursor "xterm black"`
