= BRL-CAD Tutorial Series: Volume II: Introduction to MGED
Lee A. Butler; Eric W. Edwards; Betty J. Schueler; Robert G. Parker; John R. Anderson

****
[cols=">h,<", frame="all"]
|===
| AUTHORS:
| Lee A. Butler +
  Eric W. Edwards +
  Betty J. Schueler +
  Robert G. Parker +
  John R. Anderson

| ORGANIZATION:
| *U.S. Army Research Laboratory* +
  Aberdeen Proving Ground, MD  21005-5068

| REPORT:
| ARL-SR-102 +
  April 2001
|===
****

.Disclaimers
****
Approved for public release; distribution is unlimited.

The findings in this report are not to be construed as an official
Department of the Army position unless so designated by other
authorized documents.

Citation of manufacturer's or trade names does not constitute an
official endorsement or approval of the use thereof.

Destroy this report when it is no longer needed. Do not return it\ to
the originator.
****

.Abstract
****
Since 1979, the U.S. Army Research Laboratory has been developing and
distributing the BRL-CAD constructive solid geometry (CSG) modeling
package for a wide range of military and industrial applications. The
package includes a large collection of tools and utilities including
an interactive geometry editor, ray-tracing and generic framebuffer
libraries, a network-distributed image-processing and
signal-processing capability, and an embedded scripting language.

As part of this effort, a multivolume tutorial series is being
developed to assist users in the many features of the BRL-CAD
package. The “Introduction to MGED,” which is the second volume in the
series, is intended to provide new users with a basic understanding of
the Multi-Device Geometry Editor (MGED), which is the heart of
BRL-CAD. Other volumes focus on installation procedures, advanced
features, and programming.
****

== Chapters

* xref:tutorials:volume2/preface1.adoc[]
* xref:tutorials:volume2/preface2.adoc[]
* xref:tutorials:volume2/chapter1.adoc[]
* xref:tutorials:volume2/chapter2.adoc[]
* xref:tutorials:volume2/chapter3.adoc[]
* xref:tutorials:volume2/chapter4.adoc[]
* xref:tutorials:volume2/chapter5.adoc[]
* xref:tutorials:volume2/chapter6.adoc[]
* xref:tutorials:volume2/chapter7.adoc[]
* xref:tutorials:volume2/chapter8.adoc[]
* xref:tutorials:volume2/chapter9.adoc[]
* xref:tutorials:volume2/chapter10.adoc[]
* xref:tutorials:volume2/chapter11.adoc[]
* xref:tutorials:volume2/chapter12.adoc[]
* xref:tutorials:volume2/chapter13.adoc[]
* xref:tutorials:volume2/chapter14.adoc[]
* xref:tutorials:volume2/chapter15.adoc[]
* xref:tutorials:volume2/chapter16.adoc[]
* xref:tutorials:volume2/appendix1.adoc[]

