
:sectnums!:

[preface]
= Acknowledgments

The authors would like to thank Paul Tanenbaum, TraNese Christy, Sean
Morrison, and the other members of the Advanced Computer Systems Team
who reviewed this document in a timely manner and made many helpful
suggestions to improve its accuracy and presentation.

In addition, the authors would like to acknowledge team member Mike
Muuss, who passed away while this volume was in preparation.  Mike was
the original architect of the [app]`BRL-CAD` package and guided its
development for 20 years until his death on 20 November 2000.  He
embodied a unique blend of unparalleled intellect, unquenchable
curiosity, and unending energy to advance the capabilities of
everything and everyone he touched.  A natural-born troubleshooter,
Mike approached every job, big or small, with a passion for excellence
and a child-like enthusiasm, which helped drive [app]`BRL-CAD` far
beyond expectations.

Although he never got a chance to review this document, much of this
work is a result of his vision and attention to detail.  Therefore,
the [app]`BRL-CAD` Tutorial Series is dedicated to his memory.  His
sharp mind, his warm spirit, and his loyal friendship will be greatly
missed.

:sectnums:
