== Description

link:IBME_GeometryService#NetMsg_Class[NetMsg] that contains
either a UUID or string Path that references a piece of Geometry.
Extends link:GenericOneStringMsg[GenericOneStringMsg] (thus
contains those fields also). The String field from
link:GenericOneStringMsg[GenericOneStringMsg] is used as the
UUID or Path field, depending on the Request Type.

== Warning Messages

If you want to disconnect this request,
link:DisconnectREQ[DisconnectREQ] is displayed. +++<BSRJ>++++++</BSRJ>+++

== Failure Codes

If a link:GeometryREQFAIL[GeometryREQFAIL] message is displayed,
this indicates that the GeometryREQ has failed. +++<BSRJ>++++++</BSRJ>+++

NOTE: You can read all link:Failure[Failure] codes.

== Related Subjects

link:NewHostOnNet[NewHostOnNet]

link:GeometryCHUNK[GeometryCHUNK]

link:GeometryMANIFEST[GeometryMANIFEST]

== Byte Format

|===
|  |

| *Element*
| *Length*

| RequestType
| byte (1 byte)
|===

=== Request Types

|===
|  |

| *RequestType*
| *Description*

| 0
| The Data is a UUID for the Geometry requested.

| 1
| The Data is a path to the Geometry requested.
|===

== Google Code In

This page was edited for link:Google_Code_In[Google_Code_In]
by BSRJ.
