== Mailing Lists

The BRL-CAD mailing lists are https://sourceforge.net/mail/?group_id=105292[hosted on
Sourceforge]. Some of the
primary mailing lists available are:

https://lists.sourceforge.net/lists/listinfo/brlcad-news[BRL-CAD News]
Announcement of new releases and other significant news is sent to this
list. The list is read-only and relatively low-traffic.

https://lists.sourceforge.net/lists/listinfo/brlcad-users[BRL-CAD Users]
This list is intended for anything and everything related to BRL-CAD
users. If you have a question, comment, or suggestion, feel open to talk
about it here.

https://lists.sourceforge.net/lists/listinfo/brlcad-devel[BRL-CAD Developer]
This list is intended for communications related to the development and
improvement of BRL-CAD. This list is for discussions by programmers,
documenters, artists, and any other contributor.

Please note that you must still subscribe to our mailing lists on
Sourceforge in order to post through an online mirroring service such as
http://old.nabble.com/BRL-CAD-f3277.html[Nabble].

link:category:Getting_started[category:Getting started]
