:pp: {plus}{plus}

== Converting from STEP files to BRL-CAD databases

BRL-CAD's most pressing need in the geometry file conversion category is
support for the STEP file format, a.k.a "STandard for the Exchange of
Product model data." Step is a successor to the IGES file format and
today is the major standard used for data exchange between CAD systems.

== Partial Support

currently the tool step-g has partial support, and the toolkit
https://github.com/stepcode/stepcode is branched into the src/other
source tree.

== Defining ISO Documents

The source standard for STEP is ISO-10303, which consists of hundreds of
individual parts. (list parts important to brlcad)

== Existing Open Source Tools

[discrete]
==== Tools that work with EXPRESS (ISO10303 Part 11) schemas

* http://exp-engine.sourceforge.net/[Expresso], aka Express Engine,
written in Lisp
* http://www.jsdai.net/[JSDAI], written in java

[discrete]
==== Tools that generate C{pp} from an EXPRESS schema

* NIST STEP Class Libraries
 ** There is a https://github.com/mpictor/StepClassLibrary[patched
version] of the SCL
that compiles with GCC 4.6
 ** http://www.mel.nist.gov/msid/scl/SCL.htm[Official NIST SCL
site]

//

* ESA and NASA also have some tools (expressik, lightcpp, pyexpress)
that can generate code from EXPRESS schema. For some years, ESA has
planned to release some (or all) of the code as open source;
however, they have many higher priorities (per email with a person
at ESA).
 ** Relevant google searches:
  *** http://www.google.com/search?q=iso10303-11+EXPRESS+SDAI+python+generate+c%2B%2B[iso10303-11 EXPRESS SDAI python generate
c{pp}]
  *** http://www.google.com/search?q=expressik+lightcpp[expressik
lightcpp]
 ** http://forge.osor.eu/plugins/wiki/index.php?id=175&type=g[IFC]
contains code generated by lightcpp, but *does not include*
lightcpp. Contains some info on lightcpp.

== BRL-CAD Specific Design Considerations
