= What Code to Work On
:doctype: book
:sectnums:
:toc: left
:icons: font
:experimental:
:sourcedir: .

If you would like to fix a bug or work on a major project, then this
section is for you.  Depending on how long you want to be with us, we
have tasks that will take you anywhere from a few hours to a few days
to several months to complete.  Regardless of your level of
participation, make sure you read the How to Contribute section for
information about BRL-CAD's developer guidelines.

== Two-Hour Tasks

These tasks have roughly the same complexity and require no prior
experience with BRL-CAD experience to complete.  They're a great
starting point for anyone interested in getting involved in the
development process of BRL-CAD, as they can be completed in just a
couple of hours.

Check out our list of available mini tasks that we call
http://brlcad.org/wiki/Deuces[deuces] and
http://brlcad.org/wiki/Contributor_Quickies[quickies].  Each task has
a labelled level of difficulty: easy, medium, and hard.  Although the
hard ones are math intense, don't let them scare you away.

== Two-Week Tasks

If you have few hours to spare each day, check our
http://brlcad.org/xref/source/TODO[TODO list]
(http://brlcad.org/xref/source/TODO). These tasks can help potential
developers do modifications and submit patches to gain commit access
to our code repository.  You should be able to complete the tasks on
this list within 14 days.  Before starting on a task, however, you
should discuss it with other developers on our mailing list
mailto:brlcad-devel@lists.sourceforge.net[].

We also have a
http://sourceforge.net/p/brlcad/code/HEAD/tree/brlcad/trunk/BUGS[BUGS]
file, included in each binary and source distribution, which lists the
application bugs that developers are invited to fix.  If you plan to
tackle a bug, remember to report it in our
http://sourceforge.net/p/brlcad/bugs/[bug tracker].

Students participating in Google Code-in can view tasks on the
http://brlcad.org/wiki/GCI_Tasks[BRL-CAD website]
(http://brlcad.org/wiki/GCI_Tasks). Each task is described in a little
detail, and students are directed to relevant BRL-CAD source code or
websites to help them complete these tasks.

== Two-Month Tasks

If you want to become more deeply involved in the BRL-CAD project,
then you should take the time to check our
http://brlcad.org/~sean/ideas.html[ideas page]
(http://brlcad.org/~sean/ideas.html). Students who are participating
in Google Summer Of Code should explore our
http://brlcad.org/~sean/ideas.html[projects page]
(http://brlcad.org/~sean/ideas.html) and the ideas page to get a feel
for the tasks that are available.  These tasks should take about 60
days to complete.
