site:
  title: BRL-CAD Documentation
  url: https://brlcad.org

content:
  edit_url: '{web_url}/edit/{refname}/{path}'
  sources:
  - url: https://github.com/dashohoxha/brlcad-docs
    branches: main
    start_paths:
    - docs
    - translations/*

ui:
  bundle:
    #url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/master/raw/build/ui-bundle.zip?job=bundle-stable
    url: ./ui/ui-bundle.zip
    snapshot: true
  supplemental_files: ./ui/supplemental
  output_dir: ui

asciidoc:
  attributes:
    page-pagination: true

runtime:
  fetch: true
  cache_dir: ./.cache/antora

output:
  dir: /var/www/html
