= ASC-PLOT3(1)
BRL-CAD Team
ifndef::site-gen-antora[:doctype: manpage]
:man manual: BRL-CAD
:man source: BRL-CAD
:page-layout: base

== NAME

asc-plot3 - produce Plot3 instructions from ASCII representation

== SYNOPSIS

*asc-plot3* [_file.asc_ [_unix_plot_]]

== DESCRIPTION

Reads a stream of ASCII data representing Plot3 instructions and
converts it to xref:man:5/plot3.adoc[*plot3*(5)]
format. [cmd]*asc-plot3* reads from standard input and writes to
standard output if file names are not supplied.

The input should consist of lines of the form

....

c arg arg ...
....

where _c_ is one of the single-character Plot3 command names, and it
is followed by white-space-separated arguments of appropriate number
and types for that command. Optional white space and lines beginning
with the comment character `#` are ignored.

== SEE ALSO

xref:man:1/plot3-asc.adoc[*plot3-asc*(1)],
xref:man:1/plot3-plot3.adoc[*plot3-plot3*(1)],
xref:man:1/plot3rot.adoc[*plot3rot*(1)],
xref:man:1/plot3-fb.adoc[*plot3-fb*(1)],
xref:man:3/libplot3.adoc[*libplot3*(3)],
xref:man:5/plot3.adoc[*plot3*(5)]

== AUTHOR

BRL-CAD Team

== COPYRIGHT

This software is Copyright (c) 1991-2021 by the United States
Government as represented by U.S. Army Research Laboratory.

== BUG REPORTS

Reports of bugs or problems should be submitted via electronic mail to
mailto:devs@brlcad.org[]
