= BOT_DUMP(1)
BRL-CAD Team
:doctype: manpage
:man manual: BRL-CAD
:man source: BRL-CAD
:page-layout: base

== NAME

bot_dump - export polygonal BoT primitives without performing evaluation

== SYNOPSIS

*[cmd]#bot_dump#* [-b][-n][-m [rep]_directory_][-o [rep]_file_][-t [rep]_dxf_ | [rep]_obj_ | [rep]_sat_ | [rep]_stl_][-u [rep]_units_][-v][rep]_geom.g_[[rep]_bot1_[rep]_bot2_...]

== DESCRIPTION

*[cmd]#bot_dump#* 

The *[opt]#-b#* option may be specified to indicate that the output file should be in a binary format (e.g., for formats that support ascii and binary formats like stl).

If the *[opt]#-n#* option is specified, BoT surface normals will be included in the output of __obj__ files. This option is specific to __obj__ file generation since normal vector outputs are already an integral part of the __stl__ file outputs and both the __dxf__ and __sat__ file formats do not support or require surface normal generation.

If the *[opt]#-m#* option is specified, then BoTs will be output to the directory name specified with one BoT per file.

The *[opt]#-o#* option specifies what output file the BoT data should be dumped to.

The *[opt]#-t#* is used to specify the desired output file type.  The default output type is STL in ASCII format.

The *[opt]#-u#* option takes a units string that indicates the unit conversion to perform during output (converting from internal millimeter values to the unit type specified).

== EXAMPLE
// <synopsis>
// $ bot_dump  -o <emphasis remap="I">some_bot_dump.dxf</emphasis>  -t <emphasis remap="I">dxf  sample.g  some_bot</emphasis>
// </synopsis>


== DIAGNOSTICS

Error messages are intended to be self-explanatory.

== AUTHOR

BRL-CAD Team

== COPYRIGHT

This software is Copyright (c) 2008-2021 by the United States Government as represented by U.S. Army Research Laboratory.

== BUG REPORTS

Reports of bugs or problems should be submitted via electronic mail to mailto:devs@brlcad.org[]