include::../header.adoc[]

= BRLCAD(1)

== NAME

brlcad - BRL-CAD programs for solid modeling, raytracing, graphics,
and image processing


== DESCRIPTION

The BRL-CAD Distribution contains many directories of materials
(programs, man pages, documents, libraries, etc.). The major
categories of programs are:

_mged_ :: A multi-device interactive editor for constructing and
updating combinatorial solid geometry (CSG) models. See
xref:man:1/mged.adoc[*mged*(1)], and see also _Understanding the
Preparation and Analysis of Solid Models_ by Michael John Muuss
(enclosed, in the "paper" directory).

_librt_ :: A library of functions suitable for interrogation of a CSG
solid model, utilizing ray-tracing techniques. See
xref:man:3/librt.adoc[*librt*(3)].

_rt_ :: A ray-tracing lighting model, for rendering pictures of
xref:man:1/mged.adoc[*mged*(1)] CSG models. See
xref:man:1/rt.adoc[*rt*(1)], -*rtray*(1)-,
-*rtpp*(1)-.

_conv_ :: Programs to convert xref:man:1/mged.adoc[*mged*(1)] and
-*pix*(3)- format binary files to a portable ASCII
form, and back again. See xref:man:1/asc2g.adoc[*asc2g*(1)],
-*asc2pix*(1)-,
xref:man:1/conv-vg2g.adoc[*conv-vg2g*(1)],
xref:man:1/g2asc.adoc[*g2asc*(1)],
xref:man:1/pix2asc.adoc[*pix2asc*(1)].

_libpkg_ :: A "message-passing" interface layered on top of TCP
network links, to ease construction of network-distributed
applications.

_libfb_ :: A generic frame-buffer library which includes support for a
number of display devices, as well as file, network, and debugging
interfaces. Most programs which use this library have the letters "fb"
in their names.  To override your system default frame-buffer, the
environment variable [var]`FB_FILE` can be set.  In addition, some
commands also support a [opt]*-F* [rep]_framebuffer_ option. Note that
the disk file format of _libfb_ is that of
xref:man:5/pix.adoc[*pix*(5)], allowing "framebuffer" files to be
later processed by any of the "pix" family of programs. See
xref:man:3/libfb.adoc[*libfb*(3)],
-*pix-fb*(3)-,
xref:man:5/pix.adoc[*pix*(5)], etc.

_fbserv_ :: TCP-based network server which implements remote
frame-buffer services.

_libtermio_ :: A library to handle terminal mode setting on both
Berkeley or SystemV machines.

_libplot3_ :: A public-domain version of the UNIX-Plot library which
differs from that of the standard
-*libplot*(3)-, by the addition of 3-D
primitives, color, floating point coordinate routines, and the use of
a file pointer parameter. See xref:man:3/libplot3.adoc[*libplot3*(3)],
xref:man:5/plot3.adoc[*plot3*(5)].

_librle_ :: A Run-Length-Encoding (RLE) library, providing functions
originally from the University of Utah in a library package. Note that
the current version of this library reads Edition-3 RLE files. See
-*rle-fb*(1)-,
-*fb-rle*(1)-,
-*rle-pix*(1)-,
-*pix-rle*(1)-,
-*librle*(3)-.

_util_ :: A collection of image-handling utilities, each constructed
as individual tools intended to be used in combination. See
xref:man:1/ap-pix.adoc[*ap-pix*(1)],
xref:man:1/bw-fb.adoc[*bw-fb*(1)],
-*bw-imp*(1)-,
xref:man:1/bw-pix.adoc[*bw-pix*(1)],
-*bw3-pix*(1)-,
xref:man:1/bwcrop.adoc[*bwcrop*(1)],
xref:man:1/bwdiff.adoc[*bwdiff*(1)],
xref:man:1/bwfilter.adoc[*bwfilter*(1)],
xref:man:1/bwhist.adoc[*bwhist*(1)],
xref:man:1/bwmod.adoc[*bwmod*(1)],
xref:man:1/bwrect.adoc[*bwrect*(1)],
xref:man:1/bwrot.adoc[*bwrot*(1)],
xref:man:1/bwscale.adoc[*bwscale*(1)],
xref:man:1/bwstat.adoc[*bwstat*(1)],
-*dunncolor*(1)-,
-*dunnsnap*(1)-,
xref:man:1/fb-bw.adoc[*fb-bw*(1)],
xref:man:1/fb-pix.adoc[*fb-pix*(1)],
-*fb-rle*(1)-,
-*fbanim*(1)-,
xref:man:1/fbclear.adoc[*fbclear*(1)],
xref:man:1/fbcmap.adoc[*fbcmap*(1)],
-*fbcmrot*(1)-,
xref:man:1/fbcolor.adoc[*fbcolor*(1)],
xref:man:1/fbframe.adoc[*fbframe*(1)],
xref:man:1/fbgrid.adoc[*fbgrid*(1)],
xref:man:1/fbpoint.adoc[*fbpoint*(1)],
xref:man:1/fbzoom.adoc[*fbzoom*(1)],
xref:man:1/gencolor.adoc[*gencolor*(1)],
xref:man:1/loop.adoc[*loop*(1)],
xref:man:1/pix-bw.adoc[*pix-bw*(1)],
-*pix-bw3*(1)-,
xref:man:1/pix-fb.adoc[*pix-fb*(1)],
xref:man:1/pixbackgnd.adoc[*pixbackgnd*(1)],
xref:man:1/pixbustup.adoc[*pixbustup*(1)],
xref:man:1/pixdiff.adoc[*pixdiff*(1)],
xref:man:1/pixfilter.adoc[*pixfilter*(1)],
xref:man:1/pixhist.adoc[*pixhist*(1)],
xref:man:1/pixhist3d-plot3.adoc[*pixhist3d-plot3*(1)],
xref:man:1/pixhist3d.adoc[*pixhist3d*(1)],
xref:man:1/pixinterp2x.adoc[*pixinterp2x*(1)],
xref:man:1/pixrect.adoc[*pixrect*(1)],
xref:man:1/pixrot.adoc[*pixrot*(1)],
xref:man:1/pixscale.adoc[*pixscale*(1)],
xref:man:1/pixstat.adoc[*pixstat*(1)],
xref:man:1/pixtile.adoc[*pixtile*(1)],
xref:man:1/plot3-fb.adoc[*plot3-fb*(1)],
xref:man:1/pp-fb.adoc[*pp-fb*(1)],
-*rle-fb*(1)-,
-*rle-pix*(1)-,
xref:man:1/wavelet.adoc[*wavelet*(1)],
xref:man:5/bw.adoc[*bw*(5)],
xref:man:5/pix.adoc[*pix*(5)],
xref:man:5/plot3.adoc[*plot3*(5)].

_fbed_ :: An interactive, termcap-based frame-buffer image editor. See
xref:man:1/fbed.adoc[*fbed*(1)].

_vdeck_ :: A program to convert _mged(1)_ models to _gift(1)_ format
card deck files. See xref:man:1/vdeck.adoc[*vdeck*(1)].

== FB_FILE

Whenever a framebuffer is needed, and the [opt]*-F* option has not
been specified, the environment variable [var]`FB_FILE` is checked for
the device to use.  The format of this variable is either
_[hostname:]/dev/device_name[num]_ or _UNIX_path_, the pathname of a
disk file to be used as a "virtual framebuffer". _Hostname_ is the
name of a remote machine if the remote framebuffer interface is being
used. When a local display device is being specified, the _hostname_
should not be specified, for performance reasons; just the special
string _device_name_ is used to select a particular type of
framebuffer. _Num_ is type dependent and can either mean a display
number or select some options for that type. Note that for security
reasons, it is not permitted to access a disk file via the remote
interface.

If [var]`FB_FILE` is not set, the default for your system will be
used.

The use of [path]_/dev/_ before the _device_name_ is simply to
distinguish them from filenames.  See the end of the
xref:man:3/libfb.adoc[*libfb*(3)] manual page for a list of the device
names and the meanings of any _num_ parameters they may take, and for
a more detailed discussion.

== OPTIONS

A convention exists for the options used on most of the utilities
provided. Random options are usually lower case. Options which could
specify either a screen or file size are, by convention, lower case
for file information, and upper case for screen information. Here's a
list of some of the common options you may encounter:

*-i* :: Inverse flag.  Pretend origin is in upper left corner of
screen, for that good old-fashioned fourth-quadrant behavior.

*-c* :: Various.  Typically means clear the screen first.

*-z* :: Various.  Typically means zoom-in on current area of display.

*-s* _square_file_size_ :: _WARNING:_ Behavior is undefined when the
[opt]*-s* flag is used in conjunction with the [opt]*-w* or [opt]*-n*
flags.

*-w* _file_width_ :: _WARNING:_ Behavior is undefined when the
[opt]*-S* flag is used in conjunction with the [opt]*-W* or [opt]*-N*
flags.

*-W* _screen_width_ :: specifies the number of bytes per sample, where
the flag, where the _\#_ character is a literal "pound" or "sharp"
sign character, typically found over the numeral "3" on ANSI
keyboards. Several programs (like pixrect) can operate on data samples
of arbitrary width. For example, a xref:man:5/pix.adoc[*pix*(5)]
format file can often be treated like a xref:man:5/bw.adoc[*bw*(5)]
format file with a width of three bytes per sample.

== TAPE FORMAT

When dealing with large collections of images, as might be needed for
making a movie, it frequently becomes desirable to deal with magnetic
tapes. Some of the early xref:man:5/pix.adoc[*pix*(5)] tools contained
built-in knowledge of the tape format. While this aberrant early
design has been corrected in favor of using tape-oriented programs
such as -*dd*(1)- in pipelines with the image tools,
our "standard" image format remains.

Regardless of image resolution, all tape records are 24k bytes
long. If an image does not occupy an integral number of tape records,
the last record is padded out. For example, NTSC images in 640x480
format use 37.5 records per image. The
-*files-tape*(1)- utility is helpful in
performing this function.

The capacity of an average 2400 foot reel of tape at 6250 is 6144
records of 24k bytes each. For the various combinations of density and
image resolution, a convention for the number of frames/reel exists:

[%header, cols="3*^"]
|===
|*Density*
|*Resolution*
|*Frames/reel*

|6250
|1k
|48

|6250
|640x480
|160

|6250
|512
|192

|1600
|1k
|12

|1600
|512
|48
|===

== AUTHOR

BRL-CAD Team

include::../footer.adoc[]
