include::../header.adoc[]

= BWCROP(1)

== NAME

bwcrop - crop black and white bw files

== SYNOPSIS

*bwcrop* _in.bw_ _out.bw_

*bwcrop* _in.bw_ _out.bw_ _inwidth_ _outwidth_ _outheight_ _ulx_ _uly_ _urx_ _ury_ _lrx_ _lry_ _llx_ _lly_

== DESCRIPTION

[cmd]*bwcrop* crops any quadrilateral out of an arbitrarily large
xref:man:5/bw.adoc[*bw*(5)] input file (_in.bw_), squares that region
to a given height and width output size, and writes the result to
_out.bw_. The first form of [cmd]*bwcrop* prompts for all parameters
it needs to do the cropping. All responses should be pixel counts or
first quadrant coordinates. The second form allows all of the needed
parameters to be given on the command line and is intended for use
from shell scripts. The coordinate names (the eight arguments listed
above after [rep]_outheight_) refer to the input file, and more
specifically to upper-left-x (ulx), lower-right-y (lry), etc., in
clockwise-from-upper-left order.

The nearest input pixel is selected for each output pixel.  No
interpolation is done by this program.

== SEE ALSO

xref:man:1/brlcad.adoc[*brlcad*(1)],
xref:man:1/bwrect.adoc[*bwrect*(1)],
xref:man:1/bwscale.adoc[*bwscale*(1)],
xref:man:5/bw.adoc[*bw*(5)]

== AUTHOR

BRL-CAD Team

include::../footer.adoc[]
