= BWHIST(1)
ifndef::site-gen-antora[:doctype: manpage]
:man manual: BRL-CAD
:man source: BRL-CAD
:page-role: manpage

== NAME

bwhist - display a histogram of a black and white bw file on a
framebuffer

== SYNOPSIS

*bwhist* [-v] [_file.bw_]

== DESCRIPTION

[cmd]*bwhist* displays a histogram of the pixel values in a
xref:man:5/bw.adoc[*bw*(5)] format file.  If a file is not given,
standard input is read. The output will be displayed on the frambuffer
selected via the [var]`FB_FILE` environment variable (see
xref:man:3/libfb.adoc[*libfb*(3)]).

The relative frequency is displayed on the x axis scaled so that the
maximum is full screen.  The value 0 is at the bottom of the screen,
255 is at the top. The output is overlaid on whatever is currently on
the display.

The [opt]*-v* flag will output the histogram values on the terminal.

== SEE ALSO

xref:man:1/brlcad.adoc[*brlcad*(1)],
xref:man:1/bwhisteq.adoc[*bwhisteq*(1)],
xref:man:1/bwstat.adoc[*bwstat*(1)], xref:man:5/bw.adoc[*bw*(5)]

== BUGS

This program assumes it has at least 512 lines in y to work with.

== AUTHOR

BRL-CAD Team

== COPYRIGHT

This software is Copyright (c) 1989-2021 by the United States
Government as represented by U.S. Army Research Laboratory.

== BUG REPORTS

Reports of bugs or problems should be submitted via electronic mail to
mailto:devs@brlcad.org[]
