include::../header.adoc[]

= BWSCALE(1)

== NAME

bwscale - change the size of a black and white bw file

== SYNOPSIS

*bwscale* [-r] [-s _squareinsize_] [-w _in_width_] [-n _in_height_] [-S _squareoutsize_] [-W _out_width_] [-N _out_height_] [_infile.bw_] > _outfile.bw_

== DESCRIPTION

*bwscale* will take a black and white xref:man:5/bw.adoc[*bw*(5)]
format file of given dimensions and produce a larger or smaller scaled
version. The [opt]*-w* and [opt]*-n* flags specify the input file
width and number of scan lines in pixels; they can be set to the same
value via [opt]*-s*. Similarly, the [opt]*-W* and [opt]*-N* flags
specify the desired output file width and number of scan lines in
pixels; they can be set to the same value via [opt]*-S*. Defaults of
512 are assumed for any unspecified dimensions.

By default, the algorithm used is bilinear interpolation if scaling
up, and a box filter of arbitrary size if scaling down.  For the box
filter a "square pixel" assumption is made; that is, all whole and
fractional input pixels falling into a rectangle the size of an output
pixel contribute equally according to the fraction of the output pixel
area they cover. When interpolating, the edge pixels are preserved,
i.e., all of the interpolated pixels fall inside of the edges.  This
can be a bit surprising when doubling the size of a file, for example,
as only the edge pixels will fall at exactly the location of an output
pixel.

Specifying the [opt]*-r* flag changes from bilinear interpolation to
nearest neighbor interpolation, i.e., it enlarges the image by pixel
replication.

== SEE ALSO

xref:man:1/brlcad.adoc[*brlcad*(1)],
xref:man:1/bwcrop.adoc[*bwcrop*(1)],
xref:man:1/bwrect.adoc[*bwrect*(1)], xref:man:5/bw.adoc[*bw*(5)],
xref:man:1/pixscale.adoc[*pixscale*(1)]

== BUGS

This program cannot scale up in one dimension and down in the other at
the same time.

The box filter used for scaling down results in the usual
high-frequency ripple.

Optional cubic interpolation would be nice.

== AUTHOR

BRL-CAD Team

include::../footer.adoc[]
