= CAD_PAREA(1)
ifndef::site-gen-antora[:doctype: manpage]
:man manual: BRL-CAD
:man source: BRL-CAD
:page-role: manpage

== NAME

cad_parea - compute area of polygon

== SYNOPSIS

*cad_parea* [-i _input_] [-o _output_]

== DESCRIPTION

[cmd]*cad_parea* reads from _input_ (standard input if not given) a
series of polygon vertex (_x_,_y_) coordinate values and writes to
_output_ (standard output if not given) the polygon's area. Lines not
beginning with a number are silently skipped. Vertices are assumed to
be given in counter-clockwise cyclic order.

== HINTS

A hole can be accommodated as a clockwise section connected to the
periphery by a line segment traced in both directions.

Disjoint pieces may be connected by a line segment traced in both
directions.

== EXAMPLE

....
$ cad_parea # _comment_ 1 0 2 0 2 1 3 1 3 2 2 2 1 2 0 2 0 1 1 1 _^D_ 4 
....

== SEE ALSO

xref:man:1/cad_boundp.adoc[*cad_boundp*(1)]

== DIAGNOSTICS

Improperly formatted input produces an error message and terminates
[cmd]*cad_parea* with non-zero exit status.

[cmd]*cad_parea* outputs "0" for the area of a degenerate polygon.

== AUTHOR

Douglas A. Gwyn, BRL/VLD-VMB

== COPYRIGHT

This software is Copyright (c) 1991-2021 by the United States
Government as represented by U.S. Army Research Laboratory.

== BUG REPORTS

Reports of bugs or problems should be submitted via electronic mail to
mailto:devs@brlcad.org[]
