include::../header.adoc[]

= CAD_BOUNDP(1)

== NAME

cad_boundp - find bounding polygon of two-dimensional view

== SYNOPSIS

*cad_boundp* [-i _input_] [-o _output_] [-t _tolerance_] [-v]

== DESCRIPTION

[cmd]*cad_boundp* reads from _input_ (standard input if not specified)
a series of line segment endpoint (_x_,_y_) coordinate values
describing a two-dimensional view of the edges of a (possibly
transparent) three-dimensional object and writes to _output_ (standard
output if not specified) the (_x_,_y_) coordinates of vertices of the
bounding polygon in counter-clockwise order, starting with the vertex
having the smallest _y_ coordinate. If the [opt]*-v* argument is used,
instead of points the output will consist of line segment data
suitable for input into another invocation of [cmd]*cad_boundp* .

Input lines not beginning with a number are silently skipped. This
feature can be used to accommodate comments or additional control
information in the data stream.

When a _tolerance_ is specified, a point is considered to be identical
to a previously-input point if its _x_ and _y_ coordinates are both
within _tolerance_ of the first point encountered within a group
passing the tolerance test. Otherwise, point coordinates must match
precisely or the algorithm will produce erroneous results.

== RESTRICTIONS

[cmd]*cad_boundp* may output a polygon smaller than desired or produce
a "degenerate input" message if the _tolerance_ is too tight or if
input is incomplete. It may be wise to specify double the expected
_tolerance_.

Holes within the view cannot be recognized.

Silhouette thickness must everywhere exceed _tolerance_ (no narrow
necking-down) or a portion of the silhouette will be "lost"; in
particular, the view should not consist of disjoint parts.

== EXAMPLE

....
$ cad_boundp -t 0.1 # _comment_ 0 2 0 1 3 2 3 1 2 0 1 0 0 2 3 2 0 2 3 1 0 1 3 2 2 2 2 0 1 0 1 2 2 2 1 2 0 1 3 1 _^D_ 1 0 2 0 2 1 3 1 3 2 2 2 1 2 0 2 0 1 1 1 
....

== SEE ALSO

xref:man:1/cad_parea.adoc[*cad_parea*(1)]

== DIAGNOSTICS

Any error condition causes [cmd]*cad_boundp* to terminate with
non-zero exit status after it prints an error message on the standard
error output.

An illegal argument or improperly formatted input produces an
appropriate message.

If a vertex having only one line segment connected to it is found on
the perimeter, [cmd]*cad_boundp* produces the message "degenerate
input".

If there is too much data for [cmd]*cad_boundp* to handle, the message
"out of memory" is produced.

== AUTHOR

Douglas A. Gwyn, BRL/VLD-VMB

include::../footer.adoc[]
