= CAD_PAREA(1)
BRL-CAD Team
:doctype: manpage
:man manual: BRL-CAD
:man source: BRL-CAD
:page-layout: base

== NAME

cad_parea - compute area of polygon

== SYNOPSIS

*[cmd]#cad_parea#* [-i[rep]_input_][-o[rep]_output_]

== DESCRIPTION

*[cmd]#cad_parea#* reads from __input__ (standard input if not given) a series of polygon vertex (__x__,__y__) coordinate values and writes to __output__ (standard output if not given) the polygon's area. Lines not beginning with a number are silently skipped. Vertices are assumed to be given in counter-clockwise cyclic order.

== HINTS

A hole can be accommodated as a clockwise section connected to the periphery by a line segment traced in both directions.

Disjoint pieces may be connected by a line segment traced in both directions.

== EXAMPLE

[quote]
$ cad_parea # _comment_ 1 0 2 0 2 1 3 1 3 2 2 2 1 2 0 2 0 1 1 1 _^D_ 4 

== SEE ALSO

xref:man:1/cad_boundp.adoc[*cad_boundp*](1)

== DIAGNOSTICS

Improperly formatted input produces an error message and terminates *[cmd]#cad_parea#* with non-zero exit status.

*[cmd]#cad_parea#* outputs "0" for the area of a degenerate polygon.

== AUTHOR

Douglas A. Gwyn, BRL/VLD-VMB

== COPYRIGHT

This software is Copyright (c) 1991-2021 by the United States Government as represented by U.S. Army Research Laboratory.

== BUG REPORTS

Reports of bugs or problems should be submitted via electronic mail to mailto:devs@brlcad.org[]