= DECIMATE(1)
ifndef::site-gen-antora[:doctype: manpage]
:man manual: BRL-CAD
:man source: BRL-CAD
:page-role: manpage

== NAME

decimate - Reduce image or data file of MxN tuples to one of size IxJ

== SYNOPSIS

*decimate* _nbytes/pixel_ _width_ _height_ [_outwidth_ _outheight_]

== DESCRIPTION

[cmd]*decimate* reads a file of _width_ by _height_ data items (each
of which may be of arbitrary size as given by _nbytes/pixel_ ), and
discards enough of them to result in an output file of _outwidth_ by
_outheight_ items, both of which default to 512. If the input image
size is not an integer multiple of the output image size, then the
decimated result will be padded with zero elements (pixels) on the
right and top to achieve an output image of exactly the specified
size.

To process a xref:man:5/bw.adoc[*bw*(5)] format file, use a value of 1
for _nbytes/pixel_. To process a xref:man:5/pix.adoc[*pix*(5)] format
file, use a value of 3 for _nbytes/pixel_.

== SEE ALSO

xref:man:1/brlcad.adoc[*brlcad*(1)], xref:man:5/pix.adoc[*pix*(5)],
xref:man:5/bw.adoc[*bw*(5)]

== AUTHOR

BRL-CAD Team

== COPYRIGHT

This software is Copyright (c) 1992-2021 by the United States
Government as represented by U.S. Army Research Laboratory.

== BUG REPORTS

Reports of bugs or problems should be submitted via electronic mail to
mailto:devs@brlcad.org[]
