= FAST4-G(1)
BRL-CAD Team
:doctype: manpage
:man manual: BRL-CAD
:man source: BRL-CAD
:page-layout: base

== NAME

fast4-g - FASTGEN4 Translator (FASTGEN4 to BRL-CAD)

== SYNOPSIS

*[cmd]#fast4-g#* [-dwq][-o [rep]_plot_file_][-m [rep]_muves_warnings_][-c [rep]_id_list_][-x [rep]_RT_DEBUG_FLAG_][-b [rep]_BU_DEBUG_FLAG_][rep]_file.fastgen4_[rep]_file.g_

== DESCRIPTION

*[cmd]#fast4-g#* converts the specified __file.fastgen4__ to a BRL-CAD __file.g__ file.

The *[opt]#-d#* option prints debugging information and the *[opt]#-w#* option prints warnings whenever an object is assigned a default name (no name specified in the FASTGEN4 file).

The *[opt]#-q#* option requests quiet mode, so that nothing will be printed except errors.

The *[opt]#-b#* option specifies a value for a debug flag for libbu and the *[opt]#-x#* option specifies a value for the librt debug flag.

The *[opt]#-o#* option indicates that all CTRI and CQUAD elements that get processed should be output to the specified plot_file in libplot3 format.  This plot file can be viewed in MGED using the __overlay__ command.

The *[opt]#-m#* option requests that information about any CHGCOMP and CBACKING elements be output in the specified __muves_warnings__ file.

The *[opt]#-c#* option allows the user to specify a restricted set of components to process from the input file. The __id_list__ may be a comma-separated list of ident numbers and ranges. For example, *[opt]#-c 3002,5678,9213,1002-1100#* will convert only the regions with idents of 3002,5678,9213, and everything from 1002 through 1100.

If you have a FASTGEN2 or FASTGEN3 format file, they can be converted by processing them with *[cmd]#rpatch#* and then providing the resulting rpatch file to the *[cmd]#patch-g#* converter.  See their respective manual pages for more information.

The __file.fastgen4__ file is expected to be in the FASTGEN 4.1 format as defined in the FASTGEN 4.1 User Manual.

__CCONE1__, __CCONE2__, and __CCONE3__ elements are converted to BRL-CAD truncated right cylinders (__TRC__). _CHEX2_ elements are converted to BRL-CAD arbitrary convex polyhedrons (__ARB8__). _CLINE_ elements are converted to BRL-CAD cline solids. __CQUAD__, __CTRI__, and __CHEX1__ elements are converted to faces of a BRL-CAD BOT (Bag Of Triangles). __CSPHERE__ elements are converted to BRL-CAD sphere (__SPH__) solids. BRL-CAD region ident numbers are assigned by combining the FASTGEN4 group and component numbers:

....

	ident = group x 1000 + component
....

and object names are assigned from the FASTGEN4 __$NAME__ elements using an algorithm to create unique BRL-CAD names.

== EXAMPLE
// <synopsis>
// $ fast4-g <emphasis remap="I">sample.fastgen4 sample.g</emphasis>
// </synopsis>


== SEE ALSO

xref:man:1/rpatch.adoc[*rpatch*](1), xref:man:1/patch-g.adoc[*patch-g*](1)__FASTGEN 4.1 User's Manual__, XRESV Tech Note 94-01, Hugh Griffis and Maty Lentz, April 1994

== DIAGNOSTICS

Error messages are intended to be self-explanatory.

== AUTHOR

BRL-CAD Team

== COPYRIGHT

This software is Copyright (c) 1994-2021 by the United States Government as represented by U.S. Army Research Laboratory.

== BUG REPORTS

Reports of bugs or problems should be submitted via electronic mail to mailto:devs@brlcad.org[]