include::../header.adoc[]

= FAST4-G(1)

== NAME

fast4-g - FASTGEN4 Translator (FASTGEN4 to BRL-CAD)

== SYNOPSIS

*fast4-g* [-dwq] [-o _plot_file_] [-m _muves_warnings_] [-c _id_list_] [-x _RT_DEBUG_FLAG_] [-b _BU_DEBUG_FLAG_] _file.fastgen4_ _file.g_

== DESCRIPTION

[cmd]*fast4-g* converts the specified _file.fastgen4_ to a BRL-CAD
_file.g_ file.

The [opt]*-d* option prints debugging information and the [opt]*-w*
option prints warnings whenever an object is assigned a default name
(no name specified in the FASTGEN4 file).

The [opt]*-q* option requests quiet mode, so that nothing will be
printed except errors.

The [opt]*-b* option specifies a value for a debug flag for libbu and
the [opt]*-x* option specifies a value for the librt debug flag.

The [opt]*-o* option indicates that all CTRI and CQUAD elements that
get processed should be output to the specified plot_file in libplot3
format.  This plot file can be viewed in MGED using the _overlay_
command.

The [opt]*-m* option requests that information about any CHGCOMP and
CBACKING elements be output in the specified _muves_warnings_ file.

The [opt]*-c* option allows the user to specify a restricted set of
components to process from the input file. The _id_list_ may be a
comma-separated list of ident numbers and ranges. For example,
[opt]*-c 3002,5678,9213,1002-1100* will convert only the regions with
idents of 3002,5678,9213, and everything from 1002 through 1100.

If you have a FASTGEN2 or FASTGEN3 format file, they can be converted
by processing them with [cmd]*rpatch* and then providing the resulting
rpatch file to the [cmd]*patch-g* converter.  See their respective
manual pages for more information.

The _file.fastgen4_ file is expected to be in the FASTGEN 4.1 format
as defined in the FASTGEN 4.1 User Manual.

_CCONE1_, _CCONE2_, and _CCONE3_ elements are converted to BRL-CAD
truncated right cylinders (_TRC_). _CHEX2_ elements are converted to
BRL-CAD arbitrary convex polyhedrons (_ARB8_). _CLINE_ elements are
converted to BRL-CAD cline solids. _CQUAD_, _CTRI_, and _CHEX1_
elements are converted to faces of a BRL-CAD BOT (Bag Of
Triangles). _CSPHERE_ elements are converted to BRL-CAD sphere (_SPH_)
solids. BRL-CAD region ident numbers are assigned by combining the
FASTGEN4 group and component numbers:

....
ident = group x 1000 + component
....

and object names are assigned from the FASTGEN4 _$NAME_ elements using
an algorithm to create unique BRL-CAD names.

== EXAMPLE

....
$ fast4-g sample.fastgen4 sample.g
....


== SEE ALSO

xref:man:1/rpatch.adoc[*rpatch*(1)],
xref:man:1/patch-g.adoc[*patch-g*(1)] _FASTGEN 4.1 User's Manual_,
XRESV Tech Note 94-01, Hugh Griffis and Maty Lentz, April 1994

== DIAGNOSTICS

Error messages are intended to be self-explanatory.

== AUTHOR

BRL-CAD Team

include::../footer.adoc[]
