include::../header.adoc[]

= FBFADE(1)

== NAME

fbfade - fade a frame buffer image in or out

== SYNOPSIS

*fbfade* [-H] [-f _input_image_name_] [-s _input_square_size_] [-w _input_width_]  +
     [-n _input_height_] [-S _output_square_size_] [-W _output_width_] [-N _output_height_]  +
     +[+[-F] _output_frame_buffer_name_]

== DESCRIPTION

[cmd]*fbfade* gradually displays an image on a frame buffer, one
randomly chosen pixel at a time.

=== Options

-H:: (high resolution) Assumes 1024 by 1024 pixels for default input
image size instead of 512 by 512. Explicitly-specified sizes override
the default, and if actual input image size is smaller than requested,
the actual size will be used. If output frame buffer size is not
specified, the revised input size will be requested for output. If
actual output frame buffer size is greater than requested, only the
lower-left portion of the frame buffer will be used. Actual sizes
depend on details of specific frame buffers.

-f _input_image_name_:: Inputs the image to be displayed from the
specified frame buffer or xref:man:5/pix.adoc[*pix*(5)] file, instead
of using pure background (which fades out the image already on the
output frame buffer).

-s _input_square_size_:: Specifies input image width and height.

-w _input_width_:: Specifies input image width.

-n _input_height_:: Specifies input image height.

-S _output_square_size_:: Specifies output frame buffer width and
height.

-W _output_width_:: Specifies output frame buffer width.

-N _output_height_:: Specifies output frame buffer height.

-F _output_frame_buffer_name_:: Outputs to the specified frame buffer
instead of the one specified by the _FB_FILE_ environment variable (or
the default, if _FB_FILE_ is not set). If this is the last option
specified, the _-F_ is optional.

== CAVEAT

[cmd]*fbfade* works best in conjunction with a frame buffer having
very fast access to pixels.

== EXAMPLE

The following shell script can be used to produce a slick slide show:

[source,sh]
....
fbclear
for i in *.pix
do
    fbfade -f $i
    sleep 15
done
fbfade
....

== SEE ALSO

xref:man:3/libfb.adoc[*libfb*(3)], xref:man:5/pix.adoc[*pix*(5)].

== DIAGNOSTICS

Error messages are intended to be self-explanatory.

== AUTHORS

Douglas A. Gwyn, BRL/VLD-VMB; Gary S. Moss, BRL/VLD-VMB

include::../footer.adoc[]
