= FBLINE(1)
BRL-CAD Team
:doctype: manpage
:man manual: BRL-CAD
:man source: BRL-CAD
:page-layout: base

== NAME

fbline - draw a colored line on a framebuffer

== SYNOPSIS

*[cmd]#fbline#*  [-c] [-F [rep]_framebuffer_] [-S|s [rep]_squaresize_] [-W|w [rep]_screen_width_] [-N|n [rep]_screen_height_] [-r [rep]_red_] [-g [rep]_green_] [-b [rep]_blue_] [rep]_x1_ [rep]_y1_ [rep]_x2_ [rep]_y2_

== DESCRIPTION

*[cmd]#fbline#* draws a line on the currently selected framebuffer between the points (x1, y1) and (x2, y2). The points must be within the bounds of the framebuffer, or they are silently limited to an edge. Use xref:man:1/fbpoint.adoc[*fbpoint*](1) to determine where to position the points. The environment variable FB_FILE specifies the current framebuffer; see xref:man:1/brlcad.adoc[*brlcad*](1). Alternatively, the framebuffer may be explicitly specified by using the *[opt]#-F#* flag.

By default, the requested framebuffer size is 512x512 pixels. 

The *[opt]#-S#* (or *[opt]#-s#* ) flag sets the width and height to the same value. The *[opt]#-W#* (or *[opt]#-w#* ) and *[opt]#-N#* (or *[opt]#-n#* ) flags are used for setting them individually. 

The *[opt]#-c#* flag causes the screen to be cleared before the line is displayed. The default behavior is to draw the line on the current image without clearing the screen.

The *[opt]#-r red#*  , *[opt]#-g green#*  , *[opt]#-b blue#* flags specify alternate red, green, and blue rgb values for the line color. The default color is white.  Thus, a green line is created by turning off the red and green components, i.e., with *[opt]#-r 0#* *[opt]#-b 0#* options.

== EXAMPLE

fbline -s 1024 -c -r0 -b0 82 11 300 472

== SEE ALSO

xref:man:1/brlcad.adoc[*brlcad*](1), xref:man:1/fbed.adoc[*fbed*](1), xref:man:1/fblabel.adoc[*fblabel*](1), xref:man:1/fbpoint.adoc[*fbpoint*](1), xref:man:1/plot3-fb.adoc[*plot3-fb*](1), xref:man:3/libfb.adoc[*libfb*](3), xref:man:5/pix.adoc[*pix*](5)

== AUTHOR

BRL-CAD Team

== COPYRIGHT

This software is Copyright (c) 1988-2021 by the United States Government as represented by U.S. Army Research Laboratory.

== BUG REPORTS

Reports of bugs or problems should be submitted via electronic mail to mailto:devs@brlcad.org[]