= FBPOINT(1)
BRL-CAD Team
:doctype: manpage
:man manual: BRL-CAD
:man source: BRL-CAD
:page-layout: base

== NAME

fbpoint - point at and identify screen coordinates

== SYNOPSIS

*[cmd]#fbpoint#*  [-F [rep]_framebuffer_] [-w [rep]_width_] [-n [rep]_height_] [-s [rep]_squaresize_] [-x[[rep]_prefix_]] [-y[[rep]_prefix_]] [[rep]_initialx_[rep]_initialy_]

== DESCRIPTION

*[cmd]#fbpoint#* allows you to move a non-destructive cursor around on the display. As the cursor is moved around, *[cmd]#fbpoint#* writes the coordinates of the pixel pointed at by the cursor, and the red, green, and blue values of that pixel, on standard error *[cmd]#fbpoint#* also writes the last set of coordinates pointed to on standard out on exit. The starting position is center-screen unless optional __initialx initialy__ is given.

The ``__h__'', ``__j__'', ``__k__'', and ``__l__'' commands step the cursor one pixel left, down, up, or right respectively, and the ``__H__'', ``__J__'', ``__K__'', and ``__L__'' commands step the cursor in the corresponding directions in big increments. The ``__B__'', ``__N__'', ``__P__'', and ``__L__'', and ``__^B__'' (control-B), ``__^N__'', ``__^P__'', and ``__^F__'', are also little and big (respectively) cursor movement commands.

A ``__?__'' prints a short command summary, and typing ``__q__'' or ``__Q__'' exits the program.

Using this program with grave accents in a shell script in order to interactively grab a pair of coordinates is one of its main intentions.  This is the reason for the feedback on standard error and the final coordinate pair on standard out. By default, both the x and y coordinates are written.  If the *[opt]#-x#* or *[opt]#-y#* flags are given only those coordinates will be written.  In these cases an optional __prefix__ can follow the flag which will be appended to the output coordinate. This is to facilitate passing the output of this program as arguments to another.

[[_example]]
== EXAMPLES

*[cmd]#fbpoint#* by itself is used to pick coordinates or pixel values from a display.

fbscanplot `fbpoint -y`

allows you to choose the scanline to plot using fbpoint.

pix-fb `fbpoint -x-X -y-Y` _file.pix_

allows you to select an x, y screen coordinate location and then place the lower left corner of the image __file.pix__ there.

== SEE ALSO

xref:man:1/brlcad.adoc[*brlcad*](1), xref:man:1/fbgrid.adoc[*fbgrid*](1), xref:man:1/fbzoom.adoc[*fbzoom*](1)

== AUTHOR

BRL-CAD Team

== COPYRIGHT

This software is Copyright (c) 1986-2021 by the United States Government as represented by U.S. Army Research Laboratory.

== BUG REPORTS

Reports of bugs or problems should be submitted via electronic mail to mailto:devs@brlcad.org[]