= FBSERV(1)
ifndef::site-gen-antora[:doctype: manpage]
:man manual: BRL-CAD
:man source: BRL-CAD
:page-role: manpage

== NAME

fbserv - Frame-buffer Server

== SYNOPSIS

*fbserv* [-s | _S_ | _square_size_] [-w | _W_ | _width_] [-n | _N_ | _height_] [-p _port_number_] [-F _frame_buffer_] [-v] [_port_number_] [_frame_buffer_]

== DESCRIPTION

[cmd]*fbserv* opens a framebuffer that may be used by any BRL-CAD
routine accessing a framebuffer. The [opt]*-s* (or [opt]*-S*) option
specifies that a square framebuffer of the specified size (in pixels)
is desired. The [opt]*-n* (or [opt]*-N*) option indicates the
framebuffer height. The [opt]*-w* (or [opt]*-W*) option indicates the
framebuffer width. The [opt]*-v* option (verbosity) yields more
information about the current process. The [opt]*-p* option supplies a
port number and the [opt]*-F* option indicates what framebuffer device
to use. The framebuffer device may be included on the command line
without the [opt]*-F* option if it is the last token on the command
line. The port number may also be specified without the [opt]*-p*
option. If options [opt]*-F* and [opt]*-p* are both omitted, the port
number must be followed by the framebuffer device on the command
line. While [cmd]*fbserv* is running, its port number may then be used
in other commands that access a framebuffer by supplying that port
number with the [opt]*-F* option for that command. The [cmd]*fbserv*
command may be executed by users at a shell prompt, or it may be used
as an inetd remote framebuffer server by specifying [cmd]*fbserv* as a
server program in _inetd.conf_.

== EXAMPLES

....
fbserv 0 &
....

This command will start a standalone fbserv daemon. Any access of a
framebuffer specifying port 0 will result in opening a new
framebuffer.

....
fbserv -s 1024 0 /dev/sgil &
....

The above command will open a 1024 X 1024 '/dev/sgil' framebuffer and
associate port number 0 with it. Any access of a framebuffer
specifying port 0 will use the already opened '/dev/sgil' framebuffer.

== SEE ALSO

xref:man:1/bw-fb.adoc[*bw-fb*(1)],
xref:man:1/cell-fb.adoc[*cell-fb*(1)],
xref:man:1/cmap-fb.adoc[*cmap-fb*(1)],
xref:man:1/gif-fb.adoc[*gif-fb*(1)],
xref:man:1/pix-fb.adoc[*pix-fb*(1)],
xref:man:1/plot3-fb.adoc[*plot3-fb*(1)],
xref:man:1/polar-fb.adoc[*polar-fb*(1)],
xref:man:1/rle-fb.adoc[*rle-fb*(1)],
xref:man:1/fbcmap.adoc[*fbcmap*(1)],
xref:man:1/fbcmrot.adoc[*fbcmrot*(1)],
xref:man:1/fbclear.adoc[*fbclear*(1)],
xref:man:1/fbcbars.adoc[*fbcbars*(1)],
xref:man:1/fbanin.adoc[*fbanin*(1)],
xref:man:1/fbcolor.adoc[*fbcolor*(1)],
xref:man:1/fbfade.adoc[*fbfade*(1)],
xref:man:1/fbframe.adoc[*fbframe*(1)],
xref:man:1/fbfree.adoc[*fbfree*(1)],
xref:man:1/fbgamma.adoc[*fbgamma*(1)],
xref:man:1/fbgrid.adoc[*fbgrid*(1)],
xref:man:1/fbhelp.adoc[*fbhelp*(1)],
xref:man:1/fblabel.adoc[*fblabel*(1)],
xref:man:1/fbline.adoc[*fbline*(1)],
xref:man:1/fbpoint.adoc[*fbpoint*(1)],
xref:man:1/fbscanplot.adoc[*fbscanplot*(1)],
xref:man:1/fbstretch.adoc[*fbstretch*(1)],
xref:man:1/fbzoom.adoc[*fbzoom*(1)]

== DIAGNOSTICS

Error messages are intended to be self-explanatory.

== AUTHOR

BRL-CAD Team

== COPYRIGHT

This software is Copyright (c) 1994-2021 by the United States
Government as represented by U.S. Army Research Laboratory.

== BUG REPORTS

Reports of bugs or problems should be submitted via electronic mail to
mailto:devs@brlcad.org[]
