include::../header.adoc[]

= FBSTRETCH(1)

== NAME

fbstretch - stretch a frame buffer image

== SYNOPSIS

*fbstretch* [-f _input_image_name_] [-s _input_square_size_] [-w _input_width_]  +
     [-n _input_height_] [-a] [-x _horizontal_scale_ _factor_] [-y _vertical_scale_ _factor_]  +
     [-v] [-S _output_square_size_] [-W _output_width_] [-N _output_height_]  +
     +[+[-F] _output_frame_buffer_ _name_]

== DESCRIPTION

[cmd]*fbstretch* expands or compresses a frame buffer image, in either
or both the horizontal and vertical directions. The image scaling
origin (fixed point) is the lower left-hand corner of the
display. When expanding (scale factor greater than 1), pixels are
simply replicated; when compressing (scale factor less than 1), pixel
averaging is performed unless sampling is explicitly requested by the
[rep]_-a_ option.

The default input image size is 512 by 512. Explicitly specified sizes
override the default, and if actual input image size is smaller than
requested, the actual size will be used. If not specified, requested
output frame buffer size will be the stretched revised input size. If
there are margins within the requested output beyond the stretched
image, they will be cleared to background; if the stretched image
would extend beyond the requested output size, it will be clipped to
fit, even if there is room for it in the actual frame buffer. Actual
sizes depend on details of specific frame buffers.

=== Options

-f _input_image_name_:: Inputs the image to be displayed from the
specified frame buffer or xref:man:5/pix.adoc[*pix*(5)] file, instead
of modifying the output frame buffer in place. This option may not
work if input and output frame buffers are the same device.

-s _input_square_size_:: Specifies input image width and height.

-w _input_width_:: Specifies input image width.

-n _input_height_:: Specifies input image height.

-a :: (no averaging) Specifies that output pixels will be sampled from
the input, instead of being computed by averaging RGB values.

-v :: (verbose) Causes actual sizes and scale factors used to be
printed on the standard error output.

-x _horizontal_scale_factor_:: Scales the image by the specified
factor in the horizontal direction; the default is the ratio of
requested output to input widths, if specified, otherwise 1.

-y _vertical_scale_factor_:: Scales the image by the specified factor
in the vertical direction; the default is the ratio of requested
output to input heights, if specified, otherwise 1.

-S _output_square_size_:: Specifies output frame buffer width and
height.

-W _output_width_:: Specifies output frame buffer width.

-N _output_height_:: Specifies output frame buffer height.

-F _output_frame_buffer_name_:: Outputs to the specified frame buffer
instead of the one specified by the [rep]_FB_FILE_ environment
variable (or the default, if [rep]_FB_FILE_ is not set). If this is
the last option specified, the [rep]_-F_ is optional.

== DISCUSSION

Pixel averaging may be meaningless for some images or color maps, in
which case sampling should be specified. Images of the Mandelbrot set
(see -*mandel*(1)-) are a good example of this.

== EXAMPLE

The following procedure enlarges an image, obtained from a personal
computer via the [cmd]*gif-fb* utility, to fill a 1280-by-1024 frame
buffer.

....
$ gif-fb _image.gif_ # displays the 320x200 PC image

$ fbstretch -w 320 -n 200 -W 1280 -N 1024
....

== SEE ALSO

xref:man:1/gif-fb.adoc[*gif-fb*(1)],
-*mandel*(1)-,
xref:man:1/pixscale.adoc[*pixscale*(1)],
xref:man:3/libfb.adoc[*libfb*(3)], xref:man:5/pix.adoc[*pix*(5)]

== DIAGNOSTICS

Error messages are intended to be self-explanatory.

== AUTHOR

Douglas A. Gwyn, BRL/VLD-VMB

include::../footer.adoc[]
