include::../header.adoc[]

= G-EGG(1)

== NAME

g-egg - Panda3D Translator (BRL-CAD to EGG)

== SYNOPSIS

*g-egg* [-v89] [-xX _lvl_] [-a _abs_tol_] [-r _rel_tol_] [-n _norm_tol_] [-D _calculation_tolerance_] [-o _EGG_file_] [-P _number_of_CPUs_] _database.g_ _object(s)_

== DESCRIPTION

[cmd]*g-egg* converts the specified _object(s)_ from a BRL-CAD
_database.g_ file to the _panda3d_ file format. The [opt]*-x* option
specifies an RT debug flag and the [opt]*-X* option specifies an NMG
debug flag. The [opt]*-a*, [opt]*-r*, and [opt]*-n* options specify
tessellation tolerances. The [opt]*-D* option specifies a
calculational distance tolerance (mm). Any two vertices that are less
than this distance apart will be treated as the same vertex. The
[opt]*-v* option requests verbose output, which goes to standard
error. The [opt]*-o* option specifies the name of the file to receive
the output (stdout is the default). [opt]*-8* option tells the
facetizer to use the marching cubes algorithm. [opt]*-9* option tells
the facetizer to use the "bottess" algorithm. The [opt]*-P* option
specifies the number of CPU's to be used.

== EXAMPLE

....
$ g-egg -o sample.egg sample.g sample_object
....

== DIAGNOSTICS

Error messages are intended to be self-explanatory.

== AUTHOR

BRL-CAD Team

include::../footer.adoc[]
