include::../header.adoc[]

= G-NFF(1)

== NAME

g-nff - NFF Translator (BRL-CAD to NFF)

== SYNOPSIS

*g-nff* [-v] [-i] [-xX _lvl_] [-e _error_file_] [-D _calculation_tolerance_] [-a _abs_tol_] [-r _rel_tol_] [-n _norm_tol_] [-o _output.nff_] _database.g_ _object(s)_

== DESCRIPTION

[cmd]*g-nff* converts the specified _object(s)_ from a BRL-CAD
_database.g_ file to the _NFF_ file format. The [opt]*-x* option
specifies an RT debug flag and the [opt]*-X* option specifies an NMG
debug flag. The [opt]*-a*, [opt]*-r*, and [opt]*-n* options specify
tessellation tolerances. The [opt]*-D* option specifies a
calculational distance tolerance (mm). Any two vertices that are less
than this distance apart will be treated as the same vertex. The
[opt]*-v* option requests verbose output. The [opt]*-i* option
requests the output file units to be inches (the default is mm). The
[opt]*-o* option specifies the name of the file to receive the output
(stdout is the default). The [opt]*-e* option specifies a file for
receiving the error messages.

== EXAMPLE

....
$ g-nff -o sample.nff sample.g sample_object
....


== DIAGNOSTICS

Error messages are intended to be self-explanatory.

== AUTHOR

BRL-CAD Team

include::../footer.adoc[]
