= G-PLY(1)
BRL-CAD Team
:doctype: manpage
:man manual: User Commands
:man source: BRL-CAD
:page-layout: base

== NAME

g-ply -  Stanford PLY exporter (BRL-CAD to PLY)

== SYNOPSIS

*[cmd]#g-ply#* [-v][-xX [rep]_lvl_][-a [rep]_abs_tess_tol_][-r [rep]_rel_tess_tol_][-n [rep]_norm_tess_tol_][-t [rep]_type_][-s][-D [rep]_dist_calc_tol_]-o [rep]_output_file_name_[rep]_database.g_[rep]_object(s)_...

== DESCRIPTION

*[cmd]#g-ply#*  converts the specified__object(s)__ from a BRL-CAD _database.g_ file to the _Stanfort PLY_ file format. 

The following options are recognized.

*[opt]#-o filename#* ::
Specify output file name.

*[opt]#-s#* ::
Write out one object per file, instead of merging individual objects into a single ply file. 

*[opt]#-t#*  type (asc: ascii), (le: little endian), (be: big endian)::
Specify the type of PLY file to write. 

*[opt]#-D##* ::
Specify a calculational distance tolerance (mm). Any two vertices that are less than this distance apart will be treated as the same vertex.

*[opt]#-a##* ::
Specify the absolute tesselation tolerance.

*[opt]#-r##* ::
Specify the relative tesselation tolerance.

*[opt]#-n##* ::
Specify the surface-normal tesselation tolerance.

*[opt]#-x##* ::
Specify an RT debug flag.

*[opt]#-X##* ::
Specify an NMG debug flag.

*[opt]#-v#* ::
Enable verbose output.

== EXAMPLE
// <synopsis>
//       $ g-ply -o <emphasis remap="I">sample.ply sample.g sample_object</emphasis>
//     </synopsis>


== DIAGNOSTICS

Error messages are intended to be self-explanatory.

== AUTHOR

BRL-CAD Team

== COPYRIGHT

This software is Copyright (c) 2003-2021 by the United States Government as represented by U.S. Army Research Laboratory. 

== BUG REPORTS

Reports of bugs or problems should be submitted via electronic mail to mailto:devs@brlcad.org[]