= G-RAW(1)
BRL-CAD Team
:doctype: manpage
:man manual: User Commands
:man source: BRL-CAD
:page-layout: base

== NAME

g-raw -  RAW Translator (BRL-CAD to RAW)

== SYNOPSIS

*[cmd]#g-raw#* [-o [rep]_output_file_][-m [rep]_output_directory_][-i][-8][-D [rep]_calculation_tolerance_][-a [rep]_absolute_tol_][-r [rep]_relative_tol_][-n [rep]_normal_tol_][-xX [rep]_level_][-v][rep]_database.g_[rep]_object(s)_...

== DESCRIPTION

*[cmd]#g-raw#* converts the specified __object(s)__ from a BRL-CAD __database.g__ file to the __stereolithography__ file format.

The following options are recognized.

*[opt]#-o PATH#* ::
Specify output file name (default is stdout).

*[opt]#-m DIR#* ::
Specify a directory for output files. Each region converted is written to a separate file. File names are constructed from the full path names of each region (the path from the specified object to the region). Any "/" characters in the path name are replaced by "@" characters and "." and white space are replaced by "_" characters. If the -m option is not specified, all regions are written to the same file. The *[opt]#-o#*  and *[opt]#-m#*  options are mutually exclusive. 

*[opt]#-i#* ::
Use inches as the output format (the default is mm).

*[opt]#-8#* ::
Facetize using the marching cubes algorithm.

*[opt]#-D##* ::
Specify a calculational distance tolerance (mm). Any two vertices that are less than this distance apart will be treated as the same vertex.

*[opt]#-a##* ::
Specify the absolute tesselation tolerance.

*[opt]#-r##* ::
Specify the relative tesselation tolerance.

*[opt]#-n##* ::
Specify the surface-normal tesselation tolerance.

*[opt]#-x##* ::
Specify an RT debug flag.

*[opt]#-X##* ::
Specify an NMG debug flag.

*[opt]#-v#* ::
Enable verbose output.

== EXAMPLE
// <synopsis>
// $ g-raw -o <emphasis remap="I">sample.raw sample.g sample_object</emphasis>
// </synopsis>


== DIAGNOSTICS

Error messages are intended to be self-explanatory.

== AUTHOR

BRL-CAD Team

== COPYRIGHT

This software is Copyright (c) 2013-2021 by the United States Government as represented by U.S. Army Research Laboratory.

== BUG REPORTS

Reports of bugs or problems should be submitted via electronic mail to mailto:devs@brlcad.org[]