= G-SHELL-RECT(1)
ifndef::site-gen-antora[:doctype: manpage]
:man manual: User Commands
:man source: BRL-CAD
:page-role: manpage

== NAME

g-shell-rect - Produce triangulated shell from BRL-CAD model

== SYNOPSIS

*g-shell-rect* [-a _rpp_args_] [-R _edge_tol_] [-p _plotfile_] [-X _lvl_] [-d _debug_level_] [-b] [-n] [-i _initial_ray_dir_] [-g _cell_size_] -o _brlcad_output_file_ _database.g_ _object(s)_

== DESCRIPTION

[cmd]*g-shell-rect* converts the specified _objects(s)_ from a BRL-CAD
model _database.g_ to a single NMG solid using raytracing. Rays are
fired in a uniform grid. The direction for the first set of rays is
chosen by calculating the presented area of the bounding box of the
_object(s)_ and selecting the direction with the largest area. The
user may override this by specifying a desired initial ray direction
using the [opt]*-i* option (see below). The initial shell is
constructed using only the first and last intersections with the
_object(s)_. This will typically result in some rather large faces
with normals at right angles to the ray direction. Unless the
[opt]*-n* option is specified, these faces are then subdivided
(according to the _cell_size_) and additional rays fired from the
other two directions are used to refine their shape. The resulting NMG
solid will be named _shell_ and will be written to the specified
_brlcad_output_file_.

The following command line options are recognized:

*-g* _cell_size_:: Specify the dimensions (in millimeters) of the grid
spacing.  The default is 50mm.

*-i* _initial_ray_dir_:: Specify the initial ray direction.  Valid
values are X, Y, or Z. The best results are usually obtained by
raytracing in the direction that produces the most hits first.

*-d* _debug_level_:: Set the debugging level.  Higher values produce
more debugging information.

*-n*:: Suppresses the refinement stage (firing rays from the secondary
and tertiary axis directions).

*-b*:: Output a BOT rather than an NMG.

*-a* _rpp_args_:: Add an RPP for refining.

*-R* _edge_tol_:: Supply edge tolerance.

*-p* _plotfile_:: Supply plotfile for plot edge breaking.

*-X* _lvl_:: Supply NMG debug flags.

*-o* _output.g_:: Specifies the name of the BRL-CAD geometry file to
create.

== EXAMPLE

....
$ g-shell-rect -o shell.g sample.g sample_object
....


== DIAGNOSTICS

Error messages are intended to be self-explanatory.

== AUTHOR

BRL-CAD Team

== COPYRIGHT

This software is Copyright (c) 1998-2021 by the United States
Government as represented by U.S. Army Research Laboratory.

== BUG REPORTS

Reports of bugs or problems should be submitted via electronic mail to
mailto:devs@brlcad.org[]
