= G-STEP(1)
ifndef::site-gen-antora[:doctype: manpage]
:man manual: BRL-CAD
:man source: BRL-CAD
:page-role: manpage

== NAME

g-step - STEP Translator/Exporter (BRL-CAD to STEP AP203)

== SYNOPSIS

*g-step* -o _output_file.stp_ _database.g_ [_object(s)_]

== DESCRIPTION

[cmd]*g-step* converts the specified objects of the BRL-CAD database,
_database.g_, to a STEP AP203 file, _output_file.stp_.

The following options are recognized.

*-o* _output_file_or_directory_:: Specifies the output file to which
the STEP output is written.

There are some inherent limits when writing BRL-CAD geometry to the
AP203 format.  The primary solid object representation used by STEP is
the NURBS Boundary Representation, and BRL-CAD's CSG models must be
converted to that representation upon export.  Boolean operations are
not supported in AP203, so the objects are either to write out all
objects and post-process them in another system to get the final forms
or have BRL-CAD itself perform the boolean evaluation at the region
level.  The latter will eventually be the default, but for the moment
that feature is not yet ready for general deployment.

[[_example]]
== EXAMPLES

.Export All .g File Contents
====
[ui]`g-step -o m35.stp m35.g`

Writes out the full hierarchy of the .g file to m35.stp .
====

.Export Parts of a .g File
====
[ui]`g-step -o m35.stp m35.g cab suspension`

Writes out the hierarchies associated with the combs cab and
suspension, along with all combs and solids needed to define those
hierarchies.
====

== AUTHOR

BRL-CAD Team

== COPYRIGHT

This software is Copyright (c) 1993-2021 by the United States
Government as represented by U.S. Army Research Laboratory.

== BUG REPORTS

Reports of bugs or problems should be submitted via electronic mail to
mailto:devs@brlcad.org[]
