= G-VAR(1)
ifndef::site-gen-antora[:doctype: manpage]
:man manual: User Commands
:man source: BRL-CAD
:page-role: manpage

== NAME

g-var - Produce (OpenGL) Vertex Arrays from BOT BRL-CAD geometry

== SYNOPSIS

*g-var* [-v] [-y] [-s _scale_] [-f] [-o _outfile_] _infile.g_ _object_

== DESCRIPTION

[cmd]*g-var* writes the bag of triangle (BOT) primitives of the
specified _object_ in a binary array format to _outfile_ or to
_stdout_.

== OPTIONS

*-v*:: Request verbose output.

*-y*:: Transform the coordinate system from xyz to xzy.

*-s* [ui]`scale`:: Scale the output geometry by factor _scale_. By
default the scale factor is 0.001 (standard transformation from meters
to millimeters).

*-f*:: Flip face normals. This changes both the vertex order and the
output normals.

*-o* _outfile_:: The output will be written to _outfile_. By default
the output is written to stdout.

== FILE FORMAT

_TODO_

== EXAMPLE

....
$ g-var -o sample.mesh sample.g sample_object
....

== DIAGNOSTICS

Error messages are intended to be self-explanatory.

== AUTHOR

Prasad Silva

== COPYRIGHT

This software is Copyright (c) 2006-2021 by the United States
Government as represented by U.S. Army Research Laboratory.

== BUG REPORTS

Reports of bugs or problems should be submitted via electronic mail to
mailto:devs@brlcad.org[]
