= G-VAR(1)
BRL-CAD Team
:doctype: manpage
:man manual: User Commands
:man source: BRL-CAD
:page-layout: base

== NAME

g-var - Produce (OpenGL) Vertex Arrays from BOT BRL-CAD geometry

== SYNOPSIS

*[cmd]#g-var#* [-v][-y][-s [rep]_scale_][-f][-o [rep]_outfile_][rep]_infile.g_[rep]_object_

== DESCRIPTION

*[cmd]#g-var#* writes the bag of triangle (BOT) primitives of the specified __object__ in a binary array format to __outfile__ or to __stdout__.

== OPTIONS

*[opt]#-v#* ::
Request verbose output.

*[opt]#-y#* ::
Transform the coordinate system from xyz to xzy.

*[opt]#-s#* [ui]`scale` ::
Scale the output geometry by factor __scale__. By default the scale factor is 0.001 (standard transformation from meters to millimeters).

*[opt]#-f#* ::
Flip face normals. This changes both the vertex order and the output normals.

*[opt]#-o#* _outfile_::
The output will be written to __outfile__. By default the output is written to stdout.

== FILE FORMAT

_TODO_

== EXAMPLE
// <synopsis>
// $ g-var -o <emphasis remap="I">sample.mesh sample.g sample_object</emphasis>
// </synopsis>


== DIAGNOSTICS

Error messages are intended to be self-explanatory.

== AUTHOR

Prasad Silva

== COPYRIGHT

This software is Copyright (c) 2006-2021 by the United States Government as represented by U.S. Army Research Laboratory.

== BUG REPORTS

Reports of bugs or problems should be submitted via electronic mail to mailto:devs@brlcad.org[]