include::../header.adoc[]

= IMGDIMS(1)

== NAME

imgdims - guess the width and height of an image file

== SYNOPSIS

*imgdims* [-ns] [-# _bytes_per_pixel_] _file_name_

or

*imgdims* [-# _bytes_per_pixel_] _num_bytes_

== DESCRIPTION

[cmd]*imgdims* uses the autosizing capability of
xref:man:5/libbn.adoc[*libbn*(5)] to guess the dimensions (in pixels)
of an image. The image size may be expressed either implicitly, by
specifying the name of the file; or explicitly, by specifying a number
of bytes.

The [opt]*-n* option specifies that the dimensions should be extracted
directly from _file_name_, in the form of any of the standard BRL-CAD
command-line options. Given the [opt]*-s* option, [cmd]*imgdims*
ignores any dimensions encoded in _file_name_ and uses the size of the
file in bytes to compute the number of pixels in the image and then
guess the image's width and height. The [opt]*-#* option specifies the
size of each pixel (in bytes).

If _file_name_ is specified with neither of the [opt]*-s* and
[opt]*-n* options, [cmd]*imgdims* tries to extract the dimensions from
_file_name_, and if that fails it computes the image size and guesses
the width and height. If the [opt]*-#* option is not specified,
[cmd]*imgdims* determines the pixel size based on the extension on
_file_name_. If, additionally, _num_bytes_ was specified or
_file_name_ contains none of the recognized extensions, [cmd]*imgdims*
assumes that there are 3-byte-wide pixels.

== SEE ALSO

xref:man:3/libbn.adoc[*libbn*(3)]

== AUTHOR

Paul Tanenbaum

include::../footer.adoc[]
