= IMGDIMS(1)
BRL-CAD Team
:doctype: manpage
:man manual: BRL-CAD
:man source: BRL-CAD
:page-layout: base

== NAME

imgdims - guess the width and height of an image file

== SYNOPSIS

*[cmd]#imgdims#* [-ns][-# [rep]_bytes_per_pixel_][rep]_file_name_

or 
*[cmd]#imgdims#* [-# [rep]_bytes_per_pixel_][rep]_num_bytes_ +
    

== DESCRIPTION

*[cmd]#imgdims#* uses the autosizing capability of xref:man:5/libbn.adoc[*libbn*](5) to guess the dimensions (in pixels) of an image. The image size may be expressed either implicitly, by specifying the name of the file; or explicitly, by specifying a number of bytes.

The *[opt]#-n#* option specifies that the dimensions should be extracted directly from __file_name__, in the form of any of the standard BRL-CAD command-line options. Given the *[opt]#-s#* option, *[cmd]#imgdims#* ignores any dimensions encoded in __file_name__ and uses the size of the file in bytes to compute the number of pixels in the image and then guess the image's width and height. The *[opt]#-##* option specifies the size of each pixel (in bytes).

If __file_name__ is specified with neither of the *[opt]#-s#*  and *[opt]#-n#* options, *[cmd]#imgdims#* tries to extract the dimensions from __file_name__, and if that fails it computes the image size and guesses the width and height. If the *[opt]#-##* option is not specified, *[cmd]#imgdims#* determines the pixel size based on the extension on __file_name__. If, additionally, __num_bytes__ was specified or __file_name__ contains none of the recognized extensions, *[cmd]#imgdims#* assumes that there are 3-byte-wide pixels.

== SEE ALSO

xref:man:3/libbn.adoc[*libbn*](3)

== AUTHOR

Paul Tanenbaum

== COPYRIGHT

This software is Copyright (c) 1997-2021 by the United States Government as represented by U.S. Army Research Laboratory.

== BUG REPORTS

Reports of bugs or problems should be submitted via electronic mail to mailto:devs@brlcad.org[]