= NIRT(1)
ifndef::site-gen-antora[:doctype: manpage]
:man manual: BRL-CAD User Commands
:man source: BRL-CAD
:page-role: manpage

== NAME

nirt - interactively ray trace a BRL-CAD geometric model

== SYNOPSIS

*nirt* [_options_] _model.g_ _objects_...

== DESCRIPTION

[cmd]*nirt* operates on the specified _objects_ in the database
_model.g_, using xref:man:3/librt.adoc[*librt*(3)] to trace rays
according to commands read from the standard input and producing an
ASCII report of the results. By default, the user can interact with
[cmd]*nirt*, repeatedly specifying origination points and directions
for rays and the format and destination for the reports. Locations may
be input and output in either model coordinates (_x_, _y_, _z_)
or view (a.k.a. grid-plane) coordinates (_h_, _v_,
_d_). Similarly, direction may be input and output either as vectors
expressed in model coordinates or as angles of azimuth and elevation.

=== Options

*-A [rep]#attribute_name...#*:: Adds the names to the list of
attributes that will be reported when the "attributes" partition
information value is specified. See also the _attr_ command below.

*-M*:: Causes [cmd]*nirt* to read the eye point and either the
orientation quaternion (new format) or the view-rotation matrix (old
format) from the standard input, and fire a single ray from the point
in the specified direction. This option allows [cmd]*nirt* to be
called directly from within [cmd]*mged* using the [cmd]*nirt* and
_rrt_ commands.

*-b*:: Causes [cmd]*nirt* to perform a _backout_ command before the
first _shoot_ command (see the description of these two commands
below). This is probably only useful with the [opt]*-M* option.

*-B* _rt_bot_minpieces_:: Causes [cmd]*nirt* to adjust the setting of
_rt_bot_minpieces_ to the indicated value. A value of zero here
indicates that the "pieces" methodology should not be used. A value
greater than zero indicates that all BOT primitives containing more
than _rt_bot_minpieces_ triangles should be broken down into a
separate piece for each triangle. This can result in significant
improvement in raytrace speed at the cost of more memory use.

*-e* _script_:: Causes [cmd]*nirt* to run the _script_ string before
reading the standard input. Multiple commands in _script_ may be
separated with a semicolon ';'. Scripts specified with either the
[opt]*-e* or [opt]*-f* options are executed in the order in which they
are specified on the command line.

*-f* _format_:: Causes [cmd]*nirt* to load the predefined format (see
[opt]*-L*) _format_ or script file before reading standard input.
Scripts specified with either the [opt]*-e* or [opt]*-f* options are
executed in the order in which they are specified on the command line.

*-E*:: Causes [cmd]*nirt* to ignore any [opt]*-e* or [opt]*-f* options
specified previously on the command line.

*-L*:: List output formatting options.

*-s*:: Causes [cmd]*nirt* to run in silent (that is, non-verbose)
mode. In this mode, which is useful in a pipeline,[cmd]*nirt* does not
print its initial lines of output or the prompt.

*-v*:: Causes [cmd]*nirt* to run in verbose mode. The default is
verbose mode, except if standard input has been redirected, in which
case the default is silent mode.

*-H* _n_:: Set flag (_n_) for enable/disable informational header
(_n_=1 [on] by default, always off in silent mode).

*-u* _n_:: Sets the _useair_ member of the _rt_i_ structure to
_n_. See the discussion of the _useair_ command below.

*-O* _n_:: Causes [cmd]*nirt* to handle multiple regions' claims to
segments of a ray according to action _n_. The argument _n_ may be any
of the values 0, 1, 2, or 3, or their corresponding key words
"resolve", "rebuild_fastgen", "rebuild_all", or "retain". See the
discussion of the _overlap_claims_ command below.

*-x* _v_:: Sets the xref:man:3/librt.adoc[*librt*(3)] debug flags to
the hexadecimal bit vector _v_. See the discussion of the _libdebug_
command below.

*-X* _v_:: Sets [cmd]*nirt*'s own debug flags to the hexadecimal bit
vector _v_. See the discussion of the _debug_ command below.

[cmd]*nirt* will check in two places for a [path]_.nirtrc_ file -
first in the current directory, and if it is not found there, in the
user's home directory. If found, [cmd]*nirt* begins by reading
from it.  This start-up file may contain any [cmd]*nirt* commands and
is useful for loading predefined states or initializing actions for
output statements.

=== Commands

*xyz [x y z]* :: Sets the ray origination point to (_x_, _y_, _z_). If
this command is invoked with no arguments, [cmd]*nirt* prints the
current ray origination point in model coordinates. Default is (0, 0,
0). Changing (_x_, _y_, _z_) will change (_h_, _v_, _d_), according to
the current direction vector.

*hv [h v[d]]* :: Sets the ray origination point to (_h_, _v_, _d_). If
this command is invoked with only two arguments, [cmd]*nirt*
interprets them as _h_ and _v_, and _d_ retains its previous value. If
invoked with no argument, the command causes [cmd]*nirt* to print the
current ray origination point in view coordinates. Default is (0, 0,
0).  Changing (_h_, _v_, _d_) will change (_x_, _y_, _z_), according
to the current direction vector.

*dir [dx dy dz]* :: Sets the direction vector to the unit vector in
direction (_dx_, _dy_, _dz_). If this command is invoked with no
arguments, [cmd]*nirt* prints the current direction vector.  Default
is (-1, 0, 0).  Changing (_dx_, _dy_, _dz_) will change the azimuth
and elevation angles.

*ae [az el]* :: Sets the direction vector to point _from_ azimuth =
_az_ and elevation = _el_. If this command is invoked with no
arguments, [cmd]*nirt* prints the current values of the azimuth and
elevation angles. Default is (0, 0).  Changing azimuth and elevation
will change the direction vector.

*s* :: Fires a ray from the current origination point in the current
direction.

*bot_minpieces [n]* :: Sets "rt_bot_minpieces" to the new value
_n_. If _n_ is not provided, the current value of "rt_bot_minpieces"
is displayed.  See the discussion of the [opt]*-B* option above for
more details.

*backout [n]* :: Command to set the backout flag.  With no option,
prints the current value. When activated, backs the ray origination
point out of the geometry: _h_ and _v_ retain their previous values
and _d_ is set to _Dmax_, the largest value of _d_ anywhere in the
geometry.  Default is 0 (deactivated), 1 is active.

*useair [n]*:: Sets the _useair_ member of the _rt_i_ structure to the
integer _n_.  If _n_ is 0, then [cmd]*nirt* ignores any air in the
geometry.  If this command is invoked with no arguments, [cmd]*nirt*
prints the current value of _useair_. Default is 0.

*overlap_claims [n]* :: Specifies how to handle multiple regions'
claims to segments of a ray. If _n_ is 0 or "resolve", then all
overlaps are resolved in favor of a single region and any other
claimants are ignored.  If _n_ is 2 or "rebuild_all", then all
overlaps are rebuilt, so any overlapping regions along the ray create
individual (geometrically intersecting) partitions.  If _n_ is 3 or
"retain", then all overlaps are retained. In this case, the resulting
partitions are always geometrically disjoint, each one is owned by a
single region according to the current overlap resolution strategy,
but every claimant is recorded. If _n_ is 1 or "rebuild_fastgen", then
[cmd]*nirt* takes on _FASTGEN_ behavior, so overlaps of plate-mode
primitives are rebuilt, but other overlaps are retained. This command
is useful with the _claimant_count_, _claimant_list_, and
_claimant_listn_ output items.  Default is "resolve".

*attr {-f|-p|attr_names...}* :: When used with one or more names, adds
the names to the list of attributes that will be printed when the
"attributes" value is requested in the output format string.
+
The [opt]*-p* option to the [cmd]*attr* command causes it to print the
list of attributes that will be reported.
+
The [opt]*-f* option clears the attributes table.

*units [u]* :: Causes [cmd]*nirt* to read and write all distances and
locations in units of _u_.  Valid choices for _u_ are "mm"; "cm"; "m";
"in"; and "ft".  If this command is invoked with no arguments,
[cmd]*nirt* prints the current choice of I/O units.  Default is the
units of _model.g_.

*fmt [t format item item ...]* :: Sets the action for output
statements of type _t_. If this command is invoked with only one
argument, a valid statement type, [cmd]*nirt* prints the current
format and items for the specified type. See the discussion of output
statements below.

*dest [d]*:: Sets the destination for subsequent output actions to
_d_. If the first character of _d_ is '|', then _d_ is interpreted as
a pipeline to which to write its output. Otherwise, if _d_ is the
string "default", [cmd]*nirt* sets the destination to the standard
output. Otherwise, _d_ is interpreted as a file. In any event, _d_ is
not closed until the user quits [cmd]*nirt* or resets the destination
by another invocation of the _dest_ command. If this command is
invoked with no arguments, [cmd]*nirt* prints the current value of
_d_. Default is "default", that is, the standard output.

*statefile [f]* :: Sets the name of the state file to which to dump
and from which to load state information. See the discussion of the
_dump_ and _load_ commands below.  If this command is invoked with no
arguments, [cmd]*nirt* prints the current name of the state file.
Default is "nirt_state".

*dump* :: Writes state information to the state file.  The ray
origination point and direction vector, useair, units, destination,
and all the output actions are dumped.

*load* :: Reads state information from the state file.  The state file
loaded may contain any [cmd]*nirt* commands.

*print item*:: Prints the current value of the output item _item_. See
the discussion of output statements below.

*libdebug v* :: Sets the xref:man:3/librt.adoc[*librt*(3)] debug flags
(the _debug_ member of the _rt_g_ structure) to the hexadecimal bit
vector _v_. These flags control the amount and kind of diagnostic
print statements xref:man:3/librt.adoc[*librt*(3)] executes.  If _v_
is 0, then no diagnostics are produced. If this command is invoked
with no arguments, [cmd]*nirt* prints the current value of _v_ and the
names of any of its bits that are set.  Default is 0.

*debug v* :: Sets [cmd]*nirt*'s internal debug flags to the
hexadecimal bit vector _v_.  These flags control the amount and kind
of diagnostic print statements [cmd]*nirt* executes.  If _v_ is 0,
then no diagnostics are produced.  If this command is invoked with no
arguments, [cmd]*nirt* prints the current value of _v_ and the names
of any of its bits that are set.  Default is 0.

*?* :: Prints a help menu to the standard output.

*q* :: Quits [cmd]*nirt*.

=== Output Statements

[cmd]*nirt* allows the user a high degree of control, via the _fmt_
command, over what information gets printed out for each ray and in
what format. There are six types of output statements, each of which
is executed under appropriate circumstances. The types and their use
are:

*r*::
Ray. The first output statement executed whenever the _s_ command is invoked. 

*h*:: Head.  Executed immediately after the ray statement if the ray
hits anything.

*p*:: Partition.  Executed once for each partition along the ray if
the ray hits anything.

*f*:: Foot. The last output statement executed if the ray hits
anything.

*m*:: Miss.  Executed immediately after the ray statement if the ray
hits nothing.

*o*:: Overlap.  Executed once for each overlap along the ray if the
ray hits anything.

*g*:: Gap.  Executed once for each gap along the ray if the ray
encounters any gaps.

The action associated with each output statement type is essentially a
xref:man:3/printf.adoc[*printf*(3)] statement, with a format string
and a list of output items. The items may be chosen from a set of
values that [cmd]*nirt* updates according to user commands and
location along the ray. These values may be categorized as pertaining
to the entire ray, partitions along the ray, or overlaps.  The values
are explained in the following table.

==== Ray Information

*x_orig* :: _x_ coordinate of ray origination point.

*y_orig* :: _y_ coordinate of ray origination point.

*z_orig* :: _z_ coordinate of ray origination point.

*d_orig* :: _d_ coordinate of ray origination point.

*h* :: _h_ coordinate for the entire ray.

*v* :: _v_ coordinate for the entire ray.

*x_dir* :: _x_ component of direction vector.

*y_dir* :: _y_ component of direction vector.

*z_dir* :: _z_ component of direction vector.

*a* :: azimuth of view (i.e., of ray direction).

*e* :: elevation of view (i.e., of ray direction).

==== Partition Information

*attributes* :: A string variable consisting of the names and values
of the attributes requested by the _attr_ command or the [opt]*-A*
command line option.

*x_in* :: _x_ coordinate of entry into current region.

*y_in* :: _y_ coordinate of entry into current region.

*z_in* :: _z_ coordinate of entry into current region.

*d_in* :: _d_ coordinate of entry into current region.

*x_out* :: _x_ coordinate of exit from current region.

*y_out* :: _y_ coordinate of exit from current region.

*z_out* :: _z_ coordinate of exit from current region.

*d_out* :: _d_ coordinate of exit from current region.

*los* :: line-of-sight distance through current region.

*scaled_los* :: scaled line of sight: product of line-of-sight
distance through current region and region solidity (sometimes called
"percent LOS").

*path_name* :: full path name of current region.

*reg_name* :: name of current region, as might be obtained by passing
_path_name_ to xref:man:1/basename.adoc[*basename*(1)].

*reg_id* :: region ID of current region.

*claimant_count* :: number of regions claiming this partition (that
is, participating in a retained overlap).

*claimant_list* :: space-separated list of names of regions claiming
this partition (that is, participating in a retained overlap).

*claimant_listn* :: Same as _claimant_list_, except that it is
newline-, rather than space-separated.

*obliq_in* :: entry obliquity for current region.

*obliq_out* :: exit obliquity for current region.

*nm_x_in* :: _x_ component of entry normal vector

*nm_y_in* :: _y_ component of entry normal vector

*nm_z_in* :: _z_ component of entry normal vector

*nm_h_in* :: _h_ component of entry normal vector

*nm_v_in* :: _v_ component of entry normal vector

*nm_d_in* :: _d_ component of entry normal vector

*nm_x_out* :: _x_ component of exit normal vector

*nm_y_out* :: _y_ component of exit normal vector

*nm_z_out* :: _z_ component of exit normal vector

*nm_h_out* :: _h_ component of exit normal vector

*nm_v_out* :: _v_ component of exit normal vector

*nm_d_out* :: _d_ component of exit normal vector

*surf_num_in* :: entry-surface ID of entry solid.

*surf_num_out* :: exit-surface ID of exit solid.

*ap Informat* on

*x_gap_in* :: _x_ coordinate of entry into gap.

*y_gap_in* :: _y_ coordinate of entry into gap.

*z_gap_in* :: _z_ coordinate of entry into gap.

*gap_los* :: line-of-sight distance through gap.

==== Overlap Information

*ov_reg1_name* :: name of one of the overlapping regions.

*ov_reg2_name* :: name of the other overlapping region.

*ov_reg1_id* :: region ID of one of the overlapping regions.

*ov_reg2_id* :: region ID of the other overlapping region.

*ov_sol_in* :: name of one of the overlapping solids.

*ov_sol_out* :: name of the other overlapping solid.

*ov_los* :: line-of-sight distance through the overlap.

*ov_x_in* :: _x_ coordinate of entry into overlap.

*ov_y_in* :: _y_ coordinate of entry into overlap.

*ov_z_in* :: _z_ coordinate of entry into overlap.

*ov_d_in* :: _d_ coordinate of entry into overlap.

*ov_x_out* :: _x_ coordinate of exit from overlap.

*ov_y_out* :: _y_ coordinate of exit from overlap.

*ov_z_out* :: _z_ coordinate of exit from overlap.

*ov_d_out* :: _d_ coordinate of exit from overlap.

== HINTS

Ray origination coordinates specified with the _hv_ command are
immediately converted for internal use to model coordinates, according
to the current direction vector.  If you want to change the ray
direction and origination point, and you're using view coordinates,
you probably want to change the ray direction _before_ you use the
_hv_ command.

The name "nirt" stands for "Natalie's interactive ray tracer". 

== DEFINITIONS

The usage in [cmd]*nirt* of the following terms corresponds to that
found in xref:man:1/mged.adoc[*mged*(1)] and elsewhere throughout
BRL-CAD. We provide the definitions here for reference.

=== View Coordinates

We define the view coordinate system (more precisely its basis vectors
_m_, _n_, and _o_) in terms of the basis vectors _i_, _j_, and _k_ of
the model coordinate system as follows:

_m_ is the opposite of the direction vector and corresponds to _d_,
_n_ = _k_ × _m_ corresponds to _h_, and _o_ = _m_ × _n_ corresponds to
_v_.

Thus if the direction vector is (-1, 0, 0), then (_d_, _h_, _v_) =
(_x_, _y_, _z_).

=== Azimuth and Elevation

Azimuth is the angle measured around _k_ (right-hand rule) from the
_xz_ plane to _m_. Elevation is the angle measured toward _k_ from the
_xy_ plane to _m_.

== FILES

_~/.nirtrc_::
run-time configuration file

== SEE ALSO

xref:man:1/mged.adoc[*mged*(1)], xref:man:3/librt.adoc[*librt*(3)],
xref:man:3/printf.adoc[*printf*(3)]

== AUTHOR

BRL-CAD Team

== COPYRIGHT

This software is Copyright (c) 1984-2021 United States Government as
represented by the U.S. Army Research Laboratory.

== BUG REPORTS

Reports of bugs or problems should be submitted via electronic mail to
mailto:devs@brlcad.org[]
