include::../header.adoc[]

= PATCH-G(1)

== NAME

patch-g - convert FASTGEN ASCII databases into binary MGED databases.

== SYNOPSIS

*patch-g* [_options_] _output.g_

== DESCRIPTION

This program converts FASTGEN geometry into BRL-CAD
xref:man:1/mged.adoc[*mged*(1)] formats. FASTGEN is a modeling system
used by the Air Force and Navy to create military target
descriptions. FASTGEN databases consist of the following primitives
which can be converted by [cmd]*patch-g* : polygons, plates, boxes,
wedges, cylinders, spheres, and rods. It is recommended that
[cmd]*patch-g* be run with the [opt]*-p* option for most uses.

[cmd]*patch-g* requires that the FASTGEN file be run through the
pre-processor [cmd]*rpatch* . This is achieved by executing rpatch <
_fastgen_file_ > _file.rpatch_. Once this step is executed,
[cmd]*patch-g* can be used to convert the intermediate file into a
binary xref:man:1/brlcad.adoc[*brlcad*(1)] ".g" file.

[cmd]*patch-g* will provide messages when encountering problems in the
conversion of FASTGEN geometry. For further debugging information, the
-d flag with levels 1-3 of debugging can be provided.

The available options are:

*-T tolerance_distance*:: The _tolerance_distance_ is specified in
inches. Any two vertices within this distance from each other will be
considered the same vertex.

*-A perp_tolerance*:: The _perp_tolerance_ is specified as the cosine
of an angle (0.0 through 1.0). If the cosine of the angle between two
vectors is less than the specified tolerance, then the vectors are
considered perpendicular.

*-u number_of_unions*:: The _number_of_unions_ is the number of union
operations per region, and has a pre-specified default value.

*-x librt_debug_flag*:: Specifies a flag for debugging the _librt_
package.

*-X NMG_debug_flag*:: Specifies a flag for NMG routine debugging.

*-p*:: Produce polysolid output rather than the default NMG solids.

*-6*:: Convert plate-mode triangles using ARB6 solids.

*-f preprocessed_input_file*:: Use the specified file as the input for
conversion.

*-i labels_file*:: Specifies desired group names to override defaults.

*-m materials_file*:: Specifies material properties to be assigned to
components.

*-n*:: Process volume mode as plate mode.

*-t title*:: Specifies a title for the output model (default is
"patch-g conversion").

*-o top_level_name*:: Specifies a name for the top level object
(default is "all").

*-r*:: Reverse normals for plate mode triangles.

*-c "X Y Z"*:: Specifies centroid, in inches, for some plate mode
surface normal calculations. Quotation marks are needed to provide for
the embedded blanks.

*-d debug_level*:: Specifies a debug level (1-3).

== EXAMPLE

  rpatch < fastgen_file > file.rpatch

  patch-g -p -f file.rpatch  file.g

== DIAGNOSTICS

The diagnostics are intended to be self-explanatory.

== SEE ALSO

xref:man:1/brlcad.adoc[*brlcad*(1)], xref:man:1/mged.adoc[*mged*(1)]

== AUTHOR

Bill Mermagen, Jr.

include::../footer.adoc[]
