= PATCH-G(1)
BRL-CAD Team
:doctype: manpage
:man manual: BRL-CAD
:man source: BRL-CAD
:page-layout: base

== NAME

patch-g - convert FASTGEN ASCII databases into binary MGED databases.

== SYNOPSIS

*[cmd]#patch-g#* [[rep]_options_][rep]_output.g_

== DESCRIPTION

This program converts FASTGEN geometry into BRL-CAD xref:man:1/mged.adoc[*mged*](1) formats. FASTGEN is a modeling system used by the Air Force and Navy to create military target descriptions. FASTGEN databases consist of the following primitives which can be converted by *[cmd]#patch-g#* : polygons, plates, boxes, wedges, cylinders, spheres, and rods. It is recommended that *[cmd]#patch-g#* be run with the *[opt]#-p#* option for most uses.

*[cmd]#patch-g#* requires that the FASTGEN file be run through the pre-processor *[cmd]#rpatch#*  . This is achieved by executing rpatch<__fastgen_file__>__file.rpatch__. Once this step is executed, *[cmd]#patch-g#* can be used to convert the intermediate file into a binary xref:man:1/brlcad.adoc[*brlcad*](1) ".g" file.

*[cmd]#patch-g#* will provide messages when encountering problems in the conversion of FASTGEN geometry. For further debugging information, the -d flag with levels 1-3 of debugging can be provided.

The available options are:

*[opt]#-T tolerance_distance#* ::
The __tolerance_distance__ is specified in inches. Any two vertices within this distance from each other will be considered the same vertex.

*[opt]#-A perp_tolerance#* ::
The __perp_tolerance__ is specified as the cosine of an angle (0.0 through 1.0). If the cosine of the angle between two vectors is less than the specified tolerance, then the vectors are considered perpendicular.

*[opt]#-u number_of_unions#* ::
The __number_of_unions__ is the number of union operations per region, and has a pre-specified default value. 

*[opt]#-x librt_debug_flag#* ::
Specifies a flag for debugging the __librt__ package.

*[opt]#-X NMG_debug_flag#* ::
Specifies a flag for NMG routine debugging.

*[opt]#-p#* ::
Produce polysolid output rather than the default NMG solids.

*[opt]#-6#* ::
Convert plate-mode triangles using ARB6 solids.

*[opt]#-f preprocessed_input_file#* ::
Use the specified file as the input for conversion.

*[opt]#-i labels_file#* ::
Specifies desired group names to override defaults.

*[opt]#-m materials_file#* ::
Specifies material properties to be assigned to components.

*[opt]#-n#* ::
Process volume mode as plate mode.

*[opt]#-t title#* ::
Specifies a title for the output model (default is "patch-g conversion").

*[opt]#-o top_level_name#* ::
Specifies a name for the top level object (default is "all").

*[opt]#-r#* ::
Reverse normals for plate mode triangles.

*[opt]#-c "X Y Z"#* ::
Specifies centroid, in inches, for some plate mode surface normal calculations. Quotation marks are needed to provide for the embedded blanks.

*[opt]#-d debug_level#* ::
Specifies a debug level (1-3).

== EXAMPLE

rpatch < _fastgen_file_ > _file.rpatch_

patch-g -p -f _file.rpatch  file.g_

== DIAGNOSTICS

The diagnostics are intended to be self-explanatory.

== SEE ALSO

xref:man:1/brlcad.adoc[*brlcad*](1), xref:man:1/mged.adoc[*mged*](1)

== AUTHOR

Bill Mermagen, Jr.

== COPYRIGHT

This software is Copyright (c) 1991-2021 by the United States Government as represented by U.S. Army Research Laboratory.

== BUG REPORTS

Reports of bugs or problems should be submitted via electronic mail to mailto:devs@brlcad.org[]