include::../header.adoc[]

= PIX-PNG(1)

== NAME

pix-png - convert a BRL-CAD PIX format image to a PNG (Portable
Network Graphics) format image

== SYNOPSIS

*pix-png* [-a] [-g _gamma_] [-n _file_height_] [-w _file_width_] [-s _squaresize_] [-o _PNG_file_] [_PIX_file_] [> _PNG_file_]

== DESCRIPTION

[cmd]*pix-png* converts a _BRL PIX(5)_ format file to a _PNG_ format
file on the standard output. The PNG file created will be an RGB file
with a bit-depth of 8 and a file gamma of 1.0.

PIX image files do not contain information about their size.  The size
of the input PIX image file must be specified if the dimensions are
not the default 512x512 size.

== OPTIONS

*-a*:: autosize the input file to determine file image height and
width

*-g gamma*:: sets the specified gamma correction value into the
created PNG file. A value of 0.6 is a close approximation of PC
display monitors.  A negative gamma value disables writing a gAMA
chunk out entirely (and is the default).

*-n file_height*:: tells [cmd]*pix-png* that the input is
_file_height_ scanlines tall

*-w file_width*:: tells [cmd]*pix-png* that the input is _file_width_
pixels wide

*-s squaresize*:: sets both the width and the height for the input to
be _squaresize_

*-o PNG_file*:: tells [cmd]*pix-png* to write image data to the
specified _PNG_file_ output file.  The [cmd]*pix-png* command will not
write out binary image data directly to a terminal device as a
safeguard.

== SEE ALSO

xref:man:1/brlcad.adoc[*brlcad*(1)],
xref:man:1/png-pix.adoc[*png-pix*(1)],
xref:man:1/pix-fb.adoc[*pix-fb*(1)], xref:man:5/pix.adoc[*pix*(5)]

== AUTHOR

BRL-CAD Team

include::../footer.adoc[]
