= PIX-SUN(1)
BRL-CAD Team
:doctype: manpage
:man manual: BRL-CAD
:man source: BRL-CAD
:page-layout: base

== NAME

pix-sun - convert a BRL PIX(5) format image to a Sun Rasterfile format

== SYNOPSIS

*[cmd]#pix-sun#* [-d][-s [rep]_squaresize_][-w [rep]_file_width_][-n [rep]_file_height_]<[rep]_BRLpixfile_>[rep]_rasterfile_

== DESCRIPTION

*[cmd]#pix-sun#* converts the __BRL PIX(5)__ format file on the standard input to a __Sun Rasterfile__ format file on the standard output.  The rasterfile produced is a "standard" (as opposed to "byte encoded") image, with 8 bits per pixel, with a palette of 256 colors.

== OPTIONS

*[opt]#-d#* ::
use a dither map

*[opt]#-n file_height#* ::
tells *[cmd]#pix-sun#* that the input is __file_height__ scanlines tall

*[opt]#-s squaresize#* ::
sets both the width and the height for the input to be __squaresize__

*[opt]#-w file_width#* ::
tells *[cmd]#pix-sun#* that the input is __file_width__ pixels wide

== AUTHOR

BRL-CAD Team

== COPYRIGHT

This software is Copyright (c) 1989-2021 by the United States Government as represented by U.S. Army Research Laboratory.

== BUG REPORTS

Reports of bugs or problems should be submitted via electronic mail to mailto:devs@brlcad.org[]