= PIX-PNG(1)
BRL-CAD Team
:doctype: manpage
:man manual: BRL-CAD
:man source: BRL-CAD
:page-layout: base

== NAME

pix-png - convert a BRL-CAD PIX format image to a PNG (Portable Network Graphics) format image

== SYNOPSIS

*[cmd]#pix-png#* [-a][-g [rep]_gamma_][-n [rep]_file_height_][-w [rep]_file_width_][-s [rep]_squaresize_][-o [rep]_PNG_file_][[rep]_PIX_file_][> [rep]_PNG_file_]

== DESCRIPTION

*[cmd]#pix-png#* converts a __BRL PIX(5)__ format file to a __PNG__ format file on the standard output. The PNG file created will be an RGB file with a bit-depth of 8 and a file gamma of 1.0.

PIX image files do not contain information about their size.  The size of the input PIX image file must be specified if the dimensions are not the default 512x512 size.

== OPTIONS

*[opt]#-a#* ::
autosize the input file to determine file image height and width

*[opt]#-g gamma#* ::
sets the specified gamma correction value into the created PNG file. A value of 0.6 is a close approximation of PC display monitors.  A negative gamma value disables writing a gAMA chunk out entirely (and is the default).

*[opt]#-n file_height#* ::
tells *[cmd]#pix-png#* that the input is __file_height__ scanlines tall

*[opt]#-w file_width#* ::
tells *[cmd]#pix-png#* that the input is __file_width__ pixels wide

*[opt]#-s squaresize#* ::
sets both the width and the height for the input to be __squaresize__

*[opt]#-o PNG_file#* ::
tells *[cmd]#pix-png#* to write image data to the specified __PNG_file__ output file.  The *[cmd]#pix-png#* command will not write out binary image data directly to a terminal device as a safeguard.

== SEE ALSO

xref:man:1/brlcad.adoc[*brlcad*](1), xref:man:1/png-pix.adoc[*png-pix*](1), xref:man:1/pix-fb.adoc[*pix-fb*](1), xref:man:5/pix.adoc[*pix*](5)

== AUTHOR

BRL-CAD Team

== COPYRIGHT

This software is Copyright (c) 1998-2021 by the United States Government as represented by U.S. Army Research Laboratory.

== BUG REPORTS

Reports of bugs or problems should be submitted via electronic mail to mailto:devs@brlcad.org[]