= PIX-ALIAS(1)
BRL-CAD Team
:doctype: manpage
:man manual: BRL-CAD
:man source: BRL-CAD
:page-layout: base

== NAME

pix-alias - convert an image from pix format to Alias(tm) pix format

== SYNOPSIS

*[cmd]#pix-alias#* [-s [rep]_squaresize_][-w [rep]_file_width_][-n [rep]_file_height_]<[rep]_BRLpixfile_>[rep]_ALIASpixfile_

== DESCRIPTION

*[cmd]#pix-alias#* converts the (BRL) __pix(5)__ format file on the standard input to an __Alias pix__ format file on the standard output.

== OPTIONS

*[opt]#-n#* [rep]_file_height_ ::
tells *[cmd]#pix-alias#* that the input is __file_height__ scanlines tall

*[opt]#-w#* [rep]_file_width_ ::
tells *[cmd]#pix-alias#* that the input is __file_width__ pixels wide

*[opt]#-s#* [rep]_squaresize_ ::
sets both the width and the height for the input to be __squaresize__

== AUTHOR

BRL-CAD Team

== COPYRIGHT

This software is Copyright (c) 1989-2021 by the United States Government as represented by U.S. Army Research Laboratory.

== BUG REPORTS

Reports of bugs or problems should be submitted via electronic mail to mailto:devs@brlcad.org[]