include::../header.adoc[]

= PIX2ASC/ASC2PIX(1)

== NAME

pix2asc - encode and decode color pixel files

== SYNOPSIS

*pix2asc* < _file.pix_ > _file.asc_

*asc2pix* < _file.asc_ > _file.pix_

== DESCRIPTION

[cmd]*pix2asc* and [cmd]*asc2pix* are simple filters which convert
color _pix(5)_ files from their binary form to a portable ASCII
form, and back. [cmd]*pix2asc* reads the binary file on standard in
and writes ASCII on standard out. [cmd]*asc2pix* does the reverse.

The binary file consists of a sequence of three-tuples of _unsigned
chars_ representing the red, green, and blue intensities for each
pixel. The ASCII version of the file has one RGB pixel per
newline-terminated line, with each pixel represented as six
hexadecimal digits.

When moving _pix(5)_ files between UNIX systems via tape (see _tar(1)_
and _cpio(1)_) or via network (see _rcp(1)_ and _ftp(1)_), this
conversion to ASCII is unnecessary, as all UNIX files are byte
streams, regardless of the underlying hardware. However, when
transporting images to non-UNIX machines, these tools are
invaluable. Note that xref:man:1/rt.adoc[*rt*(1)] can directly
generate the ASCII form of an image file using the [opt]*-O* flag,
allowing it to be easily used on non-UNIX systems.

== SEE ALSO

xref:man:1/brlcad.adoc[*brlcad*(1)], xref:man:5/pix.adoc[*pix*(5)],
xref:man:5/bw.adoc[*bw*(5)]

== AUTHOR

_BRL-CAD Team_

include::../footer.adoc[]
