= PIXBLEND(1)
ifndef::site-gen-antora[:doctype: manpage]
:man manual: BRL-CAD
:man source: BRL-CAD
:page-role: manpage

== NAME

pixblend - blend two pix(5) or bw(5) images

== SYNOPSIS

*pixblend* [-[_r_ | _i_] _value_] [-s _seedval_] [-S] [-g _gvalue_] _file1.pix_ _file2.pix_ > _out.pix_

== DESCRIPTION

[cmd]*pixblend*, given two streams of data, typically
xref:man:5/pix.adoc[*pix*(5)] or xref:man:5/bw.adoc[*bw*(5)] images,
generates a "blended" output stream of the same size. This routine
operates on a pixel-by-pixel basis, and thus is independent of the
resolution of the image. The type of blending performed is determined
by the following options:

== OPTIONS

*-r* _VALUE_:: This specifies random blending; for each pixel of the
output stream, a number will be chosen uniformly from the interval [0,
1]. If this number exceeds VALUE, then the pixel from the first image
will be output; otherwise, the pixel from the second image will be
output.  Note that if VALUE is 0, then the output will equal the first
image; if VALUE is 1, then the output will equal the second image.

*-i* _VALUE_:: This specifies linear interpolation; for each pixel of
the output stream, the interpolated pixel ((1.0 - VALUE) * pixel1 +
VALUE * pixel2) will be output (where pixel1 and pixel2 are the
corresponding pixels from file1 and file2, respectively).  Note that
if VALUE is 0, then the output will equal the first image; if VALUE is
1, then the output will equal the second image.

*-s* _SEEDVAL_:: Sets the random number seed to SEEDVAL (default is
0).

*-S*:: Instructs [cmd]*pixblend* to use bits from the clock as a
random number seed.

*-g* _GVALUE_:: Tells [cmd]*pixblend* to "glitterize" the image; if
the random draw for a pixel is below GVALUE, then the pixel output is
white; otherwise, the pixel used is determined by the ratio set with
the [opt]*-r* option (see above).

== EXAMPLES

....
pixblend -i .25 source.pix destination.pix > out.pix

pixblend -r .75 source.pix destination.pix > out.pix

pixblend -r .5 -s source.pix destination.pix > out.pix

pixblend -r .5 -s 23 source.pix destination.pix > out.pix
....

== SEE ALSO

xref:man:1/brlcad.adoc[*brlcad*(1)],
xref:man:1/gencolor.adoc[*gencolor*(1)],
xref:man:5/pix.adoc[*pix*(5)], xref:man:5/bw.adoc[*bw*(5)]

== AUTHOR

BRL-CAD Team

== COPYRIGHT

This software is Copyright (c) 1995-2021 by the United States
Government as represented by U.S. Army Research Laboratory.

== BUG REPORTS

Reports of bugs or problems should be submitted via electronic mail to
mailto:devs@brlcad.org[]
