include::../header.adoc[]

= PIXHALVE(1)

== NAME

pixhalve - halve a color pix file

== SYNOPSIS

*pixhalve* [-a] [-s _squareinsize_] [-w _in_width_] [-n _in_height_] [<] [_infile.pix_] > _outfile.pix_

== DESCRIPTION

[cmd]*pixhalve* will take a color xref:man:5/pix.adoc[*pix*(5)] format
file of given dimensions and reduce the resolution of the file by one
half in each direction using a 5x5 pyramid filter.  If a file name is
not given, standard input will be used. The [opt]*-w* and [opt]*-n*
flags specify the input file width and number of scan lines in pixels;
they can be set to the same value via [opt]*-s*. Defaults of 512 are
assumed for unspecified dimensions.

The [opt]*-a* flag indicates autosizing (off by default).

== SEE ALSO

xref:man:1/brlcad.adoc[*brlcad*(1)],
xref:man:1/pixcrop.adoc[*pixcrop*(1)],
xref:man:1/pixrect.adoc[*pixrect*(1)],
xref:man:1/pixinterp2x.adoc[*pixinterp2x*(1)],
xref:man:1/pixscale.adoc[*pixscale*(1)], xref:man:5/pix.adoc[*pix*(5)]

== AUTHOR

BRL-CAD Team

include::../footer.adoc[]
