include::../header.adoc[]

= PIXSHRINK(1)

== NAME

pixshrink - shrink a color pix file

== SYNOPSIS

*pixshrink* [-s _squareinsize_] [-w _in_width_] [-n _in_height_] [-f _shrink_factor_] [-u] [_infile.pix_] > _outfile.pix_

== DESCRIPTION

*pixshrink* will take a color xref:man:5/pix.adoc[*pix*(5)] format
file of given dimensions and produce a smaller scaled version. The
[opt]*-w* and [opt]*-n* flags specify the input file width and number
of scan lines in pixels. They can both be set to the same value via
[opt]*-s.* Defaults of 512 are assumed for unspecified dimensions. The
integer scaling factor ([rep]_shrink_factor_) is set with the
[opt]*-f* flag.  By default, the factor is 2.  Thus, pixshrink forms
the logical opposite of the _pixinterp2x (1)_ program.

The program reads the entire image into memory, and then scales the
image down to 1/[rep]_shrink_factor_ the original size in both
dimensions.

By default, pixshrink uses boxcar averaging to produce the output
pixels from the input.  The [opt]*-u* option causes pixshrink to use
image undersampling instead.

== SEE ALSO

xref:man:1/brlcad.adoc[*brlcad*(1)],
xref:man:1/pixcrop.adoc[*pixcrop*(1)],
xref:man:1/pixrect.adoc[*pixrect*(1)],
xref:man:1/pixinterp2x.adoc[*pixinterp2x*(1)],
xref:man:1/pixscale.adoc[*pixscale*(1)], xref:man:5/pix.adoc[*pix*(5)]

== BUGS

If the dimensions of the input image are not evenly divisible by the
shrink factor, incorrect and bizarre output is generated.

== AUTHOR

BRL-CAD Team

include::../footer.adoc[]
