= PIXTILE(1)
ifndef::site-gen-antora[:doctype: manpage]
:man manual: BRL-CAD
:man source: BRL-CAD
:page-role: manpage

== NAME

pixtile - paste small images together into one large image

== SYNOPSIS

*pixtile* [-s _squareinsize_] [-w _file_width_] [-n _file_height_] [-S _squareoutsize_] [-W _out_width_] [-N _out_height_] [-o _startframe_] _basename_ > _file.pix_

*pixtile* [-s _squareinsize_] [-w _file_width_] [-n _file_height_] [-S _squareoutsize_] [-W _out_width_] [-N _out_height_] _file1_ _file2_ ... _fileN_ > _file.pix_

== DESCRIPTION

[cmd]*pixtile* takes a collection of numbered small images and places
them side by side in one larger image.  The input and output files are
assumed to be in xref:man:5/pix.adoc[*pix*(5)] format. By default, the
output file will be made 512x512 pixels in size.

The input files have a default width of 64 pixels per scanline and are
usually square, i.e. have the same height as width. Specifying the
[opt]*-s* flag changes the default size to _squareinsize_ pixels per
scanline and _squareinsize_ scanlines as given in the argument
list. The [opt]*-w* flag can be used to specify the input file width
in pixels and the [opt]*-n* flag can be used to specify the input file
height in scanlines.

If the [opt]*-S* flag is supplied, the output size is changed from the
default value of 512 to _squareoutsize_ pixels per scanline and
_squareoutsize_ scanlines. The [opt]*-W* flag sets the output width
size to _out_width_ pixels per scanline. Similarly, the [opt]*-N* flag
sets the output height size to _out_height_ scanlines.

*-s* _squareinsize_:: Specify both the number of pixels per scanline
and the number of scanlines in the input files.  The default is 64.

*-w* _file_width_:: Specify the width (in pixels) per scanline of the
input file. The default is 64.

*-n* _file_height_:: Specify the number of scanlines to be read from
the input file. The default is 64.

*-S* _squareoutsize_:: Specify both the number of pixels per scanline
(width) and the number of scanlines (height) for the output file.  The
default is 512.

*-W* _out_width_:: Specify the width (in pixels) per scanline of the
output file. The default is 512.

*-N* _out_height_:: Specify the number of scanlines to be sent to the
output file. The default is 512.

*-o* _startframe_:: Specify the starting frame number, where
_startframe_ is substituted for _num_ in _basename.num_.

The files being pasted together should have names of the form
_basename.num_, where _basename_ is given on the command line, and
_num_ is a consecutive series of integers.  By default the first image
is assumed to be number " 0 ", but an alternate _startframe_ can be
given by using the [opt]*-o* flag and supplying _startframe_. The
program keeps reading these small files until either the next frame
does not exist, or the output file is full. They are placed in the
output file from lower left to upper right. The progress of the
composition is displayed on standard error.

If the basename is given as "-" (a minus sign), preceded by a "--"
(two minus signs) to terminate
xref:man:3/bu_getopt.adoc[*bu_getopt*(3)] processing, then the stream
of images is read from stdin rather than a file, such as might be
generated by a program like
xref:man:1/pcd-pix.adoc[*pcd-pix*(1)]. Such a stream could also be
processed into files by xref:man:1/pixbustup.adoc[*pixbustup*(1)].

Alternatively, if more than one _basename_ (filename) argument is
supplied on the command line, the names of the files being pasted
together are assumed to be explicitly stated and the [opt]*-o* flag is
not valid.  This allows files with different names to be used without
having to change those names.

This program is the companion of xref:man:1/fbanim.adoc[*fbanim*(1)],
which will step through these small images on a framebuffer capable of
zooming and windowing.  Thus many small low resolution frames can be
used as an animation "preview" for a higher resolution sequence, the
latter of which would go onto video tape or film.

[[_example]]
== EXAMPLES

  pixtile -S 1024 -s 128 -o 2 anim > out.pix

will read files _anim.2_ through _anim.65_, placing them from lower
left to upper right in a 1024x1024 pixel file _out.pix_.

  pixtile -s 256 lowerleft lowerright upperleft upperright > out.pix

will read files _lowerleft_, _lowerright_, _upperleft_, and
_upperright_, placing them from lower left to upper right in a 512x512
file _out.pix_.

== SEE ALSO

xref:man:1/brlcad.adoc[*brlcad*(1)],
xref:man:1/fbanim.adoc[*fbanim*(1)], xref:man:5/pix.adoc[*pix*(5)]

== AUTHOR

BRL-CAD Team

== COPYRIGHT

This software is Copyright (c) 1989-2021 by the United States
Government as represented by U.S. Army Research Laboratory.

== BUG REPORTS

Reports of bugs or problems should be submitted via electronic mail to
mailto:devs@brlcad.org[]
