= PIXUNTILE(1)
BRL-CAD Team
:doctype: manpage
:man manual: BRL-CAD
:man source: BRL-CAD
:page-layout: base

== NAME

pixuntile - break image up into separate files

== SYNOPSIS

*[cmd]#pixuntile#* [-s [rep]_squareinsize_][-w [rep]_in_width_][-n [rep]_in_height_][-S [rep]_squareoutsize_][-W [rep]_out_width_][-N [rep]_out_height_][-o [rep]_startframe_][rep]_basename_<[rep]_file.pix_
*[cmd]#pixuntile#* [-s [rep]_squareinsize_][-w [rep]_in_width_][-n [rep]_in_height_][-S [rep]_squareoutsize_][-W [rep]_out_width_][-N [rep]_out_height_][rep]_file1_[rep]_file2_...[rep]_fileN_<[rep]_file.pix_

== DESCRIPTION

*[cmd]#pixuntile#* performs the inverse operation of xref:man:1/pixtile.adoc[*pixtile*](1). It takes a large image composed of a collection of small images and places each of them in a separate file. The input and output files are assumed to be in xref:man:5/pix.adoc[*pix*](5) format. By default, the input file is assumed to be 512x512 pixels in size.

The output files have a default width of 64 pixels and are usually square, i.e. have the same height as width. Specifying the *[opt]#-S#* flag changes the default size to __squareoutsize__ pixels in width and height. (The *[opt]#-W#*  and *[opt]#-N#*  flags are used for width and height, respectively.  For the input file, these functions are available through the *[opt]#-s#* , *[opt]#-w#* , and *[opt]#-n#*  flags.) 

The files being produced as output will have names of the form __basename.num__, where __basename__ is given on the command line, and __num__ is a consecutive series of integers.  By default the first image is assumed to be number " 0 ", but an alternate __startframe__ can be given by using the *[opt]#-o#* [rep]_startframe_ flag and specifying the starting output frame number, where __startframe__ is substituted for __num__ in __basename.num__.

Alternatively, if more than one __basename__ (filename) argument is supplied on the command line, the names of the files are used as the output file names.

== EXAMPLE

[ui]`pixuntile -s 1024 -S 128 out < in.pix` will read the 1024x1024 file __in.pix__ and place the 128x128 chunks of that file from lower left to upper right in the files __out.0__ through __out.63__.

== SEE ALSO

xref:man:1/pixtile.adoc[*pixtile*](1), xref:man:1/brlcad.adoc[*brlcad*](1), xref:man:5/pix.adoc[*pix*](5)

== AUTHOR

BRL-CAD Team

== COPYRIGHT

This software is Copyright (c) 1988-2021 by the United States Government as represented by U.S. Army Research Laboratory.

== BUG REPORTS

Reports of bugs or problems should be submitted via electronic mail to mailto:devs@brlcad.org[]