= PLOT3-ASC(1)
BRL-CAD Team
:doctype: manpage
:man manual: BRL-CAD
:man source: BRL-CAD
:page-layout: base

== NAME

plot3-asc - convert a Plot3 stream to ASCII

== SYNOPSIS

*[cmd]#plot3-asc#* [-v][[rep]_unix_plot_]

== DESCRIPTION

Reads a stream in xref:man:5/plot3.adoc[*plot3*](5) format and converts it to an ASCII representation. Standard input is read if a file name is not supplied. If the *[opt]#-v#* option is given, the single-character command names are replaced with mnemonic strings and a summary of plot command usage is written to standard error.

== SEE ALSO

xref:man:1/asc-plot3.adoc[*asc-plot3*](1), xref:man:1/plot3-plot3.adoc[*plot3-plot3*](1), xref:man:1/plot3rot.adoc[*plot3rot*](1), xref:man:1/plot3-fb.adoc[*plot3-fb*](1), xref:man:3/libplot3.adoc[*libplot3*](3), xref:man:5/plot3.adoc[*plot3*](5)

== AUTHOR

BRL-CAD Team

== COPYRIGHT

This software is Copyright (c) 1991-2021 by the United States Government as represented by U.S. Army Research Laboratory.

== BUG REPORTS

Reports of bugs or problems should be submitted via electronic mail to mailto:devs@brlcad.org[]