= PLOT3COLOR(1)
BRL-CAD Team
:doctype: manpage
:man manual: BRL-CAD
:man source: BRL-CAD
:page-layout: base

== NAME

plot3color - output a UnixPlot color command

== SYNOPSIS

*plot3color*_r__g__b_[<]_unix_plot_>_unix_plot_

== DESCRIPTION

[cmd]*plot3color* outputs a UnixPlot command to set the current drawing color to the given __r g__ and __b__ values.  These values should be numbers from 0 to 255 and represent black to full up Red, Green, and Blue values respectively.

To allow this command to be used in pipelines, an optional input file can be given.  All of the input will be passed through until end of file, and then the color command will be appended to the end.

This command exists mostly as an aid for making graphs and things from shell commands.

== SEE ALSO

xref:man:1/plot3line2.adoc[*plot3line2*(1)], xref:man:1/plot3-plot3.adoc[*plot3-plot3*(1)], xref:man:5/plot3.adoc[*plot3*(5)]

== AUTHOR

BRL-CAD Team

== COPYRIGHT

This software is Copyright (c) 1988-2021 by the United States Government as represented by U.S. Army Research Laboratory.

== BUG REPORTS

Reports of bugs or problems should be submitted via electronic mail to mailto:devs@brlcad.org[]