include::../header.adoc[]

= PLOT3-PLOT3(1)

== NAME

plot3-plot3 - convert an extended to a simple UnixPlot file

== SYNOPSIS

*plot3-plot3* [-v] [-S] < _unix_plot_ > _unix_plot_

== DESCRIPTION

UnixPlot is a simple machine and device independent plotting file
format found on both System V and BSD Unix systems.  BRL has extended
that format to include color, three dimensional plotting, machine
independent floating point coordinates, and a flush command for
interactive output.

[cmd]*plot3-plot3* converts an extended UnixPlot file to the simpler
format for use by older, and non-extended, programs.  It drops color
and flush commands, strips the Z coordinate of 3D commands, and
converts floating point coordinates to integer.  By default,
conversion to integer is done by simple truncation.  If the [opt]*-S*
option is given, the "space" command in the plot file is used to
center and scale the plot to the full 16 bit signed integer plotting
space (-32767 to +32767).  This is particularly useful for converting
floating point files.  The [opt]*-v* verbose option causes each plot
command to be described as it is being converted.

== DIAGNOSTICS

A warning message is given if the input plot file did not contain a
space command since most older UnixPlot programs require them.

== SEE ALSO

-*plot*(1)-,
xref:man:1/plot3rot.adoc[*plot3rot*(1)],
xref:man:1/plot3-fb.adoc[*plot3-fb*(1)],
-*plot3debug*(1)-,
xref:man:3/libplot3.adoc[*libplot3*(3)],
xref:man:5/plot3.adoc[*plot3*(5)]

== AUTHOR

BRL-CAD Team

include::../footer.adoc[]
