= PNG-BW(1)
ifndef::site-gen-antora[:doctype: manpage]
:man manual: BRL-CAD
:man source: BRL-CAD
:page-role: manpage

== NAME

png-bw - convert a Portable Networks Graphics (PNG) format file to a
BW format

== SYNOPSIS

*png-bw* [-ntsc] [-crt] [-R [_num_]] [-G [_num_]] [-B [_num_]] [_in.png_] > _out.bw_

== DESCRIPTION

[cmd]*png-bw* will convert a _PNG_ format file from its standard input
and produce a black and white xref:man:5/bw.adoc[*bw*(5)] file on its
standard output, If the PNG file contains a B/W image the conversion
is direct, however, if the PNG file contains a color image, then by
default all three colors are weighted equally.  The [opt]*-ntsc* uses
weighting based on the NTSC primaries and the D6500 alignment white.
The [opt]*-crt* flag applies weights for "typical" CRT phosphor
chromaticities and the D6500 white.

Individual color plane(s) can be selected via the [opt]*-R -G* and
[opt]*-B* flags. If one or more of these flags is followed by a value,
the value will be treated as a weight to be applied to that color This
value is implicitly 1.0 divided by the number of colors selected for
the flags which are not followed by a value.

== EXAMPLES

  png-bw -R -B < file.png > file.bw

will equally blend the red and blue color planes.

  png-bw bw_file.png < file.bw

will convert a b/w PNG file to _bw(5)_ format.

  png-bw -R0.30 -G0.59 -B0.11 < file.png > file.bw

has the same effect as the [opt]*-ntsc* flag. 

\[The [opt]*-crt* weights are: 0.26, 0.66, 0.08]

== SEE ALSO

xref:man:1/brlcad.adoc[*brlcad*(1)],
xref:man:1/png-pix.adoc[*png-pix*(1)],
xref:man:1/bw-png.adoc[*bw-png*(1)],
xref:man:1/pix-png.adoc[*pix-png*(1)], xref:man:5/pix.adoc[*pix*(5)],
xref:man:5/bw.adoc[*bw*(5)]

== AUTHOR

John R. Anderson

== COPYRIGHT

This software is Copyright (c) 1998-2021 by the United States
Government as represented by U.S. Army Research Laboratory.

== BUG REPORTS

Reports of bugs or problems should be submitted via electronic mail to
mailto:devs@brlcad.org[]
