= RPATCH(1)
BRL-CAD Team
:doctype: manpage
:man manual: BRL-CAD
:man source: BRL-CAD
:page-layout: base

== NAME

rpatch - convert FASTGEN ASCII databases into a format suitable for

== SYNOPSIS

*[cmd]#rpatch#* [-D][-3]<[rep]_FASTGEN_FILE_>[rep]_OUTPUT_FILE_

== DESCRIPTION

This program reformats FASTGEN files to a form usable by *[cmd]#patch-g#*  . The *[opt]#-D#* option handles type 3 components as donuts rather than triangles. The *[opt]#-3#* option reads FASTGEN3 format files (coordinates are each 10 columns wide).

== EXAMPLE

rpatch < _fastgen_file_ > _file.rpatch_

== DIAGNOSTICS

The diagnostics are intended to be self-explanatory.

== SEE ALSO

xref:man:1/brlcad.adoc[*brlcad*](1), xref:man:1/mged.adoc[*mged*](1), xref:man:1/patch-g.adoc[*patch-g*](1)

== AUTHOR

John R. Anderson

== COPYRIGHT

This software is Copyright (c) 1994-2021 by the United States Government as represented by U.S. Army Research Laboratory.

== BUG REPORTS

Reports of bugs or problems should be submitted via electronic mail to mailto:devs@brlcad.org[]