include::../header.adoc[]

= RTCHECK(1)

== NAME

rtcheck - Make UNIX-Plot of overlaps in an mged model, using
raytracing

== SYNOPSIS

*rtcheck* [_options_]... _model.g_ _objects_... > _overlaps.plot3_

== DESCRIPTION

[cmd]*rtcheck* operates on the indicated _objects_ in the input
_model.g_ and produces a floating point 3-D BRL-style
xref:man:5/plot3.adoc[*plot3*(5)] format file on standard output, in
millimeters.

The orientation of the rays to be fired may be specified by the
[opt]*-a* and [opt]*-e* options, in which case the model will be
autosized, and the grid will be centered on the centroid of the model,
with ray spacing chosen to span the entire set of _objects._
Alternatively, with the [opt]*-M* option, a transformation matrix may
be provided on standard input which maps model-space to view-space. In
this case, the grid ranges from -1.0 < = X,Y < = +1.0 in view space,
with the size of the grid (number of rays fired) specified with the
[opt]*-s* option. The [opt]*-M* option is most useful when
[cmd]*rtcheck* is being automatically invoked from within
xref:man:1/mged.adoc[*mged*(1)] using the [cmd]*rtcheck* command in
_mged_.

The following options are recognized. 

*-g#*:: The grid cell width, in millimeters.  Ordinarily, the cell
width is computed by dividing the view size by the number of pixels of
width. This option provides an alternate direct means to set the grid
cell width.

*-s#*:: Number of rays to fire in X and Y directions (square
grid). Default is 512 (512 x 512).

*-r*:: Report unique overlaps. At the end of a view, a list of unique
pairs of overlapping regions is printed, along with a count of the
number of detected overlaps for each pair. Not all detected overlap
combinations are necessarily listed, as the overlap partition may mask
a second overlap that is a continuation of an already detected
overlap.

*-a#*:: Select azimuth in degrees.  Used with [opt]*-e* and conflicts
with [opt]*-M*

*-e#*:: Select elevation in degrees.  Used with [opt]*-a* and
conflicts with [opt]*-M*

*-G*:: Sets the grid cell height, in millimeters.

*-M*:: Read model2view matrix from standard input. Conflicts with
[opt]*-a* and [opt]*-e*

*-P#*:: Specify the maximum number of processors (in a multi-processor
system) to be used for this execution.  The default is 1.

*-+ t*:: Specify that rtcheck should output plot file data in text
format. Default is binary plot data.

[cmd]*rtcheck* also accepts all other options that the
xref:man:1/rt.adoc[*rt*(1)] program implements, such as for non-square
views, perspective, etc.

The [cmd]*rtcheck* program is a simple front-end to
xref:man:3/librt.adoc[*librt*(3)] which is most useful when used from
xref:man:1/mged.adoc[*mged*(1)]. The output can be independently
viewed using the UNIX-plot viewers like
xref:man:1/plot3-fb.adoc[*plot3-fb*(1)],
xref:man:1/tplot.adoc[*tplot*(1)], etc.

== SEE ALSO

xref:man:1/mged.adoc[*mged*(1)], xref:man:1/rt.adoc[*rt*(1)],
xref:man:1/rtray.adoc[*rtray*(1)], xref:man:1/rtpp.adoc[*rtpp*(1)],
xref:man:1/plot3-fb.adoc[*plot3-fb*(1)],
xref:man:1/tplot.adoc[*tplot*(1)],
xref:man:3/libplot3.adoc[*libplot3*(3)],
xref:man:3/librt.adoc[*librt*(3)], xref:man:5/plot3.adoc[*plot3*(5)]

== DIAGNOSTICS

Numerous error conditions are possible. Descriptive messages are
printed on stderr (file descriptor 2).

[[_author]]
== AUTHORS

_BRL-CAD Team_

== BUGS

Most deficiencies observed while using the [cmd]*rtcheck* program are
a consequence of problems in xref:man:3/librt..adoc[*librt.*(3)

include::../footer.adoc[]
