= RTSHOT(1)
BRL-CAD Team
:doctype: manpage
:man manual: BRL-CAD
:man source: BRL-CAD
:page-layout: base

== NAME

rtshot - fire one ray at an mged model, for debugging

== SYNOPSIS

*[cmd]#rtshot#* [[rep]_options_]...[rep]_model.g_[rep]_objects_...

== DESCRIPTION

*[cmd]#rtshot#* fires a single ray at the indicated __objects__ in the input __model.g__ and produces a printed summary of the geometry that the ray passes through. The orientation of the ray to be fired is specified by giving any two of the three options *[opt]#-a#* *[opt]#-d#* and *[opt]#-p.#* 

The::
*[opt]#-d#* option is followed by three numbers specifying the direction vector.

The::
*[opt]#-p#* option is followed by three numbers specifying the start point.

The::
*[opt]#-a#* option is followed by three numbers specifying a point to be fired "at".

*[opt]#-t ##* ::
specifies the number of triangles per piece for facetted primitives (currently only the BOT). The default value is 4.

*[opt]#-b ##* ::
specifies the threshold for breaking facetted primitives into pieces. The default is 32.

*[opt]#-x ##* ::
Set debug flags to (hexadecimal) number.

*[opt]#-U ##* ::
Set use_air flag.

*[opt]#-v attribute_name1 [attribute_name2 ...]#* ::
This option specifies a list of attribute names to be listed (along with the appropriate values) for each region hit.

*[opt]#-O # or keyword#* ::
This option indicates how overlaps should be handled. The __resolve__ or `0` argument is the default (normal BRL-CAD mode, all overlaps are resolved and no overlaps appear in the output). The __rebuild_fastgen__ or `1` argument mimics FASTGEN4 raytracing (plate-mode overlaps appear in the output). The __rebuild_all__ or `2` argument rebuilds all overlaps that occurred along the ray (all overlaps appear in the output). The __retain__ or `3` argument does not resolve any overlaps (each unique combination of intersection extent and list of claiming regions produces a single partition).

*[opt]#-n ##* ::
This option specifies the number of rings to use in a ray bundle (does not include the central ray).

*[opt]#-c ##* ::
This option specifies the number of rays in each ring. The rays in each ring are not aligned with the rays in the previous ring, they make an outward spiral pattern. A central ray is included.

*[opt]#-R ##* ::
This option specifies the radius of the ray bundle. Each ring is evenly spaced with the outermost ring at this radius.

The *[cmd]#rtshot#* program is a simple front-end to xref:man:3/librt.adoc[*librt*](3) which can be invoked directly by the user. If a ray bundle is desired, all of the *[opt]#-n#* , *[opt]#-c#* , and *[opt]#-R#* options must be specified. The output from a ray bundle is handled as a single ray. Any overlaps between rays in the bundle are resolved by favoring rays closer to the central ray. The default is to fire a single ray.

== SEE ALSO

xref:man:1/mged.adoc[*mged*](1), xref:man:1/rt.adoc[*rt*](1), xref:man:1/pix-fb.adoc[*pix-fb*](1), xref:man:1/rtray.adoc[*rtray*](1), xref:man:1/rtpp.adoc[*rtpp*](1), xref:man:3/librt.adoc[*librt*](3), xref:man:5V/ray.adoc[*ray*](5V), xref:man:5/pix.adoc[*pix*](5)

== DIAGNOSTICS

Numerous error conditions are possible. Descriptive messages are printed on standard error.

== BUGS

Most deficiencies observed while using the *[cmd]#rtshot#* program are usually with the xref:man:3/librt.adoc[*librt*](3) package instead.

== AUTHOR

BRL-CAD Team

== COPYRIGHT

This software is Copyright (c) 1987-2021 United States Government as represented by the U.S. Army Research Laboratory.

== BUG REPORTS

Reports of bugs or problems should be submitted via electronic mail to mailto:devs@brlcad.org[]