include::../header.adoc[]

= SHOWSHOT(1)

== NAME

showshot - generate MGED commands to represent a ray through some
geometry

== SYNOPSIS

*showshot* [-n _name_] [-r _radius_]

== DESCRIPTION

[cmd]*showshot* reads the specification for a ray through some
geometry and generates xref:man:1/mged.adoc[*mged*(1)] commands to
produce a database object representing the ray. The input should
consist of lines of the form

....
object  x_in  y_in  z_in  x_out  y_out  z_out
....

as might be obtained from xref:man:1/nirt.adoc[*nirt*(1)], where
_object_ is the name of a database object along the ray, and (_x_in_,
_y_in_, _z_in_) and (_x_out_, _y_out_, _z_out_) are the points at
which the ray enters and exits _object_, respectively. The first and
last lines of input are assumed to correspond to the first and last
objects encountered along the ray. Otherwise, the lines of input may
be in any order.

The first xref:man:1/mged.adoc[*mged*(1)] command generated by
[cmd]*showshot* produces an RCC to represent the ray itself. This
cylinder has its vertex at the entry point for the first object along
the ray and extends to the exit point for the last object-all the
other coordinates in the input are ignored. _Showshot_ then generates
commands to make the solid a member of a region, which is assigned the
color 255 255 0 (yellow). Finally, [cmd]*showshot* generates commands
to create a group that contains the ray region and each of the objects
specified in the input.

=== Options

The command-line options and their meanings are given below.

*-n* _name_:: Specifies that the string _name_ be used as the root for
the names of the new database objects. The ray solid and ray region
will be called __name__.s and __name__.r, respectively, and the group
will be called _name_. Default is ray._PID_, where _PID_ is the
process ID of the [cmd]*showshot* process.

*-r* _radius_:: Specifies that the RCC representing the ray should
have a radius of _radius_ units. Default is 1.

== DIAGNOSTICS

If the input stream does not conform to the expected format, then
[cmd]*showshot* complains and exits with status 1.

== SEE ALSO

xref:man:1/mged.adoc[*mged*(1)], xref:man:1/nirt.adoc[*nirt*(1)]

== AUTHOR

Paul Tanenbaum

include::../footer.adoc[]
