include::../header.adoc[]

= SUN-PIX(1)

== NAME

sun-pix - convert Sun bitmaps from screendump(1) into pix(5) or bw(5)
raster image

== SYNOPSIS

*sun-pix* [-b] [-H] [-i] [-P] [-v] [-C] [_sun.bitmap_]

== DESCRIPTION

[cmd]*sun-pix* is a program to take Sun bitmap files created with
Sun's -*screendump*(1)- command, and convert
them to a xref:man:5/pix.adoc[*pix*(5)] format file.  If the [opt]*-b*
flag is specified, a xref:man:5/bw.adoc[*bw*(5)] format file is
created instead.  Note that [cmd]*sun-pix* will refuse to write to a
terminal; its output must be redirected unless it's invoked with the
[opt]*-H* flag.  The dimensions of the input file are the dimensions
of the output file, and use of the [opt]*-H* flag will cause the image
size to be printed without further processing of the input, or
generation of any other output; the image size is output as a pair of
command line options (_i.e._, _-w1152 -n900_) suitable for use with
other xref:man:1/brlcad.adoc[*brlcad*(1)] tools such as
xref:man:1/pix-fb.adoc[*pix-fb*(1)]. When the [opt]*-v* flag is
specified, all the fields of the header are printed on stderr, to aid
debugging.  Note that the "encoded" format is not supported.

Specifying the [opt]*-i* flag will invert the sense of a one-bit wide
input image, _i.e._, exchanging black for white.  The default Sun
image is black print on white background; the [opt]*-i* flag will give
a white image on black background, which is often better for purposes
of creating overlays to be composited with
xref:man:1/pixmerge.adoc[*pixmerge*(1)] on top of color images.

The [opt]*-P* flag indicates that the input is a pure bitmap with no
Sun-style header on it.  The first bit to be processed will be the
most significant bit (MSB), _i.e._, the left-most bit in the byte.

The [opt]*-C* flag indicates that the color map is to be output.

Note that the input file is expected to be in Sun ("network") byte
order (_i.e._, "big-endian", with byte 0 on the left), regardless of
the byte order of the machine running this program.

== BUGS

24-bit images are not supported yet.

== SEE ALSO

xref:man:1/brlcad.adoc[*brlcad*(1)],
xref:man:1/pix-fb.adoc[*pix-fb*(1)],
xref:man:1/pixmerge.adoc[*pixmerge*(1)],
xref:man:5/pix.adoc[*pix*(5)], xref:man:5/bw.adoc[*bw*(5)]

== AUTHOR

BRL-CAD Team

include::../footer.adoc[]
