include::../header.adoc[]

= UG-G(1)

== NAME

ug-g - Unigraphics Translator (Unigraphics to BRL-CAD)

== SYNOPSIS

*ug-g* [-d _level_] [-i _starting_ident_number_] [-n _part_no_to_part_name_mapping_file_] [-t _surface_tolerance_] [-a _surface_normal_tolerance_] [-R _use_refset_name_] [-c _min_chamfer_] [-r _min_round_] [-f] [-s] [-u] -o _database.g_ _part_filename_ [_subpart1_ _subpart2_...]

== DESCRIPTION

[cmd]*ug-g* converts the specified _part_filename_ model to a BRL-CAD
_database.g_ file. The _part_filename_ is expected to be a Unigraphics
part file. The [opt]*-d* specifies a debug _level_. Currently this is
either on or off for levels 0 or 1. The [opt]*-i* option specifies a
starting ident number for the conversion. Each part converted will be
assigned an ident number, starting with the one specified. The
[opt]*-n* option provides a part number to name mapping file. This can
be provided if the Unigraphics model uses part numbers instead of part
names. If provided, the mapping file will be consulted for part names
during the conversion, and the BRL-CAD model will use the names rather
than the part numbers. The [opt]*-t* option specifies the surface
error tolerance for tesellation (in mm). The [opt]*-a* option
specifies an surface normal tolerance for tesellation (in
degrees). The [opt]*-R* option specifies a Unigraphics reference set
name. If supplied, only the specified reference set will be
converted. The [opt]*-c* option specifies a minimum chamfer
dimension. Any chamfers with dimensions of this minimum or less will
be ignored. The [opt]*-r* option specifies a minimum round radius. Any
rounds or blends with radii of curvature of this minimum or less will
be ignored. The [opt]*-f* option requests that no CSG conversion be
attempted, so that all BRL-CAD geometry will be Bot primitives. The
[opt]*-s* option requests that all features get listed rather than
only those successfully converted to CSG. This option has no effect if
the [opt]*-f* option is specified. The [opt]*-u* option requests
surface normals to be extracted from the Unigraphics model and
assigned to Bot primitives. The [opt]*-o* option specifies a BRL-CAD
output file for the conversion. If a list of optional _subparts_ is
specified on the command line, only those subparts of the Unigraphics
_part_filename_ are converted.

Note that this converter requires the Unigraphics _ugopen_
module. This may be obtained from Unigraphics.

== EXAMPLE

....
$ ug-g -o sample.g sample.prt
....

== AUTHOR

BRL-CAD Team

include::../footer.adoc[]
