= PLOT3(5)
BRL-CAD Team
ifndef::site-gen-antora[:doctype: manpage]
:man manual: BRL-CAD
:man source: BRL-CAD
:page-layout: base

== NAME

plot3 - 3-D and color graphic plotting interface


== DESCRIPTION

Files of this format are produced by programs such as
xref:man:1/pixhist3d-plot3.adoc[*pixhist3d-plot3*(1)], using the
routines described in xref:man:3/libplot3.adoc[*libplot3*(3)] and are
interpreted for various devices by standard programs described in
xref:man:1G/plot.adoc[*plot*(1G)], as well as additional programs such
as xref:man:1/plot3-fb.adoc[*plot3-fb*(1)]. The format of output from
_libplot3_ differs from that of _libplot_ only in the addition of 3-D
primitives and color. A graphics file is a stream of plotting
instructions. Each instruction consists of an ASCII letter usually
followed by bytes of binary information. The instructions are executed
in order. A point is designated by four bytes representing the _x_ and
_y_ values; each value is a signed 16-bit integer. These integers are
written with the most significant byte first. Three-dimensional data
have an additional _z_ value, which is assumed to be zero for
two-dimensional instructions. The last designated point in an _l_,
_m_, _n_, _p_, _L_, _M_, _N_, or _P_ instruction becomes the "current
point" for the next instruction.

Each of the following descriptions begins with the name of the
corresponding routine in xref:man:3/libplot3.adoc[*libplot3*(3)].

_m_ :: move: The next four bytes give a new current point.

_n_ :: cont: Draw a line from the current point to the point given by
the next four bytes. See xref:man:1G/plot.adoc[*plot*(1G)].

_p_ :: point: Plot the point given by the next four bytes.

_l_ :: line: Draw a line from the point given by the next four bytes
to the point given by the following four bytes.

_t_ :: label: Place the following ASCII string so that its first
character falls on the current point. The string is terminated by a
new-line.

_a_ :: arc: The first four bytes give the center, the next four give
the starting point, and the last four give the end point of a
circular arc. The least significant coordinate of the end point is
used only to determine the quadrant. The arc is drawn
counter-clockwise.

_c_ :: circle: The first four bytes give the center of the circle, the
next two the radius. Circles and arcs are not supported on all
devices.

_e_ :: erase: Start another frame of output.

_f_ :: linmod: Take the following string, up to a new-line, as the
style for drawing further lines. The styles are "dotted", "solid",
"longdashed", "shortdashed", and "dotdashed". Effective only for the
[opt]*-T4014* and [opt]*-Tver* options of
xref:man:1G/plot.adoc[*plot*(1G)] (TEKTRONIX 4014 terminal and
Versatec plotter).

_s_ :: space: The next four bytes give the lower left corner of the
plotting area; the following four give the upper right corner. The
plot will be magnified or reduced to fit the device as closely as
possible.

The following were added at BRL. Three-dimensional primitives have
their _z_ values ignored when displayed on two-dimensional devices.

_C_ :: color: The next three bytes give respectively the intensities
(0..255) of the three color components (additive colors red, green,
and blue if a terminal; subtractive colors cyan, magenta, and yellow
if hardcopy) to be used for subsequent plotting. The initial color is
assumed to be (255,255,255), which is white on a terminal and black on
hardcopy. Color specifications are ignored for black-and-white
devices.

_M_ :: 3move: The next six bytes give a new current point.

_N_ :: 3cont: Draw a line from the current point to the point given by
the next six bytes. See xref:man:1G/plot.adoc[*plot*(1G)].

_P_ :: 3point: Plot the point given by the next six bytes.

_L_ :: 3line: Draw a line from the point given by the next six bytes
to the point given by the following six bytes.

_S_ :: 3space: The next six bytes give the minimum corner of the
plotting area; the following six give the maximum corner. The plot
will be magnified or reduced to fit the device as closely as possible.

_F_ :: 3flush:

_x_ :: double_point: The double-precision version of point.

_v_ :: double_line: The double-precision version of line.

_o_ :: double_move: The double-precision version of move.

_q_ :: double_cont: The double-precision version of cont.

_w_ :: double_space: The double-precision version of space.

_i_ :: double_circle: The double-precision version of circle.

_r_ :: double_arc: The double-precision version of arc.

_W_ :: double_3space: The double-precision, 3_D version of space.

_X_ :: double_3point: The double-precision, 3_D version of point.

_O_ :: double_3move: The double-precision, 3_D version of move.

_Q_ :: double_3cont: The double-precision, 3_D version of cont.

_V_ :: double_3line: The double-precision, 3_D version of line.

Space settings that exactly fill the plotting area with unity scaling
appear below for devices supported by the filters of
xref:man:1G/plot.adoc[*plot*(1G)]. The upper limit is just outside the
plotting area, except for the Megatek which displays the entire range
of possible coordinates. In every case the plotting area is taken to
be square; points outside may be displayable on devices whose face is
not square.

_DASI 300_ :: space(0, 0, 4096, 4096);

_DASI 300s_ :: space(0, 0, 4096, 4096);

_DASI 450_ :: space(0, 0, 4096, 4096);

TEKTRONIX 4014 :: space(0, 0, 3120, 3120);

Versatec plotter :: space(0, 0, 2048, 2048);

Megatek display :: space(-32768, -32768, 32767, 32767);

== SEE ALSO

xref:man:3/libplot3.adoc[*libplot3*(3)], xref:man:n/plot.adoc[*plot*(n)].

xref:man:1G/graph.adoc[*graph*(1G)], xref:man:1G/plot.adoc[*plot*(1G)] in the _UNIX System User Reference Manual_.

== AUTHOR

Douglas A. Gwyn made the 3-D and color extensions to UNIX-plot.

== COPYRIGHT

This software is Copyright (c) 1989-2021 by the United States Government as represented by U.S. Army Research Laboratory.

== BUG REPORTS

Reports of bugs or problems should be submitted via electronic mail to mailto:devs@brlcad.org[]
