= Tutorials
Sean Morrison; Eric Edwards; Harmanpreet Singh; Check Nyah; Issac Kamga; Clifford Yapp; Scott Nesbitt

<xi:include xmlns:xi="http://www.w3.org/2001/XInclude" href="../books/tutorial_series_authors.xml" xpointer="Intro_MGED_Tutorial_Series_II_authors"/><publishername>Army Research Laboratory</publishername><biblioid class="pubsnumber">ARL-SR-102</biblioid><pubdate>April 2001</pubdate><legalnotice><para>Approved for public release; distribution is unlimited</para><para>The findings in this report are not to be construed as an
      official Department of the Army position unless so designated
      by other authorized documents.</para><para>Citation of manufacturer's or trade names does not constitute
      an official endorsement or approval of the use thereof.</para><para>Destroy this report when it is no longer needed. Do not return
      it to the originator.</para></legalnotice>


<xi:include xmlns:xi="http://www.w3.org/2001/XInclude" href="../books/tutorial_series_authors.xml" xpointer="Intro_MGED_Tutorial_Series_III_authors"/><publishername>Army Research Laboratory</publishername><biblioid class="pubsnumber">ARL-SR-119</biblioid><pubdate>September 2003</pubdate><legalnotice><para>Approved for public release; distribution is unlimited</para><para>The findings in this report are not to be construed as an
      official Department of the Army position unless so designated
      by other authorized documents.</para><para>Citation of manufacturer's or trade names does not constitute
      an official endorsement or approval of the use thereof.</para><para>Destroy this report when it is no longer needed. Do not return
      it to the originator.</para><para>Note that the name BRL-CAD and the BRL-CAD eagle logo are
      trademarks of the U.S. Army.</para></legalnotice></info><bibliography><info><title>References</title></info><biblioentry xreflabel="dummyentry1"><authorgroup><author><personname><firstname>John</firstname><surname>Smith</surname></personname></author></authorgroup><copyright><year>1988</year></copyright><publisher><publishername>Somebody</publishername></publisher><citetitle>Placeholder until xincludes from bibliography file are set up</citetitle><subtitle>sometitle</subtitle><pagenums>000-999</pagenums></biblioentry></bibliography>



<author><personname><firstname>John </firstname><othername>R. </othername><surname>Anderson</surname></personname></author><author><personname><firstname>Eric </firstname><othername>W. </othername><surname>Edwards</surname></personname></author><productnumber>ARL-SR-122</productnumber><date>May 2004</date><legalnotice><para>The findings in this report are not to be construed as an official
Department of the Army position unless so designated by other authorized
documents.</para><para>Citation of manufacturer's or trade names does not constitute an official
endorsement or approval of the use thereof.</para><para>Destroy this report when it is no longer needed. Do not return it to the
originator.</para><para>Note that the name BRL-CAD and the BRL-CAD eagle logo are trademarks of the
U.S. Army.</para><para>Army Research Laboratory
Aberdeen Proving Ground, MD  21005-5068</para><para>ARL-SR-121  May 2004</para></legalnotice></info><dedication><formalpara><info><title>Dedication</title></info><para> The authors would like to thank Messrs. Lee Butler, Edwin Davisson, William
Landis, and David Davis for technically reviewing this document in a timely
manner and for making numerous suggestions to improve its content and
presentation. The authors also thank Dr. Paul Tanenbaum for the use of his
graphics for figures 1 and 2 and Ms. TraNese Christy for her help in
adapting them for presentation in this document. Finally, the authors
would like to posthumously acknowledge Mr. Michael Muuss, the original
architect of BRL-CAD. Without his vision, intellect, and diligence, this
work would not have been possible. Thus, the BRL-CAD Tutorial Series is
dedicated to his memory.</para></formalpara></dedication>


include::partial$chapters.adoc[]
