= BRL-CAD Tutorial Series: Volume III: Principles of Effective Modeling
Lee A. Butler; Eric W. Edwards; Dwayne L. Kregel

****
[cols=">h,<", frame="all"]
|===
| AUTHORS:
| Lee A. Butler +
  Eric W. Edwards +
  Dwayne L. Kregel
| ORGANIZATION:
| *U.S. Army Research Laboratory* +
  Aberdeen Proving Ground, MD  21005-5068

| REPORT:
| ARL-SR-119 +
  September 2003
|===
****

.Disclaimers
****
Approved for public release; distribution is unlimited

The findings in this report are not to be construed as an official
Department of the Army position unless so designated by other
authorized documents.

Citation of manufacturer's or trade names does not constitute an
official endorsement or approval of the use thereof.

Destroy this report when it is no longer needed. Do not return it\ to
the originator.

Note that the name BRL-CAD and the BRL-CAD eagle logo are trademarks
of the U.S. Army.
****

.Acknowledgments
****
The authors would like to acknowledge Mr. John Anderson, Mr. Sean
Morrison, Mr. Keith Applin, Mr. Charles Kennedy, Ms. TraNese Christy,
and Ms. Wendy Winner for reviewing this document at various stages in
its development and for providing many helpful suggestions for
improving its content and presentation.

In addition, the following individuals and organizations are thanked
for contributing various tables and figures throughout the
report. They include Ms. Wendy Winner, Mr. Michael Gillich, Dr. Paul
Tanenbaum, the Aberdeen office of the Science Applications
International Corporation (SAIC), and the SURVICE Engineering Company.

Finally, the authors would especially like to acknowledge Mr. Michael
Muuss, the original architect of BRL-CAD, who passed away in the fall
of 2000. Without his vision, intellect, and diligence, this work would
not have been possible. The BRL-CAD Tutorial Series is dedicated to
his memory.
****

== Chapters

* xref:tutorials:modeling/chapter1.adoc[]
* xref:tutorials:modeling/chapter2.adoc[]
* xref:tutorials:modeling/chapter3.adoc[]
* xref:tutorials:modeling/chapter4.adoc[]
* xref:tutorials:modeling/chapter5.adoc[]
* xref:tutorials:modeling/chapter6.adoc[]
* xref:tutorials:modeling/chapter7.adoc[]
* Appendices
** xref:tutorials:modeling/appendix1.adoc[]
** xref:tutorials:modeling/appendix2.adoc[]
** xref:tutorials:modeling/appendix3.adoc[]
** xref:tutorials:modeling/appendix4.adoc[]
** xref:tutorials:modeling/appendix5.adoc[]
** xref:tutorials:modeling/appendix6.adoc[]

