:pp: {plus}{plus}

== Personal Information

|===
|  |

| *Name*
| Aditya Gulati

| *email*
| adityagulatiadityagulati@gmail.com

| *IRC*
| AdityaGulati

| *Phone Number*
| +91 9996548714

| *Time Zone*
| UTC +5:30

|
|
|===

=== Background

I am a first year student studying in the Indian Institute of Technology
Kanpur. I am pursuing my undergrad in Mathematics and Scientific
Computing. My past projects include cryptography, compiler design, Data
transfer protocols, Data analysis, Game designing, Quiz Website design
and many more.

== Project Details

=== Project title

Improvements in Online Geometry viewer

=== Project Details

This project is really an umbrella term under which I'll make different
improvements to the OGV. The list of improvements are proposed as below:

==== Documentation

The OGV currently does have very good documentation. I am proposing to
complete to the documentation for both the users and the developer. This
would go on in the background through out the duration of the project.
Once I get familiarised with the code, I would start to document when
ever I see it useful.

==== Update meteor to latest version

I would install the latest of meteor to the project and along with it,
its compatible dependencies. (I have already done this in a fork, Just
working out some kinks is left).

==== Port three.js to latest version

Just like meteor, I would update three.js to its latest version and make
the changes needed to make it work smoothly. ( I have finished this too
but is causing the kinks I was taking about).

==== Data not found error

When you run meteor for first time you get an error that says "Couldn't
find a template named "dataNotFound" or "dataNotFound". Are you sure you
defined it?"This happens when brl-cad is not installed on server. I
would change this error statement to state this exact problem. And
change the template to one of the objects.

==== Email server error

Make a required setting that requires the admin to set up an email
server before the signup/login begins.

==== Edit link not working

Currently the edit link redirects to 404. I would look into it and
remove the error.

==== CSS code improvement

This is a nice one. I would break the main css file into small ones with
complete documentation so they are easier to understand and implement.

==== No error if upload failed

f due to some reason upload of the model fails, there's no error
indicating that it has failed. I would look into it and work towards
fing it.

==== Upload progress

I would add an upload progress bar that shows the upload progress.

==== Mediawiki oAuth

I would implement a login with mediaWiki into the OGV system.

==== Auto-position

I would create a function such that it automatically positions the
object in the center and zoomed just enough to be visible completely.

=== Timeline

==== Community bonding

I would get familiar with the code and along with that fix my errors for
Meteor update and three.js update.

==== Week 1

I would work towards finishing the data not found error.

==== Week 2

I would work towards fixing the Email server error.

==== Week 3

I would work towards fixing the Edit link not working error.

==== Week 4-5

I would work towards the CSS code improvement.

==== Week 6

I would work towards showing error if upload failed.

==== Week 7-8

I would work towards making the upload progress bar.

==== Week 9

I would work towards Mediawiki Authentication.

==== Week 10

I would work towards the Auto-Position.

==== Week 11-12

Testing.

=== Time Availability

I can devote 50-60 hours a week for the first 10 weeks, since I don't
have any other major commitments for the summer. For the last 2 weeks, I
would be able to give 40-45 hrs a week.

== Why me

I am really interested in doing this project and would give my complete
effort for its completion. I have been contributing to open source
communities for 5 years now(. I was a finalist for BRL-CAD in GCI 4
years ago. I am proficient C{pp}, JavaScript and Meteor.js.
