*NOTOC* *Please note that all textual contents of BRL-CAD Wiki,
unless specifically marked otherwise, are released under the terms of
the link:BSD_Documentation_License[BSD Documentation License]
(BDL).*

The http://brlcad.org/wiki[BRL-CAD Wiki] is a primary source for
information about the BRL-CAD solid modeling software. The community
that contributes to the wiki is a voluntary association of individuals
and groups who are developing an open-content common resource of
technical knowledge, media, and documentation. As is the nature of a
wiki site, the BRL-CAD Wiki provides anyone with an Internet connection
and a World Wide Web browser the opportunity to alter content found
herein. Therefore, please be advised that the content on this site has
not necessarily been reviewed by professionals with the expertise
necessary to provide you with complete, accurate, or reliable
information.

That's not to say that you won't find valuable, accurate, and useful
information in the BRL-CAD Wiki. Most of the time you certainly will.
There just is no reasonable guarantee of accuracy, validity, and
appropriate relevance for information found in the wiki due to the
nature of the content. The content on any given page may have been
recently changed, vandalized, or may simply be incorrect information.
All information provided is without any implied warranty of fitness for
any purpose or use whatsoever. Review and utilize the information found
at your own discretion.

*_None of the authors, contributors, sponsors, administrators,
affiliates, system operators, or anyone else connected with BRL-CAD Wiki
in any way whatsoever can be responsible for the appearance, accuracy,
libelous nature, or use of any information that is contained in this
site, linked from these web pages, linked from other sites, or
redistributed in other forms._*

Please make sure that you understand that the information on the BRL-CAD
websites is being provided freely, and that no kind of agreement or
contract is created between you and the owners or users of this site,
the owners of the servers upon which it is housed, any individual
BRL-CAD wiki contributors, any project administrators, affiliates,
system operators or anyone else who is in any way connected with this
project or sister projects. They are not subject to any claims against
them directly. While you are being granted a limited license to copy and
reproduce content from the BRL-CAD Wiki; it does not create or imply any
contractual or extra contractual liability on the part of the BRL-CAD
Wiki or any of its agents, members, organizers, or other users.

There is no agreement or understanding between you and the BRL-CAD
project regarding your use or modification of this information beyond
the terms of the link:BSD_Documentation_License[BSD Documentation
License] (BDL); neither is anyone
that contributes to any BRL-CAD website responsible should someone
change, edit, modify, or remove any information that is posted or
otherwise provided.

=== Trademarks

Any of the trademarks, service marks, collective marks, design rights,
personality rights or similar rights that are mentioned, used or cited
on the BRL-CAD website are the property of their respective owners.
Their use here does not imply that you may use them for any other
purpose other than as allowed under the terms of the BSD Documentation
License.

=== Jurisdiction and legality of content

Publication of information found on BRL-CAD Wiki may be in violation of
the laws of the country or jurisdiction from where you are viewing this
information. The BRL-CAD Wiki is maintained in reference to the
protections afforded under local and federal law in the United States of
America. http://www.jomadjeans.com[Ankle Grazer Jeans] Copyright is
asserted in all countries were copyright protection is available. Laws
in your country or jurisdiction may not protect or allow the same kinds
of speech or distribution. The BRL-CAD open source project does not
encourage the violation of any laws; and cannot be responsible for any
violations of such laws should you link to this domain or use,
reproduce, or republish the information contained on the BRL-CAD
websites.

This site is not sponsored, endorsed, or run by the U.S. Government.

Thank you for spending the time to read this page, and please enjoy your
experience using the BRL-CAD Wiki.
