:doctype: book

Online geometry viewer (OGV) is aimed to enable users to view BRL-CAD's
geometry files (.g files) on browser. Development started in 2013 and
efforts were made to make it functional and no doubt it is working but
lacks robust back-end and good looking front-end (user interface). While
details about back-end are mentioned
link:Online_Geometry_Viewer_Back-end[here], this page is focused
only on front-end i.e. designing of user interface for OGV keeping the
user experience in mind.

Current state of OGV's user interface is OK type and is not much user
friendly. Making an influential user interface for OGV requires great
deal of understanding of project's functionality, creativity, aesthetic
sense and knowledge of certain GUI principles.

You will need to work in collaboration with OGV's back-end developer to
discuss and clarify certain things before beginning (and during working
period). Although it is a great learning process and opportunity to work
as team on a real world open source CAD project but it also requires
certain responsibilities on your part.

Feel free to discuss anything about the project at IRC or mailing list.

= References

* link:Online_Geometry_Viewer_Back-end[Online Geometry Viewer
Back-end]
* link:Online_Geometry/TODO[Online Geometry: TODO]

= Requirements

* Familiarity with web development technologies(HTML, CSS, JavaScript,
jQuery etc.)
