[[_chapt_introduction]]
= 1. Introduction
:doctype: book
:sectnums:
:icons: font
:experimental:
:sourcedir: .

:fn-1: footnote:[On 30 September 1992, the U.S. Army Ballistic \
Research Laboratory (BRL) was deactivated and subsequently became part \
of the U.S. Army Research Laboratory (ARL) on 1 October 1992.]

== Background, Purpose, and Scope

Since 1979, the U.S.  Army Research Laboratory {fn-1} has been
developing and distributing the Ballistic Research Laboratory -
Computer-Aided Design (BRL-CAD) three-dimensional (3-D) solid modeling
package to support combat vehicle vulnerability studies and various
other military and industrial applications.  The software, which is
now in its third generation, includes a large collection of tools and
utilities, including an interactive geometry editor, raytracing and
generic framebuffer libraries, network-distributed
image-processing/signal-processing capabilities, and an embedded
scripting language.

In support of the package, a multivolume tutorial series is being
written to assist users with the many features and functionality of
BRL-CAD.  Three volumes have been published thus far.  Volume I
provides an overview of the package contents and installation (Butler
and Edwards, 2002).  Volume II addresses the basic functionality of
the package's Multi-Device Geometry Editor (MGED) and offers a
comprehensive list of the user commands available (Butler et al.,
2001).  Volume III discusses the modeling process as well as
principles and techniques to help maximize BRL-CAD's effectiveness
(Butler et al., 2003).  All of these documents are available for
download at http://ftp.arl.army.mil/brlcad/ (U.S.  Army Research
Laboratory, 2003).

The purpose of Volume IV is to discuss issues of compatibility and
conversion between the BRL-CAD geometry file format and the formats of
various other computer-aided design (CAD), computer-aided
manufacturing (CAM), and computer-aided engineering (CAE) packages.
Conversion is increasingly important for BRL-CAD users who must
interact with a growing number of Government and commercial
organizations involved in the research, development, testing, and
evaluation of today's combat systems.

Note that this document addresses BRL-CAD geometry converters, not
BRL-CAD image converters (e.g., `pix-bw`, `pix-ps`, `pix-rle`,
`bw-ps`, and `pl-ps`). For further information on image conversion,
see the man page on the utility of interest.

Also, because of the many file formats in existence today and the
rapidly changing nature of computer software and software companies,
it would be impractical to try to address all of the conversion paths
and methods that are currently or potentially possible.  Many times,
conversion from one file format to another is not a one-to-one
process.  Depending on the amount of time and effort the BRL-CAD user
is willing to invest, seemingly incompatible formats can be "forced"
to convert via another CAD format or via a standardized CAD format
(e.g., the Initial Graphics Exchange Specification [IGES] or the
Standard for the Exchange of Product Model Data [STEP]). In fact, when
it comes to converting from BRL-CAD, the widely accepted Stereo
Lithography Tessellation Language (STL) format offers a crude path to
convert BRL-CAD objects to virtually any commercial CAD system.  The
user is reminded, however, that such forced conversions can sometimes
produce geometry of such poor quality (e.g., low-resolution or lossy
output formats) or poor performance characteristics (e.g., large or
computationally intensive output files) that completely rebuilding a
model from scratch might be a preferable alternative.

In any case, the focus of this document is on the primary formats that
convert to and from BRL-CAD. xref:converting/chapter2.adoc[] discusses
pertinent characteristics specific to the BRL-CAD
format. xref:converting/chapter3.adoc[] addresses general conversion
to/from the American Standard Code for Information Interchange (ASCII)
format. xref:converting/chapter4.adoc[] addresses the primary formats
that convert to BRL-CAD. xref:converting/chapter5.adoc[] addresses the
primary formats that convert from
BRL-CAD. xref:converting/chapter6.adoc[] provides guidance for those
users who desire to create their own customized converters.  And
xref:converting/chapter7.adoc[] addresses postconversion issues.  In
addition, the user is encouraged to consult the web sites and other
resources cited at the end of each converter discussion to obtain the
latest information on each format.

== The Need for Conversion

Since its inception, BRL-CAD has proven itself to be a particularly
effective tool for producing high-resolution and physically realistic
geometry for ballistic penetration, radar signature, and other types
of related analyses.  However, several commercial CAD packages have
also gained popularity, especially within organizations that design
and manufacture military systems.  Although these packages are not
designed for vulnerability studies per se, their widespread use
throughout military circles necessitates that BRL-CAD users be able to
convert to and/or from them.

There are numerous benefits associated with the use of commercial
packages in vulnerability studies.  The Survivability/Vulnerability
Information Analysis Center (SURVIAC) identified some of the most
common benefits in its 2002 State-of-the-Art Report (SOAR) on
geometric modeling.  They include the following (SURVICE Engineering
Company, 2002):

* _Reduced Modeling Time and Effort_ -- Manufacturers often spend
  hundreds of hours constructing detailed CAD models to streamline
  their design, production, and assembly processes (e.g., through
  computer numerical control equipment). It therefore makes economic
  sense-and is consistent with the military's ongoing commitment to
  leverage commercial off-the-shelf technology-to take advantage of
  existing geometric models and data where possible and avoid the
  significant cost and effort of building new models from scratch.
* _Increased Funding and Support_ -- Because commercial packages must
  maintain a larger user base to stay competitive in the open market,
  the most popular packages typically possess ample funding and
  personnel to continuously develop, support, and improve them.
* _Compatibility With Standardized Formats_ -- Most commercial packages
  possess the direct or indirect (through third-party vendors)
  capability to convert to standard or intermediary geometry formats,
  making the packages compatible (at least to some degree) with a wide
  range of other CAD formats.
* _Third-Party Add-On Support_ -- Large commercial packages typically
  offer a variety of plug-ins for other packages/utilities.

Of course, commercial CAD packages also have some common liabilities
when used for vulnerability studies.  They include the following
(SURVICE Engineering Company, 2002):

* _Incompatible/Inaccessible File Formats_ -- As discussed in
  xref:converting/chapter2.adoc[], some CAD formats use the boundary
  representation (BREP) approach to solid modeling, which is largely
  incompatible with the constructive solid geometry (CSG) approach
  that BRL-CAD uses. In addition, although most commercial packages
  have some capability for data exchange conversion, data storage is
  often in a proprietary (and therefore inaccessible) native
  format. Moreover, when target descriptions are converted to a format
  designed for vulnerability assessment (i.e., BRL-CAD or FASTGEN),
  they often require manual checking, adjustment, and additional
  modeling (see xref:converting/chapter7.adoc[]). Typical problems
  that must be addressed include the translation of curved and
  irregular surfaces, the representation of solids of rotation,
  tolerancing, and interference handling.
* _Too Much Detail_ -- Commercial geometry files often contain too much
  of a good thing for vulnerability analysis. That is to say,
  commercial CAD packages often model geometry all the way to the
  "nuts and bolts" level, whereas vulnerability analyses are
  typically concerned only with details down to the level of shielding
  and critical components. Unfortunately, added detail produces
  unnecessarily large and complex input files and thus longer
  processing times for vulnerability assessments.
* _Too Little Detail_ -- In addition to providing too much detail,
  commercial packages sometimes provide too little detail for
  vulnerability studies. Vulnerability analysts and the applications
  designed to interrogate geometry rely on geometric measurements and
  material properties not always present in commercial CAD formats.
* _Package-Specific Naming Conventions_ -- Some organizations and CAD
  packages use unique object naming schemes that make geometry
  difficult to organize and work with when converted to or from
  BRL-CAD format.
* _Relatively Slow Raytracing Capability_ -- Commercial CAD packages
  typically have relatively slow raytracing speeds, and raytracing is
  the primary means of geometry interrogation in vulnerability
  assessment.
* _Limited Integrated Vulnerability Assessment Support_ -- Commercial
  CAD packages are designed for engineering analysis, not ballistic
  analysis and therefore offer few, if any, "shotlining" tools and
  limited integrated vulnerability assessment support.
* _High Cost_ -- In addition to facing the typically high cost of
  commercial CAD software, the user often faces the decision of
  whether or not to invest in non-PC hardware (e.g., UNIX
  workstations) to obtain maximum performance, especially with large,
  complex geometry. In addition, users may be required to pay
  continuing licensing and maintenance fees, often on a per-seat basis
  (although recent developments have offered PC-based implementations
  and short-term leasing "seats" to make these packages more
  affordable).

Not surprisingly, when considering the benefits and liabilities of
using commercial packages in vulnerability assessment, one can see
that the conversion of these formats to/from BRL-CAD is one of the
most needed as well as one of the most challenging tasks the BRL-CAD
user faces today.
