= Callback

MGED has several callbacks that get called at strategic times in order
to give the GUI a chance to update itself after something important
has happened.

* opendb_callback -- this is called after opening a database to update
  the command windows`' title bar and to update the raytrace control
  panel.
* begin_edit_callback -- this is called at the start of an edit to
  reconfigure the GUI`'s edit menus and to initialize other parts of
  the GUI with information about the solid/object being edited.
* active_edit_callback -- this is called during an active edit, after
  MGED perceives a change to the solid/object being edited, to
  continuously update GUI components during an edit.
* end_edit_callback -- this is called at the end of an edit to
  reconfigure the GUI to a non-edit configuration.
* output_callback -- this is called when things need to be printed to
  the command window(s) (i.e. after issuing a command).
* solid_list_callback -- this is called whenever MGED`'s internal
  solid list changes. Note - the solid list changes whenever
  solids/objects are e`'d up or when they are deleted from the
  display.

