include::../header.adoc[]

= adc(nged)

== NAME

adc - This command controls the angle/distance cursor.

== SYNOPSIS

*adc* [-i] _subcommand_

== DESCRIPTION

This command controls the angle/distance cursor. The [cmd]*adc*
command with no arguments toggles the display of the angle/distance
cursor (ADC). The _-i_ option, if specified, causes the given value(s)
to be treated as increments. Note that the _-i_ option is ignored when
getting values or when used with subcommands where this option makes
no sense. You can also control the position, angles, and radius of the
ADC using a knob or the knob command. This command accepts the
following subcommands:

[cmd]*vars*::
Returns a list of all ADC variables and their values (i.e., var = val). 

[cmd]*draw [0|1]*::
Set or get the draw parameter. 

[cmd]*a1 [angle]*::
Set or get angle1 in degrees. 

[cmd]*a2 [angle]*::
Set or get angle2 in degrees. 

[cmd]*dist [distance]*::
Set or get radius (distance) of tick in local units. 

[cmd]*odist [distance]*::
Set or get radius (distance) of tick (+-2047). 

[cmd]*hv [position]*::
Set or get position (grid coordinates and local units). 

[cmd]*xyz [position]*::
Set or get position (model coordinates and local units). 

[cmd]*x [xpos]*::
Set or get horizontal position (+-2047). 

[cmd]*y [ypos]*::
Set or get vertical position (+-2047). 

[cmd]*dh* [rep]_distance_::
Add to horizontal position (grid coordinates and local units). 

[cmd]*dv* [rep]_distance_::
Add to vertical position (grid coordinates and local units). 

[cmd]*dx* [rep]_distance_::
Add to _x_ position (model coordinates and local units). 

[cmd]*dy* [rep]_distance_::
Add to _y_ position (model coordinates and local units). 

[cmd]*dz* [rep]_distance_::
Add to _z_ position (model coordinates and local units). 

[cmd]*anchor_pos [0|1]*::
Anchor ADC to current position in model coordinates. 

[cmd]*anchor_a1 [0|1]*::
Anchor angle1 to go through anchorpoint_a1. 

[cmd]*anchor_a2 [0|1]*::
Anchor angle2 to go through anchorpoint_a2. 

[cmd]*anchor_dst [0|1]*::
Anchor tick distance to go through anchorpoint_dst. 

[cmd]*anchorpoint_a1 [x y z]*::
Set or get anchor point for angle1 (model coordinates and local units). 

[cmd]*anchorpoint_a2 [x y z]*::
Set or get anchor point for angle2 (model coordinates and local units). 

[cmd]*anchorpoint_dst [x y z]*::
Set or get anchor point for tick distance (model coordinates and local units). 

[cmd]*reset*::
Reset all values to their defaults. 

[cmd]*help*::
Print the help message. 

== EXAMPLES

The examples show the use of the [cmd]*adc* command with no arguments,
with _i_, and with subcommands.

====
[prompt]#mged># [ui]`adc`

Toggle display of angle/distance cursor. 
====

====
[prompt]#mged># [ui]`adc a1 37.5`

Sets angle1 to 37.5 degrees. 
====

====
[prompt]#mged># [ui]`adc a1 37.5`

Gets angle1. 
====

====
[prompt]#mged># [ui]`adc xyz 100 0 0`

Moves ADC position to (100,0,0), model coordinates and local units.
====

== AUTHOR

BRL-CAD Team

include::../footer.adoc[]
