include::../header.adoc[]

= BOT_DECIMATE(nged)

== NAME

bot_decimate - Reduces the number of triangles in the
old_bot_primitive and saves the results to the new_bot_primitive.

== SYNOPSIS

*bot_decimate* [-f _feature_size_] [-c _maximum_chord_error_] [-n _maximum_normal_error_] [-e _minimum_edge_length_] {_new_bot_primitive_} {_old_bot_primitive_}

== DESCRIPTION

Reduces the number of triangles in the _old_bot_primitive_ and saves
the results to the _new_bot_primitive_. The reduction is accomplished
through an edge decimation algorithm. Only changes that do not violate
the specified constraints are performed. Specifying the _feature_size_
parameter will result in use of the new GCT decimator (this parameter
is mutually exclusive with the other tolerances). The
_maximum_chord_error_ parameter specifies the maximum distance allowed
between the original surface and the surface of the new BOT primitive
in the current editing units. The _maximum_normal_error_ specifies the
maximum change in surface normal (degrees) between the old and new
surfaces. The _minimum_edge_length_ specifies the length of the
longest edge that will be decimated. At least one constraint must be
supplied. If more than one constraint is specified, then only
operations that satisfy all the constraints are performed.

== EXAMPLES

These examples demonstrate the use of the [cmd]*bot_decimate* command
to create new primitives by reducing the number of triangles within
certain constraints.

.Decimate Specifying Chord Error and Max Normal Error
====
Creating a new BOT primitive by reducing the number of triangles in
the old BOT primitive and specifying the maximum chord error and
maximum normal error between the old and new primitives.

[prompt]#mged># [ui]`bot_decimate -c 0.5 -n 10.0 bot.new abot`

Creates a new BOT primitive named _bot.new_ by reducing the number of
triangles in _abot_ while keeping the resulting surface within 0.5
units of the surface of _abot_ and keeping the surface normals within
10 degrees.

Note that the constraints specified only relate the output BOT
primitive to the input BOT primitive for a single invocation of the
command. Repeated application of this command on its own BOT output
will result in a final BOT primitive that has unknown relationships to
the original BOT primitive. For example:

[prompt]#mged># [ui]`bot_decimate -c 10.0 bot_b bot_a`

[prompt]#mged>#[ui]`bot_decimate -c 10.0 bot_c bot_b`

This sequence of commands will produce primitive _bot_c_ with up to
20.0 units of chord error between _bot_a_ and _bot_c_.

[prompt]#mged># [ui]`bot_decimate -c 10.0 bot_b bot_a`

[prompt]#mged># [ui]`bot_decimate -n 5.0 bot_c bot_b`

This sequence of commands will produce primitive _bot_c_ with no
guaranteed relationships to _bot_a_.
====

== AUTHOR

BRL-CAD Team

include::../footer.adoc[]
