= BREP(nged)
BRL-CAD Team
:doctype: manpage
:man manual: BRL-CAD MGED User Commands
:man source: BRL-CAD
:page-layout: base

== NAME

brep - 
    This command does a boundary representation which represents the solid geometry by describing the topology and corresponding geometry.
    

== SYNOPSIS

*[cmd]#brep#* {[rep]_obj_}[--no-evaluation][[rep]_command_ | [rep]_brepname_ | [rep]_suffix_]

== DESCRIPTION

If [rep]_obj_  is not a brep object, then *[cmd]#brep#*  attempts to convert it to a brep object. If [rep]_brepname_  is given, then *[cmd]#brep#*  defaults to [rep]_obj_ _brep; if --no-evaluation is given, then *[cmd]#brep#*  attempts to convert a combination to an unevaluated BREP named [rep]_suffix_  (again defaulting to [rep]_obj_ _brep). 

Otherwise, the behavior of *[cmd]#brep#*  is determined by which of these subcommands is specified: 
*[cmd]#info#* 
::
Return count information (surfaces, curves, etc.) for a BREP. 
*[cmd]#info C#* [[rep]_index_ | [rep]_index_ -[rep]_index_]
::
Return information for a specific BREP '3D curve'. 
*[cmd]#info S#* [[rep]_index_ | [rep]_index_ -[rep]_index_]
::
Return information for a specific BREP 'surface'. 
*[cmd]#info F#* [[rep]_index_ | [rep]_index_ -[rep]_index_]
::
Return information for a specific BREP 'face'. 
*[cmd]#info T#* [[rep]_index_ | [rep]_index_ -[rep]_index_]
::
Return information for a specific BREP 'trim'. 
*[cmd]#info E#* [[rep]_index_ | [rep]_index_ -[rep]_index_]
::
Return information for a specific BREP 'edge'. 
*[cmd]#info TB#* [[rep]_index_ | [rep]_index_ -[rep]_index_]
::
Return information for a specific BREP 'piecewise bezier trim'. 
*[cmd]#info SB#* [[rep]_index_ | [rep]_index_ -[rep]_index_]
::
Return information for a specific BREP 'piecewise bezier surface'. 
*[cmd]#plot S#* [[rep]_index_ | [rep]_index_ -[rep]_index_]
::
Plot a specific BREP 'surface'. 
*[cmd]#plot Suv#* {[rep]_index_ | [rep]_index_ -[rep]_index_}{[rep]_u_}{[rep]_v_}
::
Plot a specific BREP 'surface' 3d point at specified uv. 
*[cmd]#plot UV#* {[rep]_index_ | [rep]_index_ -[rep]_index_}{[rep]_u1_}{[rep]_u2_}{[rep]_v1_}{[rep]_v2_}
::
Plot a specific BREP 'surface' 3d bounds at specified uv bounds. 
*[cmd]#plot F#* [[rep]_index_ | [rep]_index_ -[rep]_index_]
::
Plot a specific BREP 'face'. 
*[cmd]#plot I#* [[rep]_index_ | [rep]_index_ -[rep]_index_]
::
Plot a specific BREP 'isosurface'. 
*[cmd]#plot SN#* [[rep]_index_ | [rep]_index_ -[rep]_index_]
::
Plot a specific BREP 'surface normal'. 
*[cmd]#plot KN#* [[rep]_index_ | [rep]_index_ -[rep]_index_]
::
Plot a specific BREP 'surface knot'. 
*[cmd]#plot F2d#* [[rep]_index_ | [rep]_index_ -[rep]_index_]
::
Plot a specific BREP 'face in 2d'. 
*[cmd]#plot SBB#* [[rep]_index_ | [rep]_index_ -[rep]_index_]
::
Plot a specific BREP 'surfaceleafs'. 
*[cmd]#plot SBB2d#* [[rep]_index_ | [rep]_index_ -[rep]_index_]
::
Plot a specific BREP 'surfaceleafs in 2d'. 
*[cmd]#plot TD#* [[rep]_index_ | [rep]_index_ -[rep]_index_]
::
Plot a specific BREP 'trim direction'. 
*[cmd]#plot T#* [[rep]_index_ | [rep]_index_ -[rep]_index_]
::
Plot a specific BREP 'trim'. 
*[cmd]#plot T2d#* [[rep]_index_ | [rep]_index_ -[rep]_index_]
::
Plot a specific BREP 'trim in 2d'. 
*[cmd]#plot TBB#* [[rep]_index_ | [rep]_index_ -[rep]_index_]
::
Plot a specific BREP 'trimleafs'. 
*[cmd]#plot TBB2d#* [[rep]_index_ | [rep]_index_ -[rep]_index_]
::
Plot a specific BREP 'trimleafs in 2d'. 
*[cmd]#plot E#* [[rep]_index_ | [rep]_index_ -[rep]_index_]
::
Plot a specific BREP 'edge3d'. 
*[cmd]#plot SCV#* [[rep]_index_ | [rep]_index_ -[rep]_index_]
::
Plot a specific BREP 'nurbs control net'. 
*[cmd]#flip#* 
::
Flip all faces in the BREP (turns it 'inside out'). 
*[cmd]#translate#* {[rep]_SCV_}{[rep]_index_}{[rep]_i_}{[rep]_j_}{[rep]_dx_}{[rep]_dy_}{[rep]_dz_}
::
Translate a surface control vertex 
*[cmd]#intersect#* {[rep]_obj2_}{[rep]_i_}{[rep]_j_}[PP | PC | PS | CC | CS | SS]
::
Visualize intersecting two BREP objects.  The last argument specifies what portions of each to intersect; if it is not specified, it defaults to SS: 
+

PP::
Intersect a point from the first object with a point from the second.

PC::
Intersect a point from the first object with a curve from the second.

PS::
Intersect a point from the first object with a surface from the second.

CC::
Intersect a curve from the first object with a curve from of the second.

CS::
Intersect a curve from the first object with a surface from the second

SS::
Intersect a surface from the first object with a surface from the second.
*[cmd]#u#* {obj2}{output}
::
Take the union of [rep]_obj_  and [rep]_obj2_ , storing the result in [rep]_output_ . 
*[cmd]#i#* {obj2}{output}
::
Take the intersection of [rep]_obj_ and [rep]_obj2_ , storing the result in [rep]_output_ . 
*[cmd]#-#* {obj2}{output}
::
Take the difference of [rep]_obj_  and [rep]_obj2_ , storing the result in [rep]_output_ . 
*[cmd]#x#* {obj2}{output}
::
Take the exclusive or of [rep]_obj_ and [rep]_obj2_ , storing the result in [rep]_output_ . 
*[cmd]#csg#* 
::
Take the specified B-Rep and attempt to generate a CSG implicit boolean tree that will define the same solid shape. 

== EXAMPLES

.Info
====

[prompt]#mged># [ui]`brep obj.randomobj info` ::
This outputs general information about obj.randomobj, including counts of various entity types such as surfaces, curves, vertices, etc.

[prompt]#mged># [ui]`brep obj.randomobj info F 2` ::
Output info about the 2nd face of the BREP object obj.randomobj.
====

.Plot
====

[prompt]#mged># [ui]`brep obj.randomobj plot S 1-3` ::
This plots the 1st through 3rd surfaces of obj.randomobj in the graphics display window.
====

.Intersect
====

[prompt]#mged># [ui]`brep obj.randomobj intersect sph2.randomobj 2 4` ::
This displays the intersection of obj.randomobj's 2nd surface with sph2.randomobj's 4th surface.

[prompt]#mged># [ui]`brep obj.randomobj intersect sph2.randomobj 3 2 PC` ::
This displays the intersection of obj.randomobj's 3rd point with sph2.randomobj's 2nd curve.
====

== AUTHOR

BRLCAD-TEAM

== BUG REPORTS

Reports of bugs or problems should be submitted via electronic mail to mailto:devs@brlcad.org[]