= COPYMAT(nged)
BRL-CAD Team
:doctype: manpage
:man manual: BRL-CAD User Commands
:man source: BRL-CAD
:page-layout: base

== NAME

copymat - Copies the transformation matrix from a member of one
    combination to the member of another.
    

== SYNOPSIS

*[cmd]#copymat#*  {[rep]_comb1/memb1 comb2/memb2_}

== DESCRIPTION

Copies the transformation matrix from a member of one combination to the member of another. 

== EXAMPLES

The example shows the use of the *[cmd]#copymat#*  command to set the matrix for a member in one combination equal to the matrix for another member in another combination. 

.Set the matrix for a member in one combination equal to the matrix for another member in another combination. 
====
[prompt]#mged># [ui]`copymat comb1/memb1 comb2/memb2` 

Sets the matrix for member _memb2_ in combination _comb2_ equal to the matrix for member _memb1_ in combination __comb1__.
====

== AUTHOR

BRL-CAD Team

== BUG REPORTS

Reports of bugs or problems should be submitted via electronic mail to mailto:devs@brlcad.org[]