include::../header.adoc[]

= D(nged)

== NAME

d - Deletes the specified list of objects from the mged display.

== SYNOPSIS

*d* {_objects_}

== DESCRIPTION

Deletes the specified list of objects from the _mged_ display. This is
a synonym for the [cmd]*erase* command. Only objects that have been
explicitly displayed may be deleted with the [cmd]*d* command (use the
[cmd]*who* command to see a list of explicitly displayed
objects). Objects that are displayed as members of explicitly
displayed combinations cannot be deleted from the display with this
command (see [cmd]*erase -r*). Note that this has no effect on the
_BRL-CAD_ database itself. To actually remove objects from the
database, use the [cmd]*kill* command.

== EXAMPLES

The example shows the use of the [cmd]*d* command to delete a region
and a shape from the _mged_ display.

.Delete a region and a shape from the _mged_ display.
====
[prompt]#mged># [ui]`d region1 shapea`

Deletes _region1_ and _shapea_ from the _mged_ display.
====

== AUTHOR

BRL-CAD Team

include::../footer.adoc[]
