= DEBUGDIR(nged)
BRL-CAD Team
:doctype: manpage
:man manual: BRL-CAD User Commands
:man source: BRL-CAD
:page-layout: base

== NAME

debugdir - 
      Displays a dump of the in-memory directory for the current
      database file.
    

== SYNOPSIS

*debugdir*

== DESCRIPTION

Displays a dump of the in-memory directory for the current database file. The information listed for each directory entry includes: 



* memory address of the directory structure.
* name of the object.
* "d_addr" for objects on disk, or "ptr" for objects in memory.
* "SOL," "REG," or "COM" if the object is a shape, region, or combination, respectively. 
* file offset (for objects on disk) or memory pointer (for objects in memory). 
* number of instances referencing this object (not normally filled in). 
* number of database granules used by this object. 
* number of times this object is used as a member in combinations (not normally filled in). 


== EXAMPLES

The example shows the use of the [cmd]*debugdir* command to get a dump of the in-memory directory. 

.Get a dump of the in-memory directory.
====
[prompt]#mged>#[ui]`debugdir`

Gets a dump of the in-memory directory.
====

== AUTHOR

BRL-CAD Team

== BUG REPORTS

Reports of bugs or problems should be submitted via electronic mail to mailto:devs@brlcad.org[]