include::../header.adoc[]

= EDIT(nged)

== NAME

edit - Edits objects, using subcommands.

== SYNOPSIS

*edit* [(<<_subcommands,1>>)subcommand [(<<_args,2>>)args] _object_...]

[[_subcommands]]
(1)subcommands: :: help translate rotate scale ...

[[_args]]
(2)args: :: [(<<_from,3>>)from] (<<_to,4>>)to [(<<_args,2>>)more_args]...

[[_from]]
(3)from: :: [-n] -k {(<<_obj,5>>)from_object (<<_pos,6>>)from_position}

[[_to]]
(4)to: :: [-n] [-a -r] {(<<_obj,5>>)to_object (<<_pos,6>>)to_position}

[[_obj]]
(5)obj: :: [_path/_] _object_ [(<<_coord,7>>)offset_distance]

[[_pos]]
(6)pos: :: {(<<_coord,7>>)coords} {[-x {_x_ (<<_obj,5>>)x-obj}] [-y {_y_ (<<_obj,5>>)y-obj}] [-z {_z_ (<<_obj,5>>)z-obj}]}

[[_coord]]
(7)coord: :: _x_ [_y_ [_z_]]


== DESCRIPTION

Operates on objects in the database, solely through the use of
__subcommand__s. The flexibility of the [cmd]*edit* __subcommand__s
lies in their utilization of a common style of syntax. Coordinates in
model space, offsets, and objects are all accepted interchangeably as
reference points. A single reference point is equivalent to an
absolute point in model space. A pair of reference points specifies a
distance or an angle, and is supplied as a set of _from_ - _to_
arguments (a _from_ argument is similar to the concept of a
keypoint). Reference points may be incomplete, and specify only one or
two coordinates.

The format of the standard options accepted by subcommands, [opt]*-n*,
[opt]*-k*, [opt]*-a*/[opt]*-r*, and [opt]*-x*/[opt]*-y*/[opt]*-z*, is
defined here. The interpretation of these options, however, is left up
to the implementation of a given subcommand.

All edit commands interpret a lone point ([cmd]*.*) as a special
operator, called the batch operator. The batch operator is accepted as
an argument to the options [opt]*-k*, [opt]*-a*, and [opt]*-r*. In a
batch operation, each individual _object_ is operated on using the
bounding box center of itself in place of the batch operator. While
all __object__s move together in a non-batch operation, in batch
operations, each _object_ may move independently of all other
__object__s.

If any _from_ coordinates are omitted, they default to the bounding
box center of the first _object_ is used as _from_. To use the natural
origin of the first _object_ as _from_, _from_object_ must be manually
set to whatever _object_ is set to. If any _to_ coordinates are
omitted, they default to the values set in _from_.

The quantity and arrangement of standard [cmd]*edit* arguments as well
as their interpretation depends upon the subcommand. See the manual
page for a given subcommand for more information on its usage:

  >  man edit_subcommandName

== OPTIONS

*-n*:: Use the natural origin of the object specified as an argument
to [opt]*-k*, [opt]*-a*, or [opt]*-r* rather than its bounding box
center.

*-k*:: Sets the keypoint _from_ to either __from_object__'s bounding
box center or _from_position_.

*-a*:: Sets the destination point _to_ to either __to_object__'s
bounding box center or _to_position_.

*-r*:: Sets the destination point _to_ to a point offset by
_to_position_ from the _from_ point.

*-x* *-y* *-z*:: Sets the coordinate of a particular axis.

== EXAMPLES

.Get the authoritative list of available subcommands. 
====
[prompt]#># [ui]`edit`

[prompt]#># [ui]`edit help`

Prints usage and a list of available subcommands.
====

.Get the usage of a subcommand.
====
[prompt]#># [ui]`edit translate`

Print usage of the translate subcommand
====

.Use the help subcommand to print extended usage of subcommands. 
====
[prompt]#># [ui]`edit translate help`

[prompt]#># [ui]`edit help translate`

Print extended usage of the translate subcommand. Each subcommand also
accepts _help_ as an argument, so that the extended usage is still
available if [cmd]*edit translate* is aliased to something else.
====

.A fake subcommand is used to show how standard [cmd]*edit* arguments and nonstandard [cmd]*edit* arguments are used. 
====
[prompt]#># [ui]`edit fake_subcmd -B 12 -k sph.s 1.5 7 -a 0 0 0 cube.s`

The nonstandard [opt]*-B* option is unique to [cmd]*fake_subcmd*. An
explanation of how it is used would be found in the manual for
fake_subcmd, if there were one. The remaining options and arguments
are standardized. The [opt]*-k* and [opt]*-a* options are used to
specify a _from_ - _to_ pair, as defined in this manual for
[cmd]*edit*. The interpretation of the vector created by these points
would be defined in the [cmd]*fake_subcmd* manual.
====

== AUTHOR

BRL-CAD Team

include::../footer.adoc[]
