include::../header.adoc[]

= EQN(nged)

== NAME

eqn - Allows the user to rotate the face of an ARB shape by providing
the coefficients of an equation of the desired plane for the face.

== SYNOPSIS

*eqn* {_A B C_} []

== DESCRIPTION

Allows the user to rotate the face of an ARB shape by providing the
coefficients of an equation of the desired plane for the face. The
coefficients _A, B,_ and _C_ are from the plane equation:

[math]*Ax + By + Cz = D*

The user must be editing an _ARB_ shape and be rotating a face of the
_ARB_ for this command to have any effect. When entering such a state,
the user will be asked which of the face vertices should be held
constant, and from this information the _D_ coefficient of the
equation is determined.

== EXAMPLES

The example shows the use of the [cmd]*eqn* command to rotate the face
of the ARB being edited to be parallel to the _xy_ plane.

.Rotate the face of an _ARB_ to be parallel to the _xy_ plane.
====
[prompt]#mged># [ui]`eqn 0 0 1`

The face of the _ARB_ is rotated to be parallel to the _xy_ plane.
====

== AUTHOR

BRL-CAD Team

include::../footer.adoc[]
