include::../header.adoc[]

= HELPDEVEL(nged)

== NAME

helpdevel - Returns a list of available developer commands along with
a one-line usage message for each. If a command is supplied as an
argument, the one-line usage message for that command is returned.

== SYNOPSIS

*helpdevel* [_command_]

== DESCRIPTION

Returns a list of available _developer_ commands along with a one-line
usage message for each. If a command is supplied as an argument, the
one-line usage message for that command is returned. The [cmd]*help,
helplib, ?, ?devel,* and [cmd]*?lib* commands provide additional
information on available commands.

== EXAMPLES

The example shows the use of the [cmd]*helpdevel* command to display a
one-line usage message for a specified developer command.

.Display a one-line usage message for a specified developer command.
====
[prompt]#mged># [ui]`helpdevel winset`

Displays a one-line usage message for the [cmd]*winset* command.
====

== AUTHOR

BRL-CAD Team

include::../footer.adoc[]
