= HELP(nged)
BRL-CAD Team
:doctype: manpage
:man manual: BRL-CAD User Commands
:man source: BRL-CAD
:page-layout: base

== NAME

help - Returns a list of available MGED commands along with a one-line usage message for each.
    If a command is supplied as an argument, the one-line usage message for that command is returned.
   

== SYNOPSIS

*[cmd]#help#*  [[rep]_command_]

== DESCRIPTION

Returns a list of available MGED commands along with a one-line usage message for each. If a command is supplied as an argument, the one-line usage message for that command is returned. The *[cmd]#helpdevel, helplib, ?, ?devel,#*  and *[cmd]#?lib#*  commands provide 	additional information on available commands. 

== EXAMPLES

The example shows the use of the *[cmd]#help#*  command to display a one-line usage message for 	a specific command. 

.Display a one-line usage message for a command.
====

[prompt]#mged># [ui]`help ae` ::
Displays a one-line usage message for the *[cmd]#ae#*  command.
====

== AUTHOR

BRL-CAD Team

== BUG REPORTS

Reports of bugs or problems should be submitted via electronic mail to mailto:devs@brlcad.org[]