= ILL(nged)
BRL-CAD Team
:doctype: manpage
:man manual: BRL-CAD User Commands
:man source: BRL-CAD
:page-layout: base

== NAME

ill - Performs the function of selecting an object after entering solid
(i.e., primitive)illuminate or object illuminate mode.
   

== SYNOPSIS

*[cmd]#ill#*  {[rep]_obj_name_}

== DESCRIPTION

Performs the function of selecting an object after entering _solid_	(i.e., primitive) _illuminate_ or _object illuminate_ mode. In _solid illuminate_ mode, this command selects the specific shape for editing. In__object illuminate__ mode, this command selects the leaf object for the object path, 	then the user may use the mouse to select where along the object path the editing should be applied. In 	both modes,the _ill_ command will only succeed if the specified _obj_name_ is only referenced once in the displayed objects; otherwise a _multiply referenced_ message will be displayed. If the *[cmd]#ill#*  command fails, the user must resort 	to either using the mouse to make the selection, or using aip and M 1 0 0. 

== EXAMPLES

The example shows the use of the *[cmd]#ill#*  command to select a specified object for 	editing. 

.Select an object for editing.
====

[prompt]#mged># [ui]`ill shapea` ::
_Shapea>_ is selected for editing. 
====

== AUTHOR

BRL-CAD Team

== BUG REPORTS

Reports of bugs or problems should be submitted via electronic mail to mailto:devs@brlcad.org[]