include::../header.adoc[]

= KILL(nged)

== NAME

kill - Deletes specified objects from the current database.

== SYNOPSIS

*kill* [-f] {_objects_}

== DESCRIPTION

Deletes the specified _objects_ from the current database.  This
command affects only the _objects_ actually listed on the command
line. If a combination is killed, its members are not affected. If the
_-f_ option is specified, then kill will not complain if some, or all,
of the _objects_ specified do not actually exist in the database. Note
that the _objects_ are killed immediately. There is no need for a
[cmd]*write file* command in MGED, and there is no [cmd]*undo*
command.

*Use this command with caution.* Other commands that remove objects
from the database are [cmd]*killall* and [cmd]*killtree*.

The [opt]*-q* option may be added to suppress database object lookup
messages reporting failure, which will otherwise let the user know an
invalid object was specified.

== EXAMPLES

The example shows the use of the [cmd]*kill* command to delete
specified objects from the database.

.Delete objects from the database.
====
[prompt]#mged># [in]`kill group1 region2 shapeb`

Deletes _group1, region2_, and _shapeb_ from the database.
====

== AUTHOR

BRL-CAD Team 

include::../footer.adoc[]
