= LC(nged)
BRL-CAD Team
:doctype: manpage
:man manual: BRL-CAD User Commands
:man source: BRL-CAD
:page-layout: base

== NAME

lc - Lists codes (i.e. region attributes) 'region_id', 'material_id', 'los', 'region name', 'region parent' within a group or combination.
   

== SYNOPSIS

*lc* [-d | -m | -s] [-r] [-z] [-0 | -1 | -2 | -3 | -4 | -5] [-f | {_FileName_}] {_GroupName_}

== DESCRIPTION

The 'lc' command lists a set of codes (i.e. attributes) of regions within a group/combination. Listed in columns are the following: 'region_id', 'material_id', 'los', 'region name', 'region parent'. If a value is unset, it is reported as '--'.

== OPTIONS

*-d*::
Specifies to list only one region with each 'region_id'. 

*-s*::
Specifies to list only one region with each combination of 'region_id', 'material_id' and 'los'.  In addition to the output of '-d', it lists those cases where 'region_id' is the same but 'material_id' and/or 'los' are different. 

*-m*::
Specifies to list only regions with shared 'region_id' values where one or more of the objects in the set of objects defined by shared 'region_id' value reports a different 'material_id' and/or 'los'.  Essentially, this allows users to quickly find and resolve inconsistent 'material_id' and 'los' settings within a 'region_id' group. 

*-r*::
Remove regions from the list in which their parent is a region and the region is subtracted within the parent. The '-r' option can be combined with any other option. 

*-z*::
Specifies descending (z-a) sort order. 

*-0*::
Specifies sort column 1, 2, 3, 4 or 5 (referring to columns listed in the description of this command); 1 is default. If 0 is specified, the regions are listed in the order in which they are stored, but this will be overridden if [opt]*-d* or [opt]*-s* is used, because of the sorting which needs to be done when either of those options is used. 

*-f FileName*::
Identifies output should be to a file and specifies the file name. If the path is not included as part of the 'FileName' the path will be the 'current directory'. 

== AUTHOR

BRL-CAD Team

== BUG REPORTS

Reports of bugs or problems should be submitted via electronic mail to mailto:devs@brlcad.org[]