= PLOT(nged)
BRL-CAD Team
:doctype: manpage
:man manual: BRL-CAD User Commands
:man source: BRL-CAD
:page-layout: base

== NAME

plot - Creates a UNIX plot of the current MGED display.
   

== SYNOPSIS

*[cmd]#plot#*  [-float] [-zclip] [-2d] [-grid] [[rep]_output_file_] [[rep]_filter_]

== DESCRIPTION

Creates a UNIX plot of the current MGED display. If an _output_file_ is specified, the plot is stored in that file. If a _filter_ is specified, the output is sent to that __filter__. The *[opt]#-float#*  option requests a plot file with real numbers rather than integers. The *[opt]#-zclip#*  option requests that the plot be clipped to the viewing cube in the Z-direction. The *[opt]#-2d#*  option requests a two-dimensional plot (the default is 3D). The *[opt]#-grid#*  option is intended to include a grid in the plot, but is currently not implemented. This command does not 	use the _dm-plot_ display manager. The *[cmd]#pl#*  command performs the same 	function, but does use the _dm-plot_ display manager. 

== EXAMPLES

The example shows the use of the *[cmd]#plot#*  command to create a UNIX plot of the current MGED 	display and pipe the results to the specified command. 

.Create a UNIX plot of the current MGED display and send the results to a specified command.
====
[prompt]#mged>#  plot -float | pldebug 

Creates a UNIX plot of the current MGED display and pipe the results to the *[cmd]#pldebug#*  command. 
====

== AUTHOR

BRL-CAD Team

== BUG REPORTS

Reports of bugs or problems should be submitted via electronic mail to mailto:devs@brlcad.org[]