include::../header.adoc[]

= PREVIEW(nged)

== NAME

preview - Allows the user to preview animation scripts in MGED.

== SYNOPSIS

*preview* [-v] [-d _delay_] [-D _start_frame_number_] [K _end_frame_number_] {_rt_script_file_}

== DESCRIPTION

Allows the user to _preview_ animation scripts in MGED. The _-d_
option provides a delay in seconds to be applied between each frame
(the default is no delay). The _-D_ option allows the user to specify
a starting frame number, and the _-K_ option allows the specification
of an ending frame number. The _-v_ flag indicates that the objects
displayed in the MGED graphics window should be displayed in
"evaluated" mode, as would be the result of the [cmd]*ev*
command. Note that this may significantly slow the _preview_.

== EXAMPLES

The example shows the use of the [cmd]*preview* command to preview
specified frames of an animation script.

.Preview an animation script.
====
[prompt]#mged># [ui]`preview -D 101 -K 237 script.rt`

Displays the animation script stored in the file named _script.rt_
from frame number 101 through frame number 237.
====

== AUTHOR

BRL-CAD Team

include::../footer.adoc[]
