= PRJ_ADD(nged)
BRL-CAD Team
:doctype: manpage
:man manual: BRL-CAD User Commands
:man source: BRL-CAD
:page-layout: base

== NAME

prj_add - Appends information to the specified shaderfile.
    

== SYNOPSIS

*prj_add* [-t] [-b] [-n] {_shaderfile_} [_image_file_] [_image_width_] [_image_height_]

== DESCRIPTION

Appends information to the specified __shaderfile__. The information appended is in the form required by the projection shader (__prj__) and includes the _image_file_ (typically a pix file), the _image_width_ and __image_height__, and current view parameters from the MGED 	display.  The resulting _shaderfile_ may then be used as the parameter to the _prj_ shader.  Before executing this command, 	the region wireframe display in MGED should be aligned with the _image_file_ (underlaid in MGEDs framebuffer) and the _image_file_ should have the same height and width as the MGED display.  The _-t_ option indicates that the image should be projected through the object.  The _-n_ option requests that antialiasing not be 	done. 

== EXAMPLES

!--There are no examples.--> 

== AUTHOR

BRL-CAD Team

== BUG REPORTS

Reports of bugs or problems should be submitted via electronic mail to mailto:devs@brlcad.org[]