include::../header.adoc[]

= QRAY(nged)

== NAME

qray - Gets/sets query ray characteristics.

== SYNOPSIS

*qray* [_subcommand_]

== DESCRIPTION

Gets/sets _query ray_ characteristics. Without a subcommand, the usage
message is printed. The _qray_ command accepts the following
subcommands:

[cmd]*vars*:: Prints a list of all query ray variables.

[cmd]*basename* [_str_]:: If _str_ is specified, then set basename to
_str_.  Otherwise, return the basename. Note that the basename is the
name used to create the fake shape names corresponding to the
query ray. There will be one fake shape for every color used along
the ray.

[cmd]*effects* [_t|g|b_]:: Set or get the type of _effects_ that will
occur when firing a query ray. The effects of firing a ray can be
either _t_ for textual output, _g_ for graphical output, or _b_ for
both textual and graphical.

[cmd]*echo* [_0|1_]:: Sets or gets the value of _echo_.  If set to 1,
the actual [cmd]*nirt* command used will be echoed to the screen.

[cmd]*oddcolor* [_r g b_]:: Sets or gets the color of odd partitions.

[cmd]*evencolor* [_r g b_]:: Sets or gets the color of even
partitions.

[cmd]*voidcolor* [_r g b_]:: Sets or gets the color of areas where the
ray passes through nothing.

[cmd]*overlapcolor* [_r g b_]:: Sets or gets the color of areas that
overlap.

[cmd]*fmt* [_r|h|p|f|m|o_ [_str_]]:: Sets or gets the format
string(s). See the _man_ page of [cmd]*nirt* for more details.

[cmd]*script* [_str_]:: Sets or gets the [cmd]*nirt* script string.

[cmd]*help*:: Prints the usage message.

== EXAMPLES

The four examples show the use of the [cmd]*qray* command without a
subcommand and with three of the listed subcommands.

.Print the usage message.
====
[prompt]#mged># [in]`qray`

Prints the usage message. 
====

.Return the overlap format string.
====
[prompt]#mged># [in]`qray fmt o`

Returns the overlap format string. 
====

.Return the rgb color used to color odd partitions.
====
[prompt]#mged># [in]`qray oddcolor`

Returns the rgb color used to color odd partitions. 
====

.Set the odd partition color to red.
====
[prompt]#mged># [in]`qray oddcolor 255 0 0`

Sets the odd partition color to red. 
====

== AUTHOR

BRL-CAD Team

include::../footer.adoc[]
