include::../header.adoc[]

= RCC-BLEND(nged)

== NAME

rcc-blend - Generates a blend at an end (base [b] or top [t]) of the
specified RCC shape.

== SYNOPSIS

*rcc-blend* {_rccname newname thickness_} [b] [t]

== DESCRIPTION

Generates a blend at an end (base [_b_] or top [_t_]) of the specified
RCC shape. The thickness is the radius of the TOR curvature. The blend
is saved as a region made up of an RCC and a TOR. The default end is
the base.

== EXAMPLES

The two examples show the use of the [cmd]*rcc-blend* command to
generate a blend at the base and at the top of specified RCC shapes.

.Generate a blend at the base of a specified RCC shape.
====
[prompt]#mged># [in]`rcc-blend rcc.s blend.s 10`

Creates a region named _blend.s_ that extends 10 units from the base
of _rcc.s_.
====

.Generate a blend at the top of a specified RCC shape.
====
[prompt]#mged># [in]`rcc-blend rcc.s blend.s 10 t`

Creates a region named _blend.s_ that extends 10 units from the top of
_rcc.s_.
====

== AUTHOR

BRL-CAD Team

include::../footer.adoc[]
