include::../header.adoc[]

= REGIONS(nged)

== NAME

regions - Creates a summary of all the regions in the specified list
of objects.  The summary is written in the specified output_file.

== SYNOPSIS

*regions* {_output_file_} {_objects_}

== DESCRIPTION

Creates a summary of all the regions in the specified list of
_objects_. The summary is written in the specified _output_file_. The
summary includes, for each region, a sequential region number, its
ident, air code, material code, los, the path from one of the
_objects_ to the region, and the Boolean formula for the region.

== EXAMPLES

The example shows the use of the [cmd]*regions* command to create a
summary of the regions that are in the specified objects. The summary
is written in a specified file.

.Create a summary of regions contained in specified objects.
====
[prompt]#mged># [ui]`regions regions_file group1 group2`

Places a summary of all the regions from _group1_ and _group2_ in the
file named _regions_file_.
====

== AUTHOR

BRL-CAD Team

include::../footer.adoc[]
