= REGIONS(nged)
BRL-CAD Team
:doctype: manpage
:man manual: BRL-CAD User Commands
:man source: BRL-CAD
:page-layout: base

== NAME

regions - Creates a summary of all the regions in the specified list of
objects.  The summary is written in the specified output_file.
   

== SYNOPSIS

*[cmd]#regions#*  {[rep]_output_file_} {[rep]_objects_}

== DESCRIPTION

Creates a summary of all the regions in the specified list of __objects__. The summary is written in the specified __output_file__. The summary includes, for each region, a sequential region number, 	its ident, air code, material code, los, the path from one of the _objects_ to the region, and the Boolean formula for the region. 

== EXAMPLES

The example shows the use of the *[cmd]#regions#*  command to create a summary of the regions that are in the specified objects. The summary is written in a specified file. 

.Create a summary of regions contained in specified objects.
====
[prompt]#mged># [ui]`regions regions_file group1 group2` 

Places a summary of all the regions from _group1_ and _group2_ in the file named __regions_file__. 
====

== AUTHOR

BRL-CAD Team

== BUG REPORTS

Reports of bugs or problems should be submitted via electronic mail to mailto:devs@brlcad.org[]