include::../header.adoc[]

= ROTOBJ(nged)

== NAME

rotobj - Rotates the currently edited object by z angle degrees about
the z direction, y angle degrees about the y direction, and x angle
degrees about the x direction in that order.

== SYNOPSIS

*rotobj* [-i] [_x-angle_] [_y-angle_] [_z-angle_]

== DESCRIPTION

Rotates the currently edited object by _z_ angle degrees about the _z_
direction, _y_ angle degrees about the _y_ direction, and _x_ angle
degrees about the _x_ direction in that order. If an _-i_ option is
included, then the rotations are treated as increments to the previous
rotations. MGED must be in the matrix edit mode for this command to be
useful. The [cmd]*p* command provides a similar capability for
primitive editing.

== EXAMPLES

The example shows the use of the [cmd]*rotobj* command to rotate the
currently edited object by a given number of degrees in the _x_, _y_,
and _z_ directions.

.Rotate the current object by a specified number of degrees in the _x, y,_ and _z_ directions.
====
[prompt]#mged># [in]`rotobj 0 0 25`

Rotates the currently edited object by 25° about the _z_ direction
from the original orientation.
====

== AUTHOR

BRL-CAD Team

include::../footer.adoc[]
