include::../header.adoc[]

= SHOWMATS(nged)

== NAME

showmats - Lists the transformation matrices encountered along the
specified path and also lists the accumulated matrix at the end of the
path.

== SYNOPSIS

*showmats* {_path_}

== DESCRIPTION

Lists the transformation matrices encountered along the specified path
and also lists the accumulated matrix at the end of the _path_. If any
member occurs more than once in a combination along the path, then a
matrix will be listed for each occurrence of that member, and the
accumulated matrix will only use the first occurrence. Related
commands are [cmd]*putmat, copymat,* and [cmd]*listeval*.

== EXAMPLES

The example shows the use of the [cmd]*showmats* command to list the
transformation matrices along the specified path and the accumulated
matrix for the entire path.

.List the transformation matrices along a path and the accumulated matrix for the path.
====
[prompt]#mged># [ui]`showmats head/skull/jaw`

Lists the transformation matrices along the path "head/skull/jaw" and
the accumulated matrix for the entire path.
====

== AUTHOR

BRL-CAD Team

include::../footer.adoc[]
