= SUMMARY(nged)
BRL-CAD Team
:doctype: manpage
:man manual: BRL-CAD MGED Commands
:man source: BRL-CAD
:page-layout: base

== NAME

summary - The summary command with no arguments lists the number of primitive shapes, regions, and nonregion combinations in the current database.
   

== SYNOPSIS

*[cmd]#summary#*  [s] [r] [g]

== DESCRIPTION

The *[cmd]#summary#*  command with no arguments lists the number of primitive shapes, regions, and nonregion combinations in the current database. If the _s_ argument is supplied, then the name of each _primitive shape_ is also listed. Similarly, the__r__ flag asks for the _region_ names, and _g_ asks 	for the names of all the combinations (including __region__). The flags may be concatenated 	to get combined output. 

== EXAMPLES

The example shows the use of the *[cmd]#summary#*  command with an argument to list a summary of 	primitive shapes and regions for the current database. 

.List a summary of primitive shapes and regions for the current database.
====
[prompt]#mged># [ui]`summary sr` 

Lists a summary of primitive shapes and regions for the current database. 
====

== AUTHOR

BRL-CAD Team

== BUG REPORTS

Reports of bugs or problems should be submitted via electronic mail to mailto:devs@brlcad.org[]