= TOPS(nged)
BRL-CAD Team
:doctype: manpage
:man manual: BRL-CAD MGED Commands
:man source: BRL-CAD
:page-layout: base

== NAME

tops - Displays a list of all the top-level objects in the current database. 

== SYNOPSIS

*tops*

== DESCRIPTION

Displays a list of all the _top-level_ objects in the current database. The top-level objects are all those 	objects that are not referenced by some other combination. The hierarchical structure of BRL-CAD databases usually means that there will 	be a top-level object that includes all (or at least most) of the objects in the database. 

== EXAMPLES

The example shows the use of the [cmd]*tops* command to list all the top-level objects in the current database. 

.List all the top-level objects in the current database.
====
[prompt]#mged>#[ui]`tops`

Lists all the top-level objects in the current database. 
====

== AUTHOR

BRL-CAD Team

== BUG REPORTS

Reports of bugs or problems should be submitted via electronic mail to mailto:devs@brlcad.org[]