include::../header.adoc[]

= VOXELIZE(nged)

== NAME

voxelize - Takes as input a primitive or a collection of primitives
,old_obj, and creates a region new_obj which is the collection of
voxels(RPPs) approximating the old_obj.

== SYNOPSIS

*voxelize* [[-d] | \{n}] [[-s] | {"%s %s %s"}] [[-t] | \{f}] {_new_obj old_obj_} [_old_obj1 old_obj2 ..._]

== DESCRIPTION

Takes as input a primitive or a collection of primitives , _old_obj_,
and creates a region _new_obj_ which is the collection of voxels(RPPs)
approximating the _old_obj_. The _-d_ option specifies the level of
detail(precision in approximation of volume) required. An argument of
n means that n * n rays will be shot through each row, and an
approximation of volume filled in each voxel region is reached
averaging these n * n values. The _-s_ option lets the user specify
the voxel size in each direction. The _-t_ option specifies the
threshold volume to decide if voxel is to be included in the voxelized
output. The threshold should always be a value between 0 and 1.

== EXAMPLES

The following example shows the use of the [cmd]*voxelize* command to
create a voxelized version of an existing object (_old_object_) and
naming the output(_new_object_).

.Create a voxelized version of an existing primitive or collection.
====
[prompt]#mged># [in]`voxelize -d 2 -s "0.5 0.5 0.5" -t 0.3 newregion.r oldregion.r`

Creates a voxelized region corresponding to the original region
_oldregion.r_.

The region _newregion.r_ consists of the resulting voxels.

The _-d 2_ option means that on each voxel row, 2*2(=4) rays are
uniformly shot over the area and an approximation of the volume is
reached from the raytrace data of these four rays.

_-s "0.5 0.5 0.5"_ sets the size of the voxels as 0.5 units (user's
choice of units) in each dimension.

_-t 0.3_ means that a voxel region is considered to be "filled" if the
approximated volume of _oldregion.r_ filling this voxel region is 30%
of its total volume.
====

== AUTHOR

BRL-CAD Team

include::../footer.adoc[]
