= ZOOM(nged)
BRL-CAD Team
:doctype: manpage
:man manual: BRL-CAD MGED Commands
:man source: BRL-CAD
:page-layout: base

== NAME

zoom - Changes the size of the viewing cube for the MGED display,
resulting in a zoom in or zoom out effect.
   

== SYNOPSIS

*[cmd]#zoom#*  {[rep]_scale_factor_}

== DESCRIPTION

Changes the size of the viewing cube for the MGED display, resulting in a zoom in or zoom out effect. A _scale_factor_ greater than one reduces the size of the viewing cube (zoom in). A _scale_factor_ of less than one increases the size of the viewing cube (zoom out). 

== EXAMPLES

The example shows the use of the *[cmd]#zoom#*  command to reduce the size of the viewing cube by half. 

.Reduce the size of the viewing cube by half.
====
[prompt]#mged># [ui]`zoom 2` 

Reduces the size of the current viewing cube by half (effectively doubling the size of objects in the display). 
====

== AUTHOR

BRL-CAD Team

== BUG REPORTS

Reports of bugs or problems should be submitted via electronic mail to mailto:devs@brlcad.org[]