:doctype: book

*tl;dr* use a http://webchat.freenode.net/[web interface] or install
https://addons.mozilla.org/en-US/firefox/addon/chatzilla/[a Firefox
extension].

= IRC

The BRL-CAD community operates in the *#brlcad* channel on the
Freenode IRC network (irc.freenode.net:6667). The channel serves as a
real-time avenue for interacting with other BRL-CAD users and developers
around the world. This document explains IRC, chatting, and, and
recommended software.

= What is IRC?

IRC stands for Internet Relay Chat. It's a method of communication where
you join a channel to read and write messages to other people in that
channel. It's similar to instant messaging but for chatting with lots of
people simultaneously.

= What is Chatting?

Chatting is _real-time_ *text-based* communication. It's a means to
interact and collaborate with other people that may be on the other side
of the world.

= Why Chat?

* _Fun_: while the focus of the channel is to talk about BRL-CAD,
everyone is there voluntarily. It's a friendly gathering for people
with a common interest.

//

* _Persistence_: IRC has many special features that make it really
easy and convenient to stay interactively engaged in a community.
There are services for registering identities and keeping
discussions under control. You can leave messages for others even if
you don't know their e-mail or phone number. You can keep searchable
transcripts of discussions. You can get involved in discussions that
span minutes, days, or more.

//

* _One to Many_: you're talking with a group of people instantly.
While some people will idly lurk in a channel to only read
discussions, you have the opportunity to interact with many core
project participants including developers to get answers to
questions, leverage the insights of others, and contribute back to
BRL-CAD.

//

* _Commit Notification_: changes to BRL-CAD's source code and changes
to the website are announced in real-time to the IRC channel so you
can see modifications being made to BRL-CAD as they happen.

= IRC Etiquette

If this is your first time using IRC, there are a few things you should
know and expect:

* *Be polite.* Everyone is there voluntarily and not necessarily to
help you. Be nice or leave.

//

* *Be patient.* If you have a question, ask your question and wait.
People are on the channel from time zones around the world so your
question might be read immediately or several hours later. It's
considered rude to ask a question and then leave within a few
minutes.

//

* *Be considerate.* When you connect to a channel, wait a few
minutes to get a feel for any discussions already under way. You do
not need to announce or introduce yourself, but should be mindful to
stay on topic. Don't waste other people's time.

//

* *Ask smart questions.* Don't ask to ask ("Can I ask a question?").
Don't ask if someone is there ("Is John here?"). Ask the real
question you intended to ask them and wait patiently for a response.
See _http://www.catb.org/esr/faqs/smart-questions.html[How to Ask Questions the Smart
Way]_ for more
suggestions.

//

* *Listen and learn.*

= What Software?

Depending on your operating system, there are lots of choices available.
A comprehensive selection of clients can be found in this http://www.ircreviews.org/clients/[IRC client
list].

For the lazy, you could use a http://webchat.freenode.net/[web
interface] or install https://addons.mozilla.org/en-US/firefox/addon/chatzilla/[a Firefox
extension].

'''

This document was based in-part on the http://www.linuxchix.org/irc-beginners.html[LinuxChix IRC for
Beginners] guide. Thanks
ladies!
