= +++<strong>+++Online Geometry viewer for GSOC - 2018 +++</strong>+++

== +++<b>+++Scope for GSoC 2018 +++</b>+++

We have been working on OGV for 5 years. It started with PHP and then
was revamped to meteor.js (before it was cool). This year we want to
focus on the backend of OGV, making sure it works properly, converts the
models properly and basically finishing a version of OGV and launching
it for the masses. So it's going to be a really exciting summer this
year. We have arranged a list of features, bugs, and enhancements that
we think should be handled this year and have put them
(https://github.com/BRL-CAD/OGV-meteor/projects/1?fullscreen=true) here
on github. These issues are arranged via priority, so you will get an
idea about what you can include in your proposal for this summer.

== +++<b>+++Checklist to write proposal for OGV +++</b>+++

* Download and clone OGV from https://github.com/BRL-CAD/OGV-meteor
* Run OGV on your local. Can you find some steps missing in Readme?
* Fork OGV repo
* Choose a couple of +++<b>+++low hanging +++</b>+++ issues, solve then and send
a pull request. More PRs equal better chances of selection!
* +++<b>+++Talk to mentors about your PR +++</b>+++
* Choose list of issues that you would like to solve this summer
* Make sure it contains as
many(https://github.com/BRL-CAD/OGV-meteor/projects/1?fullscreen=true)
high priority issues as possible.
* Did you find a bug? Do you think there's a feature that's really
important but it's not here? Feel free to add it to your proposal.
* Make a detailed weekly plan for your summer. More detailed, the
better. Include why, what and how whenever you can.
* +++<b>+++Share your proposal with your mentors +++</b>+++
* Make any changes if required
* Put the proposal on BRL-CAD wiki
* +++<b>+++Talk about your proposal with your mentors. Get feedback. +++</b>+++
* Submit it to Google Summer of Code website.
