= A Call to Arms (and Contributors)
:doctype: book
:sectnums:
:toc: left
:icons: font
:experimental:
:sourcedir: .

[quote.epigraph,Mike Muuss]
The future exists first in the imagination, then in the will, then in reality.

Welcome to BRL-CAD! Whether you are a developer, documenter, graphic artist, academic, or someone who just wants to be involved in a unique open source project, BRL-CAD has a place for you.
Our contributors come from all over the world and use their diverse backgrounds and talents to help maintain and enhance one of the oldest computer-aided design (CAD) packages used in government and industry today. 

== What is BRL-CAD?

BRL-CAD (pronounced be-are-el-cad) is a powerful, cross-platform, open source solid modeling system that includes interactive three-dimensional (3D) solid geometry editing, high-performance ray tracing support for rendering and geometric analysis, network-distributed framebuffer support, image and signal-processing tools, path tracing and photon mapping support for realistic image synthesis, a system performance analysis benchmark suite, an embedded scripting interface, and libraries for robust high-performance geometric representation and analysis. 

For more than two decades, BRL-CAD has been the primary solid modeling CAD package used by the U.S.
government to help model military systems.
The package has also been used in a wide range of military, academic, and industrial applications, including the design and analysis of vehicles, mechanical parts, and architecture.
Other uses have included radiation dose planning, medical visualization, terrain modeling, constructive solid geometry (CSG), modeling concepts, computer graphics education and system performance benchmark testing. 

BRL-CAD supports a wide variety of geometric representations, including an extensive set of traditional implicit "primitive shapes" (such as boxes, ellipsoids, cones, and tori) as well as explicit primitives made from collections of uniform B-spline surfaces, non-uniform rational B-spline (NURBS) surfaces, n-manifold geometry (NMG), and purely faceted polygonal mesh geometry.
All geometric objects may be combined using boolean set-theoretic CSG operations such as  union, intersection and difference. 

Overall, BRL-CAD contains more than 400 tools, utilities, and applications and has been designed to operate on many common operating system environments, including BSD, Linux, Solaris, Mac OS X, and Windows.
The package is distributed in binary and source code form as Free Open Source Software (FOSS), provided under Open Source Initiative (OSI) approved license terms. 

== History and Vision

BRL-CAD was originally conceived and written by the late Michael Muuss, the inventor of the popular PING network program.
In 1979, the U.S.
Army Ballistic Research Laboratory (BRL) (the agency responsible for creating ENIAC, the world's first general-purpose electronic computer in the 1940s) identified a need for tools that could assist with the computer simulations and analysis of combat vehicle systems and environments.
When no existing CAD package was found to be adequate for this specialized purpose, Mike and fellow software developers began developing and assembling a unique suite of utilities capable of interactively displaying, editing, and interrogating geometric models.
Those early efforts subsequently became the foundation on which BRL-CAD was built. 

Development of BRL-CAD as a unified software package began in 1983, and its first public release came in 1984.
Then, in 2004, BRL-CAD was converted from a limited-distribution U.S.
government-controlled code to an open source project, with portions licensed under the LGPL and BSD licenses. 

Today, the package's source code repository is credited as being the world's oldest, continuously developed open source repository.
As a project, pride is taken in preserving all history and contributions. 

The ongoing vision for BRL-CAD development is to provide a robust, powerful, flexible, and comprehensive solid modeling system that includes: 

* Faithful high-performance geometric representation.
* Efficient and intuitive geometry editing.
* Comprehensive conversion support for all solid geometry formats.
* Effective geometric analysis tools for 3D CAD.


== Key Strengths

All CAD packages are not alike.
Among the many strengths of the BRL-CAD package are the following: 

* BRL-CAD is _open source!_ Don't like something? You can make it better.
* You can leverage __decades of invested development__. BRL-CAD is the most feature-filled open source CAD system available, with hundreds of years time invested.
* __Your work will get used__. BRL-CAD is in production use and downloaded thousands of times every month by people all around the world.
* You have the ability to create extensively __detailed realistic models__.
* You can model objects on scales ranging from (potentially) the subatomic through the galactic, while essentially providing __all the details, all the time__.
* You can leverage _one of the fastest_ raytracers in existence (for many types of geometry).
* You can convert to and from a wide range of __geometry file formats__.
* BRL-CAD has a powerful, _customizable scripting interface_ with many advanced editing and processing capabilities.


== Want to Be a Contributor?

With BRL-CAD being a part of the open source community since 2004, contributors from all over the world are able to enhance the features and functions of the package in many different ways.
In return, these contributors have had a unique opportunity to: 

* Join a team of passionate and talented contributors who share the common values of open source development. Open source emphasizes free redistribution; openly available source code; full, open participation; and nondiscrimination against individuals, groups, technologies, or fields of interest. (To learn more, see http://opensource.org.)
* Drive needed improvements in the open source software community's support for solid modeling and CAD software capabilities.
* Experiment with new and state-of-the-art algorithms and ideas within the context of a fully open CAD system that is in production use and has an established user community.
* Become a better developer. Whether you're a newbie or a seasoned developer with decades of experience, you can always work on a BRL-CAD project that is catered toward improving your abilities.
* Become part of a legacy. Participate in a robust and historically significant open source project that goes all the way back to the days of the DEC PDP-11/70 and VAX-11/780.
* Gain practical experience working on a real-world, large-scale software project.

If you would like to be a BRL-CAD contributor, the primary areas currently identified for future development and enhancement include the following: 

* _Improved graphical user interface and usability_ to accommodate increasingly varied user needs and participation levels. This includes improving the look-and-feel and features of: 
+
** the primary editing graphical interface (MGED)
** the geometric visualization and interaction management system (libdm).
* _Improved hybrid boundary representation geometry support_ to support all 3D CAD models regardless of whether they use implicit or explicit geometric representation. Geometry formats we are particularly focusing on include: 
+
** volumetric models (VOL)
** spline-surface (for example, NURBS) and polygonal (for example, triangle mesh) boundary representations (BREP)
** implicit primitives.
* _Improved geometry services and functionality,_ including the ability to provide: multiuser access controls 
+
** comprehensive revision history
** collaborative enhanced multiuser modeling
** more flexible application development.
* In addition, BRL-CAD's existing geometry kernel functions are continuously being refactored. Help turn them into a comprehensive, scriptable command framework, create an object-oriented geometry kernel application programming interface (API), or build a lightweight network daemon protocol for language agnostic client application development.
* _Improved open source awareness and increased development participation_ via: 
+
** establishing strong open source community ties
** improving software documentation
** openly welcoming new contributors and users.

Let the contributions begin! 