include::../header.adoc[]

= BW-PS(1)

== NAME

bw-ps - convert a black and white bw file to PostScript

== SYNOPSIS

*bw-ps* [-e] [-c] [-L] [-s _input_squaresize_] [-w _input_width_] [-n _input_height_] [-S _inches_square_] [-W _inches_width_] [-N _inches_height_] [_infile.bw_] > _outfile.ps_

== DESCRIPTION

*bw-ps* will take a black and white xref:man:5/bw.adoc[*bw*(5)] format
file of given dimensions and produce a Postscript file on the standard
output. The [opt]*-w* and [opt]*-n* flags specify the input file width
and number of scan lines in pixels. They can both be set to the same
value via [opt]*-s.* If no input size is given, defaults of 512 are
assumed.

By default the output PostScript image size is 6.75 inches. The
[opt]*-c* option will center it on a 8.5 x 11 inch page. If a
different output size is desired, [opt]*-S* [opt]*-W* and [opt]*-N*
can be used to set the size in inches analogous to the input
parameters. Finally, [opt]*-L* selects landscape mode, i.e. rotates
the output image by ninety degrees.

Encapsulated PostScript files can be generated via [opt]*-e*.

== EXAMPLES

....
bw-ps -c _image.bw_ > _image.ps_
....

Produces a 6.75 inch PostScript file from an 512 x 512 input image and
centers it on an 8.5 x 11 inch page.

....
bw-ps -e -w 1024 -n 768 _image.bw_ > _image.ps_
....

Takes the file image.bw which has the dimensions of 1024 pixels wide
by 768 pixels high, and produces an Encapsulated Postscript version
of it.

....
bw-ps -L -c -S 5.2 < _image.bw_ > _image.px_
....

Makes a PostScript file of the (assumed 512 square) image, with the
output image 5.2 inches square, in landscape mode, centered on an 8.5
x 11 inch page.

== SEE ALSO

xref:man:1/brlcad.adoc[*brlcad*(1)], xref:man:5/bw.adoc[*bw*(5)]

== AUTHOR

BRL-CAD Team

include::../footer.adoc[]
