include::../header.adoc[]

= DBCLEAN(1)

== NAME

dbclean - a shell script for compacting mged databases.

== SYNOPSIS

*dbclean* _in_model.g_ _out_model.g_

== DESCRIPTION

[cmd]*dbclean* operates on the indicated input database _in_model.g_
and produces a compacter version of the same as _out_model.g_.

The objective is to remove "holes" in the original database which
resulted from use of the __kill__/__killall__ commands in
xref:man:1/mged.adoc[*mged*(1)]. Note that when a database is
compacted in this manner, the compacting is dependent on the
successful completion of the converters
xref:man:1/g2asc.adoc[*g2asc*(1)] and
xref:man:1/asc2g.adoc[*asc2g*(1)]. The compacting will only be aborted
if one of the conversions fails.  Thus, when either converter "skips"
solids, [cmd]*dbclean* will continue, and _out_model.g_ will be
written, albeit without the skipped solids.  This will also result in
a smaller database.

== EXAMPLE

This section will acquaint the user with the ordinary usage of
[cmd]*dbclean*.

....
dbclean in_model.g out_model.g
....

This will result in a compacted version of the input.

== SEE ALSO

xref:man:1/mged.adoc[*mged*(1)]

== DIAGNOSTICS

Numerous error conditions are possible, usually due to errors in the
geometry database. Descriptive messages are printed on standard error
(file descriptor 2).

== BUGS

Most deficiencies observed while using the [cmd]*dbclean* program are
usually with the xref:man:1/g2asc.adoc[*g2asc*(1)] and
xref:man:1/asc2g.adoc[*asc2g*(1)] packages instead.

== AUTHOR

_BRL-CAD Team_

include::../footer.adoc[]
