include::../header.adoc[]

= G-ACAD(1)

== NAME

g-acad - Convert from BRL-CAD format to Lockheed Martin's ACAD format

== SYNOPSIS

*g-acad* [-vi] [-xX _lvl_] [-e _error_file_] [-D _calculation_tolerance_] [-a _abs_tol_] [-r _rel_tol_] [-P _number_of_CPUs_] [-n _norm_tol_] [-o _ACAD_file_] _database.g_ _object(s)_

== DESCRIPTION

[cmd]*g-acad* converts the specified _object(s)_ from a BRL-CAD
_database.g_ file to the in-house Lockheed Martin's Advanced
Computer-Aided Design _(ACAD)_ file format (formerly the General
Dynamics ACAD file format).  This converter has NOT connected with
Autodesk Inc.'s AutoCAD file format. The [opt]*-x* option specifies an
RT debug flag and the [opt]*-X* option specifies an NMG debug
flag. The [opt]*-a* , [opt]*-r* , and [opt]*-n* options specify
tessellation tolerances. The [opt]*-D* option specifies a
calculational distance tolerance (mm). Any two vertices that are less
than this distance apart will be treated as the same vertex. The
[opt]*-v* option requests verbose output. The [opt]*-i* option
requests the output file units to be inches (the default is mm). The
[opt]*-o* option specifies the name of the file to receive the output
(stdout is the default). The [opt]*-e* option specifies a file for
receiving the error messages. The [opt]*-P* option specifies the
number of CPU's to be used, and also turns on a flag to enable the
receiving of core dumps.

== EXAMPLE

....
$ g-acad -o sample.ACAD sample.g sample_object
....

== DIAGNOSTICS

Error messages are intended to be self-explanatory.

== AUTHOR

BRL-CAD Team

include::../footer.adoc[]
