include::../header.adoc[]

= G-DXF(1)

== NAME

g-dxf - AutoCad DXF Translator (BRL-CAD to DXF)

== SYNOPSIS

*g-dxf* [-v] [-i] [-p] [-xX _lvl_] [-D _calculation_tolerance_] [-a _abs_tol_] [-r _rel_tol_] [-n _norm_tol_] [-P _dummy_arg_] [-o _DXF_file_] _database.g_ _object(s)_

== DESCRIPTION

[cmd]*g-dxf* converts the specified _object(s)_ from a BRL-CAD
_database.g_ file to the _AutoCad DXF_ file format. The [opt]*-x*
option specifies an RT debug flag and the [opt]*-X* option specifies
an NMG debug flag. The [opt]*-a* option may be used to specify an
absolute tessellation tolerance (in millimeters). This requires that
the maximum absolute error from the tessellated surface to the actual
surface must not be greater than _abs_tol_. The [opt]*-n* option
specifies a surface normal error tolerance (in degrees) for the
tessellation. The [opt]*-r* option may be used to set a relative error
tolerance. This effectively sets an absolute tolerance for each
primitive solid by multiplying the overall size of the solid by
_rel_tol_. The [opt]*-D* option specifies a calculational distance
tolerance (mm). Any two vertices that are less than this distance
apart will be treated as the same vertex. The [opt]*-v* option
requests verbose output. The [opt]*-i* option requests the output file
units to be inches (the default is mm). The [opt]*-p* option requests
that the output consist entirely of POLYFACE MESH entities. (The
default is all 3DFACE entities.) The [opt]*-P* option is to enable
core dumps (dummy argument is for number of processors, currently
disabled). The [opt]*-o* option specifies the name of the file to
receive the output (stdout is the default).

== EXAMPLE

....
$ g-dxf -o sample.dxf sample.g sample_object
....

== DIAGNOSTICS

Error messages are intended to be self-explanatory.

== AUTHOR

BRL-CAD Team

include::../footer.adoc[]
