include::../header.adoc[]

= PLOT3LINE2(1)

== NAME

plot3line2 - output a 2D UnixPlot line

== SYNOPSIS

*plot3line2* _x1_ _y1_ _x2_ _y2_ [_r_ _g_ _b_] [<] _unix_plot_ > _unix_plot_

== DESCRIPTION

[cmd]*plot3line2* outputs a UnixPlot command to draw a line in the XY
plane from the point (_x1 y1_) to the point (_x2 y2_). These points
can be floating point and the output is always written as a floating
point plotting command.  If you need an integer command then feed the
output of this through
xref:man:1/plot3-plot3.adoc[*plot3-plot3*(1)]. If an optional [_r g
b_] is given, where _r_, _g_, and _b_ are values from 0 to 255
representing Red, Green, and Blue color values, the line will be drawn
in that color.  Otherwise the current drawing color (white by default)
is used.

To allow this command to be used in pipelines, an optional input file
can be given.  All of the input will be passed through until end of
file, and then the line will be appended to the end.

This command exists mostly as an aid for making graphs and things from
shell commands.

== SEE ALSO

xref:man:1/plot3color.adoc[*plot3color*(1)],
xref:man:1/plot3-plot3.adoc[*plot3-plot3*(1)],
xref:man:5/plot3.adoc[*plot3*(5)]

== AUTHOR

BRL-CAD Team

include::../footer.adoc[]
