include::../header.adoc[]

= STL-G(1)

== NAME

stl-g - Stereolithography Translator (STL to BRL-CAD)

== SYNOPSIS

*stl-g* [-db] [-i _initial_ident_] [-I _constant_ident_] [-m _material_code_] [-N _forced_name_] [-c _units_] [-t _tolerance_] [-x _RT_DEBUG_FLAG_] _file.stl_ _file.g_

== DESCRIPTION

[cmd]*stl-g* converts the specified _file.stl_ to a BRL-CAD _file.g_
file. Use the [opt]*-b* option if you have a binary STL file (the
default is ASCII). The [opt]*-d* option prints debugging
information. The [opt]*-c* option specifies the units that are used in
the STL file. The _units_ string may be "mm", "in", "ft", ... (default
is "mm"). The [opt]*-t* option specifies a tolerance distance (in mm)
such that any two vertices within tolerance distance of each other are
treated as the same vertex. The [opt]*-i* option sets the starting
ident number for the regions created. As each new region is created,
this number will be incremented before assigning the next ident number
(conflicts with [opt]*-I* ). The [opt]*-I* option sets a constant
ident number that will be assigned to all the regions created
(conflicts with [opt]*-i* ). The [opt]*-m* option sets a material code
that will be assigned to all the regions created (default is 1). The
[opt]*-N* option sets a name for the resulting BRL-CAD object. STL
files typically do not contain any object names. The [opt]*-x* option
sets an RT debug flag (see raytrace.h). The _file.stl_ file is
expected to be a stereolithography file.

== EXAMPLE

....
$ stl-g sample.stl sample.g
....

== DIAGNOSTICS

Error messages are intended to be self-explanatory.

== AUTHOR

BRL-CAD Team

include::../footer.adoc[]
