include::../header.adoc[]

= TANKILL-G(1)

== NAME

tankill-g - TANKILL Translator (TANKILL to BRL-CAD)

== SYNOPSIS

*tankill-g* [-n] [-t _tolerance_] [-i _input_tankill_file_] [-o _database.g_]

== DESCRIPTION

[cmd]*tankill-g* converts the specified _input_tankill_file_ to a
BRL-CAD _database.g_ file. The _tolerance_ provided is the maximum
distance (in mm) between two vertices at which they will be considered
to be the same vertex. The [opt]*-n* option provides output in the
form of NMG primitives rather than the default which is BOT
objects. The _input_tankill_file_ is expected to be in the _TANKILL_
format used by the British Defense Research Agency. This is a simple
triangular patch format where each object is described by a series of
vertices. Triangular facets are built from the first, second, and
third vertices; from the second, third, and fourth vertices; from the
third, fourth and fifth; and so on. Each object is converted to a
single BOT object which is then placed into its own region and
assigned the component code provided in the TANKILL file.

== EXAMPLE

....
$ tankill-g sample.tankill sample.g
....

== DIAGNOSTICS

Error messages are intended to be self-explanatory.

== AUTHOR

BRL-CAD Team

include::../footer.adoc[]
