= LIBDM 

       Robert
   G. Parker
 <mulferts@austin.dsccc.com>
:doctype: book
:sectnums:
:toc: left
:icons: font
:experimental:

== Preface 

=== Unknown Title!

LIBDM provides the <<_api, API>> for accessing BrlCad's display managers. Display managers can be thought of as configurable drawing machines that grind away on generic drawing commands called vlists resulting in display manager specific drawing actions. Vlists are capable of specifying points, lines and polygons in 3D. Display managers are also capable of drawing 2D points, lines, and strings. 

The following DM (display manager) types are supported: 



.Key Frame
[cols="1,1", frame="all", options="header"]
|===
| DM Type
| Canvas Type

|X
|X window

|ogl
|mixed X/OpenGL window

|ps
|postscript file

|plot
|unix plot file
|===

== Application Programming Interface 

[[_api]]
=== LIBDM's Application Programming Interface 

_struct dm *_**DM_OPEN**__( int dtype, int argc, char *argv[] )__

_DM_OPEN_ creates a display manager of type _dtype_ and returns a pointer to its _dm_ structure. _argc_ and _argv_ are passed to <<_dm_p,dm_processOptions>> for interpretation.__DM_NULL__ is returned if unable to acquire a display manager. 


[source]
----

    int dtype;
    int argc;
    char *argv[];
    struct dm *dmp;

    /*
     * Open a 512x512 X display manager window on the local
     * display using my_default_bindings to set default key
     * and mouse button bindings.
     */
    dtype = DM_TYPE_X;
    argv[0] = "X_open";
    argv[1] = "-i";
    argv[2] = "my_default_bindings";
    argv[3] = "-S";
    argv[4] = "512";
    argv[5] = "-d";
    argv[6] = ":0";
    argv[7] = (char *)NULL;
    dmp = DM_OPEN(dtype, argc, argv);
----

_int_**DM_CLOSE**__( struct dm *dmp )__

_DM_CLOSE_ closes the display manager indicated by__dmp__. 


[source]
----

            /* open a display manager */
    dmp = DM_OPEN(dtype, argc, argv);

              .  .  .

    /* close the display manager */
    DM_CLOSE(dmp);
----

_int_**DM_DRAW_BEGIN**__( struct dm *dmp )__

_DM_DRAW_BEGIN_ prepares the display manager indicated by _dmp_ for a round of drawing. 


[source]
----

            /* begin another drawing sequence */
    (void)DM_DRAW_BEGIN(dmp);
----

_int_**DM_DRAW_END**__( struct dm *dmp )__

_DM_DRAW_END_ ends the drawing sequence for the display manager indicated by __dmp__. This should be called before the next call to _<<_dm_draw_begin, DM_DRAW_BEGIN>>_ in order to see the results of the current drawing sequence. 


[source]
----

          /* end the current drawing sequence */
    (void)DM_DRAW_END(dmp);
----

_int_**DM_NORMAL**__( struct dm *dmp )__

_DM_NORMAL_ restores the display manager indicated by _dmp_ to a normal mode of operation (i.e. not scaled, rotated, displaced, etc.). 


[source]
----

            /* restore to normal mode */
    (void)DM_NORMAL(dmp);
----

_int_**DM_LOADMATRIX**__( struct dm *dmp, mat_t mat, int which_eye )__

_DM_LOADMATRIX_ loads the display manager indicated by _dmp_ with a new transformation matrix. _mat_ indicates the matrix to be loaded.__which_eye__ denotes the eye the matrix applies to and can have a value of 0 to indicate non-stereo, a value of 1 to indicate the right eye, or a value of 2 to indicate the left eye. 


[source]
----

              /* load the display manager with mat --- not using stereo */
    (void)DM_LOADMATRIX(dmp, mat, 0);
----

_int_**DM_DRAW_STRING_2D**__( struct dm *dmp, char *str, int x, int y, int size, int use_aspect )__

_DM_DRAW_STRING_2D_ draws a string in the display manager window indicated by __dmp__. _str_ is a pointer to the string to be drawn. x and y indicate where to begin drawing the string and are expected to be in the range [-2048,2047]. The _size_ argument indicates the font size to use (currently used only by dm-ps). The expected values for _size_ are 0 for small, 1 for medium, 2 for large, and 3 for huge.__use_aspect__ indicates whether to use the aspect ratio to modify the starting point where the string will be drawn. 


[source]
----

          /*
     * - draw the string starting at the lower left corner
     * - use the small font
     * - don't use aspect ratio to modify string placement
     */
    (void)DM_DRAW_STRING_2D(dmp, "starting string at lower left", -2040, -2040, 0, 0)
----

_int_**DM_DRAW_LINE_2D**__( struct dm *dmp, int x1, int y1, int x2, int y2 )__

_DM_DRAW_LINE_2D_ is used to draw two-dimensional lines in the display manager window indicated by _dmp. x1, y1, x2,_ and _y2_ indicate the coordinates for the line to be drawn. 


[source]
----

          /* draw a line from the lower left corner of the window to the upper right corner */
    (void)DM_DRAW_LINE_2D(dmp, -2048, -2048, 2047, 2047);
----

_int_**DM_DRAW_POINT_2D**__( struct dm *dmp, int x, int y )__

_DM_DRAW_POINT_2D_ draws a point in the display manager window indicated by __dmp__.__x__ and _y_ indicate the coordinates for the point to be drawn. 


[source]
----

          /* draw a yellow dot in the center of the window */
    (void)DM_SET_FGCOLOR(dmp, 230, 230, 0, 1);
    (void)DM_DRAW_POINT_2D(dmp, 0, 0);
----

_int_**DM_DRAW_VLIST**__( struct dm *dmp, struct rt_vlist *vp )__

_DM_DRAW_VLIST_ takes the vlist pointer _vp_ and interprets it for drawing into the display manager window indicated by __dmp__. 


[source]
----

          /* draw the vlists pointed to by view_list_ptr */
    (void)DM_DRAW_VLIST(dmp, view_list_ptr);
----

__int__**DM_SET_FGCOLOR**__( struct dm *dmp, short r, short g, short b, int strict )__

_DM_SET_FGCOLOR_ sets the color for drawing in the display manager indicated by __dmp__.__r, g,__ and _b_ denote the color and have values in the range [0,255].__Strict__ specifies to really use this color (i.e. don't allow ogl to do fancy things with the color when depth cueing). 


[source]
----

          /* set the drawing color to red */
    (void)DM_SET_FGCOLOR(dmp, 220, 0, 0, 1);
----

__int__**DM_SET_BGCOLOR**__( struct dm *dmp, short r, short g, short b )__

_DM_SET_BGCOLOR_ sets the background color for the display manager indicated by _dmp. r, g,_ and _b_ denote the color and have values in the range [0,255]. 


[source]
----

          /* set the background color to red */
    (void)DM_SET_BGCOLOR(dmp, 220, 0, 0);
----

_int_**DM_GET_BGCOLOR**__( struct dm *dmp, Tcl_Interp *interp )__

_DM_SET_BGCOLOR_ gets the background color for the display manager indicated by _dmp_ and places the result in interp. 


[source]
----

          /* get the background color */
    return DM_GET_BGCOLOR(dmp, interp);
----

_int_**DM_SET_LINE_ATTR**__( struct dm *dmp, int width, int style )__

_DM_SET_LINE_ATTR_ sets the display managers (i.e. dmp) line width to width and sets its line style to__style__. Currently, there are only 2 valid values for _style: 0_ for solid lines and 1 for dashed lines. 


[source]
----

          /* set the display manager up to draw fat dashed lines */
    (void)DM_SET_LINE_ATTR(dmp, 10, 1);
----

_int_**DM_SET_WIN_BOUNDS**__( struct dm *dmp, int clip[6] )__

_DM_SET_WIN_BOUNDS_ sets the view clipping planes for the display manager indicated by__dmp. clip__ is interpreted as follows: {XMIN, XMAX, YMIN, YMAX, ZMIN, ZMAX} 


[source]
----

          int clip[6] = { -2048, 2047, -2048, 2047, -2048, 2047 };

    /* set the display managers clipping planes */
    (void)DM_SET_WIN_BOUNDS(dmp, clip);
----

_int_**DM_ENDDLIST**__( struct dm *dmp )__

_DM_ENDDLIST_ ends the definition of the display list currently being defined for the display manager indicated by __dmp__. 


[source]
----

          /* define display list 1 to draw objects */
    (void)DM_BEGINDLIST(dmp, 1);

    /* Put code to draw objects here */

    (void)DM_ENDDLIST(dmp);
----

__int__**DM_DRAWDLIST**__( struct dm *dmp, unsigned int list )__

_DM_DRAWDLIST_ draws the previously defined display list list in the display manager indicated by __dmp__. 


[source]
----

          unsigned int i;

    /* draw display lists 1 through 9 */
    for (i = 1; i < 10; ++i)
       (void)DM_DRAWDLIST(dmp, i);
----

_int_**DM_FREEDLISTS**__( struct dm *dmp, unsigned int list, int range )__

_DM_FREEDLISTS_ frees the display lists indicated by__list and range. list__ indicates the display list to start with and range indicates the number of display lists to be freed. 


[source]
----

       /* free display lists 10 through 29 */
    (void)DM_FREEDLISTS(dmp, 10, 20);
----

=== LIBDM's Other Support Routines 

_int_**dm_share_list**__( struct dm *dmp1, struct dm *dmp2 )__

_dm_share_dlist_ provides a way to (un)share display lists. If dmp1 and dmp2 are not NULL, dmp1 will share its display lists with dmp2. If dmp2 is NULL, dmp1 will no longer share its display lists. 

_void_**dm_fogHint**__( struct dm *dmp, int fastfog )__

_dm_fogHint_ is used to give a hint to the display manager about whether to use an efficient fog calculation method or the most accurate. Note - this is currently only implemented by the ogl display manager. 


[source]
----

              /* use the most efficient method for calculating fog */
    dm_fogHint(dmp, 1);

    /* use the most accurate method for calculating fog */
    dm_fogHint(dmp, 0);
----

_int_**dm_limit**__( val )__

_dm_limit_ takes an integer argument and returns zero if (NOISE <= val < = NOISE)  where NOISE is the size of the dead spot around zero. If ( val < -NOISE ), the return value is__( val + NOISE )__. If _( NOISE < val ),_ the return value is _( val - NOISE )._


[source]
----

              /* The examples below assume that NOISE is 16 */

    /* i = 0 */
    i = dm_limit(16);

    /* i = 1 */
    i = dm_limit(17);

    /* i = 0 */
    i = dm_limit(-16);

    /* i = -1 */
    i = dm_limit(-17);
----

_int_**dm_unlimit**__( val )__

_dm_unlimit_ takes an integer value and returns zero if _( val == 0 )._ If _( 0 < val ),_ the return value is _( NOISE + val ). If ( val < 0 ),_ the return value is__( -NOISE + val ).__ In short, dm_unlimit puts NOISE back into val. 


[source]
----

            /* i = 0 */
    i = dm_unlimit(0);

    /* i = 17 */
    i = dm_unlimit(1);

    /* i = -17 */
    i = dm_unlimit(-1);
----

_fastf_t_**dm_wrap**__( val )__

_dm_wrap_ wraps__val__ into the range [-1.0, 1.0]. 


[source]
----

              /* f = 0.9 */
    f = dm_wrap(0.9);

    /* f = -0.5 */
    f = dm_wrap(1.5);

    /* f = 0.0 */
    f = dm_wrap(6.0);

    /* f = 1.0 */
    f = dm_wrap(7.0);

    /* f = 0.5 */
    f = dm_wrap(-1.5);

    /* f = -1.0 */
    f = dm_wrap(-5.0);
----

_int_**dm_processOptions**__(struct dm *dmp, struct bu_vls *vls, int argc, char *argv[])__

_dm_processOptions_ is used primarily by LIBDM's display manager open routines to process options. The table below lists the available options. Note - the application would not typically call processOptions. The application would instead build the desired options into the argv list that is supplied to the call to DM_OPEN. 



.Key Frame
[cols="1,1", frame="all", options="header"]
|===
| Options
| Description

|-d string
|This option specifies where to draw the display manager. string is expected to be in the same form as the X DISPLAY environment variable.

|-i init_script
|This option specifies a Tcl script to use to initialize the display manager.

|-N height
|This option specifies the number of scanlines or height to make the display manager window.

|-n name
|This option specifies a name to use for the display manager.

|-S size
|This option specifies the display manager windows square size.

|-s
|This option turns on stereo mode and is currently only available with the ogl display manager.

|-t 0\|1
|This option specifies whether the display manager window will be a top level window or an embedded window. A non-zero value indicates a top level window, while zero indicates an embedded window.

|-W width 
|This option specifies the width in pixels of the display manager window.
|===

_void_**dm_configureWindowShape**__( dmp )__

_dm_configureWindowShape_ is used to update the internal state of a display manager after its window has been newly created or resized. This routine is typically called by an event handler. 

_void_**dm_zbuffer**__( struct dm *dmp, zbuffer_on )__

_dm_zbuffer_ is used to turn Z-buffering on/off. Note - zbuffering is only supported by the__ogl__ display manager. 


[source]
----

              /* turn zbuffering on */
    dm_zbuffer(dmp, 1);
----

_void___dm_lighting____( struct dm *dmp, int lighting_on )__

_dm_lighting_ is used to turn lighting on/off. Note - lighting is only supported by the ogl display manager. 


[source]
----

              /* turn lighting on */
    dm_lighting(dmp, 1);
----

_fastf_t_**dm_Xx2Normal**__( struct dm *dmp, int x )__

_dm_Xx2Normal_ takes x in X screen coordinates and returns a value in the range [-1.0, 1.0]. dmp indicates the display manager of interest. 

_fastf_t_**dm_Xy2Normal**__( struct dm *dmp, int y, int use_aspect )__

_dm_Xy2Normal_ takes y in X screen coordinates and returns a value in the range [-1.0, 1.0].__dmp__ indicates the display manager of interest. _use_aspect specifies_ whether to use the window's aspect ratio in the calculation. 

_int_**dm_Normal2Xx**__( struct dm *dmp, fastf_t x )__

_dm_Normal2Xx_ takes x in normalized coordinates and returns a value in X screen coordinates.__dmp__ indicates the display manager of interest 

_int_**dm_Normal2Xy**__( struct dm *dmp, fastf_t y )__

_dm_Normal2Xy_ takes y in normalized coordinates and returns a value in X screen coordinates.__dmp__ indicates the display manager of interest. 

_int_**Dm_Init**__( Tcl_Interp *interp )__

_Dm_Init initializes_ LIBDM's tcl commands.__interp__ indicates the Tcl interpreter. 

=== LIBDM's Tcl Interface 

*dm_bestXType*__display__

_dm_bestXType_ returns the best available display manager type that can be used on the X server indicated by __display__.__Display__ is specified the same and has the same meaning as the X DISPLAY environment variable. 

*dm_validXType*__display dtype__

_dm_validXType_ returns 1 if dtype is a valid display manager type for the X server indicated by__display__. Otherwise, 0 is returned.__Display__ is specified the same and has the same meaning as the X DISPLAY environment variable. 

== Display Manager Objects

=== NAME 

dm_open - create and manipulate a display manager object. 

=== SYNOPSIS 

*dm_open* [__pathName__ type [options]] 

=== COMMAND LINE OPTIONS 

Option: 

*-N*__height__

Specifies the window's height (i.e. number of raster lines). 

Option: 

*-W*__width__

Specifies the window's width. 

Option: 

*-S*__size__

Specifies the window's square size (i.e. width and height). 

Option: 

*-i*__initproc__

Specifies the initialization proc. This proc is called with the pathName as an argument. 

Option: 

*-t*__0|1>__

Specifies the toplevel flag. 0 indicates the display manager object is an internal window, while 1 indicates a toplevel window. 

Option: 

*-d*__dpy__

Specifies the display string in a format understood by X windows. 

=== DESCRIPTION 

The dm_open command creates a new window (given by the pathName argument) and makes it into a display manager object for displaying geometry. Additional options, described above, may be specified on the command line to configure aspects of the display manager object. The dm_open command returns its pathName argument. At the time this command is invoked, there must not exist a window named pathName, but pathName's parent must exist. 

=== METHODS 

The *dm_open* command creates a new Tcl command whose name is pathName. This command may be used to invoke various operations on the display manager object. It has the following general form: 

_pathName option ?arg arg ...?_

Option and the args determine the exact behavior of the command. The following commands are possible for display manager objects: 

_pathName_**bg ["r g b"]**

Set/get the background color. The rgb components are expected to be integers between 0 and 255. pathName bounds [xmin xmax ymin ymax zmin zmax] 

Set/get the window bounds. Some display managers use this to calculate clipping planes (i.e. X). 

_pathName_**clear**

Clear the drawing area using the background color. 

_pathName_**close**

Close the display manager object. 

_pathName_**configure**

Called to handle Configure events. 

_pathName_**debug [0|1]**

Set/get debug mode. 0 indicates debugging is off while 1 indicates debugging is on. 

_pathName_**drawBegin**

Begin the drawing sequence. 

_pathName_**drawEnd**

End the drawing sequence. This will cause the graphics pipe to be flushed. 

_pathName drawGeom_**geo_obj(s)**

Draw one or more drawable geometry objects. 

_pathName_**drawLine x1 y1 x2 y2**

Draw the 2D line indicated by endpoints (x1, y1) and (x2, y2). The given coordinates are expected to be in the range [-1, 1]. 

_pathName_**drawPoint x y**

Draw the 2D point at position (x, y). 

_pathName_**drawSList slp**

Draw the solid list specified by the solid list pointer (i.e.slp). 

_pathName_**drawString str x y size use_aspect**

Draw the 2D string starting at position (x, y). The x and y coordinates are expected to be in the range [-1, 1]. The size is currently ignored. The use_aspect flag indicates whether or not to use the aspect ratio to modify the starting position. 

_pathName_**drawVList vlp**

Draw the vector list specified by the vector list pointer (i.e.vlp). 

_pathName_**fg ["r g b"]**

Set/get the foreground color. The rgb components are expected to be integers between 0 and 255. 

_pathName_**flush**

Flushes the X server's request buffer. 

_pathName_**get_aspect**

Get the window's aspect ratio (i.e. width / height). 

_pathName_**light [0|1]**

Set/get light mode. 0 indicates light is off while 1 indicates light is on. 

_pathName_**linestyle [0|1]**

Set/get linestyle. 0 indicates solid lines while 1 indicates dashed lines. 

_pathName_**linewidth [width]**

Set/get linewidth. This setting determines how fat to draw the wireframe lines. 

_pathName_**listen [port]**

Set/get the port used to listen for framebuffer clients. Port values less than zero turn off listening. 

_pathName_**loadmat mat**

Load the matrix, mat, into the display manager. This is typically a model2view matrix. 

_pathName_**normal**

Restore display manager to a normal mode of operation (i.e. not scaled, rotated, displaced, etc.). 

_pathName_**observer [subcommand]**

This command is used to maintain a list of observers. Observers are objects who have registered an interest in when this display manager object receives pixels in its role as a framebuffer server. Whenever pixel data is received the observers on the list are notified. 

_pathName_**observer attach obs [command]**

Add the specified observer, obs, to the list of observers. If command is specified then it is executed each time pixel data is received. Otherwise, the observer is expected to have an update method which is called with the name of this display manager object as an argument. 

_pathName observer detach obs_

Remove the specified observer, obs, from the list of observers. 

_pathName_**observer show**

Return the list of observers for this display manager object. 

_pathName_**perspective [0|1]**

Set/get perspective mode. 0 indicates perspective is off, while 1 indicates perspective is on. 

_pathName_**refreshfb**

Draws/displays the pixels stored in the widget's framebuffer. 

_pathName_**size [width height]**

Set/get the window size. 

_pathName_**sync**

Flushes the X server's request buffer and waits until all events have been processed. 

_pathName_**zbuffer [0|1]**

Set/get zbuffer mode. 0 indicates that zbuffer is off, while 1 indicates zbuffer is on. 

_pathName_**zclip [0|1]**

Set/get zclipping mode. 0 indicates zclipping is off, while 1 indicates zclipping is on. 


[source]
----

The following sequence creates a display manager object and draws two yellow lines that connect the opposite corners of the window.
cwish> dm_open .d X -t 0 -s 400
.d
cwish> pack .d -expand yes -fill both
cwish> .d drawBegin
cwish> .d fg "255 255 0"
cwish> .d drawLine -1 1 1 -1
cwish> .d drawLine -1 -1 1 1
cwish> .d drawEnd
----