= LIBPLOT3(3)
BRL-CAD Team
:doctype: manpage
:man manual: BRL-CAD
:man source: BRL-CAD
:page-layout: base

== NAME

libplot3 - graphics interface subroutines

== SYNOPSIS


[source,c]
----
void pl_3box (FILE *fp,
              int x0,
              int y0,
              int z0,
              int x1,
              int y1,
              int z1);
----

== DESCRIPTION

These subroutines generate graphic output commands for processing with the __plot(1)__ plotting filters. They are slightly more general than those in __libplot__ as these take a file pointer.   They also include the BRL 3-D extensions to the plot intermediate code.

_Pl_space_ or __pl_3space__ must be used before any of the graphic primitives to declare the amount of space necessary. See __plot3(5)__.

_Pl_box_ or __pl_3box__ draws a box between the two given opposite points. The ''pen'' will be left at the second point.

_Pl_circle_ draws a circle of radius __r__ with center at the point (__x__, `y`). Note that __circle__ and __arc__ cannot be transformed in three space if one is using a filter to do that.

_Pl_arc_ draws an arc of a circle with center at the point (__x__, `y`) between the points (__x0__, __y0__) and (__x1__, `y1`).

String arguments to __pl_label__ and __pl_linmod__ are terminated by nulls and do not contain new-lines.

There are also 2-D and 3_D double-precision versions, with arguments identical to their counterparts above.  The naming conventions are to change the prefix to "pd"; examples are thus __pd_point__ and __pd_3point.__ Vector versions for 3_D (also double-precision) are prefixed "pdv", as in __pdv_3point.__

See __plot3(5)__ and __plot(5)__ for a description of the effect of the remaining functions.

== FILES

/usr/brlcad/lib/libplot3`$$.$$`a	produces output for xref:man:1G/plot.adoc[*plot*(1G)] filters

== WARNINGS

In order to compile a program containing these functions in __file.c__ it is necessary to use ``cc __file.c__ -lplot3''.

_Color_ specification and three-dimensional primitives are BRL extensions to the "unix plot" language that are not generally found on other systems.

== SEE ALSO

xref:man:1/plot.adoc[*plot*(1)], xref:man:1/pl-fb.adoc[*pl-fb*(1)], xref:man:5/plot3.adoc[*plot3*(5)], xref:man:5/plot.adoc[*plot*(5)]

== AUTHOR

BRL-CAD Team

== COPYRIGHT

This software is Copyright (c) 1989-2021 by the United States Government as represented by U.S. Army Research Laboratory.

== BUG REPORTS

Reports of bugs or problems should be submitted via electronic mail to mailto:devs@brlcad.org[]