= What Documentation to Work On
:doctype: book
:sectnums:
:toc: left
:icons: font
:experimental:
:sourcedir: .

If you would like to work on a major project, then this section is for you.
Depending on how much you want to participate, we have documentation tasks that you can tackle and complete in a short or longer time.
In any case, you are invited to work on the documentation for BRL-CAD forever. 

Like our development tasks, the documentation tasks that we have available can take you anywhere from two hours to two days to two or more weeks to complete. 

== Two-Hour Tasks

If you want to get started working on the BRL-CAD documentation immediately, one great way to do that is by helping to clean up the existing documentation.
Take a look at the documentation and check the spelling or copy edit it to make the documentation more concise or to correct problems with grammar or punctuation.
Alternatively, check out our list of http://brlcad.org/wiki/Deuces#Documentation_and_Training[documentation tasks] (http://brlcad.org/wiki/Deuces#Documentation_and_Training) that you can complete in two hours or less. 

== Two-Day Tasks

If you have a little more time to devote to the documentation, we maintain a list of tasks that will take you anywhere from a few hours to a few days to complete.
You can find that list on the http://brlcad.org/wiki/Contributor_Quickies[BRL-CAD website] (http://brlcad.org/wiki/Contributor_Quickies). These tasks have roughly the same complexity and require no prior experience with BRL-CAD. 

We also have a list of bugs in our https://github.com/BRL-CAD/brlcad/blob/main/BUGS[BUGS file].
While most of the bugs in the list focus on the BRL-CAD code, there are a few related to the documentation.
If you plan to tackle a documentation bug, remember to report it in our https://github.com/BRL-CAD/brlcad/issues[issue tracker] (https://github.com/BRL-CAD/brlcad/issues). 

== Two-Week Tasks

If you are familiar with CAD in general and BRL-CAD in particular, then you might want to try creating some tutorial and training material.
Check out our list of http://brlcad.org/wiki/Contributor_Quickies#Training[training material that we need] (http://brlcad.org/wiki/Contributor_Quickies#Training). 