'\" t
.\"     Title: ap-pix
.\"    Author: [see the "AUTHOR(S)" section]
.\" Generator: Asciidoctor 2.0.10
.\"      Date: 2021-07-14
.\"    Manual: BRL-CAD
.\"    Source: BRL-CAD
.\"  Language: English
.\"
.TH "AP\-PIX" "1" "2021-07-14" "BRL\-CAD" "BRL\-CAD"
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.ss \n[.ss] 0
.nh
.ad l
.de URL
\fI\\$2\fP <\\$1>\\$3
..
.als MTO URL
.if \n[.g] \{\
.  mso www.tmac
.  am URL
.    ad l
.  .
.  am MTO
.    ad l
.  .
.  LINKSTYLE blue R < >
.\}
.SH "NAME"
ap\-pix \- convert Applicon files to pix files
.SH "SYNOPSIS"
.sp
\fBap\-pix\fP [\-v] \fIfile.ap\fP > \fIfile.pix\fP
.SH "DESCRIPTION"
.sp
\fBap\-pix\fP converts an Applicon drum plotter image file into a
\fBpix\fP(5) file.
.sp
The Applicon file is assumed to consist of a number lines each 3456
bits long; the resulting \fIpix\fP file thus has scanlines of 3456 pixels.
.SH "SEE ALSO"
.sp
\fBbrlcad\fP(1), \fBpix\fP(5)
.SH "AUTHOR"
.sp
BRL\-CAD Team
.SH "COPYRIGHT"
.sp
This software is Copyright (c) 1989\-2021 by the United States
Government as represented by U.S. Army Research Laboratory.
.SH "BUG REPORTS"
.sp
Reports of bugs or problems should be submitted via electronic mail to
.MTO "devs\(atbrlcad.org" "" ""