'\" t
.\"     Title: bwfilter
.\"    Author: [see the "AUTHOR(S)" section]
.\" Generator: Asciidoctor 2.0.10
.\"      Date: 2021-07-14
.\"    Manual: BRL-CAD
.\"    Source: BRL-CAD
.\"  Language: English
.\"
.TH "BWFILTER" "1" "2021-07-14" "BRL\-CAD" "BRL\-CAD"
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.ss \n[.ss] 0
.nh
.ad l
.de URL
\fI\\$2\fP <\\$1>\\$3
..
.als MTO URL
.if \n[.g] \{\
.  mso www.tmac
.  am URL
.    ad l
.  .
.  am MTO
.    ad l
.  .
.  LINKSTYLE blue R < >
.\}
.SH "NAME"
bwfilter \- apply a 3x3 filter to a black and white bw file
.SH "SYNOPSIS"
.sp
\fBbwfilter\fP [\-f \fItype\fP] [\-v] [\-d \fIdiv\fP] [\-O \fIoffset\fP] [\-s \fIsquaresize\fP] [\-w \fIwidth\fP] [\-n \fIheight\fP] [\-o \fIout_file\fP] [\fIfile.bw\fP] > \fInewfile.bw\fP
.SH "DESCRIPTION"
.sp
\fBbwfilter\fP applies one of several 3x3 kernel filters to a black
and white \fBbw\fP(5) format file. It will take a file
name or else read from standard input. The input file size will be
assumed to be 512x512 pixels unless the \fB\-s\fP, \fB\-w\fP, or
\fB\-n\fP flags are used to tell it otherwise (see
\fBbrlcad\fP(1)). By default a low pass filter is
used.  The \fB\-f\fP \fItype\fP flag can be used to specify a
different type of filter.
.sp
The \fItype\fP choices include:
.sp
\fIlo\fP
.RS 4
low pass, the default.
.RE
.sp
\fIhi\fP
.RS 4
high pass
.RE
.sp
\fIvg\fP
.RS 4
vertical gradient
.RE
.sp
\fIhg\fP
.RS 4
horizontal gradient
.RE
.sp
\fIla\fP
.RS 4
laplacian
.RE
.sp
\fIb\fP
.RS 4
boxcar low pass
.RE
.sp
Most filters divide the result of the kernel multiplication by some
value about in order to scale it back to a 0\(->255 range. For example,
the boxcar divides by nine.  The \fB\-d\fP flag can be used to change
this divisor. Some filters also add an offset to their results.  The
output of a laplacian for example is "centered" about zero, thus it
adds 128 to the answer to yield a difference from neutral grey. The
\fB\-O\fP flag can be used to change this offset.
.sp
The \fB\-v\fP flag displays the max and minimum values and the kernel
information on standard error.
.SH "BUGS"
.sp
This should allow any 3x3 kernel to be specified.
.SH "SEE ALSO"
.sp
\fBbrlcad\fP(1),
\fBbwscale\fP(1), \fBbw\fP(5)
.SH "AUTHOR"
.sp
BRL\-CAD Team
.SH "COPYRIGHT"
.sp
This software is Copyright (c) 1989\-2021 by the United States
Government as represented by U.S. Army Research Laboratory.
.SH "BUG REPORTS"
.sp
Reports of bugs or problems should be submitted via electronic mail to
.MTO "devs\(atbrlcad.org" "" ""