'\" t
.\"     Title: fbhelp
.\"    Author: [see the "AUTHOR(S)" section]
.\" Generator: Asciidoctor 2.0.10
.\"      Date: 2021-07-14
.\"    Manual: BRL-CAD
.\"    Source: BRL-CAD
.\"  Language: English
.\"
.TH "FBHELP" "1" "2021-07-14" "BRL\-CAD" "BRL\-CAD"
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.ss \n[.ss] 0
.nh
.ad l
.de URL
\fI\\$2\fP <\\$1>\\$3
..
.als MTO URL
.if \n[.g] \{\
.  mso www.tmac
.  am URL
.    ad l
.  .
.  am MTO
.    ad l
.  .
.  LINKSTYLE blue R < >
.\}
.SH "NAME"
fbhelp \- provide information on frame buffer selections
.SH "SYNOPSIS"
.sp
\fBfbhelp\fP [\-F \fIframebuffer\fP]
.SH "DESCRIPTION"
.sp
\fBfbhelp\fP displays information about the selection of frame buffer
devices available to the \fBlibfb\fP(3) frame
buffer library and the whole family of \fIfb\fP programs in the BRL\-CAD
package, for the machine \fBfbhelp\fP is run on.
.sp
The display device used by a program is taken first from the \fB\-F\fP
\fIframebuffer\fP option if given, else from the environment variable
\fIFB_FILE\fP, or finally from whatever the default display is for that
system. \fBfbhelp\fP will tell you what the available choices of
frame buffers are, as well as detailed information about any options
the currently selected device may have.
.SH "SEE ALSO"
.sp
\fBlibfb\fP(3), \fBbrlcad\fP(1)
.SH "AUTHOR"
.sp
BRL\-CAD Team
.SH "COPYRIGHT"
.sp
This software is Copyright (c) 1989\-2021 by the United States
Government as represented by U.S. Army Research Laboratory.
.SH "BUG REPORTS"
.sp
Reports of bugs or problems should be submitted via electronic mail to
.MTO "devs\(atbrlcad.org" "" ""