'\" t
.\"     Title: fbstretch
.\"    Author: [see the "AUTHOR(S)" section]
.\" Generator: Asciidoctor 2.0.10
.\"      Date: 2021-09-13
.\"    Manual: BRL-CAD
.\"    Source: BRL-CAD
.\"  Language: English
.\"
.TH "FBSTRETCH" "1" "2021-09-13" "BRL\-CAD" "BRL\-CAD"
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.ss \n[.ss] 0
.nh
.ad l
.de URL
\fI\\$2\fP <\\$1>\\$3
..
.als MTO URL
.if \n[.g] \{\
.  mso www.tmac
.  am URL
.    ad l
.  .
.  am MTO
.    ad l
.  .
.  LINKSTYLE blue R < >
.\}
.SH "NAME"
fbstretch \- stretch a frame buffer image
.SH "SYNOPSIS"
.sp
\fBfbstretch\fP [\-f \fIinput_image_name\fP] [\-s \fIinput_square_size\fP] [\-w \fIinput_width\fP]
.br
[\-n \fIinput_height\fP] [\-a] [\-x \fIhorizontal_scale\fP \fIfactor\fP] [\-y \fIvertical_scale\fP \fIfactor\fP]
.br
[\-v] [\-S \fIoutput_square_size\fP] [\-W \fIoutput_width\fP] [\-N \fIoutput_height\fP]
.br
[[\-F] \fIoutput_frame_buffer\fP \fIname\fP]
.SH "DESCRIPTION"
.sp
\fBfbstretch\fP expands or compresses a frame buffer image, in either
or both the horizontal and vertical directions. The image scaling
origin (fixed point) is the lower left\-hand corner of the
display. When expanding (scale factor greater than 1), pixels are
simply replicated; when compressing (scale factor less than 1), pixel
averaging is performed unless sampling is explicitly requested by the
\fI\-a\fP option.
.sp
The default input image size is 512 by 512. Explicitly specified sizes
override the default, and if actual input image size is smaller than
requested, the actual size will be used. If not specified, requested
output frame buffer size will be the stretched revised input size. If
there are margins within the requested output beyond the stretched
image, they will be cleared to background; if the stretched image
would extend beyond the requested output size, it will be clipped to
fit, even if there is room for it in the actual frame buffer. Actual
sizes depend on details of specific frame buffers.
.SS "Options"
.sp
\-f \fIinput_image_name\fP
.RS 4
Inputs the image to be displayed from the
specified frame buffer or \fBpix\fP(5) file, instead
of modifying the output frame buffer in place. This option may not
work if input and output frame buffers are the same device.
.RE
.sp
\-s \fIinput_square_size\fP
.RS 4
Specifies input image width and height.
.RE
.sp
\-w \fIinput_width\fP
.RS 4
Specifies input image width.
.RE
.sp
\-n \fIinput_height\fP
.RS 4
Specifies input image height.
.RE
.sp
\-a
.RS 4
(no averaging) Specifies that output pixels will be sampled from
the input, instead of being computed by averaging RGB values.
.RE
.sp
\-v
.RS 4
(verbose) Causes actual sizes and scale factors used to be
printed on the standard error output.
.RE
.sp
\-x \fIhorizontal_scale_factor\fP
.RS 4
Scales the image by the specified
factor in the horizontal direction; the default is the ratio of
requested output to input widths, if specified, otherwise 1.
.RE
.sp
\-y \fIvertical_scale_factor\fP
.RS 4
Scales the image by the specified factor
in the vertical direction; the default is the ratio of requested
output to input heights, if specified, otherwise 1.
.RE
.sp
\-S \fIoutput_square_size\fP
.RS 4
Specifies output frame buffer width and
height.
.RE
.sp
\-W \fIoutput_width\fP
.RS 4
Specifies output frame buffer width.
.RE
.sp
\-N \fIoutput_height\fP
.RS 4
Specifies output frame buffer height.
.RE
.sp
\-F \fIoutput_frame_buffer_name\fP
.RS 4
Outputs to the specified frame buffer
instead of the one specified by the \fIFB_FILE\fP environment
variable (or the default, if \fIFB_FILE\fP is not set). If this is
the last option specified, the \fI\-F\fP is optional.
.RE
.SH "DISCUSSION"
.sp
Pixel averaging may be meaningless for some images or color maps, in
which case sampling should be specified. Images of the Mandelbrot set
(see \fBmandel\fP(1)) are a good example of this.
.SH "EXAMPLE"
.sp
The following procedure enlarges an image, obtained from a personal
computer via the \fBgif\-fb\fP utility, to fill a 1280\-by\-1024 frame
buffer.
.sp
.if n .RS 4
.nf
$ gif\-fb _image.gif_ # displays the 320x200 PC image

$ fbstretch \-w 320 \-n 200 \-W 1280 \-N 1024
.fi
.if n .RE
.SH "SEE ALSO"
.sp
\fBgif\-fb\fP(1),
\fBmandel\fP(1),
\fBpixscale\fP(1),
\fBlibfb\fP(3), \fBpix\fP(5)
.SH "DIAGNOSTICS"
.sp
Error messages are intended to be self\-explanatory.
.SH "AUTHOR"
.sp
Douglas A. Gwyn, BRL/VLD\-VMB
.SH "COPYRIGHT"
.sp
This software is Copyright (c) 1989\-2021 by the United States
Government as represented by U.S. Army Research Laboratory.
.SH "BUG REPORTS"
.sp
Reports of bugs or problems should be submitted via electronic mail to
.MTO "devs\(atbrlcad.org" "" ""