'\" t
.\"     Title: g-dxf
.\"    Author: [see the "AUTHOR(S)" section]
.\" Generator: Asciidoctor 2.0.10
.\"      Date: 2021-07-14
.\"    Manual: BRL-CAD
.\"    Source: BRL-CAD
.\"  Language: English
.\"
.TH "G\-DXF" "1" "2021-07-14" "BRL\-CAD" "BRL\-CAD"
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.ss \n[.ss] 0
.nh
.ad l
.de URL
\fI\\$2\fP <\\$1>\\$3
..
.als MTO URL
.if \n[.g] \{\
.  mso www.tmac
.  am URL
.    ad l
.  .
.  am MTO
.    ad l
.  .
.  LINKSTYLE blue R < >
.\}
.SH "NAME"
g\-dxf \- AutoCad DXF Translator (BRL\-CAD to DXF)
.SH "SYNOPSIS"
.sp
\fBg\-dxf\fP [\-v] [\-i] [\-p] [\-xX \fIlvl\fP] [\-D \fIcalculation_tolerance\fP] [\-a \fIabs_tol\fP] [\-r \fIrel_tol\fP] [\-n \fInorm_tol\fP] [\-P \fIdummy_arg\fP] [\-o \fIDXF_file\fP] \fIdatabase.g\fP \fIobject(s)\fP
.SH "DESCRIPTION"
.sp
\fBg\-dxf\fP converts the specified \fIobject(s)\fP from a BRL\-CAD
\fIdatabase.g\fP file to the \fIAutoCad DXF\fP file format. The \fB\-x\fP
option specifies an RT debug flag and the \fB\-X\fP option specifies
an NMG debug flag. The \fB\-a\fP option may be used to specify an
absolute tessellation tolerance (in millimeters). This requires that
the maximum absolute error from the tessellated surface to the actual
surface must not be greater than \fIabs_tol\fP. The \fB\-n\fP option
specifies a surface normal error tolerance (in degrees) for the
tessellation. The \fB\-r\fP option may be used to set a relative error
tolerance. This effectively sets an absolute tolerance for each
primitive solid by multiplying the overall size of the solid by
\fIrel_tol\fP. The \fB\-D\fP option specifies a calculational distance
tolerance (mm). Any two vertices that are less than this distance
apart will be treated as the same vertex. The \fB\-v\fP option
requests verbose output. The \fB\-i\fP option requests the output file
units to be inches (the default is mm). The \fB\-p\fP option requests
that the output consist entirely of POLYFACE MESH entities. (The
default is all 3DFACE entities.) The \fB\-P\fP option is to enable
core dumps (dummy argument is for number of processors, currently
disabled). The \fB\-o\fP option specifies the name of the file to
receive the output (stdout is the default).
.SH "EXAMPLE"
.sp
.if n .RS 4
.nf
$ g\-dxf \-o sample.dxf sample.g sample_object
.fi
.if n .RE
.SH "DIAGNOSTICS"
.sp
Error messages are intended to be self\-explanatory.
.SH "AUTHOR"
.sp
BRL\-CAD Team
.SH "COPYRIGHT"
.sp
This software is Copyright (c) 1989\-2021 by the United States
Government as represented by U.S. Army Research Laboratory.
.SH "BUG REPORTS"
.sp
Reports of bugs or problems should be submitted via electronic mail to
.MTO "devs\(atbrlcad.org" "" ""