'\" t
.\"     Title: g-shell-rect
.\"    Author: [see the "AUTHOR(S)" section]
.\" Generator: Asciidoctor 2.0.10
.\"      Date: 2021-07-14
.\"    Manual: BRL-CAD
.\"    Source: BRL-CAD
.\"  Language: English
.\"
.TH "G\-SHELL\-RECT" "1" "2021-07-14" "BRL\-CAD" "BRL\-CAD"
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.ss \n[.ss] 0
.nh
.ad l
.de URL
\fI\\$2\fP <\\$1>\\$3
..
.als MTO URL
.if \n[.g] \{\
.  mso www.tmac
.  am URL
.    ad l
.  .
.  am MTO
.    ad l
.  .
.  LINKSTYLE blue R < >
.\}
.SH "NAME"
g\-shell\-rect \- Produce triangulated shell from BRL\-CAD model
.SH "SYNOPSIS"
.sp
\fBg\-shell\-rect\fP [\-a \fIrpp_args\fP] [\-R \fIedge_tol\fP] [\-p \fIplotfile\fP] [\-X \fIlvl\fP] [\-d \fIdebug_level\fP] [\-b] [\-n] [\-i \fIinitial_ray_dir\fP] [\-g \fIcell_size\fP] \-o \fIbrlcad_output_file\fP \fIdatabase.g\fP \fIobject(s)\fP
.SH "DESCRIPTION"
.sp
\fBg\-shell\-rect\fP converts the specified \fIobjects(s)\fP from a BRL\-CAD
model \fIdatabase.g\fP to a single NMG solid using raytracing. Rays are
fired in a uniform grid. The direction for the first set of rays is
chosen by calculating the presented area of the bounding box of the
\fIobject(s)\fP and selecting the direction with the largest area. The
user may override this by specifying a desired initial ray direction
using the \fB\-i\fP option (see below). The initial shell is
constructed using only the first and last intersections with the
\fIobject(s)\fP. This will typically result in some rather large faces
with normals at right angles to the ray direction. Unless the
\fB\-n\fP option is specified, these faces are then subdivided
(according to the \fIcell_size\fP) and additional rays fired from the
other two directions are used to refine their shape. The resulting NMG
solid will be named \fIshell\fP and will be written to the specified
\fIbrlcad_output_file\fP.
.sp
The following command line options are recognized:
.sp
\fB\-g\fP \fIcell_size\fP
.RS 4
Specify the dimensions (in millimeters) of the grid
spacing.  The default is 50mm.
.RE
.sp
\fB\-i\fP \fIinitial_ray_dir\fP
.RS 4
Specify the initial ray direction.  Valid
values are X, Y, or Z. The best results are usually obtained by
raytracing in the direction that produces the most hits first.
.RE
.sp
\fB\-d\fP \fIdebug_level\fP
.RS 4
Set the debugging level.  Higher values produce
more debugging information.
.RE
.sp
\fB\-n\fP
.RS 4
Suppresses the refinement stage (firing rays from the secondary
and tertiary axis directions).
.RE
.sp
\fB\-b\fP
.RS 4
Output a BOT rather than an NMG.
.RE
.sp
\fB\-a\fP \fIrpp_args\fP
.RS 4
Add an RPP for refining.
.RE
.sp
\fB\-R\fP \fIedge_tol\fP
.RS 4
Supply edge tolerance.
.RE
.sp
\fB\-p\fP \fIplotfile\fP
.RS 4
Supply plotfile for plot edge breaking.
.RE
.sp
\fB\-X\fP \fIlvl\fP
.RS 4
Supply NMG debug flags.
.RE
.sp
\fB\-o\fP \fIoutput.g\fP
.RS 4
Specifies the name of the BRL\-CAD geometry file to
create.
.RE
.SH "EXAMPLE"
.sp
.if n .RS 4
.nf
$ g\-shell\-rect \-o shell.g sample.g sample_object
.fi
.if n .RE
.SH "DIAGNOSTICS"
.sp
Error messages are intended to be self\-explanatory.
.SH "AUTHOR"
.sp
BRL\-CAD Team
.SH "COPYRIGHT"
.sp
This software is Copyright (c) 1989\-2021 by the United States
Government as represented by U.S. Army Research Laboratory.
.SH "BUG REPORTS"
.sp
Reports of bugs or problems should be submitted via electronic mail to
.MTO "devs\(atbrlcad.org" "" ""