'\" t
.\"     Title: g-stl
.\"    Author: [see the "AUTHOR(S)" section]
.\" Generator: Asciidoctor 2.0.10
.\"      Date: 2021-07-14
.\"    Manual: BRL-CAD
.\"    Source: BRL-CAD
.\"  Language: English
.\"
.TH "G\-STL" "1" "2021-07-14" "BRL\-CAD" "BRL\-CAD"
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.ss \n[.ss] 0
.nh
.ad l
.de URL
\fI\\$2\fP <\\$1>\\$3
..
.als MTO URL
.if \n[.g] \{\
.  mso www.tmac
.  am URL
.    ad l
.  .
.  am MTO
.    ad l
.  .
.  LINKSTYLE blue R < >
.\}
.SH "NAME"
g\-stl \- Stereolithography Translator (BRL\-CAD to STL)
.SH "SYNOPSIS"
.sp
\fBg\-stl\fP [\-o \fIoutput_file\fP] [\-m \fIoutput_directory\fP] [\-b] [\-i] [\-8] [\-D \fIcalculation_tolerance\fP] [\-a \fIabsolute_tol\fP] [\-r \fIrelative_tol\fP] [\-n \fInormal_tol\fP] [\-xX \fIlevel\fP] [\-v] \fIdatabase.g\fP \fIobject(s)\fP...
.SH "DESCRIPTION"
.sp
\fBg\-stl\fP converts the specified \fIobject(s)\fP from a BRL\-CAD
\fIdatabase.g\fP file to the \fIstereolithography\fP file format.
.sp
The following options are recognized.
.sp
\fB\-o PATH\fP
.RS 4
Specify output file name (default is stdout).
.RE
.sp
\fB\-m DIR\fP
.RS 4
Specify a directory for output files. Each region converted
is written to a separate file. File names are constructed from the
full path names of each region (the path from the specified object to
the region). Any "/" characters in the path name are replaced by "@"
characters and "." and white space are replaced by "_" characters. If
the \-m option is not specified, all regions are written to the same
file. The \fB\-o\fP and \fB\-m\fP options are mutually exclusive.
.RE
.sp
\fB\-b\fP
.RS 4
Write output as a binary STL file. The default is ASCII. In the
case of ASCII output, the region name is specified on the "solid" line
of the STL file. In the case of binary output, all the regions are
output as a single STL part.
.RE
.sp
\fB\-i\fP
.RS 4
Use inches as the output format (the default is mm).
.RE
.sp
\fB\-8\fP
.RS 4
Facetize using the marching cubes algorithm.
.RE
.sp
\fB\-D#\fP
.RS 4
Specify a calculational distance tolerance (mm). Any two
vertices that are less than this distance apart will be treated as the
same vertex.
.RE
.sp
\fB\-a#\fP
.RS 4
Specify the absolute tesselation tolerance.
.RE
.sp
\fB\-r#\fP
.RS 4
Specify the relative tesselation tolerance.
.RE
.sp
\fB\-n#\fP
.RS 4
Specify the surface\-normal tesselation tolerance.
.RE
.sp
\fB\-x#\fP
.RS 4
Specify an RT debug flag.
.RE
.sp
\fB\-X#\fP
.RS 4
Specify an NMG debug flag.
.RE
.sp
\fB\-v\fP
.RS 4
Enable verbose output.
.RE
.SH "EXAMPLE"
.sp
.if n .RS 4
.nf
$ g\-stl \-o sample.stl sample.g sample_object
.fi
.if n .RE
.SH "DIAGNOSTICS"
.sp
Error messages are intended to be self\-explanatory.
.SH "AUTHOR"
.sp
BRL\-CAD Team
.SH "COPYRIGHT"
.sp
This software is Copyright (c) 1989\-2021 by the United States
Government as represented by U.S. Army Research Laboratory.
.SH "BUG REPORTS"
.sp
Reports of bugs or problems should be submitted via electronic mail to
.MTO "devs\(atbrlcad.org" "" ""