'\" t
.\"     Title: gastank
.\"    Author: [see the "AUTHOR(S)" section]
.\" Generator: Asciidoctor 2.0.10
.\"      Date: 2021-09-13
.\"    Manual: BRL-CAD
.\"    Source: BRL-CAD
.\"  Language: English
.\"
.TH "GASTANK" "1" "2021-09-13" "BRL\-CAD" "BRL\-CAD"
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.ss \n[.ss] 0
.nh
.ad l
.de URL
\fI\\$2\fP <\\$1>\\$3
..
.als MTO URL
.if \n[.g] \{\
.  mso www.tmac
.  am URL
.    ad l
.  .
.  am MTO
.    ad l
.  .
.  LINKSTYLE blue R < >
.\}
.SH "NAME"
gastank \- Creates a BRL\-CAD .g file containing gas tanks.
.SH "SYNOPSIS"
.sp
\fBgastank\fP [\fIoptions\fP]...
.SH "DESCRIPTION"
.sp
\fBgastank\fP is a program to create a BRL\-CAD data base of gas
tanks. Up to twenty\-six gas tanks of the same size may be
created. These gas tanks are solid with rounded corners and edges.
They are appropriate for use with millimeter wave signature analysis.
They are not appropriate for infra red or vulnerability
analysis. \fBgastank\fP uses libwdb to create a BRL\-CAD database.
The gas tanks are composed of three arb8s, eight spheres, and twelve
cylinders.  This program may be run interactively or the user may
specify options on a command line.  If the user chooses to run the
program interactively he answers the questions as the program
prompts him. Below are the options that can be used on the command
line.
.SH "OPTIONS"
.sp
\fB\-f\fP \fIname.g\fP
.RS 4
BRL\-CAD file name.
.RE
.sp
\fB\-n #\fP
.RS 4
The number of gas tanks to be created (must be less than or equal to 26).
.RE
.sp
\fB\-H #\fP
.RS 4
Height of gas tank in millimeters.
.RE
.sp
\fB\-w #\fP
.RS 4
Width of gas tank in millimeters.
.RE
.sp
\fB\-d #\fP
.RS 4
Depth of gas tank in millimeters.
.RE
.sp
\fB\-r #\fP
.RS 4
Radius of the corner in millimeters.
.RE
.SH "EXAMPLES"
.sp
.B Example 1. Interactive \fBgastank\fP Session
.br
.RS 4
.sp
.if n .RS 4
.nf
$ gastank

This program constructs a solid gas tank with all
edges and corners rounded.

Enter the mged file to be created (25 char max).
        gastank.g
Enter the number of gas tanks to create (26 max).
        3
Enter the height, width, and depth of the gas tank (units mm).
        300 200 400
Enter the radius of the corners (units mm).
        30

mged file:  gastank.g
height of gas tank:  300.000000 mm
width of gas tank:  200.000000 mm
depth of gas tank:  400.000000 mm
radius of corner:  30.000000 mm
number of gas tanks:  3
.fi
.if n .RE
.RE
.sp
.B Example 2. Single\-Line \fBgastank\fP Command
.br
.RS 4
.sp
\f(CRgastank \-fgastank.g \-n3 \-H300 \-w200 \-d400 \-r30\fP
.RE
.sp
Both of these examples produce the same result \- 3 gas tanks with a
height of 300mm, a width of 200mm, a depth of 400mm, and a radius for
the corner of 30mm.  The BRL\-CAD database file created in each case is
gastank.g
.SH "AUTHOR"
.sp
Susan A. Coates
.SH "SEE ALSO"
.sp
bolt(1), handle(1), window(1), window_frame(1)
.SH "COPYRIGHT"
.sp
This software is Copyright (c) 1989\-2021 by the United States
Government as represented by U.S. Army Research Laboratory.
.SH "BUG REPORTS"
.sp
Reports of bugs or problems should be submitted via electronic mail to
.MTO "devs\(atbrlcad.org" "" ""