'\" t
.\"     Title: pix-ps
.\"    Author: [see the "AUTHOR(S)" section]
.\" Generator: Asciidoctor 2.0.10
.\"      Date: 2021-07-14
.\"    Manual: BRL-CAD
.\"    Source: BRL-CAD
.\"  Language: English
.\"
.TH "PIX\-PS" "1" "2021-07-14" "BRL\-CAD" "BRL\-CAD"
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.ss \n[.ss] 0
.nh
.ad l
.de URL
\fI\\$2\fP <\\$1>\\$3
..
.als MTO URL
.if \n[.g] \{\
.  mso www.tmac
.  am URL
.    ad l
.  .
.  am MTO
.    ad l
.  .
.  LINKSTYLE blue R < >
.\}
.SH "NAME"
pix\-ps \- convert a color pix file to PostScript
.SH "SYNOPSIS"
.sp
\fBpix\-ps\fP [\-e] [\-c|\-l] [\-L] [\-s \fIinput_squaresize\fP] [\-w \fIinput_width\fP] [\-n \fIinput_height\fP] [\-S \fIinches_square\fP] [\-W \fIinches_width\fP] [\-N \fIinches_height\fP] [\fIinfile.pix\fP] > \fIoutfile.ps\fP
.SH "DESCRIPTION"
.sp
\fBpix\-ps\fP will take a color \fBpix\fP(5) format
file of given dimensions and produce a Postscript file on the standard
output. The \fB\-w\fP and \fB\-n\fP flags specify the input file width
and number of scan lines in pixels. They can both be set to the same
value via \fB\-s.\fP If no input size is given, defaults of 512 are
assumed.
.sp
By default the output PostScript image size is 6.75 inches. The
\fB\-c\fP option (on by default) will center it on a 8.5 x 11 inch
page; otherwise, the \fB\-l\fP option uses the lower left corner. If a
different output size is desired, \fB\-S\fP, \fB\-W\fP, and \fB\-N\fP
can be used to set the size in inches analogous to the input
parameters. Finally, \fB\-L\fP selects landscape mode, i.e. rotates
the output image by ninety degrees.
.sp
Encapsulated PostScript files can be generated via \fB\-e.\fP
.SH "EXAMPLES"
.sp
.if n .RS 4
.nf
pix\-ps \-c image.pix > image.ps
.fi
.if n .RE
.sp
Produces a 6.75 inch PostScript file from a 512x512 input image and
centers it on an 8.5 x 11 inch page.
.sp
.if n .RS 4
.nf
pix\-ps \-e \-w 1024 \-n 768 image.pix > image.ps
.fi
.if n .RE
.sp
Takes the file image.pix which has the dimensions of 1024 pixels wide
by 768 pixels high, and produces an Encapsulated Postscript version
of it.
.sp
.if n .RS 4
.nf
pix\-ps \-L \-c \-S 5.2 < image.pix > image.ps
.fi
.if n .RE
.sp
Makes a PostScript file of the (assumed 512x512) image, with the
output image 5.2 inches square, in landscape mode, centered on an 8.5
x 11 inch page.
.SH "SEE ALSO"
.sp
\fBbrlcad\fP(1),
\fBbw\-ps\fP(1), \fBpix\fP(5)
.SH "AUTHOR"
.sp
BRL\-CAD Team
.SH "COPYRIGHT"
.sp
This software is Copyright (c) 1989\-2021 by the United States
Government as represented by U.S. Army Research Laboratory.
.SH "BUG REPORTS"
.sp
Reports of bugs or problems should be submitted via electronic mail to
.MTO "devs\(atbrlcad.org" "" ""