'\" t
.\"     Title: pixsaturate
.\"    Author: [see the "AUTHOR(S)" section]
.\" Generator: Asciidoctor 2.0.10
.\"      Date: 2021-07-14
.\"    Manual: BRL-CAD
.\"    Source: BRL-CAD
.\"  Language: English
.\"
.TH "PIXSATURATE" "1" "2021-07-14" "BRL\-CAD" "BRL\-CAD"
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.ss \n[.ss] 0
.nh
.ad l
.de URL
\fI\\$2\fP <\\$1>\\$3
..
.als MTO URL
.if \n[.g] \{\
.  mso www.tmac
.  am URL
.    ad l
.  .
.  am MTO
.    ad l
.  .
.  LINKSTYLE blue R < >
.\}
.SH "NAME"
pixsaturate \- saturate a pix file
.SH "SYNOPSIS"
.sp
\fBpixsaturate\fP \fIsaturation\fP < \fIinfile.pix\fP > \fIoutfile.pix\fP
.SH "DESCRIPTION"
.sp
\fBpixsaturate\fP saturates a color pix file using the \fIsaturation\fP
value.  A value of 0 gives monochrome, 1.0 gives the original image,
and values larger than 1.0 give a more saturated image.
.SH "SEE ALSO"
.sp
\fBbrlcad\fP(1), \fBpix\fP(5),
\fBpixfade\fP(1)
.SH "AUTHOR"
.sp
BRL\-CAD Team
.SH "COPYRIGHT"
.sp
This software is Copyright (c) 1989\-2021 by the United States
Government as represented by U.S. Army Research Laboratory.
.SH "BUG REPORTS"
.sp
Reports of bugs or problems should be submitted via electronic mail to
.MTO "devs\(atbrlcad.org" "" ""