'\" t
.\"     Title: pixtile
.\"    Author: [see the "AUTHOR(S)" section]
.\" Generator: Asciidoctor 2.0.10
.\"      Date: 2021-07-14
.\"    Manual: BRL-CAD
.\"    Source: BRL-CAD
.\"  Language: English
.\"
.TH "PIXTILE" "1" "2021-07-14" "BRL\-CAD" "BRL\-CAD"
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.ss \n[.ss] 0
.nh
.ad l
.de URL
\fI\\$2\fP <\\$1>\\$3
..
.als MTO URL
.if \n[.g] \{\
.  mso www.tmac
.  am URL
.    ad l
.  .
.  am MTO
.    ad l
.  .
.  LINKSTYLE blue R < >
.\}
.SH "NAME"
pixtile \- paste small images together into one large image
.SH "SYNOPSIS"
.sp
\fBpixtile\fP [\-s \fIsquareinsize\fP] [\-w \fIfile_width\fP] [\-n \fIfile_height\fP] [\-S \fIsquareoutsize\fP] [\-W \fIout_width\fP] [\-N \fIout_height\fP] [\-o \fIstartframe\fP] \fIbasename\fP > \fIfile.pix\fP
.sp
\fBpixtile\fP [\-s \fIsquareinsize\fP] [\-w \fIfile_width\fP] [\-n \fIfile_height\fP] [\-S \fIsquareoutsize\fP] [\-W \fIout_width\fP] [\-N \fIout_height\fP] \fIfile1\fP \fIfile2\fP ... \fIfileN\fP > \fIfile.pix\fP
.SH "DESCRIPTION"
.sp
\fBpixtile\fP takes a collection of numbered small images and places
them side by side in one larger image.  The input and output files are
assumed to be in \fBpix\fP(5) format. By default, the
output file will be made 512x512 pixels in size.
.sp
The input files have a default width of 64 pixels per scanline and are
usually square, i.e. have the same height as width. Specifying the
\fB\-s\fP flag changes the default size to \fIsquareinsize\fP pixels per
scanline and \fIsquareinsize\fP scanlines as given in the argument
list. The \fB\-w\fP flag can be used to specify the input file width
in pixels and the \fB\-n\fP flag can be used to specify the input file
height in scanlines.
.sp
If the \fB\-S\fP flag is supplied, the output size is changed from the
default value of 512 to \fIsquareoutsize\fP pixels per scanline and
\fIsquareoutsize\fP scanlines. The \fB\-W\fP flag sets the output width
size to \fIout_width\fP pixels per scanline. Similarly, the \fB\-N\fP flag
sets the output height size to \fIout_height\fP scanlines.
.sp
\fB\-s\fP \fIsquareinsize\fP
.RS 4
Specify both the number of pixels per scanline
and the number of scanlines in the input files.  The default is 64.
.RE
.sp
\fB\-w\fP \fIfile_width\fP
.RS 4
Specify the width (in pixels) per scanline of the
input file. The default is 64.
.RE
.sp
\fB\-n\fP \fIfile_height\fP
.RS 4
Specify the number of scanlines to be read from
the input file. The default is 64.
.RE
.sp
\fB\-S\fP \fIsquareoutsize\fP
.RS 4
Specify both the number of pixels per scanline
(width) and the number of scanlines (height) for the output file.  The
default is 512.
.RE
.sp
\fB\-W\fP \fIout_width\fP
.RS 4
Specify the width (in pixels) per scanline of the
output file. The default is 512.
.RE
.sp
\fB\-N\fP \fIout_height\fP
.RS 4
Specify the number of scanlines to be sent to the
output file. The default is 512.
.RE
.sp
\fB\-o\fP \fIstartframe\fP
.RS 4
Specify the starting frame number, where
\fIstartframe\fP is substituted for \fInum\fP in \fIbasename.num\fP.
.RE
.sp
The files being pasted together should have names of the form
\fIbasename.num\fP, where \fIbasename\fP is given on the command line, and
\fInum\fP is a consecutive series of integers.  By default the first image
is assumed to be number " 0 ", but an alternate \fIstartframe\fP can be
given by using the \fB\-o\fP flag and supplying \fIstartframe\fP. The
program keeps reading these small files until either the next frame
does not exist, or the output file is full. They are placed in the
output file from lower left to upper right. The progress of the
composition is displayed on standard error.
.sp
If the basename is given as "\-" (a minus sign), preceded by a "\-\-"
(two minus signs) to terminate
\fBbu_getopt\fP(3) processing, then the stream
of images is read from stdin rather than a file, such as might be
generated by a program like
\fBpcd\-pix\fP(1). Such a stream could also be
processed into files by \fBpixbustup\fP(1).
.sp
Alternatively, if more than one \fIbasename\fP (filename) argument is
supplied on the command line, the names of the files being pasted
together are assumed to be explicitly stated and the \fB\-o\fP flag is
not valid.  This allows files with different names to be used without
having to change those names.
.sp
This program is the companion of \fBfbanim\fP(1),
which will step through these small images on a framebuffer capable of
zooming and windowing.  Thus many small low resolution frames can be
used as an animation "preview" for a higher resolution sequence, the
latter of which would go onto video tape or film.
.SH "EXAMPLES"
.sp
.if n .RS 4
.nf
pixtile \-S 1024 \-s 128 \-o 2 anim > out.pix
.fi
.if n .RE
.sp
will read files \fIanim.2\fP through \fIanim.65\fP, placing them from lower
left to upper right in a 1024x1024 pixel file \fIout.pix\fP.
.sp
.if n .RS 4
.nf
pixtile \-s 256 lowerleft lowerright upperleft upperright > out.pix
.fi
.if n .RE
.sp
will read files \fIlowerleft\fP, \fIlowerright\fP, \fIupperleft\fP, and
\fIupperright\fP, placing them from lower left to upper right in a 512x512
file \fIout.pix\fP.
.SH "SEE ALSO"
.sp
\fBbrlcad\fP(1),
\fBfbanim\fP(1), \fBpix\fP(5)
.SH "AUTHOR"
.sp
BRL\-CAD Team
.SH "COPYRIGHT"
.sp
This software is Copyright (c) 1989\-2021 by the United States
Government as represented by U.S. Army Research Laboratory.
.SH "BUG REPORTS"
.sp
Reports of bugs or problems should be submitted via electronic mail to
.MTO "devs\(atbrlcad.org" "" ""