'\" t
.\"     Title: rtarea
.\"    Author: [see the "AUTHOR(S)" section]
.\" Generator: Asciidoctor 2.0.10
.\"      Date: 2021-09-13
.\"    Manual: BRL-CAD
.\"    Source: BRL-CAD
.\"  Language: English
.\"
.TH "RTAREA" "1" "2021-09-13" "BRL\-CAD" "BRL\-CAD"
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.ss \n[.ss] 0
.nh
.ad l
.de URL
\fI\\$2\fP <\\$1>\\$3
..
.als MTO URL
.if \n[.g] \{\
.  mso www.tmac
.  am URL
.    ad l
.  .
.  am MTO
.    ad l
.  .
.  LINKSTYLE blue R < >
.\}
.SH "NAME"
rtarea \- Calculate exposed and presented surface areas
.SH "SYNOPSIS"
.sp
\fBrtarea\fP [\fIoptions\fP]... \fImodel.g\fP \fIobjects\fP...
.SH "DESCRIPTION"
.sp
The \fBrtarea\fP command calculates the exposed, presented and
centers of surface areas of specified geometry objects from a
particular view.  The summary output includes details for individual
regions, assemblies (combinations that contain regions), and
summarized totals.
.sp
The \fIexposed\fP area corresponds to what a human observer would see
looking at the object(s) in question, if all the objects were
non\-transparent.  For example, say rays were cast towards two cubes,
each one of which is a region, one in front of the other, grouped into
an assembly, with the ray direction pointed into the page:
.sp
.if n .RS 4
.nf
|\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-| Rear Cube
|                |
|                |
|        |\-\-\-\-\-\-\-\-\-\-\-\-\-\-| Front Cube
|        |       |      |
|        |       |      |
|\-\-\-\-\-\-\-\-|\-\-\-\-\-\-\-|      |
         |              |
         |              |
         |\-\-\-\-\-\-\-\-\-\-\-\-\-\-|
.fi
.if n .RE
.sp
The exposed area of the Front Cube corresponds to the total area of
the sheet, since it is not occluded by any other object:
.sp
.if n .RS 4
.nf
|\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-| Rear Cube
|                |
|                |
|        |\-\-\-\-\-\-\-\-\-\-\-\-\-\-| Front Cube
|        |**************|
|        |**************|
|\-\-\-\-\-\-\-\-|**************|
         |**************|
         |**************|
         |\-\-\-\-\-\-\-\-\-\-\-\-\-\-|
.fi
.if n .RE
.sp
The Rear Cube, on the other hand, IS occluded by the Front Cube and
would thus report only a fraction of its area as exposed:
.sp
.if n .RS 4
.nf
|\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-| Rear Cube
|****************|
|****************|
|********|\-\-\-\-\-\-\-\-\-\-\-\-\-\-| Front Cube
|********|       |      |
|********|       |      |
|\-\-\-\-\-\-\-\-|\-\-\-\-\-\-\-|      |
         |              |
         |              |
         |\-\-\-\-\-\-\-\-\-\-\-\-\-\-|
.fi
.if n .RE
.sp
An object that combines both of these sheets would thus report as its
exposed area the sum of the exposed areas of the individual sheets:
.sp
.if n .RS 4
.nf
|\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-| Rear Cube
|****************|
|****************|
|****************|\-\-\-\-\-\-| Front Cube
|***********************|
|***********************|
|\-\-\-\-\-\-\-\-|**************|
         |**************|
         |**************|
         |\-\-\-\-\-\-\-\-\-\-\-\-\-\-|
.fi
.if n .RE
.sp
\fIPresented\fP area, unlike exposed area, does not take occlusion into
account.  It is the equivalent of taking each object and considering
it in isolation.  So for the previous case of two sheets of metal, the
Front Cube would report the same area:
.sp
.if n .RS 4
.nf
|\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-| Rear Cube
|                |
|                |
|        |\-\-\-\-\-\-\-\-\-\-\-\-\-\-| Front Cube
|        |**************|
|        |**************|
|\-\-\-\-\-\-\-\-|**************|
         |**************|
         |**************|
         |\-\-\-\-\-\-\-\-\-\-\-\-\-\-|
.fi
.if n .RE
.sp
the Rear Cube, on the other hand, ALSO reports its full area:
.sp
.if n .RS 4
.nf
|\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-| Rear Cube
|****************|
|****************|
|****************\-\-\-\-\-\-\-| Front Cube
|****************|      |
|****************|      |
|\-\-\-\-\-\-\-\-|\-\-\-\-\-\-\-|      |
         |              |
         |              |
         |\-\-\-\-\-\-\-\-\-\-\-\-\-\-|
.fi
.if n .RE
.sp
When reporting the presented area of the group, there is a subtle
point \- rtarea does not count area covered by multiple regions
multiple times when totaling the presented area.  So for the group
containing both cubes, the presented area is NOT the cumulative area
of both regions\(aq presented areas but the area of the union of those
two areas.  In this case, that works out to be the same as the exposed
area.
.sp
.if n .RS 4
.nf
|\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-| Rear Cube
|****************|
|****************|
|****************|\-\-\-\-\-\-| Front Cube
|***********************|
|***********************|
|\-\-\-\-\-\-\-\-|**************|
         |**************|
         |**************|
         |\-\-\-\-\-\-\-\-\-\-\-\-\-\-|
.fi
.if n .RE
.sp
It should be noted that rtarea only counts surfaces with a surface
normal that has a component looking back in the direction of the ray.
So, for example, a cube with only one face looking "back toward" the
ray will not report area from other faces as "presented", since their
surface normals will indicate they are not surfaces being presented to
the ray.
.if n .sp
.RS 4
.it 1 an-trap
.nr an-no-space-flag 1
.nr an-break-flag 1
.br
.ps +1
.B Warning
.ps -1
.br
.sp
\fIRtarea\fP may not correctly report area or center when
instancing is done at the group level. Using \fBxpush\fP can be a
workaround for this problem.
.sp .5v
.RE
.sp
The model geometry is the list of \fIobjects\fP in the input database
\fImodel.g\fP.
.sp
\fB\-X #\fP
.RS 4
Sets rtarea debug flags to a (hexadecimal) number. A flag
value of 1 causes 3\-D plot output to be written to stdout. All solid
RPPs are plotted as grey boxes, and the walk path is in alternating
blue and green segments. A flag value of 2 adds red segments for all
attempted steps, as well as the final steps. A flag value of 3 adds
some debugging prints to stderr in addition to the plots.  This is
useful for immediate path review, e.g., \f(CRrtarea \-X 1 ... | tiris\fP
.RE
.sp
\fB\-x #\fP
.RS 4
Sets librt debug flags to a (hexadecimal) number.
.RE
.sp
\fB\-n #\fP
.RS 4
Number of steps.
.RE
.sp
The \fBrtarea\fP program employs \fBlibrt\fP(3)
for the geometry interrogation.
.SH "ADDITIONAL OPTIONS"
.sp
To configure its behavior, \fBrtarea\fP makes use of the \fB\-c\fP
option.
.sp
Note that this approach is necessitated by the fact that \fIlibrt (3)\fP
has used up nearly the entire alphabet. A transition to GNU\-style long
option names is planned.
.sp
\fB\-c "set compute_centers=#"\fP
.RS 4
and
.RE
.sp
\fB\-c "set cc=#"\fP
.RS 4
determine whether area centers should be computed
and reported. Valid values are 1 (on) and 0 (off). The default is off.
.RE
.SH "EXAMPLES"
.sp
.B Example 1. Rtarea processing of example.g
.br
.RS 4
.sp
The command \fBrtarea example.g all\fP computes the area for model
\(aqexample.g\(aq group \(aqall\(aq.
.sp
The command \fBrtarea \-c "set cc=1" example.g all\fP computes the
area and centers for model \(aqexample.g\(aq group \(aqall\(aq.
.RE
.SH "SEE ALSO"
.sp
\fBmged\fP(1), \fBrt\fP(1),
\fBpix\-fb\fP(1),
\fBlibrt\fP(3), \fBpix\fP(5)
.SH "DIAGNOSTICS"
.sp
Numerous error conditions are possible. Descriptive messages are
printed on stderr.
.SH "AUTHOR"
.sp
BRL\-CAD Team
.SH "COPYRIGHT"
.sp
This software is Copyright (c) 1989\-2021 by the United States
Government as represented by U.S. Army Research Laboratory.
.SH "BUG REPORTS"
.sp
Reports of bugs or problems should be submitted via electronic mail to
.MTO "devs\(atbrlcad.org" "" ""