'\" t
.\"     Title: rtwizard
.\"    Author: [see the "AUTHOR(S)" section]
.\" Generator: Asciidoctor 2.0.10
.\"      Date: 2021-09-13
.\"    Manual: BRL-CAD
.\"    Source: BRL-CAD
.\"  Language: English
.\"
.TH "RTWIZARD" "1" "2021-09-13" "BRL\-CAD" "BRL\-CAD"
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.ss \n[.ss] 0
.nh
.ad l
.de URL
\fI\\$2\fP <\\$1>\\$3
..
.als MTO URL
.if \n[.g] \{\
.  mso www.tmac
.  am URL
.    ad l
.  .
.  am MTO
.    ad l
.  .
.  LINKSTYLE blue R < >
.\}
.SH "NAME"
rtwizard \- Combines images from several raytracing techniques to produce complex images.
.SH "SYNOPSIS"
.sp
\fBrtwizard\fP [\fIoptions\fP]...
.SH "DESCRIPTION"
.sp
\fBrtwizard\fP is a tool that automates the use of several BRL\-CAD
graphical programs to produce complex images.  There are two primary
modes of operation \- a graphical client to guide users through the
process of creating images, and a command line mode to allow users who
already know what options they wish to use to quickly and
automatically produce images.  Graphical mode is used when
insufficient information is supplied to produce an image (unless an
option specifically ruling out graphical mode is passed) and command
line mode (used automatically when there \fIis\fP enough information to
produce an image, unless GUI mode is specifically requested.) When in
graphical mode, rtwizard is self explanatory.  This manual documents
the command line options available when \fInot\fP operating in graphical
mode.
.sp
Images produced by \fIrtwizard\fP use three primary elements \- standard
full color raytracings produced by \fBrt\fP, "line drawing" style
images produced by \fBrtedge\fP, and a faded greyscale version of
color raytracings produced with a variety of image manipulation tools
included with BRL\-CAD.
.sp
When specifying options on the command line, it is usually better
practice to fully qualify what a particular item is \- for example,
using \fB\-i\fP to specifically identify the input file instead of
relying on the .g suffix.  There is a limited ability to recognize
common usage patterns (for example, "\fBrtwizard\fP file.g
output_image.png geometry_object" will generate an image of
geometry_object in the file output_image.png) but the most unambigous
specification uses the options.
.sp
The following options are recognized.
.SS "Input/Output Options"
.sp
\fIgeometry_file.g\fP
.RS 4
The first argument without an option flag (the
leftmost argument is regarded as the first) that identifies an
existing file with a .g suffix will be used to specify the working
geometry database, unless overridden by the \fBi\fP option.  Remember
that some option flags accept multiple arguments and can create
ambiguities about the meaning of a .g option and in such situations
\fBi\fP should be used.
.RE
.sp
\fB\-i\fP \fIgeometry_file\fP
.RS 4
Specifying the geometry database containing the
objects to be raytraced.  The \fBi\fP option will override a
non\-flagged geometry file specification.
.RE
.sp
\fIoutput_file.imgformat\fP
.RS 4
The name and image format of the final
output image generated by rtwizard.  When specifying the output file
name without using a flag, a .pix or .png image format extension is
necessary.  The first valid, unflagged output file name will be used
unless overridden by the \fBo\fP.  If the output filename uses a .png
image format extension, the Portable Network Graphics image format
will be used when writing out the file.  Otherwise, a standard BRL\-CAD
pix image will be generated. Remember that some option flags accept
multiple arguments and can create ambiguities about the meaning of a
image name option and in such situations \fBo\fP should be used.
.RE
.sp
\fB\-o\fP \fIoutput_file[.imgformat]\fP
.RS 4
The name (and optionally the image
format) of the final output image generated by rtwizard.  If the
output filename uses a .png file extension, the Portable Network
Graphics image format will be used when writing out the file.
Otherwise, a standard BRL\-CAD pix image will be generated.
.RE
.sp
\fB\-d\fP \fIframebuffer_device\fP
.RS 4
The type of framebuffer to use when
running fbserv to establish a framebuffer.  By default, "/dev/mem" is
used for a non\-graphical framebuffer \- other options include /dev/X,
/dev/ogl, and (Windows only) /dev/wgl. A /dev/mem framebuffer created
by \fBrtwizard\fP will be closed after the image generation is
complete.
.RE
.sp
\fB\-p\fP \fIport_number\fP
.RS 4
The number of the framebuffer port to use when
running \fBfbserv\fP to establish a framebuffer.  An existing
framebuffer may also be specified and used.  In the case of a
pre\-existing non\-graphical framebuffer, \fBrtwizard\fP will not close
the framebuffer automatically after the raytracing process is
complete.
.RE
.sp
\fB\-\-gui\fP
.RS 4
Run rtwizard\(cqs graphical interface, even if the command line
options specify enough information to produce an image.
.RE
.sp
\fB\-\-no\-gui\fP
.RS 4
Run rtwizard on the command line, even if the command
line options do not specify enough information to produce an image.
Overridden by \-\-gui option if both are specified.
.RE
.SS "Model View Options"
.sp
When it comes to preparing the view for an RtWizard image, there are
two options.  One is to use the "user level" controls, which reflect
the view manipulations used by users on the command line.  The other
is to use the "low level" specifiers, which are more typically used
when \fBrtwizard\fP is run by automated scripts.  The two methods are
mutually exclusive.
.sp
\fB\-a\fP \fIangle (degrees)\fP
.RS 4
Set azimuth angle.
.RE
.sp
\fB\-e\fP \fIangle (degrees)\fP
.RS 4
Set elevation angle.
.RE
.sp
\fB\-\-twist\fP \fIangle (degrees)\fP
.RS 4
Set twist angle.
.RE
.sp
\fB\-P\fP \fIangle (degrees)\fP
.RS 4
Set the perspective angle.
.RE
.sp
\fB\-z\fP \fIvalue\fP
.RS 4
Set the zoom factor (smaller factor results in a
smaller object in the view, and vice versa).
.RE
.sp
\fB\-\-center\fP \fIX Y Z\fP
.RS 4
Set the xyz coordinates of the center of the
view.
.RE
.SS "Image Generation Options"
.sp
The three options that are used to input geometry object lists need to
parse multiple arguments, so any options immediately following either
of them need to use an explicit argument flag to signal termination of
the input list to the option parser \- for example, an input .g file
needs to be specified with the \fB\-i\fP if it comes after a list of
ghost objects.
.sp
\fB\-c\fP \fIobj1[,...]\fP
.RS 4
Specify objects to render using full color using a
comma separated list.
.RE
.sp
\fB\-C\fP \fIvalue\fP
.RS 4
Set the background color to use when raytracing full
color objects.  May use R/G/B or hex style color specification.
.RE
.sp
\fB\-g\fP \fIobj1[,...]\fP
.RS 4
Specify objects to be rendered using ghosting
using a comma separated list.
.RE
.sp
\fB\-G\fP \fIvalue\fP
.RS 4
Control the degree of visibility to use when rendering
ghost objects.
.RE
.sp
\fB\-l\fP \fIobj1[,...]\fP
.RS 4
Specify objects to render lines with using rtedge
using a comma separated list.
.RE
.sp
\fB\-\-line\-color\fP \fIvalue\fP
.RS 4
Specify color to use when rendering edge
lines.  In addition to R/G/B and hex color specifications, the keyword
"region" is also supported \- in the latter case, region colors will be
used for lines.
.RE
.sp
\fB\-\-non\-line\-color\fP \fIvalue\fP
.RS 4
Specify color rtedge will use for
non\-line rendering.
.RE
.sp
\fB\-n\fP \fIvalue\fP
.RS 4
Specify the height of the generated image in pixels.
.RE
.sp
\fB\-O\fP \fIvalue\fP
.RS 4
Specify the occlusion mode rtedge will use for line
rendering.
.RE
.sp
\fB\-s\fP \fIvalue\fP
.RS 4
Specify the width and height of the generated image in
pixels.  Width can be overridden by the \fBw\fP option and height by
the \fBn\fP option.
.RE
.sp
\fB\-t\fP \fIimage_type\fP
.RS 4
Specify the type of image to be rendered. The
images produces by \fBrtwizard\fP are categorized by \fIpicture type\fP \-
there are six picture types built on full color raytracing, ghosting,
and \fBrtedge\fP line renderings. If a type is specified and
insufficient information is supplied to generate that particular image
type, rtwizard will exit with an error.
.sp
.it 1 an-trap
.nr an-no-space-flag 1
.nr an-break-flag 1
.br
.B Table 1. RtWizard Image Types
.TS
allbox tab(:);
lt lt lt.
T{
.sp
Type
T}:T{
.sp
Name
T}:T{
.sp
Description
T}
T{
.sp
A
T}:T{
.sp
Simple Full\-Color Image
T}:T{
.sp
Standard \fBrt\fP image.
T}
T{
.sp
B
T}:T{
.sp
Simple Line Drawing
T}:T{
.sp
Standard \fBrtedge\fP image.
T}
T{
.sp
C
T}:T{
.sp
Highlighted Image
T}:T{
.sp
Full Color \fBrt\fP image enhanced with \fBrtedge\fP lines.
T}
T{
.sp
D
T}:T{
.sp
Mixed Full Color and Edges
T}:T{
.sp
Like Type C, except objects may be selectively enhanced with \fBrtedge\fP lines.
T}
T{
.sp
E
T}:T{
.sp
Ghost Image with Inserts
T}:T{
.sp
A combination of Full Color elements and faded greyscale raytracings for context.
T}
T{
.sp
F
T}:T{
.sp
Ghost Image with Inserts and Edges
T}:T{
.sp
A Type E image further enhanced with \fBrtedge\fP lines.
T}
.TE
.sp
.RE
.sp
\fB\-w\fP \fIvalue\fP
.RS 4
Specify the width of the generated image in pixels.
.RE
.SH "EXAMPLES"
.sp
Introduction
.sp
.B Example 1. Basic Color Image
.br
.RS 4
.sp
\f(CRrtwizard m35.g component\fP
.sp
Results in a default color image of the m35 truck, output to
rtwizard.pix
.RE
.sp
.B Example 2. Line Drawing Image
.br
.RS 4
.sp
\f(CRrtwizard \-d /dev/ogl m35.g \-l component\fP
.sp
Results in a line drawing of the m35 truck being display in an OpenGL
framebuffer
.RE
.sp
.B Example 3. Complex Image
.br
.RS 4
.sp
\f(CRrtwizard \-d /dev/ogl \-i m35.g \-c component/power.train \-g component \-l component\fP
.sp
Results in a view of the m35 truck highlighting the engine (in color)
with the truck being shown as a ghosted, edged background.
.RE
.sp
.B Example 4. Complex Image with Non\-Default View
.br
.RS 4
.sp
\f(CRrtwizard \-d /dev/ogl \-i m35.g \-c component/power.train \-g component \-l component \-a \-35 \-e 15 \-z 1.6\fP
.sp
Same as the previous image, except viewing the truck from a different
direction and zoomed in closer.
.RE
.sp
.B Example 5. Multiple Color Objects
.br
.RS 4
.sp
\f(CRrtwizard \-d /dev/ogl \-i m35.g \-c component/power.train,component/suspension \-z 1.6\fP
.sp
View the power train and suspension of the truck as color objects.
.RE
.SH "SEE ALSO"
.sp
\fBrt\fP(1), \fBrtedge\fP(1)
.SH "AUTHOR"
.sp
BRL\-CAD Team
.SH "BUGS"
.sp
Most deficiencies observed while using the \fBrtwizard\fP program are
a consequence of problems in commands used by rtwizard to generate
images, such as rtedge.
.SH "COPYRIGHT"
.sp
This software is Copyright (c) 1989\-2021 by the United States
Government as represented by U.S. Army Research Laboratory.
.SH "BUG REPORTS"
.sp
Reports of bugs or problems should be submitted via electronic mail to
.MTO "devs\(atbrlcad.org" "" ""