'\" t
.\"     Title: pix
.\"    Author: [see the "AUTHOR(S)" section]
.\" Generator: Asciidoctor 2.0.10
.\"      Date: 2021-07-14
.\"    Manual: BRL-CAD
.\"    Source: BRL-CAD
.\"  Language: English
.\"
.TH "PIX" "5" "2021-07-14" "BRL\-CAD" "BRL\-CAD"
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.ss \n[.ss] 0
.nh
.ad l
.de URL
\fI\\$2\fP <\\$1>\\$3
..
.als MTO URL
.if \n[.g] \{\
.  mso www.tmac
.  am URL
.    ad l
.  .
.  am MTO
.    ad l
.  .
.  LINKSTYLE blue R < >
.\}
.SH "NAME"
pix \- Color RGB image file format and utilities
.SH "FORMAT"
.sp
A \fIpix\fP file contains sequences of pixels. Each pixel is stored as
three \fIunsigned char\fPs, first red, then green, then blue. The
intensity of each color ranges from 0 ("off") to 255 ("on"). The first
pixel in a \fIpix\fP file is the lower left corner of the image. The
pixels proceed from left\-to\-right across each scanline, with scanlines
being written from the bottom to the top of the image.
.sp
By convention, \fIpix\fP images are usually square, and thus their
dimensions can be determined by the file size.  If this is not the
case, often only the file width need be known by a program reading the
file.  History has left us with two "standard" sizes, 512x512 and the
"higher" 1024x1024. A common practice for other file sizes is to
include the file width in the filename.
.sp
At some time in the future \fIpix\fP files will probably get self\-typing
headers so that parameters such as their size can be automatically
determined by programs.
.SH "UTILITIES"
.sp
\fIpix\-fb\fP
.RS 4
display a .pix format image on a framebuffer.
.RE
.sp
\fIfb\-pix\fP
.RS 4
produce a .pix file from a framebuffer image.
.RE
.sp
\fIpix\-bw\fP
.RS 4
convert a .pix file to a black and white .bw file.
.RE
.sp
\fIbw\-pix\fP
.RS 4
convert a black and white .bw file to a .pix file.
.RE
.sp
\fIap\-pix\fP
.RS 4
convert an Applicon Color Plotter file to a .pix file.
.RE
.sp
\fIpixtile\fP
.RS 4
combine several small .pix files into one large one.
.RE
.sp
\fIpixstat\fP
.RS 4
gives statistics concerning a .pix file.
.RE
.sp
\fIpixhist\fP
.RS 4
displays a color histogram on a framebuffer.
.RE
.sp
\fIpixhist3d\fP
.RS 4
display three views of an RGB color space histogram on
a framebuffer.
.RE
.sp
\fIpixhist3d\-plot3\fP
.RS 4
unix plot of RGB color space utilization.
.RE
.sp
\fIpixdiff\fP
.RS 4
shows which pixels/colors differ between two .pix files.
.RE
.sp
\fIpixrect\fP
.RS 4
extracts an arbitrary rectangle from a .pix file.
.RE
.sp
\fIpixrot\fP
.RS 4
rotate, reverse, or invert a .pix file.
.RE
.sp
\fIpixscale\fP
.RS 4
scale a .pix file up or down.
.RE
.sp
\fIpixfilter\fP
.RS 4
a collection of 3x3 kernel filters for .pix files.
.RE
.sp
\fIbw3\-pix\fP
.RS 4
merges three .bw files into one .pix file.
.RE
.sp
\fIpix\-bw3\fP
.RS 4
separates .pix file RGB colors into three .bw files.
.RE
.SH "FILES"
.sp
file.pix
.SH "SEE ALSO"
.sp
\fBbrlcad\fP(1), \fBbw\fP(5), and
above named programs.
.SH "AUTHOR"
.sp
BRL\-CAD Team
.SH "COPYRIGHT"
.sp
This software is Copyright (c) 1989\-2021 by the United States
Government as represented by U.S. Army Research Laboratory.
.SH "BUG REPORTS"
.sp
Reports of bugs or problems should be submitted via electronic mail to
.MTO "devs\(atbrlcad.org" "" ""