[[_voliiiintro]]
= Introduction
:doctype: book
:sectnums:
:toc: left
:icons: font
:experimental:
:sourcedir: .

Since 1979, the U.S.  Army Research Laboratory (ARL) has been
developing and distributing the U.S.  Army Ballistic Research
Laboratory - Computer-Aided Design (BRL-CAD) constructive solid
geometry (CSG) modeling package for a wide range of military and
industrial applications.  The package includes a large collection of
tools and utilities including an interactive geometry editor,
raytracing and generic framebuffer libraries, network-distributed
image-processing/signal-processing capabilities, and an embedded
scripting language.

As part of this effort, a multivolume tutorial series is under
development to assist users with the many features of the BRL-CAD
package.  Volume I provides an overview of the package contents and
installation (Butler and Edwards, 2002). Volume II addresses the basic
features and functionality of the package's Multi-Device Geometry
Editor (MGED) and offers a comprehensive list of the user commands
available (Butler et al., 2001). These documents are available for
download at http://ftp.arl.army.mil/brlcad/ (U.S.  ARL, 2003).

The purpose of Volume III is to discuss the components of the modeling
process and suggest principles for maximizing the effectiveness of
BRL-CAD's capabilities.  Because of the large diversity in modeling
projects, these principles have largely been kept to a general nature
so that they have the widest applicability possible.  In addition,
several appendices have been included to offer detailed discussions on
several BRL-CAD tools and features, including the pipe primitive
(Appendix A), the projection shader (Appendix B), the extruded bitmap
primitive (Appendix C), the .mgedrc file (Appendix D), the Build
Pattern tool (Appendix E), and the build_region command (Appendix F).

Future volumes in the tutorial series are planned to discuss geometry
format conversion, advanced modeling features, and programming
options.