= Creating primitive objects

Most types of xref:BRL-CAD_Primitives.adoc[*primitive geometric
objects*] can be created using any of the following MGED command line
(CLI) or graphical user interface (GUI) commands:

*in* :: Entering a CLI *in* command allows you to interactively create
an object with a specified name, type and parameters. That information
can either be included in the initial command or provided in response
to prompts that are displayed if any required information is omitted
from the command line.
*form* :: Selecting *Primitive Editor* from the GUI *Edit* menu
displays a form/dialog box you can use to name, set the parameters of
and then create objects of most (but not all) types. Some derivative
objects do not have their own forms, in which case the primitive
editor will display the base object's form.
*create* :: Selecting an object type from the GUI *Create* menu
displays the object-naming dialog box, then creates and displays an
object of that type having default parameter values.
*make* :: Entering a CLI *make* command also creates and displays an
object of a specified type having a specified name and default
parameter values.

Note that the Create menu is essentially the GUI equivalent of the CLI
make command. After using either, you will generally want to
xref:Changing_the_properties_of_primitive_objects.adoc[*edit*] the
resulting object's default location, shape and size.

Primitive objects can also be created by:

* using the CLI *cp* command to make a copy of an existing object,
which can then be moved and modified;
* using the CLI *dbconcat* or GUI File->Import command to merge in all
objects defined by another geometry file; and
* entering TCL *put* commands via the command window.

See also:

* xref:Determining_the_properties_of_primitive_objects.adoc[]
* xref:Changing_the_properties_of_primitive_objects.adoc[]
