= Early Raytracing History

Even though the BRL-CAD computer aided design package has a very long
development history by the standards of most modern software, it is
actually the latest in a line of raytracing systems dating back to the
1960s. Much of that history is documented in technical reports from
the Ballistic Research Laboratory (later the U.S. Army Research
Laboratory.)  A first hand account of Richard Hoyt's earliest work on
vehicle shotline calculations by Davidson C. Hardison can be found in
http://www.arl.army.mil/arlreports/1999/ARL-SR-90.pdf[ARL-SR-90],
starting at the bottom of page 29. Although the report does not
explicitly date Hoyt's work, from context it appears to have taken
place in the mid to late 1950s. This account details what may very
well be the first true raytracing of a geometric model, done quite
literally _by hand!_ Although not computerized, this work appears to
be the original foundation on which all of the Ballistic Research
Laboratory's subsequent computerized raytracing systems were
designed - if anyone knows more about this very early work and whether
any records of it still survive, the BRL-CAD developers would be quite
interested to see it!

== MAGIC

Although there were immediately efforts to use available computer
systems like ORDVAC to assist with the enormous bookkeeping involved
in shotline calculations, the first computerized raytracer at the
Ballistic Research Laboratory that appears in technical reports was
the MAGIC system, developed by Mathematical Applications
Group, Inc. (MAGI) in the mid 1960s. Richard Hoyt is listed as BRL's
technical supervisor on the project. MAGI later went on to play a
https://design.osu.edu/carlson/history/tree/magi.html[significant
role] in the commercial development of CGI. The seminal report
detailing the original MAGIC work is "A Geometric Description
Technique Suitable for Computer Analysis of Both the Nuclear and
Conventional Vulnerability of Armored Military Vehicles," published in
August 1967. This report slightly pre-dates even Appel's papers and
cites no previous reports as source material for its raytracing
techniques (which is suggestive but not conclusive - if anyone knows
of earlier reports bearing on this topic we would very much like to
know about them.) As it was not approved for public release until much
later, its direct impact outside military circles was limited. Also,
the primary purpose of this technique from the Army's point of few was
analysis rather than realistic images.  Nevertheless MAGI-6701 stands
out as an important historical document in the field of computer
graphics.

The other significant sources of information known to exist about the
first MAGIC system are a set of manuals prepared by the Joint
Technical Coordinating Group for Munitions Effectiveness (JTCG/ME) in
1970-71 and the proceedings of the first (and apparently last?)
conference held for the users of the MAGIC and SAM-C codes in 1971.

[cols=3*~]
|===
| Report Title | Number | Date

| http://www.dtic.mil/dtic/tr/fulltext/u2/847576.pdf[A Geometric Description Technique Suitable for Computer Analysis of Both the Nuclear and Conventional Vulnerability of Armored Military Vehicles]
| MAGI-6701
| August 1967

| http://www.dtic.mil/dtic/tr/fulltext/u2/a567888.pdf[MAGIC Computer Simulation - Volume I. User Manual]
| 61 JTCG/ME-71-7-1
| 1970

| http://www.dtic.mil/dtic/tr/fulltext/u2/a567889.pdf[MAGIC Computer Simulation - Volume II. Analyst Manual Part 1]
| 61 JTCG/ME-71-7-2-1
| 1971

| http://www.dtic.mil/dtic/tr/fulltext/u2/a567890.pdf[MAGIC Computer Simulation - Volume II. Analyst Manual Part 2]
| 61 JTCG/ME-71-7-2-2
| 1971

| http://www.dtic.mil/dtic/tr/fulltext/u2/728124.pdf[The First Conference of Users of the Magic and SAM-C Programs]
| AD728124
| 1971
|===

(Note: Subsequent reports mention something called the SHOT GENERATOR
Computer program that appears to date to the same time period as
MAGIC, but I currently have no information about this code, the
JTCG/ME reports that document it, or what role it played - it is
referenced as an influence in the GIFT code design, so more
information (if available) would be interesting.)

== GIFT

Geometric Information for Targets (GIFT) succeeded MAGIC as BRL's
primary raytracer. By 1975, the first volume of a GIFT user manual had
been published documenting the new system. The second volume followed in
1979.

[cols=3*~]
|===
| Report | Number | Date

| http://www.dtic.mil/dtic/tr/fulltext/u2/b006037.pdf[The Gift Code User Manual. Volume I. Introduction and Input Requirements.]
| BRL-1802
| 1975

| http://www.dtic.mil/dtic/tr/fulltext/u2/a078364.pdf[The Gift Code User Manual. Volume II. The Output Options.]
| ARBRL-TR-02189
| 1979
|===

Unlike MAGIC, which apparently lasted only a couple years, GIFT was in
production use at BRL for a long period of time. Consequently, there
are a significant number of reports that detail uses of the GIFT
system and the development of solid modeling at BRL during the GIFT
years.

[cols=3*~]
|===
| Report | Number | Date

| http://www.dtic.mil/dtic/tr/fulltext/u2/a037898.pdf[MIFT: GIFT Combinatorial Geometry Input to VCS Code.]
| ADA037898
| MAR 1977

| http://www.dtic.mil/dtic/tr/fulltext/u2/a089818.pdf[The Prone Protected Posture]
| AMSAA-TR-284
| August 1980

| http://www.dtic.mil/dtic/tr/fulltext/u2/b060185.pdf[Combinatorial Geometry Computer Models of Sitting and Standing Crew Personnel]
| ARBRL-MR-03125
| AUG 1981

| http://www.dtic.mil/dtic/tr/fulltext/u2/a145001.pdf[COM-GEOM Interactive Display Debugger (CIDD)]
| ARBRL-TR-02574
| August 1984

| http://www.dtic.mil/dtic/tr/fulltext/u2/a161828.pdf[A Combinatorial Geometry Target Description of the High Mobility Multipurpose Wheeled Vehicle (HMMWV)]
| BRL-TR-2686
| October 1985
|===

== BRL-CAD

The final transition from GIFT to BRL-CAD was accomplished in (??). A
number of reports in this era deal with solid modeling as a technique
more than the specifics of BRL-CAD vs. GIFT, and so may reasonably be
regarded as applying to both.

[cols=3*~]
|===
| Report | Number | Date

|
|
|
|===

== Other Early Computational Analysis Efforts

=== The Air Force's MAGIC System

Although it is not a direct ancestor of BRL-CAD, Bell Aerospace was
also developing an early computer based analytical system in the late
1960s and early 1970s for the Air Force Flight Dynamics Laboratory
called MAGIC:

[cols=2*~]
|===
| Report | Summary

| http://www.dtic.mil/docs/citations/AD0685190[MAGIC: An Automated General Purpose System for Structural Analysis. Volume 1.]
| Engineer's Manual

| http://www.dtic.mil/docs/citations/AD0691893[MAGIC: An Automated General Purpose System for Structural Analysis. Volume 2.]
| User's Manual

| http://www.dtic.mil/docs/citations/AD0685191[MAGIC: An Automated General Purpose System for Structural Analysis. Volume 3.]
| Programmer's Manual

| http://www.dtic.mil/docs/citations/AD0726564[MAGIC II: An Automated General Purpose System for Structural Analysis. Volume 1.]
| Engineer's Manual (Addendum)

| http://www.dtic.mil/docs/citations/AD0726565[MAGIC II: An Automated General Purpose System for Structural Analysis. Volume 2.]
| User's Manual

| http://www.dtic.mil/docs/citations/AD0726566[MAGIC II: An Automated General Purpose System for Structural Analysis. Volume 3.]
| Programmer's Manual

| http://www.dtic.mil/docs/citations/AD0755368[MAGIC III: An Automated General Purpose System for Structural Analysis Volume 1.]
| Engineer's Manual

| http://www.dtic.mil/docs/citations/AD0755369[MAGIC III: An Automated General Purpose System for Structural Analysis. Volume 2.]
| User's Manual

| http://www.dtic.mil/docs/citations/AD0755370[MAGIC III: An Automated General Purpose System for Structural Analysis. Volume 3.]
| Programmer's Manual
|===
