= BRL-CAD Customer Profile: Ronja

_by Kyle Bodt_

Ronja (Reasonable Optical Near Joint Access) is an innovative piece of
equipment that utilizes reliable optical data links to create a current
communication range of 1.4 km and a speed of 10Mbps full duplex that can
be used as a general purpose wireless link for virtually any networking
project. This is a very important project for Twibright Labs, a small
group of computer science graduate students operating out of Charles
University in Prague in the Czech Republic. The group specializes in the
usage of Free Software and User Controlled Technology Development.

The primary output for the Ronja project is a design. The lab does not
intend to manufacture and sell the hardware that is being designed but
wants to engage in open source development of the technology. The
philosophy surrounding User Controlled Technology is the ideal that the
end-user is provided with unrestricted access to the intellectual
property surrounding the technology, including the tools that are being
used to create it. One tool playing an integral part in the development
of the Ronja designs is BRL-CAD. All of the models that Twibright labs
use to display the different variants of their Ronja concept were
created with the help of BRL-CAD. BRL-CAD has allowed the members of
Twibright labs to create instructional diagrams so that the users and
builders of their open source technology will be able to have the latest
information with regard to the proper construction of a Ronja unit. The
interactive geometry editor and ray-tracers in BRL-CAD are an integral
part in the communication of design plans for Twibright labs and enables
them to connect with the users, who are the driving force behind the
User Controlled Technology ideal.

* http://ronja.twibright.com/[Ronja homepage]
