= APROPOSLIB(nged)
BRL-CAD Team
ifndef::site-gen-antora[:doctype: manpage]
:man manual: BRL-CAD User Commands
:man source: BRL-CAD
:page-role: manpage

== NAME

aproposlib - 
      Searches through the one-line usage messages for a specified
      BRL-CAD library interface command and displays the name of each command where
      a match is found.
    

== SYNOPSIS

*aproposlib* {_keyword_}

== DESCRIPTION

The [cmd]*aproposlib* command searches through the one-line usage messages for a specified BRL-CAD library interface command and displays the name of each command where a match is found. 

== EXAMPLES

The example demonstrates the use of the [cmd]*aproposlib* command to search the one-line usage messages for a particular BRL-CAD library interface command. 

.Using the [cmd]*aproposlib* command to search theone-line usage messages for a particular BRL-CAD library interfacecommand containing "mat." 
====
[prompt]#mged>#[ui]`aproposlib mat`



....

dgo_rtweight dm_drawDataAxes dm_drawModelAxes dm_drawViewAxes dm_loadmat mat_ae
mat_ae_vec mat_aet_vec mat_angles mat_arb_rot mat_eigen2x2 mat_fromto mat_inv
mat_lookat mat_mul mat_scale_about_pt mat_trn mat_vec_ortho mat_vec_perp
mat_xform_about_pt mat_xrot mat_yrot mat_zrot quat_mat2quat quat_quat2mat
vo_model2view vo_pmat vo_pmodel2view vo_rmat vo_view2model wdb_attr wdb_bot_decimate
wdb_list wdb_match wdb_nmg_collapse wdb_paths wdb_pull wdb_push wdb_search wdb_showmats
wdb_xpush
....
====

== AUTHOR

BRL-CAD Team

== BUG REPORTS

Reports of bugs or problems should be submitted via electronic mail to mailto:devs@brlcad.org[]