= B(nged)
BRL-CAD Team
ifndef::site-gen-antora[:doctype: manpage]
:man manual: BRL-CAD User Commands
:man source: BRL-CAD
:page-layout: base

== NAME

B - 
      Clears the mged display of any currently
      displayed objects, then displays the list of objects provided in
      the parameter list.
    

== SYNOPSIS

*B* [[-A -o] | _attribute name_ {_value_}...] [-s] [-C#/#/#] [-R] [_objects_]

== DESCRIPTION

Clears the mged display of any currently displayed objects, then displays the list of objects provided in the parameter list. Equivalent to the [cmd]*Z* command followed by the command [cmd]*draw*__<objects>__. The _-C_ option provides the user a way to specify a color that overrides all other color specifications including combination colors and region id-based colors. The __-A__and _-o_ options allow the user to select objects by attribute. The _-s_ option specifies that subtracted and intersected objects should be drawn with solid lines rather than dot-dash lines. The -R option means do not automatically resize the view if no other objects are displayed. See the [cmd]*draw* command for a detailed description of the options. 

== EXAMPLES

The following are run from the MGED command prompt. 

.Display a named object
====

[prompt]#mged>#[ui]`B some_object`::
The display clears, and the object named _some_object_ is displayed. 
====

.Draw objects having an attribute with a value 
====
[prompt]#mged>#[ui]`B -A -o Comment {First comment} Comment {Second comment}`

The display clears, then draws objects that have a "Comment" attribute with a value of either "First comment" or "Second comment." 
====

== AUTHOR

BRL-CAD Team

== BUG REPORTS

Reports of bugs or problems should be submitted via electronic mail to mailto:devs@brlcad.org[]