= BEV(nged)
ifndef::site-gen-antora[:doctype: manpage]
:man manual: BRL-CAD User Commands
:man source: BRL-CAD
:page-role: manpage

== NAME

bev - Performs the operations indicated in the Boolean_formula and
    stores the result in new_obj.
    

== SYNOPSIS

*bev* [-t] [-P#] {_new_obj_} {_Boolean_formula_}

== DESCRIPTION

Performs the operations indicated in the _Boolean_formula_ and stores the result in __new_obj__. The _new_obj_ will be stored as an NMG shape (it may be converted to a polysolid by using the [cmd]*nmg_simplify* command). If the -t option is specified, then the resulting object will consist entirely of triangular facets. The default is to allow facets of any complexity, including holes. The _-P_ option specifies the number of CPUs to use for the calculation (however, this is currently ignored). Only simple _Boolean_formulas_ are allowed. No parentheses are allowed and the operations are performed from left to right with no precedence. More complex expressions must be expressed as BRL-CAD objects using the [cmd]*r*, [cmd]*g*, or [cmd]*c*commands and evaluated using the [cmd]*facetize* or [cmd]*ev* commands. 

== EXAMPLES

The example demonstrates the use of the [cmd]*bev* command with the _-t_ option to create a triangulated object. 

.Creating a triangulated object by intersecting two objects
====

[prompt]#mged>#[ui]`bev -t triangulated_lens sphere1 + sphere2`::
Creates a triangulated object by intersecting objects _sphere1_ and _sphere2_
====

== AUTHOR

BRL-CAD Team

== BUG REPORTS

Reports of bugs or problems should be submitted via electronic mail to mailto:devs@brlcad.org[]