= BO(nged)
BRL-CAD Team
ifndef::site-gen-antora[:doctype: manpage]
:man manual: BRL-CAD User Commands
:man source: BRL-CAD
:page-layout: base

== NAME

bo - Used to create or retrieve binary opaque objects.

== SYNOPSIS

*bo* {[-i u {type}] | [-o]} {_destination_} {_source_}

== DESCRIPTION

Used to create or export binary opaque objects.  One of _-i_ or _-o_ must be specified to input or output data respectively. The _-i_ option will create a binary object, and the _-o_ option will write out a binary object's data. Currently, only uniform binary objects (arrays of values) are supported on input.  On input, the _destination_ is the name of the object to be created, and the source is the path to a file to read. On output, _destination_ is the path to a file to write out with the contents of the binary object specified as the __source__. The _type_ may be one of: 
// <simplelist type="vert">
//       <member>f -&gt; float</member>
//       <member>d -&gt; double</member>
//       <member>c -&gt; char (8 bit)</member>
//       <member>s -&gt; short (16 bit)</member>
//       <member>i -&gt; int (32 bit)</member>
//       <member>l -&gt; long (64 bit)</member>
//       <member>C -&gt; unsigned char (8 bit)</member>
//       <member>S -&gt; unsigned short (16 bit)</member>
//       <member>I -&gt; unsigned int (32 bit)</member>
//       <member>L -&gt; unsigned long (64 bit)</member>
//     </simplelist>

Note:  this command was previously named "dbbinary".

== EXAMPLES

The examples show the use of the [cmd]*bo* command to both create (__-i__ option) and to retrieve a binary object (__-o__ option). 

.Create an opaque uniform binary object of characters with a specified namecontaining the contents of a particular file.
====
[prompt]#mged>#[ui]`bo -i u c cmds /usr/brlcad/html/manuals/mged/mged_cmds.html`

Creates an opaque uniform binary object of characters with the name _cmds_	that contains the contents of the file __/usr/brlcad/html/manuals/mged/mged_cmds.html__. 
====

.Import data for a displacement map (DSP) object
====
[prompt]#mged>#[ui]`bo -i u S dsp.data /path/to/file.dsp`

This imports a file named _file.dsp_ that contains DSP data, i.e., raw data in unsigned short (16-bit) format.  The data is saved in the .g database into an object named __dsp.data__.  When creating a DSP, this _dsp.data_ object can be specified as the data source.
====

.Copy the contents of a particular binary object into a specified file.
====
[prompt]#mged>#[ui]`bo -o /home/jim/cmds.html cmds`

Copies the contents of the binary object named _cmds_ into the file named __/home/jim/cmds.html__. 
====

== AUTHOR

BRL-CAD Team

== BUG REPORTS

Reports of bugs or problems should be submitted via electronic mail to mailto:devs@brlcad.org[]