= BOT_FACE_SORT(nged)
BRL-CAD Team
ifndef::site-gen-antora[:doctype: manpage]
:man manual: BRL-CAD User Commands
:man source: BRL-CAD
:page-layout: base

== NAME

bot_face_sort - 
      Sorts the list of triangles that constitutes the BOT primitive to
      optimize it for raytracing with the specified number of triangles per
      piece.
    

== SYNOPSIS

*bot_face_sort* {_triangles_per_piece_} {_bot_primitive1>_} [_bot_primitive2 bot_primitive3_]...

== DESCRIPTION

Used to sort the list of triangles that constitutes the BOT primitive to optimize it for raytracing with the specified number of triangles per piece. Most BRL-CAD primitives are treated as a single object when a model is being prepared for raytracing, but BOT primitives are normally broken into "pieces" to improve performance. The raytracer normally uses four triangles per piece. 

== EXAMPLES

The example shows the use of the [cmd]*bot_face_sort* command to sort the list of triangles that constitutes the BOT primitive to optimize it for raytracing. 

.Sorting the faces of two primitives (each having four triangles per piece) to optimize them for raytracing 
====

[prompt]#mged>#[ui]`bot_face_sort 4 bot1 bot2`::
The faces of _bot1_ and _bot2_ to optimize them for raytracing with four triangles per piece. 
====

== AUTHOR

BRL-CAD Team

== BUG REPORTS

Reports of bugs or problems should be submitted via electronic mail to mailto:devs@brlcad.org[]