= BOT_VERTEX_FUSE(nged)
BRL-CAD Team
ifndef::site-gen-antora[:doctype: manpage]
:man manual: BRL-CAD User Commands
:man source: BRL-CAD
:page-layout: base

== NAME

bot_vertex_fuse - 
      Used to eliminate duplicate vertices from a BOT solid.
    

== SYNOPSIS

*bot_vertex_fuse* {_new_bot_solid_} {_old_bot_primitive>_}

== DESCRIPTION

Used to eliminate duplicate vertices from a BOT solid. It returns the number of vertices eliminated. No tolerance is used, so the vertices must match exactly to be considered duplicates. 

== EXAMPLES

The example shows the use of the [cmd]*bot_vertex_fuse* command to eliminate duplicate vertices from a BOT solid and store the result in a new BOT primitive. 

.Eliminating duplicate vertices from a primitive and storing the result in a new BOT primitive.
====

[prompt]#mged>#[ui]`bot_vertex_fuse bot1_fused bot1_original`::
Eliminates any duplicate vertices from the primitive named _bot1_original_ and stores the result in the new BOT primitive named __bot1_fused__. 
====

== AUTHOR

BRL-CAD Team

== BUG REPORTS

Reports of bugs or problems should be submitted via electronic mail to mailto:devs@brlcad.org[]