= BOT_CONDENSE(nged)
BRL-CAD Team
ifndef::site-gen-antora[:doctype: manpage]
:man manual: BRL-CAD User Commands
:man source: BRL-CAD
:page-role: manpage

== NAME

bot_condense - 
      Used to eliminate unused vertices from a BOT primitive.
    

== SYNOPSIS

*bot_condense* {_new_bot_primitive_} {_old_bot_primitive_}

== DESCRIPTION

Used to eliminate unused vertices from a BOT primitive. It returns the number of vertices eliminated. 

== EXAMPLES

The examples shows the use of the [cmd]*bot_condense* command to eliminate unused vertices from a BOT primitive and store the result in a new BOT primitive. 

.Basic Condensing 
====
Eliminating unused vertices from a primitive named _bot1_original_ and storing the result in a new primitive named __bot1_condensed__. 

[prompt]#mged>#[ui]`bot_condense bot1_condensed bot1_original`::
The unused vertices were deleted from bot1_original and the result was saved in bot1_condensed. 
====

== AUTHOR

Reports of bugs or problems should be submitted via electronic mail to mailto:devs@brlcad.org[]

== BUG REPORTS

Reports of bugs or problems should be submitted via electronic mail to mailto:devs@brlcad.org[]