= BREP(nged)
ifndef::site-gen-antora[:doctype: manpage]
:man manual: BRL-CAD MGED User Commands
:man source: BRL-CAD
:page-role: manpage

== NAME

brep - 
    This command does a boundary representation which represents the solid geometry by describing the topology and corresponding geometry.
    

== SYNOPSIS

*brep*{_obj_}[--no-evaluation][_command_ | _brepname_ | _suffix_]

== DESCRIPTION

If [rep]_obj_ is not a brep object, then [cmd]*brep* attempts to convert it to a brep object. If [rep]_brepname_ is given, then [cmd]*brep* defaults to [rep]_obj__brep; if --no-evaluation is given, then [cmd]*brep* attempts to convert a combination to an unevaluated BREP named [rep]_suffix_ (again defaulting to [rep]_obj__brep). 

Otherwise, the behavior of [cmd]*brep* is determined by which of these subcommands is specified: 
*info*
::
Return count information (surfaces, curves, etc.) for a BREP. 
*info C*[_index_ | _index_-_index_]
::
Return information for a specific BREP '3D curve'. 
*info S*[_index_ | _index_-_index_]
::
Return information for a specific BREP 'surface'. 
*info F*[_index_ | _index_-_index_]
::
Return information for a specific BREP 'face'. 
*info T*[_index_ | _index_-_index_]
::
Return information for a specific BREP 'trim'. 
*info E*[_index_ | _index_-_index_]
::
Return information for a specific BREP 'edge'. 
*info TB*[_index_ | _index_-_index_]
::
Return information for a specific BREP 'piecewise bezier trim'. 
*info SB*[_index_ | _index_-_index_]
::
Return information for a specific BREP 'piecewise bezier surface'. 
*plot S*[_index_ | _index_-_index_]
::
Plot a specific BREP 'surface'. 
*plot Suv*{_index_ | _index_-_index_}{_u_}{_v_}
::
Plot a specific BREP 'surface' 3d point at specified uv. 
*plot UV*{_index_ | _index_-_index_}{_u1_}{_u2_}{_v1_}{_v2_}
::
Plot a specific BREP 'surface' 3d bounds at specified uv bounds. 
*plot F*[_index_ | _index_-_index_]
::
Plot a specific BREP 'face'. 
*plot I*[_index_ | _index_-_index_]
::
Plot a specific BREP 'isosurface'. 
*plot SN*[_index_ | _index_-_index_]
::
Plot a specific BREP 'surface normal'. 
*plot KN*[_index_ | _index_-_index_]
::
Plot a specific BREP 'surface knot'. 
*plot F2d*[_index_ | _index_-_index_]
::
Plot a specific BREP 'face in 2d'. 
*plot SBB*[_index_ | _index_-_index_]
::
Plot a specific BREP 'surfaceleafs'. 
*plot SBB2d*[_index_ | _index_-_index_]
::
Plot a specific BREP 'surfaceleafs in 2d'. 
*plot TD*[_index_ | _index_-_index_]
::
Plot a specific BREP 'trim direction'. 
*plot T*[_index_ | _index_-_index_]
::
Plot a specific BREP 'trim'. 
*plot T2d*[_index_ | _index_-_index_]
::
Plot a specific BREP 'trim in 2d'. 
*plot TBB*[_index_ | _index_-_index_]
::
Plot a specific BREP 'trimleafs'. 
*plot TBB2d*[_index_ | _index_-_index_]
::
Plot a specific BREP 'trimleafs in 2d'. 
*plot E*[_index_ | _index_-_index_]
::
Plot a specific BREP 'edge3d'. 
*plot SCV*[_index_ | _index_-_index_]
::
Plot a specific BREP 'nurbs control net'. 
*flip*
::
Flip all faces in the BREP (turns it 'inside out'). 
*translate*{_SCV_}{_index_}{_i_}{_j_}{_dx_}{_dy_}{_dz_}
::
Translate a surface control vertex 
*intersect*{_obj2_}{_i_}{_j_}[PP | PC | PS | CC | CS | SS]
::
Visualize intersecting two BREP objects.  The last argument specifies what portions of each to intersect; if it is not specified, it defaults to SS: 
+

PP::
Intersect a point from the first object with a point from the second.

PC::
Intersect a point from the first object with a curve from the second.

PS::
Intersect a point from the first object with a surface from the second.

CC::
Intersect a curve from the first object with a curve from of the second.

CS::
Intersect a curve from the first object with a surface from the second

SS::
Intersect a surface from the first object with a surface from the second.
*u*{obj2}{output}
::
Take the union of [rep]_obj_ and [rep]_obj2_, storing the result in [rep]_output_. 
*i*{obj2}{output}
::
Take the intersection of [rep]_obj_ and [rep]_obj2_, storing the result in [rep]_output_. 
*-*{obj2}{output}
::
Take the difference of [rep]_obj_ and [rep]_obj2_, storing the result in [rep]_output_. 
*x*{obj2}{output}
::
Take the exclusive or of [rep]_obj_ and [rep]_obj2_, storing the result in [rep]_output_. 
*csg*
::
Take the specified B-Rep and attempt to generate a CSG implicit boolean tree that will define the same solid shape. 

== EXAMPLES

.Info
====

[prompt]#mged>#[ui]`brep obj.randomobj info`::
This outputs general information about obj.randomobj, including counts of various entity types such as surfaces, curves, vertices, etc.

[prompt]#mged>#[ui]`brep obj.randomobj info F 2`::
Output info about the 2nd face of the BREP object obj.randomobj.
====

.Plot
====

[prompt]#mged>#[ui]`brep obj.randomobj plot S 1-3`::
This plots the 1st through 3rd surfaces of obj.randomobj in the graphics display window.
====

.Intersect
====

[prompt]#mged>#[ui]`brep obj.randomobj intersect sph2.randomobj 2 4`::
This displays the intersection of obj.randomobj's 2nd surface with sph2.randomobj's 4th surface.

[prompt]#mged>#[ui]`brep obj.randomobj intersect sph2.randomobj 3 2 PC`::
This displays the intersection of obj.randomobj's 3rd point with sph2.randomobj's 2nd curve.
====

== AUTHOR

BRLCAD-TEAM

== BUG REPORTS

Reports of bugs or problems should be submitted via electronic mail to mailto:devs@brlcad.org[]