= COLOR(nged)
BRL-CAD Team
ifndef::site-gen-antora[:doctype: manpage]
:man manual: BRL-CAD User Commands
:man source: BRL-CAD
:page-layout: base

== NAME

color - Creates an entry in the database that functions as part of a color
    lookup table for displayed regions.
    

== SYNOPSIS

*color* {_low high r g b str_}

== DESCRIPTION

Creates an entry in the database that functions as part of a color lookup table for displayed regions. The ident number for the region is used to find the appropriate color from the lookup table. The _low_ and _high_ values are the limits of region ident numbers to have the indicated _rgb_ color (0-255) applied. The _str_ parameter is intended to be an identifying character string, but is currently ignored. The current list of color table entries may be displayed with the [cmd]*prcolor* command, and the entire color table may be edited using the [cmd]*edcolor* command. If a color lookup table exists, its entries will override any color assigned using the [cmd]*mater* command. 

== EXAMPLES

The example shows the use of the [cmd]*color* command to make an entry in the color lookup table for regions within a specified range of idents. 

.Making an entry in the color lookup table for regions within a specifiedrange of idents using the color red.
====
[prompt]#mged>#[ui]`color 1100 1200 255 0 0 fake_string`

Makes an entry in the color lookup table for regions with idents from 1100-1200 using the color red. 
====

== AUTHOR

BRL-CAD Team

== BUG REPORTS

Reports of bugs or problems should be submitted via electronic mail to mailto:devs@brlcad.org[]