= COPYEVAL(nged)
BRL-CAD Team
:doctype: manpage
:man manual: BRL-CAD User Commands
:man source: BRL-CAD
:page-layout: base

== NAME

copyeval - Creates a new primitive object called new_ primitiveby
    applying the transformation matrices accumulated along the
    path_to_old_primitive to the leaf primitive shape object at the end
    of the path and saving the result under the name new_ primitive.
    

== SYNOPSIS

*copyeval* {_new_primitive path_to_old_primitive_}

== DESCRIPTION

Objects in a _BRL-CAD_ model are stored as Boolean trees (combinations), with the members being primitive shapes or other Boolean trees. Each member has a transformation matrix associated with it. This arrangement allows a primitive to be a member of a combination, and that combination may be a member of another combination, and so on. When a combination is displayed, the transformation matrices are applied to its members and passed down through the combinations to the leaf (primitive shape) level. The accumulated transformation matrix is then applied to the primitive before it is drawn on the screen. The [cmd]*copyeval* command creates a new primitive object called _new_ primitive_ by applying the transformation matrices accumulated along the _path_to_old_primitive_ to the leaf primitive shape object at the end of the path and saving the result under the name _new_ primitive._ The _path_to_old_ primitive_ must be a legitimate path ending with a primitive shape. 

== EXAMPLES

The example shows the use of the [cmd]*copyeval* command to create a new primitive by applying the transformation matrices along the path to the old primitive. 

.Create a new primitive object by applying the transformation matrices along the pathto the old primitive.
====
[prompt]#mged>#[ui]`copyeval shapeb comb1/comb2/comb3/shapea`

Creates _shapeb_ from _shapea_ by applying the accumulated transformation matrices from the path comb1/comb2/comb3.
====

== AUTHOR

BRL-CAD Team

== BUG REPORTS

Reports of bugs or problems should be submitted via electronic mail to mailto:devs@brlcad.org[]