= DEBUGLIB(nged)
BRL-CAD Team
ifndef::site-gen-antora[:doctype: manpage]
:man manual: BRL-CAD User Commands
:man source: BRL-CAD
:page-layout: base

== NAME

debuglib - Allows the user to set or check the debug flags used by
    librt.
    

== SYNOPSIS

*debuglib* [_hex_code_]

== DESCRIPTION

Allows the user to set or check the debug flags used by __librt__. With no arguments, the [cmd]*debuglib* command displays all the possible settings for the _librt_ debug flag and the current value. When a _hex_code_ is supplied, that value is used as the new value for the flag. Similar debug commands for other _BRL-CAD_ libraries are [cmd]*debugbu* for _libbu_ and [cmd]*debugnmg*for the NMG portion of __librt__. 

== EXAMPLES

The first example shows the use of the [cmd]*debuglib* command (without an argument) to list the available debug values for _librt_ and the current value.  The second example shows the use of the [cmd]*debuglib* command with a hex code, which sets the _librt_ debug flag to that value. 

.List available debug values for _librt_ and the current value.
====
[prompt]#mged>#[ui]`debuglib`

Lists available debug values for _librt_ and the current value.
====

.Set the _librt_ debug flag to a specific value.
====
[prompt]#mged>#[ui]`debuglib 1`

Sets the _librt_ debug flag to <DEBUG_ALLRAYS> (prints info about rays). 
====

== AUTHOR

BRL-CAD Team

== BUG REPORTS

Reports of bugs or problems should be submitted via electronic mail to mailto:devs@brlcad.org[]