= DEBUGBU(nged)
BRL-CAD Team
ifndef::site-gen-antora[:doctype: manpage]
:man manual: BRL-CAD User Commands
:man source: BRL-CAD
:page-layout: base

== NAME

debugbu - Allows the user to set or check the debug flags used by
    libbu.
    

== SYNOPSIS

*debugbu* [_hex_code_]

== DESCRIPTION

Allows the user to set or check the debug flags used by __libbu__. With no arguments, the [cmd]*debugbu* command displays all the possible settings for the _bu_debug_ flag and the current value. When a _hex_code_ is supplied, that value is used as the new value for __bu_debug__. Similar debug commands for other _BRL-CAD_ libraries are [cmd]*debuglib* for _librt_ and [cmd]*debugnmg* for the NMG portion of __librt__. 

== EXAMPLES

The first example shows the use of the [cmd]*debugbu* command (without an argument) to display all possible settings for the _bu_debug_ flag and the current value. The second example shows the use of the [cmd]*debugbu* command with a hex code, which is used as the new value for __bu_debug__. 

.Display a list of available _bu_debug_ values andthe current value.
====
[prompt]#mged>#[ui]`debugbu`

Lists available _bu_debug_ values and the current value. 
====

.Set a new value for __bu_debug__.
====
[prompt]#mged>#[ui]`debugbu 2`

Sets _bu_debug_ to <MEM_CHECK>. 
====

== AUTHOR

BRL-CAD Team

== BUG REPORTS

Reports of bugs or problems should be submitted via electronic mail to mailto:devs@brlcad.org[]