= DEBUGNMG(nged)
BRL-CAD Team
ifndef::site-gen-antora[:doctype: manpage]
:man manual: BRL-CAD User Commands
:man source: BRL-CAD
:page-layout: base

== NAME

debugnmg - 
      Displays a list of all possible debug flags available for NMG processing.
    

== SYNOPSIS

*debugnmg* [_hex_code_]

== DESCRIPTION

The [cmd]*debugnmg* command with no options displays a list of all possible debug flags available for NMG processing. If the command is invoked with a hex number argument, that value is used as the new value for the _NMG_ debug flag. Similar debug commands for other _BRL-CAD_ libraries are [cmd]*debuglib* for _librt_ and [cmd]*debugbu* for __libbu__. 

== EXAMPLES

The example shows the use of the [cmd]*debugnmg* with a hex code argument to set the NMG debug flag value. 

.Using the hex code argument to set the NMG debug flag value.
====
[prompt]#mged>#[ui]`debugnmg 100`

Sets the _NMG_ debug flag to get details on the classification process. 
====

== AUTHOR

BRL-CAD Team

== BUG REPORTS

Reports of bugs or problems should be submitted via electronic mail to mailto:devs@brlcad.org[]