= DECOMPOSE(nged)
BRL-CAD Team
ifndef::site-gen-antora[:doctype: manpage]
:man manual: BRL-CAD User Commands
:man source: BRL-CAD
:page-layout: base

== NAME

decompose - 
      Processes an NMG shape and produces a series of new
      NMG shapes consisting of each maximally
      connected shell in the original NMG shape.
    

== SYNOPSIS

*decompose* {_NMG_shape_} [_prefix_]

== DESCRIPTION

Processes an NMG shape and produces a series of new _NMG_ shapes consisting of each maximally connected shell in the original _NMG_ shape. If an optional prefix is supplied, the resulting _NMG_ shapes will be named by using the prefix and adding an underscore character and a number to make the name unique. If no prefix is supplied, the default prefix "sh" will be used. 

== EXAMPLES

The example shows the use of the [cmd]*decompose* command (with an optional prefix) to decompose an NMG shape into shells, which are then put into separate, uniquely named NMG shapes. 

.Decompose an NMG shape into shells, which are then put into separate,uniquely named NMG shapes. 
====
[prompt]#mged>#[ui]`decompose shape.nmg part`

Decomposes the __NMG__shape named _shape.nmg_ into maximally connected shells and puts each resulting shell into a separate _NMG_ shape named _part_1, part_2, ...._
====

== AUTHOR

BRL-CAD Team

== BUG REPORTS

Reports of bugs or problems should be submitted via electronic mail to mailto:devs@brlcad.org[]