= e(nged)
ifndef::site-gen-antora[:doctype: manpage]
:man manual: BRL-CAD User Commands
:man source: BRL-CAD
:page-role: manpage

== NAME

e_command - Adds the objects in the argument list to the display list so
  that they will appear on the MGED display. This is a
  synonym for the draw command.
   

== SYNOPSIS

*e* [-A _attribute name/value pairs_] [-s] [-A -o_attribute name/value pairs_] [-C#/#/#] [_-m1_] {_objects_}

== DESCRIPTION

Adds the objects in the argument list to the display list so that they will appear on the _MGED_ display. This is a synonym for the [cmd]*draw* command; see that entry for a full list of options. The _-C_ option provides the user a way to specify a color that overrides all other color specifications including combination colors and region-id-based colors. The _-A_ and _-o_ options allow the user to select objects by attribute. The _-s_ specifies that subtracted and intersected objects should be drawn with solid lines rather than dot-dash lines. The _-m1_ option will display BOTs shaded if the display manager is OpenGL and the zbuffer and lighting is enabled. To enable these settings, from the MGED GUI, choose "Modes/Display Manager/OpenGL", "Misc/Z-buffer" and "Misc/Lighting". If the zbuffer and lighting is already enabled, toggle them off then back on to ensure they are enabled.

== EXAMPLES

The following examples show the use of the [cmd]*e* command to draw particular objects, to specify color, to draw with shape lines rather than dot-dash lines, and to limit the objects to be drawn to those having specific attribute names and value pairs.

.Draw specific objects in the _MGED_ display.
====

[prompt]#mged>#[ui]`e object1 object2`::
Draws _object1_ and _object2_ in the MGED display.
====

.Limit the objects to be drawn to those having specific attribute names and value pairs.
====
[prompt]#mged>#[ui]`e -A -o Comment {First comment} Comment {Second comment}`

Draws objects that have a "Comment" attribute with a value of either "First comment" or "Second comment." 
====

== AUTHOR

BRL-CAD Team

== BUG REPORTS

Reports of bugs or problems should be submitted via electronic mail to mailto:devs@brlcad.org[]