= EDCODES(nged)
BRL-CAD Team
:doctype: manpage
:man manual: BRL-CAD User Commands
:man source: BRL-CAD
:page-layout: base

== NAME

edcodes - Puts the user into an editor to edit a file that has been filled
	with the ident, air code, material code, LOS, and name of all the regions in the
	specified objects.
   

== SYNOPSIS

*edcodes* {_objects_} []

== DESCRIPTION

Puts the user into an editor to edit a file that has been filled with the ident, air code, material code, LOS, and name of all the regions in the specified objects. The user may then modify the entries (except for the names). The editor used is whatever the user has set in the environment variable __EDITOR__. If _EDITOR_ is not set, then _/bin/ed_ is used. 

== EXAMPLES

The example shows the use of the [cmd]*edcodes* command for editing the region codes in the 		files of two objects. 

.Edit the region codes of two objects.
====

[prompt]#mged>#[ui]`edcodes object1 object2`::
Enables the user to edit the region codes for all regions below _object1_ and __object2__. 
====

== AUTHOR

BRL-CAD Team

== BUG REPORTS

Reports of bugs or problems should be submitted via electronic mail to mailto:devs@brlcad.org[]