= EDMATER(nged)
BRL-CAD Team
ifndef::site-gen-antora[:doctype: manpage]
:man manual: BRL-CAD User Commands
:man source: BRL-CAD
:page-layout: base

== NAME

edmater - Places the user in an editor ready to edit a file filled with
	shader arguments for the combinations listed on the command line.
   

== SYNOPSIS

*edmater* {_combinations_} []

== DESCRIPTION

Places the user in an editor ready to edit a file filled with shader arguments for the combinations listed on 	the command line. The arguments placed in the file for editing are the _shader_ name and its 	own arguments, RGB color,__RGB_valid__ flag, and the inheritance flag. The editor used is 	whatever the user has set in the environment variable __EDITOR__. If _EDITOR_ is not set, then _/bin/ed_ is used. 

== EXAMPLES

The example shows the use of the [cmd]*edmater* command to edit _shader_ parameters for two combinations. 

.Editing _shader_ parameters for two combinations.
====

[prompt]#mged>#[ui]`edmater comb1 comb2`::
The _shader_ parameters can now be edited for _comb1_ and__comb2__. 
====

== AUTHOR

BRL-CAD Team

== BUG REPORTS

Reports of bugs or problems should be submitted via electronic mail to mailto:devs@brlcad.org[]