= EV(nged)
BRL-CAD Team
ifndef::site-gen-antora[:doctype: manpage]
:man manual: BRL-CAD User Commands
:man source: BRL-CAD
:page-role: manpage

== NAME

ev - Evaluates the objects specified by tessellating all primitive shapes
	in the objects and then performing any Boolean operations specified in the objects.
	The result is then displayed in the MGED display according to specified options.
   

== SYNOPSIS

*ev* [-dfnrstuvwST] [-P _\#_] [-C _\#/#/#_] {objects} []

== DESCRIPTION

Evaluates the _objects_ specified by tessellating all primitive shapes in the objects and then performing any Boolean operations specified in them. The result is then displayed in the MGED display according to specified options.

* __d__--Do not perform Boolean operations or any checking; simply convert shapes to polygons and draw them. Useful for visualizing BOT and polysolid primitives. 
* __f__--Fast path for quickly visualizing polysolid primitives. 
* __w__--Draw wireframes (rather than polygons). 
* __n__--Draw surface normals as little hairs. 
* __s__--Draw shape lines only (no dot-dash for subtract and intersect). 
* __t__--Perform CSG-to-tNURBS conversion (still under development). 
* __v__--Shade using per-vertex normals, when present. 
* __u__--Draw NMG edgeuses (for debugging). 
* __S__--Draw tNURBS with trimming curves only, no surfaces. 
* __T__--Do not triangulate after evaluating the Boolean (may produce unexpected results if not used with the _w_ option). 
* __P#__--Use # processors in parallel. Default=1. 
* __r__--Draw all objects in red. Useful for examining objects colored black. 
* __C#/#/#__--Draw all objects in the specified rgb color. 


== EXAMPLES

The first example shows the use of the [cmd]*ev* command to display two evaluated objects as shaded  	polygons.  The second example shows the use of the [cmd]*ev* command to display an evaluated object as 	wireframe without triangulating. 

.Display evaluated objects as polygons.
====

[prompt]#mged>#[ui]`ev region1 shapea`::
Displays evaluated _region1_ and _shapea_ as shaded polygons. 
====

.Display an evaluated object as wireframe without triangulation.
====
[prompt]#mged>#[ui]`ev -wT region1`

Displays an evaluated object, __region1__, as wireframe without triangulation. 
====

== AUTHOR

BRL-CAD Team

== BUG REPORTS

Reports of bugs or problems should be submitted via electronic mail to mailto:devs@brlcad.org[]