= FRACTURE(nged)
BRL-CAD Team
:doctype: manpage
:man manual: BRL-CAD User Commands
:man source: BRL-CAD
:page-layout: base

== NAME

fracture - Creates a new NMG shape for every face in the specified
NMG_shape.
   

== SYNOPSIS

*fracture* {_NMG_shape_} [_prefix_]

== DESCRIPTION

Creates a new NMG shape for every face in the specified __NMG_shape__. The new shapes will be named by adding an underscore and a number to the __prefix__. If no _prefix_ is specified, then the _NMG_shape_ name provided is used in place of the __prefix__. 

== EXAMPLES

The example shows the use of the [cmd]*fracture* command to create a new NMG shape with a 	given prefix for every face in the specified __NMG _shape__. 

.Create an NMG shape with a specific prefix for every face in a specified NMG shape.
====

[prompt]#mged>#[ui]`fracture shape1.nmg f`::
Creates a series of NMG shapes named f_#, one for each face in __shape1.nmg__. 
====

== AUTHOR

BRL-CAD Team

== BUG REPORTS

Reports of bugs or problems should be submitted via electronic mail to mailto:devs@brlcad.org[]