= GET(nged)
BRL-CAD Team
ifndef::site-gen-antora[:doctype: manpage]
:man manual: BRL-CAD MGED Commands
:man source: BRL-CAD
:page-role: manpage

== NAME

get -  Used to retrieve parameter values of database objects.
    

== SYNOPSIS

*get* {_object_name_pattern_} [_param_name_]

== DESCRIPTION

Low level command for extracting specific parameter information from geometry objects in a database.  Similar to "attr get" except that the focus of this command is on geometric parameter values (vertices, for example) instead of attribute metadata. 

== EXAMPLES

.Elliptical Torus 'r' parameter extraction
====
Use the [cmd]*get* command to exctract the r parameter value from an elliptical torus. 

[prompt]#mged>#[ui]`make eto.s eto`[prompt]#mged>#[ui]`l eto.s`

....

eto.s:  Elliptical Torus (ETO)
      V (0, 0, 0)
      N=(0, 0, 1)
      C=(200, 0, 200) mag=282.843
      r=800
      d=100
....[prompt]#mged>#[ui]`get eto.s r`

....

800
....
====

== SEE ALSO

xref:man:n/attr.adoc[*attr*(n)].

== AUTHOR

BRL-CAD Team

== COPYRIGHT

This software is Copyright (c) 2008-2021 United States Government as represented by the U.S. Army Research Laboratory. 

== BUG REPORTS

Reports of bugs or problems should be submitted via electronic mail to mailto:devs@brlcad.org[]