= HELPLIB(nged)
BRL-CAD Team
:doctype: manpage
:man manual: BRL-CAD User Commands
:man source: BRL-CAD
:page-layout: base

== NAME

helplib - Returns a list of available library commands along with a
	one-line usage message for each. If a command is supplied as an argument, the one-line
	usage message for that command is returned.
   

== SYNOPSIS

*helplib* [_command_]

== DESCRIPTION

Returns a list of available _library_ commands along with a one-line usage message for each. If a command is supplied as an argument, the one-line usage message for that command is returned. The [cmd]*help, helpdevel, ?, ?devel,* and [cmd]*?lib* commands provide additional information on available commands. 

== EXAMPLES

The example shows the use of the [cmd]*helplib* command to display a one-line usage message for a specific library command. 

.Display a one-line usage message for a specific library command.
====

[prompt]#mged>#[ui]`helplib mat_trn`::
Displays a one-line usage message for the [cmd]*mat_trn* command. 
====

== AUTHOR

BRL-CAD Team

== BUG REPORTS

Reports of bugs or problems should be submitted via electronic mail to mailto:devs@brlcad.org[]