= HISTORY(nged)
BRL-CAD Team
ifndef::site-gen-antora[:doctype: manpage]
:man manual: BRL-CAD User Commands
:man source: BRL-CAD
:page-layout: base

== NAME

history - Displays the list of commands executed during the current
MGED session.
   

== SYNOPSIS

*history* [-delays]

== DESCRIPTION

Displays the list of commands executed during the current MGED session. The one exception is the [cmd]*hist_add* command, which can add a command to the history list without executing it. If the _-delays_ option is used, then the delays between commands will also be displayed. 

== EXAMPLES

The example shows the use of the [cmd]*history* command to display the command history list 	for the current MGED session. 

.Display the command history list for the current MGED session. 
====

[prompt]#mged>#[ui]`history`::
Displays the command history list for the current MGED session. 
====

== AUTHOR

BRL-CAD Team

== BUG REPORTS

Reports of bugs or problems should be submitted via electronic mail to mailto:devs@brlcad.org[]