= IDENTS(nged)
BRL-CAD Team
ifndef::site-gen-antora[:doctype: manpage]
:man manual: BRL-CAD User Commands
:man source: BRL-CAD
:page-layout: base

== NAME

idents - Places a summary of the regions in the list of objects specified
	in the file specified.

== SYNOPSIS

*idents* {_file_name_} {_objects_}

== DESCRIPTION

Places a summary of the regions in the list of _objects_ specified in the file specified. If any regions include other regions, then only the first encountered region in that tree will be listed. The resulting file will contain two lists of regions, one in the order encountered in the list of objects, and the other ordered by ident number. The data written for each region includes (in this order) a sequential region count, the ident number, the air code, the material code, the LOS, and the path to the region. 

== EXAMPLES

The example shows the use of the [cmd]*idents* command to create a file that will list all 	regions in specified objects. 

.Create a file that lists all regions contained in specified objects.
====

[prompt]#mged>#[ui]`idents regions_file group1 group2 region3`::
Creates a file named _regions_file_ and lists all the regions in _group1, group2,_ and _region3_ in the file. 
====

== AUTHOR

BRL-CAD Team

== BUG REPORTS

Reports of bugs or problems should be submitted via electronic mail to mailto:devs@brlcad.org[]