= IN(nged)
ifndef::site-gen-antora[:doctype: manpage]
:man manual: BRL-CAD User Commands
:man source: BRL-CAD
:page-role: manpage

== NAME

in - Allows the user to type in the arguments needed to create a shape
	with the name new_shape_name of the type shape_type. The command 	may be invoked with no arguments, and it will prompt the user for all needed information.
  

== SYNOPSIS

*in* [[-f] | [-s]] [_new_shape_name_] [_shape_type_] {_parameters_}

== DESCRIPTION

Allows the user to type in the arguments needed to create a shape with the name _new_shape_name_ of the type __shape_type__. The command may be invoked with no arguments, and it will prompt the user for all needed information. The _-s_ option will invoke the primitive edit mode on the new shape immediately after creation. The _-f_ option does not draw the new shape, and therefore the _-s_ option may not be used in conjunction with __-f__. The possible values for _shape_type_ are: 

* arb8 -- ARB (eight vertices) 
* arb7 -- ARB (seven vertices). 
* arb 6 -- ARB (six vertices). 
* arb 5 -- ARB (five vertices). 
* arb 4 -- ARB (four vertices). 
* arbn -- Arbitrary polyhedron with arbitrary number of vertices (plane equations). 
* bot -- Bag of Triangles. 
* dsp -- Displacement Map. 
* pipe -- Pipe (run of connected pipe or wire). 
* ebm -- Extruded Bit Map. 
* vol -- Voxels. 
* hf -- Height Field deprecated, see dsp. 
* ars -- Arbitrary Faceted Solid. 
* half -- Half Space. 
* sph -- Ellipsoid (center and radius). 
* ell -- Ellipsoid (center and three semi-axes). 
* ellg -- Ellipsoid (foci and chord length). 
* ell1 -- Ellipsoid (center, one semi-axis, and a radius of revolution). 
* tor -- Torus. 
* tgc -- Truncated General Cone (most general TGC). 
* tec -- TGC (top radii are scaled from base radii). 
* rec -- TGC (right elliptical cylinder). 
* trc -- TGC (truncated right circular cone). 
* rcc -- TGC (right circular cylinder). 
* box -- ARB (vertex and three vectors). 
* raw -- ARB (right angle wedge). 
* rpp -- ARB (axis aligned rectangular parallelepiped). 
* rpc -- Right Parabolic Cylinder. 
* rhc -- Right Hyperbolic Cylinder. 
* epa -- Elliptical Paraboloid. 
* ehy -- Elliptical Hyperboloid. 
* eto -- Elliptical Torus. 
* part -- Particle. 


== EXAMPLES

The example shows the use of the [cmd]*in* command to create a shape of a specified type. 

.Create a new shape in the form of a right angle wedge.
====

[prompt]#mged>#[ui]`in new1 raw 0 0 0 0 0 1 1 0 0 0 1 0`::
Creates an _ARB_ named _new1_ in the form of a right 		  angle wedge. 
====

== AUTHOR

BRL-CAD Team

== BUG REPORTS

Reports of bugs or problems should be submitted via electronic mail to mailto:devs@brlcad.org[]