= KEYPOINT(nged)
ifndef::site-gen-antora[:doctype: manpage]
:man manual: BRL-CAD User Commands
:man source: BRL-CAD
:page-role: manpage

== NAME

keypoint - Without any options, keypoint displays the current keypoint 	setting. If a point is specified, then that point becomes the keypoint	. If reset is specified, then the default 	keypoint is restored.
   

== SYNOPSIS

*keypoint* [_xyz_] [reset]

== DESCRIPTION

Without any options, [cmd]*keypoint* displays the current keypoint setting. 	If a point is specified, then that point becomes the __keypoint__. If__reset__ is specified, then the default _keypoint_ is 	restored. The _keypoint_ is used as the center of rotation and scaling in primitive edit or matrix edit (formerly known as object edit) modes. This command has no effect when used in nonediting modes. 

== EXAMPLES

The example shows the use of the [cmd]*keypoint* command to set the keypoint 	in model units. 

.Set the keypoint.
====

[prompt]#mged>#[ui]`keypoint 10 20 30`::
Sets the _keypoint_ to the point (10 20 30) in model units. 
====

== AUTHOR

BRL-CAD Team

== BUG REPORTS

Reports of bugs or problems should be submitted via electronic mail to mailto:devs@brlcad.org[]