= LABELVERT(nged)
BRL-CAD Team
ifndef::site-gen-antora[:doctype: manpage]
:man manual: BRL-CAD User Commands
:man source: BRL-CAD
:page-role: manpage

== NAME

labelvert - Labels the vertices of the indicated objects with their
	coordinate values in the MGED display window.
   

== SYNOPSIS

*labelvert* {_objects_}

== DESCRIPTION

Labels the vertices of the indicated _objects_ with their coordinate values in the MGED display window. The _objects_ must have 	already been displayed using [cmd]*e, E, ev, B*, or any other command that 	results in the display of an object. 

== EXAMPLES

The example shows the use of the [cmd]*labelvert* command to label the 	vertices of a designated shape with their coordinate values. 

.Label the vertices of a particular shape with their coordinate values.
====

[prompt]#mged>#[ui]`labelvert shapeb`::
Places coordinate values in the display near the vertices of __shapeb__. 
====

== AUTHOR

BRL-CAD Team

== BUG REPORTS

Reports of bugs or problems should be submitted via electronic mail to mailto:devs@brlcad.org[]