= NMG_SIMPLIFY(nged)
BRL-CAD Team
ifndef::site-gen-antora[:doctype: manpage]
:man manual: BRL-CAD User Commands
:man source: BRL-CAD
:page-layout: base

== NAME

nmg_simplify - Attempts to convert an existing nmg_shape to a
simpler primitive shape type.
   

== SYNOPSIS

*nmg_simplify* [[arb] | [tgc] | [poly]] {_new_shape nmg_shape_}

== DESCRIPTION

Attempts to convert an existing nmg_shape to a simpler primitive shape type. The user may specify which type to attempt by including _arb, tgc,_ or _poly_ on the command line. If no shape 	type is specified, all will be attempted in the above order. If _tgc_ is specified, 	the code will attempt to determine if the _nmg_shape_ is an approximation of a TGC 	shape. 

== EXAMPLES

The example shows the use of the [cmd]*nmg_simplify* command to convert an existing nmg shape to a polysolid. 

.Convert an existing shape to a polysolid.
====
[prompt]#mged>#[ui]`nmg_simplify poly shapea.poly shapea.nmg`

Converts the nmg shape named _shapea.nmg_ to a polysolid named __shapea.poly__. 
====

== AUTHOR

BRL-CAD Team

== BUG REPORTS

Reports of bugs or problems should be submitted via electronic mail to mailto:devs@brlcad.org[]