= OED(nged)
BRL-CAD Team
ifndef::site-gen-antora[:doctype: manpage]
:man manual: BRL-CAD User Commands
:man source: BRL-CAD
:page-layout: base

== NAME

oed - Places MGED directly into the matrix edit mode.
   

== SYNOPSIS

*oed* {_path_lhs path_rhs_}

== DESCRIPTION

Places MGED directly into the matrix edit mode. The _path_rhs_	must be a path to a primitive shape, and _path_lhs_ must be a path to a combination 	that includes the first component of _path_rhs_ as one of its members. The edited 	matrix will be the matrix in the final component of _path_lhs_ that corresponds to 	the first component of __path_rhs__.  The last component in _path_rhs_ is used as the reference shape during object editing. 

Note that for scripting the object to be edited must be in view so a [cmd]*B*	or [cmd]*draw* must be used on the object before using the [cmd]*oed* command. 

== EXAMPLES

The example shows the use of the [cmd]*oed* command to place MGED into matrix edit mode.  The matrix in the final component of _path_lhs_ that corresponds to the first component of _path_rhs_ will be edited. 

.Place MGED in matrix edit mode.
====
[prompt]#mged>#[ui]`oed group1/group2 region1/shapea`

Places MGED into matrix edit mode, editing the matrix in _group2_ that corresponds to __region1__, using _shapea_ as the reference shape. 
====

== AUTHOR

BRL-CAD Team

== BUG REPORTS

Reports of bugs or problems should be submitted via electronic mail to mailto:devs@brlcad.org[]