= P(nged)
BRL-CAD Team
:doctype: manpage
:man manual: BRL-CAD User Commands
:man source: BRL-CAD
:page-layout: base

== NAME

p - Provides precise control over primitive editing operations that
would normally be done using the mouse or knobs.
   

== SYNOPSIS

*p* {_value1_} [_value2 value3_]

== DESCRIPTION

Provides precise control over primitive editing operations that would normally be done using the mouse or knobs. For example, a shape rotate may be performed by selecting _rotate_ from the primitive edit menu, then providing the rotation angles with the [cmd]*p* command. A command of [cmd]*p 0 30 0* would rotate 	the edited shape through 30° about the _y_ axis. Similarly, many of the individual parameters of the edited shape may be set exactly using the [cmd]*p* command. If the _scale H_ menu item is selected while editing a TGC, then the _value1_ supplied 	with a [cmd]*p* command specifies the actual length of the height vector for that TGC. This 	method is the recommended technique to set precise values for shape parameters. The [cmd]*translate* and [cmd]*rotobj* commands provide a similar capability for object editing. 

== EXAMPLES

The example shows the use of the [cmd]*p* command to precisely set the currently selected 	shape parameter of the currently edited shape. 

.Set the currently selected shape parameter of the currently edited shape.
====
[prompt]#mged>#[ui]`p 30`

Sets the currently selected shape parameter of the currently edited shape to 30 units. 
====

== AUTHOR

BRL-CAD Team

== BUG REPORTS

Reports of bugs or problems should be submitted via electronic mail to mailto:devs@brlcad.org[]