= POSTSCRIPT(nged)
BRL-CAD Team
ifndef::site-gen-antora[:doctype: manpage]
:man manual: BRL-CAD User Commands
:man source: BRL-CAD
:page-layout: base

== NAME

postscript - Temporarily attaches the Postscript display manager and outputs
	the current MGED display to the specified output_file in PostScript	 format.
   

== SYNOPSIS

*postscript* [-f _font_] [-t _title_] [-c _creator_] [-s _size_in_inches_] [-l _line_width_] {_output_file_}

== DESCRIPTION

Temporarily attaches the _Postscript_ display manager and outputs the current MGED display to the specified _output_file_ in _PostScript_ format. The _-f_ option allows the _font_ to be user-	specified. The _-t_ option allows the user to provide a title (the default is No 	Title). The _-c_ option allows the user to specify the creator of the file (the 	default is LIBDM dm-ps). The _s_ specifies the size of the drawing in inches. The__l__ specifies the width of the lines drawn. 

== EXAMPLES

The first example shows the use of the [cmd]*postscript* command to place a _PostScript_ version of the current MGED display in a specified file and give it a particular title.  The 	second example is much like the first except that a line width is specified and the title and output file 	names are different. 

.Place a _PostScript_ version of the current MGED display in a specified file.
====
[prompt]#mged>#[ui]`postscript -t "Test Title" test.ps`

Places a _PostScript_ version of the current MGED display in a file named__test.ps__ and titles it Test Title. 
====

.Specify the line width of a _PostScript_ version of the current MGED display in a 	specified file.
====
[prompt]#mged>#[ui]`postscript -l 10 -t "Test Fat Lines" fat_lines.ps`

Places a _PostScript_ version of the current MGED display with fat lines in a file 	named _fat_lines.ps_ and titles it Test Fat Lines. 
====

== AUTHOR

BRL-CAD Team

== BUG REPORTS

Reports of bugs or problems should be submitted via electronic mail to mailto:devs@brlcad.org[]