= PULL(nged)
BRL-CAD Team
:doctype: manpage
:man manual: BRL-CAD User Commands
:man source: BRL-CAD
:page-layout: base

== NAME

pull - Pulls the effects of all transformation matrices that appear in
	any combinations or primitives in the trees from the leaves up to the specified objects or node.
   

== SYNOPSIS

*pull* [_objects_]

== DESCRIPTION

Pulls the effects of all matrix transformations that appear in any combinations or primitives in the tree from the leaves up to the specified __objects__. This will restore the parameters of the _primitive shapes_ if any of the transformation matrices were not identity matrices. All the transformation matrices visited will be set to the current transformation matrix as it moves up the tree. This command will fail, and no changes will be made, if the specified _object_ is a primitive shape referenced by the list of __objects__. 

== EXAMPLES

The example shows the use of the [cmd]*pull* command to pull the effects of any transformation matrices from leaves(primitive shapes) of a tree up to the specified head objects. 

.Pull the effects of any transformation matrices from the leaves(primitive shapes) of the tree up to the specified head nodes(objects).
====
[prompt]#mged>#[ui]`pull group1 regiona`

Pulls the effects of any transformation matrices from the primitive shapes in the tree up to the root nodes specified by _group1_ 	and __regiona__. 
====

== AUTHOR

BRL-CAD Team

== BUG REPORTS

Reports of bugs or problems should be submitted via electronic mail to mailto:devs@brlcad.org[]