= REGDEF(nged)
BRL-CAD Team
:doctype: manpage
:man manual: BRL-CAD User Commands
:man source: BRL-CAD
:page-layout: base

== NAME

regdef - Sets the default region attributes used by the r and c	 commands when building a BRL-CAD region.
   

== SYNOPSIS

*regdef* {_regionID_} [_airID_[_los%_[_materialID_]]]

== DESCRIPTION

Sets the default region attributes used by the [cmd]*r* and [cmd]*c* commands when building a BRL-CAD region. The default _ident_ 	number is incremented each time a new region is created with the [cmd]*r* or[cmd]*c* commands. 

== EXAMPLES

The example shows the use of the [cmd]*regdef* command to set the default 	region attributes used by the [cmd]*r* and [cmd]*c* commands when 	building a BRL-CAD region. 

.Set region default attributes.
====
[prompt]#mged>#[ui]`regdef 1003 0 100 8`

Sets the region default attributes to an ident of 1003, an air code of 0, an los of 100%, and a material code of 8. 
====

== AUTHOR

BRL-CAD Team

== BUG REPORTS

Reports of bugs or problems should be submitted via electronic mail to mailto:devs@brlcad.org[]