= RMATER(nged)
ifndef::site-gen-antora[:doctype: manpage]
:man manual: BRL-CAD User Commands
:man source: BRL-CAD
:page-role: manpage

== NAME

rmater - Reads the specified file and sets the combination shader, 	color, and inheritance values according to those listed in the file.   

== SYNOPSIS

*rmater* {_file_}

== DESCRIPTION

Reads the specified _file_ and sets the combination shader, color, and inheritance values according to those listed in the __file__. The 	format of the _file_ is expected to be as produced by the [cmd]*wmater* command. 

== EXAMPLES

The example shows the use of the [cmd]*rmater* command to read a specified file and set the combination attributes according to those in the file. 

.Set combination attributes according to those listed in a specified file.
====
[prompt]#mged>#[ui]`rmater mater_file`

Reads the file named _mater_file_ and sets the combination 	attributes according to those listed in the file. 
====

== AUTHOR

BRL-CAD Team

== BUG REPORTS

Reports of bugs or problems should be submitted via electronic mail to mailto:devs@brlcad.org[]