= RT(nged)
ifndef::site-gen-antora[:doctype: manpage]
:man manual: BRL-CAD MGED Commands
:man source: BRL-CAD
:page-role: manpage

== NAME

rt - Executes the BRL-CAD rt program with the default options of
	"-s50  M."
   

== SYNOPSIS

*rt* [_options_] [_--objects_]

== DESCRIPTION

Executes the BRL-CAD _rt_ program with the default options of "-s50 M." If perspective is turned on, then the _-p_ option will be 	included with the value of the perspective angle. The current database name is added to the 	end of the [cmd]*rt* command line along with either the specified _objects_ or, if none is specified, the list of currently displayed objects. The__rt__ program is written such that options may be repeated, and the 	last occurrence of an option will override any earlier occurrences.  This allows the user 	to specify other _size (-s)_ options. The [cmd]*rrt* command 	performs a similar function, but may be used to execute other programs as well. The__-M__ option tells _rt_ to read the viewing parameters 	from standard input.  See the _man_ page on _rt_  	for details.  A related command is [cmd]*saveview*, which can be used to 	create a shell script (batch job) to raytrace this view in the background. 

== EXAMPLES

The first example shows the use of the [cmd]*rt* command to run the rt 	program to produce a color-shaded image of the current view. The second example shows the 	use of the [cmd]*rt* command to produce a color-shaded image of an object using 	MGED's current viewing parameters. 

.Run the _rt_ program to produce a color-shaded image of the current 	view in MGED.
====
[prompt]#mged>#[ui]`rt -s1024 -F/dev/Xl`

Runs the _rt_ program to produce a color-shaded image of the current 	view in the MGED display. The image will be 1024 pixels square and will be displayed on a lingering _X_ framebuffer. 
====

.Run the _rt_ program to produce a color-shaded image of an object  	using MGED's current viewing parameters.
====
[prompt]#mged>#[ui]`rt -C 200/200/255 -- roof`

Runs the _rt_ program to produce a color-shaded image of the object__roof__ using MGED's current viewing parameters. The image will have a 	sky-blue background and will be displayed on the framebuffer specified by the FB_FILE shell 	variable. 
====

== AUTHOR

BRL-CAD Team

== BUG REPORTS

Reports of bugs or problems should be submitted via electronic mail to mailto:devs@brlcad.org[]