= SAVEVIEW(nged)
BRL-CAD Team
ifndef::site-gen-antora[:doctype: manpage]
:man manual: BRL-CAD User Commands
:man source: BRL-CAD
:page-role: manpage

== NAME

saveview - Saves the current viewing parameters in the specified file
	in the form of a shell script that will run the BRL-CAD rt program as if it had been
	executed from within MGED using the rt -s512 command.

== SYNOPSIS

*saveview* [-e _command_] [-l _logfile_] [-o _outputfile_] [-e _inputfile_] {_file_} [_args_]

== DESCRIPTION

Saves the current viewing parameters in the specified _file_	in the form of a shell script that will run the BRL-CAD _rt_ program as if it had been executed from within MGED using the [cmd]*rt -s512* command.  Any _args_ 	included on the [cmd]*saveview* command line will be copied to the _file_ as 	options to the _rt_ program. If the _file_ already exists, the script 	will be appended to it. This is useful in setting up images to be raytraced later. The default script 	produced by "saveview test.rt" looks like:

____
....

#!/bin/sh
rt -M \
 -o test.rt.pix\
 $*\
 model.g\
 'object1' 'object2' \
 2>> test.rt.log\
 <<EOF
viewsize 2.780320739746094e+02;
orientation 2.480973490458727e-01 4.765905732660483e-01
7.480973490458729e-01 3.894348305183902e-01;
eye_pt 1.234152656421214e+02 7.220202900588745e+01
3.845765464924686e+01;
start 0; clean;
end;
EOF
....
____

When this script is executed, the image will be stored in __test.rt.pix__, and all 	messages and errors generated by the _rt_ program will be stored in __test.rt.log__. The above script will produce an image of _object1_ and _object2_ from the BRL-CAD database named __model.g__. The __viewsize__,__orientation__, and _eye_pt_ parameters reproduce the view displayed by 	MGED when the [cmd]*saveview* command was executed. The presence of $* in the script causes 	any additional command-line options given when the script is invoked to be interpreted as additional__rt__ options. Typically, a -s option might be used to set the image size (the default 	is 512 pixels square). See the _man_ page on _rt_ for details on 	available options. 

If you have a _saveview_ script and wish to change MGED to that view, merely cut-and- paste, or __source__, the viewsize, orientation, and eye_pt lines from the _saveview_ file into MGED. 

The following options are valid for this command: 

_-e command_::
Makes the script run the specified _command_ instead of the default of rt 

_-l logfile_::
Makes the script direct log output to the specified _logfile_ instead of to the default of __file__.log (__file__ is the inputfile basename). 

_-o outputfile_::
Makes the script output the image to the specified _outputfile_ instead of to the default of __file__.pix (__file__ is the inputfile basename). 

_-i inputfile_::
Makes the script load data from _inputfile_ instead of from the default of the currently opened database. 

== EXAMPLES

The example shows the use of the [cmd]*saveview* command to create a file that will contain a 	script to run the _rt_ program and create a color-shaded image of the current MGED 	display. 

.Save current viewing parameters in a specified file in the form of a shell script to run the BRL-CAD__rt__ program.
====
[prompt]#mged>#[ui]`saveview script.rt -s1024`

Creates (or appends to) a file named _script.rt_ that will contain a POSX shell script for running the _rt_ program and create a color-shaded image of the current MGED display. The image produced will be 1024 pixels square due to the additional [opt]*-s1024* arg specified after the script name.  Additional args are passed to __rt__. 
====

== AUTHOR

BRL-CAD Team

== BUG REPORTS

Reports of bugs or problems should be submitted via electronic mail to mailto:devs@brlcad.org[]