= SHELL(nged)
BRL-CAD Team
ifndef::site-gen-antora[:doctype: manpage]
:man manual: BRL-CAD User Commands
:man source: BRL-CAD
:page-role: manpage

== NAME

shells - Separates the specified NMG shape into its constituent shells.
   

== SYNOPSIS

*shells* [_NMG_shape_]

== DESCRIPTION

Separates the specified NMG shape into its constituent shells. Each shell is written to the database as a separate NMG object with a name of the form shell with a number appended to make the name unique. If the _NMG_ has only one shell, then only one new object will be created. This differs from the [cmd]*decompose* command in that [cmd]*decompose* will actually break the object into a number 	of separate shells if possible. 

== EXAMPLES

The example shows the use of the [cmd]*shells* command to break an NMG shape into its constituent shells. 

.Break an NMG shape into its constituent shells.
====
[prompt]#mged>#[ui]`object.nmg`

Breaks the NMG shape named _object.nmg_ into its constituent shells. 
====

== AUTHOR

BRL-CAD Team

== BUG REPORTS

Reports of bugs or problems should be submitted via electronic mail to mailto:devs@brlcad.org[]