= SOLIDS(nged)
BRL-CAD Team
ifndef::site-gen-antora[:doctype: manpage]
:man manual: BRL-CAD User Commands
:man source: BRL-CAD
:page-role: manpage

== NAME

solids - Lists a summary of all the primitive shapes used in regions
	referenced by the list of objects.
   

== SYNOPSIS

*solids* {_file_} {_objects_}

== DESCRIPTION

Lists a summary of all the primitive shapes used in regions referenced by the list of __objects__. The summary is written to the specified __file__. The summary is similar to that produced by the [cmd]*regions* command, but with 	the addition of primitive shape parameters. The shape parameters listed will have the accumulated 	transformation matrices along the path from the listed _objects_ to the primitive shape applied (as would be listed by the [cmd]*listeval* command). The [cmd]*showmats* 	command may be used to see the actual transformation matrices. 

== EXAMPLES

The example shows the use of the [cmd]*solids* command to list a summary of all the primitive 	shapes used in regions referenced by a list of objects. 

.List a summary of all the regions in a group.
====
[prompt]#mged>#[ui]`solids shapes_summary group1 regiona`

Writes a summary of all the regions in _group1_ and includes the region named __regiona__. The summary includes detailed shape parameters for the shapes used in the regions. 
====

== AUTHOR

BRL-CAD Team

== BUG REPORTS

Reports of bugs or problems should be submitted via electronic mail to mailto:devs@brlcad.org[]