= SV(nged)
BRL-CAD Team
ifndef::site-gen-antora[:doctype: manpage]
:man manual: BRL-CAD MGED Commands
:man source: BRL-CAD
:page-role: manpage

== NAME

sv - Moves the view center to (x, y, z).
   

== SYNOPSIS

*sv* {_x y_} [_z_]

== DESCRIPTION

Moves the view center to (__x, y, z__). If _z_ is not provided, then __z__=0 is used. The parameters _x, y, z_ are integer values relative to the screen. For example, the center of the screen is (0, 0, 0) and the upper left corner is (-2048, 2047, 0). 

== EXAMPLES

The two examples show the use of the [cmd]*sv* command to move the view center to a particular location on the screen. 

.Keep the view center at the center of the screen.
====
[prompt]#mged>#[ui]`sv 0 0 0`

The view is unchanged. 
====

.Move the view center half way between the current view center and the right side of the view screen.
====
[prompt]#mged>#[ui]`sv 1024 0 0`

The view center is moved half way between the current view center and the right side of the view screen. 
====

== AUTHOR

BRL-CAD Team

== BUG REPORTS

Reports of bugs or problems should be submitted via electronic mail to mailto:devs@brlcad.org[]