= T(nged)
BRL-CAD Team
ifndef::site-gen-antora[:doctype: manpage]
:man manual: BRL-CAD MGED Commands
:man source: BRL-CAD
:page-role: manpage

== NAME

t - Lists the names of specified objects in the database in alphabetical order depending on the argument given.
   

== SYNOPSIS

*t* [-a] [-c] [-r] [-s] [_objects_]

== DESCRIPTION

The [cmd]*t* command with no _object_ argument lists the name of every object in the database (in alphabetical order) except those marked as hidden with the hide command. If the _object_ argument is supplied, only those _objects_ are listed. The _object_ argument may include regular expressions for matching. The following options are also allowed: 

* a - list all objects in the database. 
* c - list all nonhidden combinations in the database. 
* r - list all nonhidden regions in the database. 
* s - list all nonhidden shapes in the database. 

The [cmd]*t* command is a synonym for the [cmd]*ls* command. Note that when any of the above options are used, the output is not formatted. 

== EXAMPLES

The five examples show the use of the [cmd]*t* command with different arguments to list names of objects, combinations, regions, or shapes. 

.List all objects with names beginning with "shape."
====
[prompt]#mged>#[ui]`t shape*`

Lists all objects with names beginning with shape. (output is formatted) 
====

.List all objects with names beginning with "shape."
====
[prompt]#mged>#[ui]`t -a shape*`

Lists all objects with names beginning with shape. 
====

.List all shapes with names beginning with wheel.
====
[prompt]#mged>#[ui]`t -s wheel*`

Lists all shapes with names beginning with wheel. 
====

.List all regions with names beginning with wheel.
====
[prompt]#mged>#[ui]`t -r wheel*`

Lists all regions with names beginning with wheel. 
====

.List all combinations with names beginning with suspension.
====
[prompt]#mged>#[ui]`t -c suspension*`

Lists all combinations with names beginning with suspension. 
====

== AUTHOR

BRL-CAD Team

== BUG REPORTS

Reports of bugs or problems should be submitted via electronic mail to mailto:devs@brlcad.org[]