= TED(nged)
BRL-CAD Team
ifndef::site-gen-antora[:doctype: manpage]
:man manual: BRL-CAD MGED Commands
:man source: BRL-CAD
:page-role: manpage

== NAME

ted - Places the parameters of the currently edited primitive shape into
a file, then starts a text editor for the user to modify the parameters.
   

== SYNOPSIS

*ted* [] []

== DESCRIPTION

The [cmd]*ted* command places the parameters of the currently edited primitive shape into a file, then starts a text editor for the user to modify the parameters. The editor used is whatever the user has set in the environment variable EDITOR. If EDITOR is not set, then _/bin/ed_  is used. MGED must be in the primitive edit mode prior to using this command. The [cmd]*red* command performs a similar function for combinations. 

== EXAMPLES

The example shows the use of the [cmd]*ted* command to place the parameters of a currently edited primitive shape into a file and start a text editor to modify the parameters. 

.Use a text editor to modify a currently edited shape.
====
[prompt]#mged>#[ui]`ted`

Starts a text editor to modify a currently edited shape. 
====

== AUTHOR

BRL-CAD Team

== BUG REPORTS

Reports of bugs or problems should be submitted via electronic mail to mailto:devs@brlcad.org[]