= TREE(nged)
BRL-CAD Team
ifndef::site-gen-antora[:doctype: manpage]
:man manual: BRL-CAD MGED Commands
:man source: BRL-CAD
:page-role: manpage

== NAME

tree - Lists the contents of the specified objects in a tree-like format
	that displays the hierarchical structure of the objects, and all objects referenced by
	them, down to the primitive shape level.
   

== SYNOPSIS

*tree* {_objects(s)_} [-a] [-c] [-i_\#_] [-o_outfile_]

== DESCRIPTION

Lists the contents of the specified _objects_ in a tree-like format that displays the hierarchical structure of the objects, and all objects referenced by them, down to the primitive shape level. If _-c_ is given, the shapes are not printed. The _-a_ option adds a list of any attributes for each object. Attributes are shown with a leading "@ " and are followed by their values. The _-o outfile_ option prints the results to __outfile__. The _-i #_ option allows the user to set the number of spaces to indent. 

== EXAMPLES

The first example shows the use of the [cmd]*tree* command to list the contents of specified objects  	hierarchically.  The second and third examples show the use of the [cmd]*tree* command with arguments. 

.Show the structure of an object down to the primitive shape level.
====
[prompt]#mged>#[ui]`tree group1`

Shows the structure of the tree rooted at _group1_ down to the primitive shape level. 
====

.Specify the amount of indentation in the tree.
====
[prompt]#mged>#[ui]`tree -i2 group1`

Uses two spaces for each level of indentation. 
====

.Specify that no shapes are to be printed.
====
[prompt]#mged>#[ui]`tree -c group1`

No shapes are printed. 
====

.Specify that attributes are listed for each object printed.
====
[prompt]#mged>#[ui]`tree -a -c group1`

No shapes are printed, but attributes are shown for the printed objects. 
====

== AUTHOR

BRL-CAD Team

== BUG REPORTS

Reports of bugs or problems should be submitted via electronic mail to mailto:devs@brlcad.org[]