include::../header.adoc[]

= UNITS(nged)

== NAME

units - With no arguments, will return the current type of units that
MGED is using.
   

== SYNOPSIS

*units* [_units_type_]

== DESCRIPTION

With no arguments, will return the current type of units that MGED is using. If a _units_type_ is specified, MGED will switch to editing in the indicated units. The actual database is always stored in millimeters, and the display is adjusted to the user's choice of units. If the _units_type_ specified on the command line is one of the types allowed, it will be written to the database file as the preferred units and succeeding invocations will use those units. The _units_type_ strings that will be remembered as the preferred editing unit are as follows:

* mm -- millimeters 
* millimeter -- millimeters 
* cm -- centimeters 
* centimeter -- centimeters 
* m -- meters 
* meter -- meters 
* in -- inches 
* inch -- inches 
* ft -- feet 
* foot -- feet 
* feet -- feet 
* um -- micrometers 

_Units_type_ strings that may be used, but will not be remembered as the preferred editing units, are as follows: 

* angstrom 
* decinanometer 
* nanometer 
* nm 
* micron 
* micrometer 
* km 
* kilometer 
* cubit 
* yd 
* yard 
* rd 
* rod 
* mi 
* mile 
* nmile 
* nautical mile 
* au 
* astronomical unit 
* lightyear 
* pc 
* parsec 


== EXAMPLES

The example shows the use of the [cmd]*units* command with a _units_type_ argument to switch 	the editing units. 

.Switch the editing units to inches.
====
[prompt]#mged>#[ui]`units in`

Switch to editing in inches and remember this as the preferred editing units for this database. 
====

== AUTHOR

BRL-CAD Team

include::../footer.adoc[]
