= VROT(nged)
ifndef::site-gen-antora[:doctype: manpage]
:man manual: BRL-CAD MGED Commands
:man source: BRL-CAD
:page-role: manpage

== NAME

vrot - Rotates the view on the current geometry display window.

== SYNOPSIS

*vrot* {_xrot yrot zrot_}

== DESCRIPTION

Rotates the view on the current geometry display window.  The parameters _xrot, yrot,_ and _zrot_ are rotations (specified in degrees) about the viewing coordinate axes.

If the display is in rotate-about-center mode, then the rotation will occur about the center of the viewing volume. In rotate-about-eye mode, the view on the display will be rotated about the eye. The [cmd]*vars* command (or a menu button) allows the user to toggle between the two modes. 

== EXAMPLES

The two examples show the use of the [cmd]*vrot* command to rotate the view on the current geometry display window about the _x_ axis and _y_ axis, respectively. 

.Rotate the view on the geometry display window about the _x_ axis.
====
[prompt]#mged>#[ui]`vrot 90 0 0`

Rotates the view 90° about the _x_ axis. 
====

.Rotate the view on the geometry display window about the _y_ axis.
====
[prompt]#mged>#[ui]`vrot 0 180 0`

Rotates the view 180° about the _y_ axis. 
====

== AUTHOR

BRL-CAD Team

== BUG REPORTS

Reports of bugs or problems should be submitted via electronic mail to mailto:devs@brlcad.org[]