= WHO(nged)
ifndef::site-gen-antora[:doctype: manpage]
:man manual: BRL-CAD MGED Commands
:man source: BRL-CAD
:page-role: manpage

== NAME

who - Lists the top-level objects that are currently displayed.
   

== SYNOPSIS

*who* [[real] | [phony] | [both]]

== DESCRIPTION

Lists the top-level objects that are currently displayed. The __phony__ flag asks for just _phony_ objects. _Phony_ objects are typically objects that are drawn in the MGED display, but are not actual database objects. Some _phony_ objects are drawings from the [cmd]*vdraw* command and the edgeuses drawn by the [cmd]*ev -u* command. The _real_ flag asks for just _real_ objects, and the _both_ flag asks for both _real_ and _phony_ objects. The default is just __real__objects. Any of the flags may be abbreviated by its first letter. The [cmd]*x* command also lists displayed shapes, but in more detail. 

== EXAMPLES

The example shows the use of the [cmd]*who* command to list the top-level phony objects that are currently displayed. 

.List the top-level phony objects that are currently displayed.
====
[prompt]#mged>#[ui]`who p`

Lists all top-level _phony_ objects currently displayed. 
====

== AUTHOR

BRL-CAD Team

== BUG REPORTS

Reports of bugs or problems should be submitted via electronic mail to mailto:devs@brlcad.org[]