= WMATER(nged)
BRL-CAD Team
ifndef::site-gen-antora[:doctype: manpage]
:man manual: BRL-CAD MGED Commands
:man source: BRL-CAD
:page-layout: base

== NAME

wmater - Lists the shader name and parameters, RGB color,
RGB_valid flag, and the inheritance flag to the specified file for the listed objects.


== SYNOPSIS

*wmater* {_file_} {_objects_}

== DESCRIPTION

Lists the shader name and parameters, RGB color, __RGB_valid__ flag, and the inheritance flag to the specified _file_ for the listed__objects__. The format used is compatible with the [cmd]*rmater* command. If _file_ already exists, the new data is appended to it. 

== EXAMPLES

The example shows the use of the [cmd]*wmater* command to list the shader parameters of two objects to a specified file. 

.List the shader parameters of two objects to a specified file.
====
[prompt]#mged>#[ui]`wmater mater_file group1 regiona`

Lists the shader parameters of _group1_ and _regiona_ to __mater_file__. 
====

== AUTHOR

BRL-CAD Team

== BUG REPORTS

Reports of bugs or problems should be submitted via electronic mail to mailto:devs@brlcad.org[]