= XPUSH(nged)
BRL-CAD Team
ifndef::site-gen-antora[:doctype: manpage]
:man manual: BRL-CAD MGED Commands
:man source: BRL-CAD
:page-role: manpage

== NAME

xpush - Pushes the effects of transformation matrices in the paths,
from the specified object to the primitive shapes, into the shapes and replaces all the
transformation matrices with identity matrices.
   

== SYNOPSIS

*xpush* {_object_}

== DESCRIPTION

Pushes the effects of transformation matrices in the paths, from the specified _object_ to the primitive shapes, into the shapes and replaces all the transformation matrices with identity matrices. The [cmd]*push* command performs a similar function, but will refuse to make any changes if any shape needs to be transformed into more than one location/orientation/scale. The [cmd]*xpush* command will recognize such situations and create extra copies of such shapes to accept the different transformation effects. New shapes created by this command will have a suffix appended to the original name to make the new name unique. Combinations referring to the new shape will also be modified to reflect the name change. The [cmd]*push* command performs the same function but will refuse to make any changes if it cannot accomplish the push without creating any new shapes. 

== EXAMPLES

The example shows the use of the [cmd]*xpush* command to move all the effects of the transformation matrices in a tree rooted at an object down to the shape level(creating new shapes if needed). 

.Move effects of transformation matrices in a tree rooted at an object to the shape level.
====
[prompt]#mged>#[ui]`xpush group1`

Moves all the effects of the transformation matrices in the tree rooted at _group1_ down to the shape level (creating new shapes if needed). 
====

== AUTHOR

BRL-CAD Team

== BUG REPORTS

Reports of bugs or problems should be submitted via electronic mail to mailto:devs@brlcad.org[]