= Working with Our Documentation

The documentation system of BRL-CAD is based on
https://docs.asciidoctor.org/asciidoc/latest/[AsciiDoc] and
https://antora.org/[Antora].

== Installing Antora

. https://github.com/nvm-sh/nvm#installation-and-update[Install `nvm`^]:
+
[source,bash]
....
wget -qO- https://raw.githubusercontent.com/nvm-sh/nvm/v0.38.0/install.sh | bash
source ~/.bashrc
command -v nvm
....

. Install the latest Node LTS release:
+
[source,bash]
....
nvm install --lts
node --version
nvm alias default 14
....

. Install Antora:
+
[source,bash]
....
npm i -g @antora/cli @antora/site-generator-default
antora -v
....

. Install https://github.com/Mogztter/antora-site-generator-lunr[Antora site generator with Lunr^]:
+
[source,bash]
....
npm i -g antora-site-generator-lunr
....


== Building the Docs Locally

. Get the code of the docs from GitHub:
+
[source,bash]
....
git clone https://github.com/BRL-CAD/brlcad-docs
....

. Generate the HTML files:
+
[source,bash]
....
cd brlcad-docs/
antora build-dev.yml
....
+
As prescribed on
https://github.com/BRL-CAD/brlcad-docs/blob/main/build-dev.yml#L29-L30[build-dev.yml^],
the output will be stored on the directory [path]`html/`.

. To view the docs, open the HTML files on a browser (the location
should be something like this:
[path]`~/brlcad-docs/**html/**docs/index.html`).


== Editing the Docs

Any text editor is OK, and most of them provide syntax highlighting
for AsciiDoc. Some of them provide more advanced features, like live
preview.

If you use Emacs, there is an
https://github.com/sensorflo/adoc-mode/wiki[adoc-mode^] for working
with AsciiDoc files. Otherwise you can use one of the editors
recommended
https://docs.asciidoctor.org/asciidoctor/latest/tooling/#ides-and-text-editors[on
this page^] (which include Atom, Brackets, Eclipse, Visual Studio Code,
etc.)

Whenever you make some changes, you need to rebuild the docs and
refresh the browser in order to view them. The Bash script
https://github.com/BRL-CAD/brlcad-docs/blob/main/utils/watch.sh[`utils/watch.sh`^]
may be used to rebuild the docs automatically whenever there are some
modifications.
