name: Build and Deploy GitHub Pages
on:
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.1

      - name: Install Antora and Build Site
        run: |
          rm -rf .nvm
          wget -q -O install-nvm.sh https://raw.githubusercontent.com/nvm-sh/nvm/v0.38.0/install.sh
          bash install-nvm.sh
          nvm install --lts
          node --version
          nvm alias default 14
          npm i -g @antora/cli @antora/site-generator-default antora-site-generator-lunr
          antora -v
          ./build.sh

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: html # The folder the action should deploy.
